module code

import cx
import sync

// ── CX pattern matcher ──────────────────────────────────────────────────────
//
// Phase 3.2. Matches a cx.ProgramPattern AST node (from vcx/code/ast.v)
// against a host CX value (from vcx/cx/ast.v) and yields a binding
// environment. Pure, no I/O, no side effects.
//
// Spec refs:
//   - spec/code.md §5 (patterns)
//   - spec/code.md §6.1 (bindings)
//   - spec/code.md §7 (for-comprehension generators consume the matcher)
//
// The matcher exposes one entry point `match_pattern(pat, val)`. It
// returns `none` on no-match or a populated `MatchEnv` on success.
// Sub-pattern matches contribute their bindings to the parent's env;
// bindings from non-matching alternatives are discarded.

// MatchEnv carries the binding map produced by a successful pattern
// match plus a closure table that the evaluator (eval.v) populates
// when it encounters `[?fn]` / `[?def]` directives.
//
// `bindings` maps the user-chosen `$name` to the matched `cx.Node`
// subtree. The same name appearing in different branches of an
// alternation is the most-recent winner; CX code §5 forbids non-linear
// bindings (same `$name` capturing two different values).
//
// `closures` maps a closure identifier (the user-chosen name from
// `[?def :name N …]` or a synthetic `__anon_<N>__` generated by
// `[?fn]`) to its Closure record. The bindings map stores closure
// references as `cx.Element` sentinels with name `__cx_closure__`
// whose `closure_id` attribute carries the identifier — see eval.v
// `mk_closure_sentinel` / `closure_id_of`.
pub struct MatchEnv {
pub mut:
	bindings    map[string]cx.Node
	// bindings_shared: when true, `bindings` is ALIASED from an immutable
	// template (not a private copy) — set on per-request dispatch envs (#317)
	// so a dispatched request pays ZERO map clones until it actually writes a
	// binding at request scope. The alias is read-only; any in-place write to
	// `env.bindings` MUST call cow_bindings() first to clone-on-write. The
	// template maps (ListenerHandler.enclosing_*, XapHost.henv_*) are written
	// only during single-threaded listener/host construction and NEVER after
	// reactors spawn, so concurrent executor-thread readers are safe (§10.5
	// isolation: a request's mutations land in its private CoW copy, never in
	// the shared template — verified by http_request_env_isolation_test.v).
	bindings_shared bool
	closures    map[string]Closure
	// closures_shared: when true, `closures` is ALIASED from the enclosing call
	// frame (not a private copy) — set on closure-call envs to avoid copying the
	// whole program-global closures table per invocation (the dominant GC-pressure
	// source on fold/map hot paths; see bench/parallel-alloc/B17-FINDINGS.md). The
	// alias is read-only; any registration site MUST call cow_closures() first to
	// clone-on-write, preserving frame-local closure scoping.
	closures_shared bool
	state       &ProgramState = unsafe { nil }
	anon_counter int
	// dyn_context is the active dynamic-scoped context established by
	// [?with-scope] (spec/code.md §8.10.8). It is a flat list
	// of map entries (inner-overrides-outer, shallow per-key) carried on
	// the env so that restore-on-scope-exit is automatic: a [?with-scope]
	// body evaluates in a clone whose dyn_context is merged; the original
	// env retains the prior context on both normal return and error
	// unwind. It is thread/coroutine-local — [?async] / [?worker] bodies
	// inherit a *snapshot* taken at spawn time (capture-at-spawn), not a
	// live alias. Readers (cx-stdlib/log) consult it at emit time. Stored
	// as the child entry-elements of the runtime `__cx_map__` map value
	// — each entry is a cx.Element whose `name` is the key and whose
	// single item is the value (see eval_map).
	dyn_context []cx.Node
	// in_function_body is set on a closure / `[?fn]` / `[?def]` body's
	// call env so a `[?def]` evaluated inside it raises CXER0204
	// (definitions are top/module-level only, §12.2). Top-level program
	// eval leaves it false.
	in_function_body bool
	// frame_pool is a per-thread free-list of closure call-frame binding maps (#36).
	// Allocating a fresh map[string]cx.Node per closure invocation dominated post-B18
	// alloc pressure (~32M maps on the #14 reduce). Pooling is sound because every path
	// that retains a frame's bindings beyond the call COPIES it (snapshot_bindings /
	// .clone() — audited), so no live alias of a returned map exists. The pool is set
	// FRESH per thread (new_env + each spawned worker) and propagated only within a
	// single thread's call chain (invoke_closure_l), so the free-list is never shared
	// across threads — no lock needed. nil = pooling disabled (safe fallback to fresh
	// alloc). Build with -d cx_frame_poison to turn pooling into an escape detector.
	frame_pool &FramePool = unsafe { nil }
	// scope is the top-level program's lexical Scope (its [?def]s + [?const]s +
	// imported members). Allocated by new_env; top-level [?def]s capture it as
	// their defining_scope so their bodies resolve consts (loaded later in the
	// §12.5 two-pass) and sibling defs. nil only in degenerate envs.
	scope &Scope = unsafe { nil }
	// cur_defining_scope is the DEFINING scope of the callable whose body is
	// currently executing (set on every closure call env to the invoked
	// closure's defining_scope). An in-body `[?fn]` captures THIS as its own
	// defining_scope (eval_fn), so a lambda RETURNED from a module def resolves
	// that module's siblings + consts when later applied, not the caller's
	// (#45 Bug-2). nil at top-level program eval and inside a plain [?fn]
	// lambda (defining_scope=nil) — there an in-body [?fn] keeps the prior
	// captured_bindings + caller-closures behavior.
	cur_defining_scope &Scope = unsafe { nil }
	// current_worker is the WorkerRecord of the concurrent [?worker] whose
	// body this evaluation runs inside (nil on the main program thread and
	// in every other spawned context). It is the §10.5.4 cancellation signal
	// for the worker-side cancellation points — [?send] / [?receive] /
	// [?try-send] / [?try-receive] / [?check-cancel] / [?sleep] / the [?for]
	// iteration boundary — which observe `current_worker.cancelled` and
	// report CXER0260. Thread-scoped like frame_pool: set once by
	// run_worker_thread and propagated through same-thread env derivations
	// (clone / clone_frame_sharing_closures / closure call envs); spawned
	// sub-contexts ([?for :par] tasks, [?test-concurrent] tasks, service
	// listeners) deliberately start nil.
	current_worker &WorkerRecord = unsafe { nil }
	// current_future is the FutureRecord of the concurrent [?async] whose
	// spawned body THIS thread is evaluating (#541) — the thread-local
	// analog of state.current_future_id (which serves the lazy
	// drive-at-await path and cannot be shared across spawned threads).
	// Cancellation points ([?sleep]/[?check-cancel]) consult it first.
	current_future &FutureRecord = unsafe { nil }
}

// FramePool: per-thread free-list of reusable closure call-frame binding maps. See the
// frame_pool field on MatchEnv. Never shared across threads (set fresh per worker), so
// the free-list needs no synchronization.
struct FramePool {
mut:
	free []map[string]cx.Node
}

// ProgramState carries the mutable, program-global state that the
// evaluator threads across all calls: the mock clock, the per-
// directive state stores used by `[?circuit-breaker]` / `[?rate-limit]`
// / `[?bulkhead]`, the channel + worker registries used by §10.4
// concurrency, plus the per-helper counters used by `[?test-seq]` /
// `[?test-err-then-ok]` / `[?test-counter]`. State is pointer-shared
// across MatchEnv clones (closures, generators, nested directive
// evaluations) so state machines, channels, and workers observe a
// single consistent view per program invocation.
pub struct ProgramState {
pub mut:
	// strict enables --strict / CX_STRICT_TYPES type validation (§12.7):
	// a `[?def]` argument failing its `::T` param annotation raises
	// CXER0206, a return failing `[returns T]` raises CXER0207. Default
	// (false) ERASES annotations — they are documentation only.
	strict          bool
	now_ns          i64  // mock-clock instant; 0 at program start
	// eval_depth is the shared string-/tree-eval recursion counter (OD-8;
	// spec/modules/cx.md §3.3). One budget across cx:eval and cx:eval-tree /
	// [?eval] so alternating the two cannot bypass the depth cap (CXER4114).
	eval_depth      int
	cb_state        map[string]CbStateRecord
	rate_state      map[string]RateStateRecord
	bulkhead_state  map[string]BulkheadStateRecord
	channels        map[string]&ChannelRecord
	workers         map[string]&WorkerRecord
	services        map[string]&ServiceRecord
	// next_service_port assigns a deterministic ephemeral-port number
	// to each [?http-service port=0]. Real listeners are out of scope for
	// scope (§1.2); the [?test-service-client] helper wires client
	// calls into the matched service via the registry without going
	// over a socket. Fixtures observe the synthesized port via
	// $test-target only.
	next_service_port int = 49152
	futures         map[string]&FutureRecord
	next_future_id  int = 1
	// current_future_id is set during lazy-await evaluation so [?sleep],
	// [?check-cancel], etc. can observe the active future's cancel flag.
	// Empty when not currently evaluating a future body.
	current_future_id string
	// await_deadline_ns is set during [?await $f :timeout DURATION]; the
	// active future's [?sleep] checks (now + dur) > deadline to raise
	// CXER0241 (AWAIT_TIMEOUT). 0 disables the deadline.
	await_deadline_ns i64
	test_counters   map[string]i64
	test_err_counts map[string]i64  // err-then-ok helper progress per call-site
	test_seq_idx    map[string]int  // test-seq cycling counter per call-site
	// registry of first-class Slice literal values.
	// `cx.ProgramSliceLiteral` evaluates to a `__cx_slice__` element whose
	// `:id` attribute keys into this map. The unevaluated axes are kept
	// here so `$_last` resolves at APPLICATION time against the receiver
	// (D11), not at slice-construction time.
	slice_literals  map[string][]cx.SliceAxis
	next_slice_id   int = 1
	// closeables is the runtime registry backing [?with-open]'s nominal
	// close-contract (spec/code.md §8.10.7). A value becomes
	// closeable when its producer registers a record here keyed by a
	// stable close-id stamped onto the handle element (the
	// `__cx_close_id__` attribute). [?with-open] invokes the record's
	// registered `close_fn` on scope exit — module-agnostic: the
	// directive never names io/process/store, it just calls the thunk the
	// producer registered. Idempotent close is enforced via `closed`.
	closeables      map[string]&CloseableRecord
	next_close_id   int = 1
	// close_log records, in invocation order, the label of every close_fn
	// the runtime actually fired. Observable via `[?test-close-log]` so
	// conformance fixtures assert LIFO / idempotence without a real io
	// handle (the closeable producers — io/process/store — land in
	// later waves; the contract + directive are validated here against a
	// synthetic [?test-closeable]).
	closeables_lock &sync.RwMutex = unsafe { nil }
	closed_already  int  // count of close_fn calls skipped due to idempotence
	close_log       []string
	// module_table is the per-program module loader state backing
	// [?lib] imports (spec/code.md §12.1). Seeded with the bundled
	// cx-stdlib sources at program start (register_bundled_stdlib);
	// [?lib] resolution loads file/HTTPS modules into it lazily. Shared
	// across MatchEnv clones via the ProgramState pointer so a module
	// loaded by one statement is visible to later statements / closures.
	module_table ModuleTable
	// current_task_id is non-zero while a cooperative scheduler task
	// holds the run-token. eval_sleep / eval_bulkhead consult it to
	// decide whether to advance the mock clock locally (no-task path)
	// or yield to the scheduler (under-task path) per spec/code.md
	// §10.2.6 cooperative-task contract. See vcx/code/scheduler.v.
	current_task_id int
	// scheduler_tasks indexes live cooperative tasks by id; populated
	// for the duration of one [?test-concurrent] driver invocation and
	// cleared on exit. Pointer-shared so [?bulkhead] / [?sleep] can
	// reach the running TaskRecord via current_task_id without
	// threading it through MatchEnv.bindings.
	scheduler_tasks map[int]&TaskRecord
	// wasm_wall_sleep_allowed controls whether the wasm host permits
	// blocking [?sleep DUR]. Default false (browser main-thread):
	// bare [?sleep DUR] raises CXER0270 (WALL_SLEEP_UNSUPPORTED_IN_HOST).
	// Web-Worker hosts opt in via _cx_wasm_set_wall_sleep(true). The
	// flag is ignored on native builds; the native wall-clock path
	// always runs unless current_task_id / :mock short-circuit.
	wasm_wall_sleep_allowed bool
	// Per-field RwMutexes serializing concurrent access to the
	// resilience-state, scheduler-bound, and fixture-counter maps
	// across parallel workers spawned by `[?map :par]` / `[?reduce :par]`
	// Mutators acquire `@lock` (write); readers
	// acquire `@rlock` (read). Granularity is per-map — different
	// state families don't contend.
	cb_state_lock         &sync.RwMutex = unsafe { nil }
	rate_state_lock       &sync.RwMutex = unsafe { nil }
	bulkhead_state_lock   &sync.RwMutex = unsafe { nil }
	channels_lock         &sync.RwMutex = unsafe { nil }
	workers_lock          &sync.RwMutex = unsafe { nil }
	services_lock         &sync.RwMutex = unsafe { nil }
	futures_lock          &sync.RwMutex = unsafe { nil }
	test_counters_lock    &sync.RwMutex = unsafe { nil }
	test_err_counts_lock  &sync.RwMutex = unsafe { nil }
	test_seq_idx_lock     &sync.RwMutex = unsafe { nil }
	scheduler_tasks_lock  &sync.RwMutex = unsafe { nil }
	// clock_lock guards now_ns + await_deadline_ns + current_future_id
	// + current_task_id (the small scalar-state group). One mutex
	// across the group is fine; these scalars are read/written
	// together in tightly correlated sequences.
	clock_lock            &sync.RwMutex = unsafe { nil }
	// cx-stdlib/log configuration (spec/std-lib/log.md §3.4). Per-program
	// (reset each new_env), pointer-shared across clones/closures so a
	// [$log:configure] in one statement is visible to a later
	// [$log:is-enabled] / [$log:*] emit within the same program. Defaults
	// per §3.4: minimum level :info (rank 1), sink "stderr", format "text".
	log_min_level int    = 1
	log_sink      string = 'stderr'
	log_format    string = 'text'
	log_file_path string
}

// ServiceRecord tracks one [?service]'s lifecycle and resource table
// per spec/code.md §10.3. Resources are stored in source order; resource
// resolution scans the table linearly matching method + path.
@[heap]
pub struct ServiceRecord {
pub mut:
	name             string
	protocol         string  // 'http'
	port             int     // resolved port (49152+ if requested as 0)
	tls_config       string  // empty when no TLS; else a stable token
	read_timeout_ns  i64
	write_timeout_ns i64
	max_body_bytes   i64
	grace_period_ns  i64
	resources        []ResourceRecord
	status           string  // 'running' | 'stopped'
	shutdown_reason  string  // 'graceful' (when [?stop]ped) | ''
	// real-socket configuration. Populated when the
	// directive carries the matching clause-children; otherwise empty
	// / default and the in-process path is taken.
	root             string  // [root "…"] — filesystem dir for [$serve-file]
	bind_host        string  // [bind-host "…"] — listener bind address
	block            bool    // [block true] — eval_http_service blocks
	// cache opts INTO the static-file cache for [$serve-file]. Default
	// false: every request reads the file fresh (always current, no cache
	// memory, no staleness). [cache true]: bodies are memoized keyed by
	// fs-path and revalidated by mtime (one stat per hit) — faster under
	// load but holds file bodies in memory. Honored identically by the
	// [$serve-file] eval path and the listener static-file fast path.
	cache            bool    // [cache true] — enable the static-file body cache
	default_headers  []cx.Attribute  // [default-headers k=v …] — applied to every response
	// listener_id keys into ProgramState.listeners for the spawned
	// V net.http server thread (if any). 0 = no listener.
	listener_id      int
	// listener_handle is an opaque pointer to the spawned `&http.Server`
	// net.http is imported only by services_listener.v so
	// matcher.v keeps its zero-net-deps stance. nil when no listener.
	listener_handle  voidptr = unsafe { nil }
}

// ResourceRecord is one [resource] child of a [?service] body. The
// :body expression is stored as an AST node so it can be re-evaluated
// per request with $request bound in the calling env.
pub struct ResourceRecord {
pub:
	method   string  // 'GET' / 'POST' / 'PUT' / 'PATCH' / 'DELETE' / 'HEAD' / 'OPTIONS'
	path     string  // PATH per §10.3.2 — `/users/:id` supported
	body     cx.ProgramNode @[required]
	auth     ?cx.ProgramNode
	produces string  // default 'application/cx'
	consumes string  // default '*/*'
}

// ClientRecord captures one [?http-client]'s configuration per
// spec/code.md §10.3.4. Postfix calls (get / post / put / …) resolve
// the target URL → service via the registry; out-of-process targets
// raise CXER0180.
pub struct ClientRecord {
pub:
	target     string  // URL: 'cx-test://NAME/' or 'http://host:port/'
	tls_config string  // matches ServiceRecord.tls_config on success
	timeout_ns i64
	// resilience: out-of-scope for the client foundation; wrap
	// the postfix call expression in [?retry] / [?timeout] / etc. to
	// achieve the same effect. The :resilience slot is parsed and
	// validated but not yet applied at client-call time.
	resilience_present bool
}

// ChannelRecord wraps a V channel of cx.Node messages with the
// FIFO + close semantics from spec/code.md §10.4.1-10.4.4. The
// channel itself is heap-allocated and shared via pointer across
// sender / receiver workers.
@[heap]
pub struct ChannelRecord {
pub mut:
	name     string
	buffer   int
	closed   bool
	// Storage for buffered sends pending a receive. Implemented as a
	// FIFO queue (not a V channel) so we can support cancellation,
	// try-send/try-receive timeouts via mock-clock, and inspection
	// for [?select]'s ready-check. A real chan T over the V runtime
	// would be the production choice once cooperative cancellation
	// is wired through the worker scheduler (Phase 3.10).
	queue    []cx.Node
	// tokens runs parallel to `queue` (same length, mutated in lock-step
	// through the ch_* helpers in eval.v): tokens[i] is the send-token of
	// queue[i]. A blocked unbuffered [?send] (§10.4.2 rendezvous, worker
	// context) uses its token to observe consumption (token gone = a
	// receiver took the value) and to RETRACT the value when cancellation
	// wins (§10.5.4 — a cancelled send must not leave its value behind).
	tokens   []u64
	// next_token mints send-tokens; 0 is never issued.
	next_token u64
	// mu serialises every queue/tokens/closed access across the main
	// thread and concurrent [?worker] threads (all access goes through
	// the ch_* helpers in eval.v). Initialised at the single construction
	// site (eval_channel).
	mu       &sync.RwMutex = unsafe { nil }
}

// FutureRecord tracks one [?async]'s lifecycle per spec/code.md §10.5.
// Futures are lazily evaluated: the body AST + the env bindings at
// declaration time are stored, and the body runs the first time
// [?await] is invoked. Cancellation is a flag the body's `[?sleep]`,
// `[?check-cancel]`, and channel ops observe at their next entry.
@[heap]
pub struct FutureRecord {
pub mut:
	id                string
	body              []cx.ProgramNode  // length-1 (see Closure.body rationale)
	bindings_snapshot map[string]cx.Node
	state             string  // 'pending' | 'running' | 'done' | 'failed' | 'cancelled'
	value             cx.Node
	cause             cx.Node
	cancel_requested  bool
	// #541 eager spawn: `concurrent` marks a future whose body runs on its
	// own V thread (the §10.5.1 DEFAULT — the lazy drive-at-await substrate
	// remains behind CX_WORKER_THREADS=0). `parked_until_ns` is the logical
	// wake time of a [?sleep DUR mock] the body is PARKED at (0 = not
	// parked): the mock sleep does NOT self-advance the shared clock — the
	// await barriers advance it when every runnable future is parked, which
	// is what keeps the mock-clock fixture battery deterministic across
	// real threads.
	concurrent      bool
	parked_until_ns i64
	// thread_id is the spawned body's pthread id (#541), stamped at thread
	// start — the §10.5.7.2 revocation registry key: cancelling a running
	// concurrent future registers this id so cap_allowed denies raw
	// effects on that thread for the remainder of the body.
	thread_id u64
}

// WorkerRecord tracks one [?worker]'s lifecycle per spec/code.md §10.4.6.
@[heap]
pub struct WorkerRecord {
pub mut:
	name      string
	done      bool
	cancelled bool
	result    cx.Node
	// concurrent is set when the body runs on its own spawned V thread — the
	// DEFAULT per §10.4.6 (#58): the worker runs alongside a blocking
	// `[$http:serve {block:true}]` instead of monopolizing the calling thread.
	// `done` flips (with `result`) when the thread finishes; [?wait-for]
	// spin-waits on it. CX_WORKER_THREADS=0 opts back into the synchronous
	// run-to-completion path (done already true when eval_worker returns).
	concurrent bool
}

// CbStateRecord tracks one circuit-breaker's state per spec §10.2.3.
pub struct CbStateRecord {
pub mut:
	open_until_ns i64  // 0 when closed; > 0 = the instant when the
	                   // breaker transitions back to half-open
	samples       int  // count of attempts in the current window
	failures      int  // count of failures in the current window
	window_start_ns i64
}

// RateStateRecord tracks one rate-limit's token bucket per §10.2.5.
pub struct RateStateRecord {
pub mut:
	tokens_remaining i64
	window_start_ns  i64
}

// BulkheadStateRecord tracks one bulkhead's slot accounting per §10.2.6.
// `max_concurrent` / `queue_cap` are recorded on first acquisition so the
// cooperative scheduler (scheduler.v) can detect "a slot just freed —
// any queued waiter on this name?" without consulting the originating
// directive AST. `wait_queue` is a FIFO of task ids parked in the
// queued-but-not-yet-acquired state; the scheduler pops the head when
// granting a slot. All fields are touched only while a task holds the
// scheduler's run-token, so no mutex is needed.
pub struct BulkheadStateRecord {
pub mut:
	max_concurrent int
	queue_cap      int
	in_flight      int
	queued         int
	wait_queue     []int
}

// Closure captures a CX code function value: parameter names, body
// expression (AST node), and a *bindings snapshot* taken at closure-
// creation time.
//
// The snapshot covers `bindings` only (not the closures map) because
// closures are stored in the program-global `MatchEnv.closures`
// registry — capturing the closures map inside a Closure would create
// a directly-recursive struct that V's codegen rejects. Closures
// referenced from a closure body are resolved at call time through
// the calling env's closures table (which is the same shared table,
// per program-global registry semantics).
// CloseableRecord backs one closeable resource registered against
// [?with-open]'s nominal close-contract (spec/code.md §8.10.7
// D8). The producer registers `close_fn` at handle-creation time; the
// directive fires it exactly once on scope exit (LIFO across a
// multi-binding form). `closed` guarantees idempotence: a second close
// — whether from a lazy iterator exhausting the same handle or a nested
// [?with-open] — is a silent no-op, never CXER3409. `label` is a human
// tag surfaced in `state.close_log` for fixture observability.
@[heap]
pub struct CloseableRecord {
pub mut:
	label    string
	closed   bool
	close_fn fn () ! @[required]
	// Concurrency-handle close (spec/code.md §10.5.7.1 — RAII over handles):
	// when `handle_kind` is non-empty the record represents an [?async]
	// future ('future') or a [?worker] ('worker') whose registered close
	// CANCELS-AND-JOINS the task rather than running a plain `close_fn`.
	// `handle_id` names the live FutureRecord id / WorkerRecord name. The
	// generic `close_fn` above is a no-op for these (the real work runs in
	// fire_close, which has the `mut env` needed to reach the registries).
	handle_kind string
	handle_id   string
}

// ParamSpec is one parameter in a function's signature.
// `default_src` is the verbatim default-value expression (empty = none),
// evaluated lazily at call time in the closure's captured environment.
pub struct ParamSpec {
pub:
	name        string
	is_named    bool
	is_rest     bool
	default_src string
	// type_src is the verbatim `::T` parameter type annotation ('' when
	// none). Erased in default mode; checked under --strict (CXER0206,
	// §12.7).
	type_src string
}

// Scope is a module's (or the top-level program's) lexical name environment —
// its closures (functions, by unqualified name + the prefixed members of the
// modules IT imports) and its bindings (consts). Built once during load and
// READ-ONLY at call time, so a closure can capture a `&Scope` reference with no
// per-call clone (B17) and share it across threads safely. Uniform lexical
// scoping (#19/#22, spec/03-approved/core/code.md): a callable
// resolves its free names in its DEFINING scope, not the caller's.
@[heap]
pub struct Scope {
pub mut:
	closures map[string]Closure
	bindings map[string]cx.Node
}

pub struct Closure {
pub:
	params []string
	// is_variadic marks a closure whose final parameter is a `:rest`
	// variadic. When set, invoke_closure binds the leading
	// positional args one-to-one and collects every trailing arg into a
	// `__cx_seq__` envelope bound to the last parameter name. Required
	// by the bundled `cx-stdlib/path` `join` (and any future variadic
	// [?def]); plain closures leave it false and keep strict arity.
	is_variadic bool
	// builtin_name, when non-empty, marks a function VALUE that wraps a
	// native builtin (builtins are first-class). invoke_closure
	// dispatches straight to the builtin with all args (builtins do their
	// own arity checking); params/body/is_variadic are unused in that case.
	builtin_name string
	// partial_target (length-1 when set) + partial_template mark a partial
	// application. partial_target[0] is the wrapped function
	// VALUE; partial_template is the captured argument list with hole
	// markers (`__cx_hole__` elements). invoke_closure fills the holes
	// left-to-right with the incoming args, then applies the target.
	partial_target   []cx.Node
	partial_template []cx.Node
	// param_specs carries the full parameter model (named / default /
	// rest) for library + [?def] closures. When non-empty,
	// invoke_closure binds via the spec list — positional args fill
	// positional params, named call-args (`:label v`) fill named params,
	// omitted params with a default get it, and a `:rest` param collects
	// the trailing positional args. [?fn] lambdas leave this empty and
	// use the simple positional path.
	param_specs []ParamSpec
	// body is a length-1 slice. Slice elements are heap-allocated by V
	// and survive struct-copy / map-storage cleanly (storing a cx.ProgramNode
	// directly here trips V's codegen on recursive-struct expansion;
	// storing a pointer to a stack-local corrupts the sum-type tag).
	body              []cx.ProgramNode
	captured_bindings map[string]cx.Node
	// defining_scope is the lexical environment the closure was DEFINED in (its
	// module / the top-level program). When set, invoke resolves the body's free
	// names — sibling functions AND module consts — against it (NOT the caller's
	// table). nil for plain `[?fn]` lambdas (which capture local lets via
	// captured_bindings and inherit the caller's closures, the prior behavior).
	defining_scope &Scope = unsafe { nil }
	// returns_type is the verbatim `[returns T]` annotation ('' when
	// none). Erased in default mode; the return value is checked against
	// it under --strict (CXER0207, §12.7).
	returns_type string
}

// body_node returns the closure's body AST node.
pub fn (c Closure) body_node() cx.ProgramNode {
	return c.body[0]
}

// ClosureBox wraps a Closure as a cx.OpaqueValue so an escaping [?fn] / partial
// can ride ON its function-value sentinel (#45): the Closure (with its
// defining_scope + captured_bindings) travels WITH the value and resolves
// wherever applied — no id→scope-table registry, hence no unbounded growth and no
// shared-Scope mutation. The box (NOT Closure itself) implements the interface so
// `Closure` keeps its plain value-struct codegen — it is copied by value on every
// closure call (the fold/map hot path), and making it satisfy an interface
// regresses that copy under -prod (cx-private #45 perf gate).
pub struct ClosureBox {
pub:
	cl Closure
}

pub fn (b ClosureBox) opaque_kind() string {
	return 'closure'
}

// new_env returns a fresh empty environment with a freshly-allocated
// ProgramState. Subsequent clones share the same ProgramState pointer
// so state-machine and mock-clock updates remain consistent.
pub fn new_env() MatchEnv {
	// Each evaluated program starts with fresh cx-stdlib/prof process-global
	// state (counters / histograms / trace buffer / default config) so prof
	// state never leaks across independent programs (stdlib_prof.v).
	prof_reset_state()
	// Likewise the cx-stdlib/session server-held registry (stdlib_session.v):
	// each program starts with a fresh, empty session store so sessions /
	// clients / CSRF tokens never leak across independent programs (the
	// conformance harness runs every fixture in one process).
	session_reset_state()
	// Likewise the cx-stdlib/authz server-held authority-store registry
	// (stdlib_authz.v): each program starts with a fresh, empty trust state
	// (delegations / guardian grants) so authority never leaks across
	// independent programs (the conformance harness runs every fixture in one
	// process).
	authz_reset_state()
	// Likewise the cx-stdlib/sched process-global timer registry + virtual
	// clock (stdlib_sched.v): each program starts with no armed timers and a
	// fresh virtual clock so schedules never leak across independent programs.
	sched_reset_state()
	// Likewise the §9.6 error-hook frame stack (error_hooks.v).
	error_hooks_reset()
	state := &ProgramState{
		now_ns:             0
		cb_state:           map[string]CbStateRecord{}
		rate_state:         map[string]RateStateRecord{}
		bulkhead_state:     map[string]BulkheadStateRecord{}
		channels:           map[string]&ChannelRecord{}
		workers:            map[string]&WorkerRecord{}
		services:           map[string]&ServiceRecord{}
		next_service_port:  49152
		futures:            map[string]&FutureRecord{}
		next_future_id:     1
		current_future_id:  ''
		await_deadline_ns:  0
		test_counters:      map[string]i64{}
		test_err_counts:    map[string]i64{}
		test_seq_idx:       map[string]int{}
		slice_literals:     map[string][]cx.SliceAxis{}
		next_slice_id:      1
		closeables:         map[string]&CloseableRecord{}
		next_close_id:      1
		close_log:          []string{}
		closeables_lock:    sync.new_rwmutex()
		module_table:       new_seeded_module_table()
		current_task_id:    0
		scheduler_tasks:    map[int]&TaskRecord{}
		wasm_wall_sleep_allowed: wasm_wall_sleep_default()
		cb_state_lock:           sync.new_rwmutex()
		rate_state_lock:         sync.new_rwmutex()
		bulkhead_state_lock:     sync.new_rwmutex()
		channels_lock:           sync.new_rwmutex()
		workers_lock:            sync.new_rwmutex()
		services_lock:           sync.new_rwmutex()
		futures_lock:            sync.new_rwmutex()
		test_counters_lock:      sync.new_rwmutex()
		test_err_counts_lock:    sync.new_rwmutex()
		test_seq_idx_lock:       sync.new_rwmutex()
		scheduler_tasks_lock:    sync.new_rwmutex()
		clock_lock:              sync.new_rwmutex()
	}
	return MatchEnv{
		bindings:    map[string]cx.Node{}
		closures:    map[string]Closure{}
		state:       state
		anon_counter: 0
		frame_pool:  &FramePool{} // fresh per-thread frame pool (#36); main-thread root
		scope:       &Scope{
			closures: map[string]Closure{}
			bindings: map[string]cx.Node{}
		}
	}
}

// clone returns a copy whose bindings + closures maps are independent
// but whose ProgramState pointer is SHARED. State machines, the mock
// clock, and test-helper counters thus remain consistent across
// speculative-match snapshots, closure-call frames, and generator
// iterations.
// cow_closures realizes a private copy of an aliased closures table before a
// write. No-op when the table is already owned (closures_shared == false), so
// the common case (frames that never register a closure) pays nothing. Must be
// called by every site that mutates env.closures.
fn (mut e MatchEnv) cow_closures() {
	if e.closures_shared {
		e.closures = e.closures.clone()
		e.closures_shared = false
	}
}

// cow_bindings realizes a private copy of an aliased bindings table before an
// in-place write — the bindings mirror of cow_closures (#317). No-op when the
// table is already owned (bindings_shared == false), so every env except a
// per-request template alias pays a single branch. Must be called by every
// site that mutates `env.bindings` in place (writes into a locally
// constructed fresh map need no guard). Child frames (clone /
// clone_frame_sharing_closures / build_param_call_env) copy bindings into
// fresh maps, so the flag never propagates past the request env itself.
fn (mut e MatchEnv) cow_bindings() {
	if e.bindings_shared {
		e.bindings = e.bindings.clone()
		e.bindings_shared = false
	}
}

fn (e MatchEnv) clone() MatchEnv {
	mut copy := MatchEnv{
		bindings: map[string]cx.Node{}
		closures: map[string]Closure{}
		state:    e.state
		anon_counter: e.anon_counter
		dyn_context: e.dyn_context.clone()
		scope:    e.scope // share the program scope (heap, read-only at call time)
		// A derived frame stays INSIDE the same lexical context (#646): dropping
		// these two reset every [?let]/[?loop]/[?for]/backtrack frame to "top
		// level", so a [?fn] created under one captured env.scope — the IMPORTING
		// program's scope — instead of the enclosing callable's defining scope,
		// and module-sibling calls inside deferred bodies failed ("no callable")
		// while the same text ran green as a program. cur_defining_scope is a
		// read-only-after-build &Scope, shared exactly like `scope` above.
		in_function_body:   e.in_function_body
		cur_defining_scope: e.cur_defining_scope
		current_worker: e.current_worker // same-thread derivation keeps the §10.5.4 cancel signal
		current_future: e.current_future // #541: the eager-async cancel/park signal derives the same way
	}
	for k, v in e.bindings {
		copy.bindings[k] = v
	}
	for k, c in e.closures {
		copy.closures[k] = c
	}
	return copy
}

// clone_frame_sharing_closures returns a per-iteration child frame for the
// `[?for]` comprehension walker (#57). It copies `bindings` into a fresh map
// (the walker writes the loop variable / let-bindings there) but ALIASES the
// `closures` table read-only (`closures_shared = true`) instead of deep-copying
// it — the same B17 optimization the closure-call path already uses
// (eval.v build_param_call_env). Cloning the whole closures table per generator
// item was the dominant per-request memory high-water in a `[?lib]`-loaded HTTP
// handler: an N-item `[?for]` copied the entire stdlib closure set N times, and
// under `-gc e` that transient high-water is held (not reclaimed), so sustained
// traffic exhausts the heap → `malloc` fails → the #57 OOM panic. Matches
// `clone()`'s field handling exactly apart from the closures alias; safe because
// every `env.closures` write site calls `cow_closures()` first.
fn (e MatchEnv) clone_frame_sharing_closures() MatchEnv {
	mut copy := MatchEnv{
		bindings:        map[string]cx.Node{}
		closures:        e.closures // aliased; cow_closures() before any write
		closures_shared: true
		state:           e.state
		anon_counter:    e.anon_counter
		dyn_context:     e.dyn_context.clone()
		scope:           e.scope
		// Same-context derivation keeps the lexical position (#646) — see clone().
		in_function_body:   e.in_function_body
		cur_defining_scope: e.cur_defining_scope
		current_worker:  e.current_worker // same-thread derivation keeps the §10.5.4 cancel signal
		current_future:  e.current_future // #541: the eager-async cancel/park signal derives the same way
	}
	for k, v in e.bindings {
		copy.bindings[k] = v
	}
	return copy
}

// match_pattern is the public entry point. Returns the binding env on
// success, `none` on no-match.
//
// The matcher itself only ever touches `env.bindings`; it never
// dereferences `env.state` / `env.closures` / `env.anon_counter`. We
// therefore skip the full `new_env()` allocation (which would build a
// fresh ProgramState with nine empty maps) and instead synthesise a
// lightweight MatchEnv whose only live field is `bindings`. The
// `state` pointer is left `nil` — callers MUST NOT pass the returned
// env to evaluator entry points; they should copy the desired
// `matched.bindings` into a real env and proceed. This is the
// hottest allocation in the §11.6 gate 15 streaming bench
// (~1.1 M match_pattern calls for the 100 MiB JSON-shape corpus —
// each previously cost ~10 map-allocations).
pub fn match_pattern(pat cx.ProgramPattern, val cx.Node) ?MatchEnv {
	// Fast pre-check: the matcher is defined over cx.Element values; a
	// non-Element val (TextNode, ScalarNode, …) can never match. Skip
	// the env allocation entirely. This is the §11.6 gate 15 hot path:
	// pattern-generator recursion over a flat record list visits every
	// textual / scalar child of every matched element, each one calling
	// match_pattern.
	if val !is cx.Element {
		return none
	}
	// Second fast pre-check: for a named head, the element name has to
	// match exactly — anything else fails before we look at attrs /
	// body. Skipping env allocation on head-name mismatch saves the
	// dominant share of allocations when the pattern is anchored to a
	// specific name (the common case in deep-find).
	el := val as cx.Element
	if pat.head.kind == .named && pat.head.value != el.name {
		return none
	}
	mut env := MatchEnv{
		bindings:     map[string]cx.Node{}
		closures:     map[string]Closure{}
		state:        unsafe { nil }
		anon_counter: 0
	}
	if match_node(pat, val, mut env) {
		return env
	}
	return none
}

// match_arm_pattern dispatches a multi-arm [?match] `:case PAT` against
// the candidate value `val`. Returns a populated MatchEnv on success
// (carrying parent bindings + any new ones from the match), or `none`
// on miss. Per and spec/code.md §5.2 rule 8:
//
//   cx.ProgramPattern    — element-shape pattern; delegates to match_pattern
//   cx.ProgramLiteral    — scalar literal pattern, type-strict per §5.2 r8
//                       (int / float / string / bool / atom)
//   cx.ProgramCall{_}    — wildcard `_`; matches anything, no bindings
//   cx.ProgramBinding    — bind-only `$name`; matches anything, binds name
//
// CXPath patterns (`:case //prose :yield …`) are not yet
// implemented; they fall through to `none` and will be added with the
// PathExpr value-kind evaluator.
pub fn match_arm_pattern(pat cx.ProgramNode, val cx.Node, parent MatchEnv) ?MatchEnv {
	mut out := parent.clone()
	if match_value_pattern(pat, val, mut out) {
		return out
	}
	return none
}

// match_value_pattern is the unified recursive matcher over the full
// MatchPattern vocabulary (spec/code.md §5.2, grammar [140a]). It
// matches `pat` against the runtime value `val`, threads bindings into
// `env`, and returns success. Collection patterns recurse through this
// same entry point for their item / value sub-patterns. On failure `env`
// may be partially mutated — callers needing rollback snapshot via
// clone() (the collection helpers do).
fn match_value_pattern(pat cx.ProgramNode, val cx.Node, mut env MatchEnv) bool {
	match pat {
		cx.ProgramPattern {
			// Element-shape pattern (rules 1–10): delegate to the element
			// matcher, which threads its own bindings into env.
			return match_node(pat, val, mut env)
		}
		cx.ProgramLiteral {
			match pat.kind {
				.map_lit {
					return match_map_pattern(pat.keys, pat.items, val, mut env)
				}
				.sequence_lit {
					return match_seq_or_array_pattern(pat.items, val, seq_marker_name, mut env)
				}
				.array_lit {
					return match_seq_or_array_pattern(pat.items, val, arr_marker_name, mut env)
				}
				else {
					// Scalar literal pattern (rule 8) — type-strict, no coercion.
					return scalar_literal_matches(pat, val)
				}
			}
		}
		cx.ProgramCall {
			// `_` parses as cx.ProgramCall{name:"_", args:[]}. Wildcard arm
			// always matches, binds nothing.
			return pat.name == '_' && pat.args.len == 0
		}
		cx.ProgramBinding {
			// Path-bearing bindings (`$x/foo`) are not legal in pattern
			// position. A rest-bind only appears inside a collection (handled
			// by the collection helpers) — a bare top-level one is a no-op
			// non-match.
			if pat.path.len > 0 || pat.is_rest {
				return false
			}
			// Typed bind `$name::T` / anonymous `_::T` (rule 14): test the
			// value's CXDM kind first.
			if pat.type_test != '' {
				if !value_matches_type(val, pat.type_test) {
					return false
				}
			}
			// Bind the value (anonymous `_` binds nothing).
			if pat.name != '_' {
				env.bindings[pat.name] = val
			}
			return true
		}
		else {
			return false
		}
	}
}

// match_seq_or_array_pattern matches a Sequence (`marker == seq_marker_name`)
// or Array (`marker == arr_marker_name`) pattern against `val` (spec/code.md
// §5.2 rules 12–13). Closed (exact arity) unless the final item is a
// rest-bind `*$rest`, which binds the trailing items as a value of the same
// kind. A `val` of the wrong kind (e.g. a scalar) is a NON-MATCH, not an
// error (rule: kind-mismatch falls through to `[else]`).
fn match_seq_or_array_pattern(items []cx.ProgramNode, val cx.Node, marker string,
                              mut env MatchEnv) bool {
	if val !is cx.Element {
		return false
	}
	el := val as cx.Element
	if el.name != marker {
		return false
	}
	// Detect a trailing rest-bind.
	mut rest_name := ''
	mut fixed := items.clone()
	if items.len > 0 {
		last := items[items.len - 1]
		if last is cx.ProgramBinding && last.is_rest {
			rest_name = last.name
			fixed = items[..items.len - 1]
		}
	}
	if rest_name == '' {
		// Closed: exact arity.
		if el.items.len != fixed.len {
			return false
		}
	} else {
		// Open tail: at least the fixed items must be present.
		if el.items.len < fixed.len {
			return false
		}
	}
	mut snap := env.clone()
	for i, sub in fixed {
		if !match_value_pattern(sub, el.items[i], mut snap) {
			return false
		}
	}
	if rest_name != '' {
		rest_items := el.items[fixed.len..].clone()
		snap.bindings[rest_name] = cx.Element{ name: marker, items: rest_items }
	}
	env = snap
	return true
}

// match_map_pattern matches a Map pattern against `val` (spec/code.md §5.2
// rule 11). Open (subset) match by key: the candidate must carry every
// non-rest key, matched by its value sub-pattern; extra keys are allowed.
// A trailing rest-bind `*$rest` (stored with an empty-string key) binds the
// unmatched pairs as a Map. A non-Map `val` is a NON-MATCH.
fn match_map_pattern(keys []string, items []cx.ProgramNode, val cx.Node,
                     mut env MatchEnv) bool {
	if val !is cx.Element {
		return false
	}
	el := val as cx.Element
	if el.name != map_marker_name {
		return false
	}
	mut rest_name := ''
	mut snap := env.clone()
	mut matched_keys := map[string]bool{}
	for i, k in keys {
		sub := items[i]
		if k == '' {
			// Rest entry: `*$rest`.
			if sub is cx.ProgramBinding && sub.is_rest {
				rest_name = sub.name
			}
			continue
		}
		// Find the candidate entry with this key.
		mut entry_val := ?cx.Node(none)
		for child in el.items {
			if child is cx.Element && child.name == k {
				entry_val = map_entry_value(child)
				break
			}
		}
		cand := entry_val or { return false }
		if !match_value_pattern(sub, cand, mut snap) {
			return false
		}
		matched_keys[k] = true
	}
	if rest_name != '' {
		mut rest_entries := []cx.Node{}
		for child in el.items {
			if child is cx.Element && child.name !in matched_keys {
				rest_entries << child
			}
		}
		snap.bindings[rest_name] = cx.Element{ name: map_marker_name, items: rest_entries }
	}
	env = snap
	return true
}

// map_entry_value extracts the value node of a `__cx_map__` entry element
// (`[key value]`). An empty-body entry yields the entry element itself.
fn map_entry_value(entry cx.Element) cx.Node {
	if entry.items.len == 1 {
		return entry.items[0]
	}
	return cx.Node(entry)
}

// scalar_literal_matches reports whether a cx.ProgramLiteral matches the
// given cx.Node under §5.2 rule 8's type-strict semantics. No coercion:
// `:case 200` does not match val "200"; `:case "ok"` does not match
// atom :ok; `:case :ok` does not match string "ok".
fn scalar_literal_matches(lit cx.ProgramLiteral, val cx.Node) bool {
	if val !is cx.ScalarNode {
		return false
	}
	sn := val as cx.ScalarNode
	match lit.kind {
		.int_lit {
			if sn.data_type != .int_type {
				return false
			}
			match sn.value {
				i64 { return sn.value == lit.int_val }
				else { return false }
			}
		}
		.float_lit {
			if sn.data_type != .float_type {
				return false
			}
			match sn.value {
				f64 { return sn.value == lit.flt_val }
				else { return false }
			}
		}
		.string_lit {
			if sn.data_type != .string_type {
				return false
			}
			match sn.value {
				string { return sn.value == lit.str_val }
				else { return false }
			}
		}
		.bool_lit {
			if sn.data_type != .bool_type {
				return false
			}
			match sn.value {
				bool { return sn.value == lit.bool_val }
				else { return false }
			}
		}
		.atom_lit {
			if sn.data_type != .atom_type {
				return false
			}
			match sn.value {
				string { return sn.value == lit.str_val }
				else { return false }
			}
		}
		else {
			return false
		}
	}
}

// match_node attempts to match `pat` against `val`, threading env.
// Returns true on success; on failure env may have been partially
// mutated — callers requiring rollback (alternation, deep-search)
// MUST snapshot+restore env via clone().
fn match_node(pat cx.ProgramPattern, val cx.Node, mut env MatchEnv) bool {
	// Pattern matching is defined over Element nodes per spec §5.1;
	// non-Element values match only against type-guard heads with
	// matching scalar / text annotations (left for the type-system
	// extension in spec §5.8).
	match val {
		cx.Element {
			return match_element(pat, val, mut env)
		}
		else {
			return false
		}
	}
}

// match_element is the core matcher for cx.Element values.
fn match_element(pat cx.ProgramPattern, el cx.Element, mut env MatchEnv) bool {
	// Head match (name / wildcard / type-guard shape; doesn't bind)
	if !match_head_shape(pat.head, el) {
		return false
	}
	// Attribute predicates
	for attr_pat in pat.attrs {
		if !match_attr(attr_pat, el, mut env) {
			return false
		}
	}
	// Bind capture short-circuit (spec/code.md §5.2 rule 5).
	//
	// A pattern of the form `[NAME $x]` or `[NAME @attr… $x]` carries
	// the binding $x as a single body item OR as a head-bind (the
	// parser's parse_optional_bind consumes a trailing $ on the head
	// when no attrs follow). In both cases the user's intent is
	// "capture the matched element by $x" — not "$x must match one
	// body child." Running match_body for these patterns would fail
	// against elements with empty / attr-only bodies (e.g. matching
	// `[order @total=200 $o]` against `[order total=200]`).
	//
	// Detect the bind-capture shape — head.bind set OR body is a
	// single `$bind` without a path — and apply the auto-unwrap rule:
	//
	//   - Named head + attribute predicates  →  $x = whole element
	//   - Named head, no attrs               →  $x auto-unwraps body
	//   - Wildcard / deep / type-guard heads →  $x = whole element
	//
	// See spec/code.md §5.2 rule 5 for the normative wording +
	// fixtures program-find-bind-* for regression coverage.
	mut bind_name := ''
	if pat.head.bind != '' {
		bind_name = pat.head.bind
	} else if pat.body.len == 1 {
		first := pat.body[0]
		if first is cx.ProgramBinding && first.path.len == 0 {
			bind_name = first.name
		}
	}
	if bind_name != '' {
		if pat.head.kind == .named && pat.attrs.len == 0 {
			env.bindings[bind_name] = unwrap_body_value(el)
		} else {
			env.bindings[bind_name] = el
		}
		return true
	}
	// Body — runs only when the body isn't a lone bind-capture.
	return match_body(pat.body, pat.direct, el, mut env)
}

// match_head_shape checks the pattern head's structural match against
// the element. Binding capture is performed in match_element after
// attrs + body match so the unwrap rule can see the full pattern.
fn match_head_shape(head cx.ProgramPatternHead, el cx.Element) bool {
	return match head.kind {
		.named      { head.value == el.name }
		.wildcard   { true }                  // * matches any element
		.deep       { true }                  // ** at head matches any element
		.type_guard { el.data_type() or { '' } == head.value }
	}
}

// match_attr evaluates one attribute predicate against the element's
// attributes. Equality and comparison predicates evaluate the
// pattern's `value` node to a scalar and compare against the
// element attribute's ScalarValue.
fn match_attr(ap cx.ProgramPatternAttr, el cx.Element, mut env MatchEnv) bool {
	mut found := ?cx.Attribute(none)
	for a in el.attrs {
		if a.name == ap.name {
			found = a
			break
		}
	}
	match ap.kind {
		.existence {
			return found != none
		}
		.absence {
			return found == none
		}
		.type_test {
			// `@name::T` (spec/code.md §5.2 rule 14, attribute position):
			// the attribute must exist and its value's CXDM kind must be T.
			a := found or { return false }
			mut dt := cx.ScalarType.string_type
			if !isnil(a.meta) {
				if d := a.meta.data_type {
					dt = cx.scalar_type_from_name(d) or { cx.ScalarType.string_type }
				}
			}
			node := cx.Node(cx.ScalarNode{ value: a.value, data_type: dt })
			return value_matches_type(node, ap.type_name)
		}
		.equality, .comparison {
			actual := found or { return false }
			pat_val := ap.value or { return false }
			// Binding-capture form: `@name=$bind` (no existing binding)
			// binds the attribute value into env rather than comparing.
			// `@name=$bind` where $bind is already bound compares against
			// the previously-bound value.
			if pat_val is cx.ProgramBinding && pat_val.path.len == 0 && ap.op == '=' {
				if existing := env.bindings[pat_val.name] {
					if existing is cx.ScalarNode {
						return scalars_equal(actual.value, existing.value)
					}
					return false
				}
				// Bind the attribute's TYPED value (cxdm.md §2.4) — same
				// materialization as the `@name` read axis, so a captured
				// atom-typed attribute stays an atom (attr_scalar_node).
				env.bindings[pat_val.name] = attr_scalar_node(actual)
				return true
			}
			// gap C: cross-binding predicate `[@name=$o/@x]`
			// the RHS is a path-bearing binding reference. Resolve the
			// path against the outer binding env (typically a `?for`
			// loop variable), reduce the resulting node to a scalar,
			// then compare with the element's attribute value the same
			// way a literal scalar RHS would. A bare `$bind` (path.len ==
			// 0) is intentionally NOT caught here — that's the
			// equality-capture form handled above.
			if pat_val is cx.ProgramBinding && pat_val.path.len > 0 {
				resolved := eval_binding(pat_val, mut env) or { return false }
				expected := node_to_scalar(resolved) or { return false }
				return compare_scalars(actual.value, ap.op, expected)
			}
			expected := literal_to_scalar(pat_val) or { return false }
			return compare_scalars(actual.value, ap.op, expected)
		}
	}
	return false
}

// compare_scalars implements the spec/code.md §5.4 attribute relop
// semantics. Equality is strict: types must agree.
fn compare_scalars(actual cx.ScalarValue, op string, expected cx.ScalarValue) bool {
	match op {
		'=', '' {
			return scalars_equal(actual, expected)
		}
		'!=' {
			return !scalars_equal(actual, expected)
		}
		else {
			// Numeric comparison; both sides MUST be numeric.
			a_n := scalar_to_f64(actual) or { return false }
			b_n := scalar_to_f64(expected) or { return false }
			return match op {
				'<'  { a_n < b_n }
				'<=' { a_n <= b_n }
				'>'  { a_n > b_n }
				'>=' { a_n >= b_n }
				else { false }
			}
		}
	}
}

fn scalars_equal(a cx.ScalarValue, b cx.ScalarValue) bool {
	match a {
		bool {
			if b is bool { return a == b }
			if b is string { return scalar_string_to_bool(b) or { return false } == a }
		}
		i64 {
			if b is i64 { return a == b }
			if b is f64 { return f64(a) == b }
			if b is string { return b.i64() == a && b.len > 0 }
		}
		f64 {
			if b is f64 { return a == b }
			if b is i64 { return a == f64(b) }
		}
		string {
			if b is string { return a == b }
			if b is bool {
				// CX auto-typing may surface `true`/`false` as string
				// or bool depending on bare-value context. Treat them
				// as equal when the string form matches the bool's
				// canonical spelling.
				return scalar_string_to_bool(a) or { return false } == b
			}
			if b is i64 { return a.i64() == b && a.len > 0 }
		}
		cx.NullValue {
			if b is cx.NullValue { return true }
		}
	}
	return false
}

fn scalar_string_to_bool(s string) ?bool {
	match s {
		'true'  { return true }
		'false' { return false }
		else    { return none }
	}
}

fn scalar_to_f64(s cx.ScalarValue) ?f64 {
	match s {
		i64    { return f64(s) }
		f64    { return s }
		else   { return none }
	}
}

// literal_to_scalar converts a cx.ProgramLiteral expression node into its
// cx.ScalarValue. Used when matching attribute equality predicates.
fn literal_to_scalar(n cx.ProgramNode) ?cx.ScalarValue {
	match n {
		cx.ProgramLiteral {
			match n.kind {
				.string_lit  { return cx.ScalarValue(n.str_val) }
				.int_lit     { return cx.ScalarValue(n.int_val) }
				.float_lit   { return cx.ScalarValue(n.flt_val) }
				.bool_lit    { return cx.ScalarValue(n.bool_val) }
				.duration_lit { return cx.ScalarValue(n.dur_val) }
				else         { return none }
			}
		}
		else {
			return none
		}
	}
}

// node_to_scalar reduces a runtime cx.Node to its scalar value for
// predicate-RHS comparison (gap C). Used when a path-bearing
// binding reference like `$o/@x` resolves to either:
//   - a bare ScalarNode (already a scalar);
//   - a synthetic terminal-attribute Element `[<attr> "value"]` produced
//     by walk_binding_path_seq's attribute-axis materialization;
//   - a single-item sequence wrapper `Element{ name: '', items: [..] }`
//     containing one of the above (multi-item sequences yield `none` —
//     scalar comparison against a sequence is not well-defined here).
// Returns none for any other shape so the predicate falls back to a
// non-match rather than panicking.
fn node_to_scalar(n cx.Node) ?cx.ScalarValue {
	if n is cx.ScalarNode {
		return n.value
	}
	if n is cx.Element {
		el := n as cx.Element
		// Sequence wrapper from walk_binding_path_seq: name == ''
		// carries the underlying focus list in items. Single-item
		// sequences degenerate to that one node's scalar; empty or
		// multi-item are not directly comparable.
		if el.name == '' {
			if el.items.len == 1 {
				return node_to_scalar(el.items[0])
			}
			return none
		}
		// Terminal-attribute synthesized element: [<attr> "value"] —
		// body holds one ScalarNode with the attribute's value.
		if el.items.len == 1 {
			child := el.items[0]
			if child is cx.ScalarNode {
				return child.value
			}
		}
	}
	return none
}

// match_body matches the pattern's body items against the element's
// child items. With `:direct false` (default) the matcher honours
// source order but allows non-matching siblings to be skipped between
// matches. With `:direct true` adjacent siblings MUST match in
// order with no skips per spec/code.md §3.1.
//
// `**` wildcard in body position matches at ANY depth — the matcher
// recursively descends into element children when looking for the
// next body item after `**`.
fn match_body(body []cx.ProgramNode, direct bool, el cx.Element, mut env MatchEnv) bool {
	if body.len == 0 {
		return true
	}
	if direct {
		return match_body_adjacent(body, el.items, 0, mut env)
	}
	return match_body_in_order(body, el.items, 0, mut env)
}

// match_body_in_order matches body items against child items in
// source order, allowing the matcher to skip non-matching children
// between matches.
fn match_body_in_order(body []cx.ProgramNode, children []cx.Node,
                       start int, mut env MatchEnv) bool {
	if body.len == 0 {
		return true
	}
	first := body[0]
	if first is cx.ProgramWildcard && first.deep {
		// `**` consumes zero-or-more descendants at any depth; try
		// matching the REMAINING body items at every descendant.
		remaining := body[1..]
		if remaining.len == 0 {
			return true // trailing ** always succeeds
		}
		return match_remaining_at_any_depth(remaining, children, mut env)
	}
	for i in start .. children.len {
		mut snap := env.clone()
		if match_body_item(first, children[i], mut snap) {
			if match_body_in_order(body[1..], children, i + 1, mut snap) {
				env = snap
				return true
			}
		}
	}
	return false
}

// match_remaining_at_any_depth tries to match `body` somewhere in
// the descendant tree rooted at any of `roots`.
fn match_remaining_at_any_depth(body []cx.ProgramNode, roots []cx.Node,
                                 mut env MatchEnv) bool {
	for root in roots {
		// Try here.
		mut snap := env.clone()
		if match_body_in_order(body, [root], 0, mut snap) {
			env = snap
			return true
		}
		// Recurse.
		if root is cx.Element {
			if match_remaining_at_any_depth(body, root.items, mut env) {
				return true
			}
		}
	}
	return false
}

// match_body_adjacent enforces strict adjacency: body[i] must match
// children[start+i] with no skipping.
fn match_body_adjacent(body []cx.ProgramNode, children []cx.Node,
                       start int, mut env MatchEnv) bool {
	if start + body.len > children.len {
		return false
	}
	for i, item in body {
		if !match_body_item(item, children[start + i], mut env) {
			return false
		}
	}
	return true
}

// unwrap_body_value applies the spec/code.md §5.2 rule 5
// auto-unwrap convention: when a body-position binding `[NAME $x]`
// matches an element with no attribute predicates in the pattern,
// the binding captures the element's body value per shape:
//   - empty body          → the matched element itself (nothing
//                           to unwrap; the element is the result)
//   - single text body    → that text as a string scalar
//   - single scalar body  → the scalar (preserving its typed value)
//   - structured body     → the element itself
// The fallback (structured body / empty body) preserves the matched
// element so further pattern matching / path navigation works on
// the binding.
fn unwrap_body_value(el cx.Element) cx.Node {
	if el.items.len == 1 {
		body := el.items[0]
		match body {
			cx.TextNode {
				return cx.Node(cx.ScalarNode{
					value:     cx.ScalarValue(body.value)
					data_type: cx.ScalarType.string_type
				})
			}
			cx.ScalarNode {
				return cx.Node(body)
			}
			else {
				// Structured body — return the element itself.
			}
		}
	}
	return cx.Node(el)
}

// match_body_item dispatches on the body-item kind.
fn match_body_item(item cx.ProgramNode, child cx.Node, mut env MatchEnv) bool {
	match item {
		cx.ProgramPattern {
			return match_node(item, child, mut env)
		}
		cx.ProgramBinding {
			// Capture without further structure constraint.
			if item.path.len > 0 {
				return false // path-bearing bindings at body position
				             // aren't a match-position construct
			}
			env.bindings[item.name] = child
			return true
		}
		cx.ProgramWildcard {
			// `*` matches one element/scalar/text; `**` is consumed by
			// match_body_in_order's deep branch and shouldn't reach here.
			return !item.deep
		}
		else {
			return false
		}
	}
}
