module code

import cx
import encoding.base58
import crypto.ed25519
import crypto.sha256

// stdlib_xsp_auth.v — native primitives backing the XSP-AUTH handshake calculus
// (spec/02-working/xap_identity_model.md §4). XSP-AUTH is the mutual,
// channel-bound proof-of-control handshake for XSP: SIGMA-style signed
// ephemeral X25519, four messages riding ordinary XSP v1 frames on stream 0.
// This file is the PURE calculus (§10 P0): message build/validate, transcript,
// Ed25519 signatures over canonical form, HKDF key schedule, key-confirmation
// tags, and the §4.8 per-request possession proofs. Randomness (nonces,
// ephemeral keypairs) is generated by the impure caller and injected — the
// same purity split did.md §6 uses.
//
// No new trust primitive (identity-model §0): signatures reuse the vc.md §4
// pattern (Ed25519 over render_canonical), key recovery reuses did_key_bytes,
// HKDF/HMAC/X25519 reuse the crypto engine internals.

// CXER codes per identity-model §4.10 (symbolic, trust-stack style).
const xsp_auth_err_version   = 'cx-err:CXER-XSP-AUTH-VERSION'
const xsp_auth_err_state     = 'cx-err:CXER-XSP-AUTH-STATE'
const xsp_auth_err_sig       = 'cx-err:CXER-XSP-AUTH-SIG'
const xsp_auth_err_confirm   = 'cx-err:CXER-XSP-AUTH-CONFIRM'
const xsp_auth_err_binding   = 'cx-err:CXER-XSP-AUTH-BINDING'
const xsp_auth_err_anonymous = 'cx-err:CXER-XSP-AUTH-ANONYMOUS-REFUSED'
const xsp_auth_err_principal = 'cx-err:CXER-XSP-AUTH-PRINCIPAL-MISMATCH'
const xsp_auth_err_stream    = 'cx-err:CXER-XSP-AUTH-STREAM'
const xsp_auth_err_proof     = 'cx-err:CXER-XSP-AUTH-PROOF'
const xsp_auth_err_rotate    = 'cx-err:CXER-XSP-AUTH-ROTATE'

// HKDF info labels (§4.5) — version-partitioned by construction.
const xsp_auth_label_tag_i   = 'xsp-auth/1/confirm/initiator'
const xsp_auth_label_tag_r   = 'xsp-auth/1/confirm/responder'
const xsp_auth_label_proof_i = 'xsp-auth/1/proof/initiator'
const xsp_auth_label_proof_r = 'xsp-auth/1/proof/responder'
const xsp_auth_label_chan    = 'xsp-auth/1/channel-id'

// ── element helpers ──────────────────────────────────────────────────────────

fn xsp_auth_child(e cx.Element, name string) ?cx.Element {
	for it in e.items {
		if it is cx.Element {
			if it.name == name {
				return it
			}
		}
	}
	return none
}

// Handshake scalar fields are read attr-OR-child: a message built fresh carries
// them as single-scalar child elements (`[nonce X]`); the SAME message decoded
// off the wire carries them as atomized attributes (`nonce=X`) because CX
// data-bin collapses single-scalar children to attributes canonically. Both
// shapes must read identically, or a decoded message would fail validation
// (identity-model §4.3 — the frame round-trip must not change meaning).
fn xsp_auth_attr_node(e cx.Element, name string) ?cx.Node {
	for a in e.attrs {
		if a.name == name {
			// The readers (arg_bytes/arg_string/vc_text_of) key off the
			// underlying ScalarValue, not the node's data_type tag — bytes
			// live as a string ScalarValue either way — so a plain node
			// carrying the attribute's value reads correctly for text, bytes,
			// and int fields alike.
			return cx.Node(cx.ScalarNode{
				value:     a.value
				data_type: cx.ScalarType.string_type
			})
		}
	}
	return none
}

fn xsp_auth_child_text(e cx.Element, name string) ?string {
	if n := xsp_auth_attr_node(e, name) {
		return vc_text_of(n)
	}
	c := xsp_auth_child(e, name) or { return none }
	if c.items.len == 0 {
		return none
	}
	return vc_text_of(c.items[0])
}

fn xsp_auth_child_bytes(e cx.Element, name string) ?[]u8 {
	if n := xsp_auth_attr_node(e, name) {
		return arg_bytes(n)
	}
	c := xsp_auth_child(e, name) or { return none }
	if c.items.len == 0 {
		return none
	}
	return arg_bytes(c.items[0])
}

fn xsp_auth_has_field(e cx.Element, name string) bool {
	for a in e.attrs {
		if a.name == name {
			return true
		}
	}
	if _ := xsp_auth_child(e, name) {
		return true
	}
	return false
}

// xsp_auth_fields_allowed rejects unknown extra children AND unknown attributes
// (§4.3 — forward compatibility is the versions field's job, not silent
// tolerance). `phase` is always permitted (it is the message tag). Accepting
// both shapes is what lets a decoded (atomized-attr) message validate while a
// hand-forged extra field — child OR attr — is still rejected.
fn xsp_auth_fields_allowed(e cx.Element, allowed []string) bool {
	for it in e.items {
		if it is cx.Element {
			if it.name !in allowed {
				return false
			}
		} else {
			return false
		}
	}
	for a in e.attrs {
		if a.name == 'phase' {
			continue
		}
		if a.name !in allowed {
			return false
		}
	}
	return true
}

fn xsp_auth_is_phase(n cx.Node, phase string) ?cx.Element {
	if n is cx.Element {
		if n.name == 'xsp-auth' && xap_elem_attr(n, 'phase') == phase {
			return n
		}
	}
	return none
}

// xsp_auth_versions_has reports whether M1's versions field offers `v`. The
// field is a `[versions 1 …]` child when fresh, or (atomized single value) a
// `versions=1` attribute after a wire round trip; both read here.
fn xsp_auth_versions_has(m1 cx.Element, v i64) bool {
	if c := xsp_auth_child(m1, 'versions') {
		for it in c.items {
			if it is cx.ScalarNode {
				if cx.scalar_value_str_public(it.value).i64() == v {
					return true
				}
			} else if it is cx.TextNode {
				if it.value.i64() == v {
					return true
				}
			}
		}
		return false
	}
	if n := xsp_auth_attr_node(m1, 'versions') {
		if s := vc_text_of(n) {
			// attribute form: a single value, or a comma-list for forward compat
			for part in s.split(',') {
				if part.trim_space().i64() == v {
					return true
				}
			}
		}
	}
	return false
}

fn xsp_auth_opt_bytes(opts cx.Node, key string) ?[]u8 {
	n := xap_map_get_node(opts, key) or { return none }
	return arg_bytes(n)
}

fn xsp_auth_opt_string(opts cx.Node, key string) ?string {
	n := xap_map_get_node(opts, key) or { return none }
	return vc_text_of(n)
}

fn xsp_auth_opt_bool(opts cx.Node, key string) bool {
	n := xap_map_get_node(opts, key) or { return false }
	if s := vc_text_of(n) {
		return s == 'true'
	}
	if n is cx.ScalarNode {
		return cx.scalar_value_str_public(n.value) == 'true'
	}
	return false
}

// ── message validation (§4.3 exact shapes) ──────────────────────────────────

fn xsp_auth_validate_hello(n cx.Node) !cx.Element {
	m1 := xsp_auth_is_phase(n, 'hello') or {
		return error('M1 must be [xsp-auth phase=hello …]')
	}
	if !xsp_auth_fields_allowed(m1, ['versions', 'initiator', 'nonce', 'eph', 'endpoint']) {
		return error('M1 carries an unknown child (v1 rejects extras)')
	}
	nonce := xsp_auth_child_bytes(m1, 'nonce') or { return error('M1 missing [nonce]') }
	eph := xsp_auth_child_bytes(m1, 'eph') or { return error('M1 missing [eph]') }
	if nonce.len != 32 || eph.len != 32 {
		return error('M1 nonce/eph must be 32 bytes')
	}
	if !xsp_auth_has_field(m1, 'versions') {
		return error('M1 missing versions')
	}
	if !xsp_auth_has_field(m1, 'endpoint') {
		return error('M1 missing endpoint')
	}
	return m1
}

fn xsp_auth_validate_challenge(n cx.Node) !cx.Element {
	m2 := xsp_auth_is_phase(n, 'challenge') or {
		return error('M2 must be [xsp-auth phase=challenge …]')
	}
	if !xsp_auth_fields_allowed(m2, ['version', 'responder', 'nonce', 'eph', 'cb', 'sig']) {
		return error('M2 carries an unknown child (v1 rejects extras)')
	}
	nonce := xsp_auth_child_bytes(m2, 'nonce') or { return error('M2 missing [nonce]') }
	eph := xsp_auth_child_bytes(m2, 'eph') or { return error('M2 missing [eph]') }
	if nonce.len != 32 || eph.len != 32 {
		return error('M2 nonce/eph must be 32 bytes')
	}
	xsp_auth_child_text(m2, 'responder') or { return error('M2 missing responder') }
	if !xsp_auth_has_field(m2, 'cb') {
		return error('M2 missing cb')
	}
	xsp_auth_child_text(m2, 'sig') or { return error('M2 missing sig') }
	return m2
}

fn xsp_auth_validate_prove(n cx.Node) !cx.Element {
	m3 := xsp_auth_is_phase(n, 'prove') or {
		return error('M3 must be [xsp-auth phase=prove …]')
	}
	if !xsp_auth_fields_allowed(m3, ['sig', 'tag', 'attach']) {
		return error('M3 carries an unknown child (v1 rejects extras)')
	}
	tag := xsp_auth_child_bytes(m3, 'tag') or { return error('M3 missing [tag]') }
	if tag.len != 32 {
		return error('M3 tag must be 32 bytes')
	}
	xsp_auth_child(m3, 'attach') or { return error('M3 missing [attach]') }
	return m3
}

fn xsp_auth_validate_confirm(n cx.Node) !cx.Element {
	m4 := xsp_auth_is_phase(n, 'confirm') or {
		return error('M4 must be [xsp-auth phase=confirm …]')
	}
	if !xsp_auth_fields_allowed(m4, ['tag', 'session']) {
		return error('M4 carries an unknown child (v1 rejects extras)')
	}
	tag := xsp_auth_child_bytes(m4, 'tag') or { return error('M4 missing [tag]') }
	if tag.len != 32 {
		return error('M4 tag must be 32 bytes')
	}
	return m4
}

// ── transcript & signatures (§4.4) ───────────────────────────────────────────

// xsp_auth_strip_sig returns M2 with its [sig] field removed — the challenge
// half of the transcript. The field is a child element on a fresh message and
// an atomized `sig=` attribute after a wire round trip (data-bin collapses
// single-scalar children); both forms strip, or the two sides of the wire
// would sign different transcripts.
fn xsp_auth_strip_sig(e cx.Element) cx.Element {
	mut items := []cx.Node{}
	for it in e.items {
		if it is cx.Element {
			if it.name == 'sig' {
				continue
			}
		}
		items << it
	}
	mut attrs := []cx.Attribute{}
	for a in e.attrs {
		if a.name == 'sig' {
			continue
		}
		attrs << a
	}
	return cx.Element{
		name:  e.name
		attrs: attrs
		items: items
	}
}

fn xsp_auth_transcript(m1 cx.Element, m2 cx.Element) cx.Element {
	return cx.Element{
		name:  'xsp-auth-transcript'
		attrs: []
		items: [
			cx.Node(xap_elem('hello', [], [cx.Node(m1)])),
			cx.Node(xap_elem('challenge', [], [cx.Node(xsp_auth_strip_sig(m2))])),
		]
	}
}

// xsp_auth_sign_payload builds the role-pinned wrapper the signed bytes cover.
// role=initiator additionally covers the responder's signature (the TLS-1.3
// transcript-closure pattern).
fn xsp_auth_sign_payload(role string, transcript cx.Element, responder_sig string) cx.Element {
	mut items := [cx.Node(transcript)]
	if role == 'initiator' {
		items << cx.Node(xap_elem('responder-sig', [], [crypto_string_node(responder_sig)]))
	}
	return cx.Element{
		name:  'xsp-auth-sign'
		attrs: [xap_attr('role', role)]
		items: items
	}
}

// xsp_auth_sign_bytes serializes the sign payload with CX data-bin (§4.4) — the
// SAME canonical binary encoding the XSP frame carries on the wire. data-bin
// encode is canonical (child-form `[nonce X]` and the atomized attr-form
// `nonce=X` a decoder produces emit identical bytes), so the initiator (who
// holds a fresh child-form message) and the responder (who decoded the wire
// into attr-form) compute byte-identical transcripts. render_canonical is NOT
// used here precisely because it is shape-sensitive across that round-trip.
fn xsp_auth_sign_bytes(payload cx.Element) ![]u8 {
	return cx.codec_emit_bytes_node('data-bin', cx.Node(payload)) or {
		return error('data-bin serialization failed: ${err.msg()}')
	}
}

fn xsp_auth_sign(seed []u8, payload cx.Element) !string {
	if seed.len != 32 {
		return error('Ed25519 seed must be 32 bytes')
	}
	priv := ed25519.new_key_from_seed(seed)
	sig := priv.sign(xsp_auth_sign_bytes(payload)!) or { return error('signing failed') }
	return 'z' + base58.encode_bytes(sig).bytestr()
}

fn xsp_auth_sig_verify(pub_key []u8, payload cx.Element, sig_mb string) bool {
	if pub_key.len != 32 || !sig_mb.starts_with('z') {
		return false
	}
	sig := base58.decode_bytes(sig_mb[1..].bytes()) or { return false }
	if sig.len != 64 {
		return false
	}
	msg := xsp_auth_sign_bytes(payload) or { return false }
	ok := ed25519.verify(ed25519.PublicKey(pub_key), msg, sig) or { return false }
	return ok
}

// xsp_auth_peer_key resolves the Ed25519 verification key for a DID: an
// explicit key in opts wins (the did:web resolve-first path); a did:key /
// did:peer:0 recovers offline (did.md §3 / identity-model §1).
fn xsp_auth_peer_key(opts cx.Node, opt_name string, did string) ![]u8 {
	if k := xsp_auth_opt_bytes(opts, opt_name) {
		if k.len != 32 {
			return error('${opt_name} must be a 32-byte Ed25519 public key')
		}
		return k
	}
	return did_key_bytes(did) or {
		return error('no ${opt_name} supplied and "${did}" is not offline-resolvable — resolve the DID document first')
	}
}

// ── key schedule (§4.5) ──────────────────────────────────────────────────────

struct XspAuthKeys {
	tag_i   []u8
	tag_r   []u8
	proof_i []u8
	proof_r []u8
	chan_id []u8
}

fn xsp_auth_derive(eph_priv []u8, peer_eph_pub []u8, nonce_i []u8, nonce_r []u8) !XspAuthKeys {
	if eph_priv.len != 32 || peer_eph_pub.len != 32 {
		return error('X25519 keys must be 32 bytes')
	}
	if nonce_i.len != 32 || nonce_r.len != 32 {
		return error('nonces must be 32 bytes')
	}
	mut sk := eph_priv.clone()
	x25519_clamp(mut sk)
	ss := x25519_scalar_mult(sk, peer_eph_pub)
	// RFC 7748: reject the all-zero shared secret (low-order peer point).
	mut acc := u8(0)
	for b in ss {
		acc |= b
	}
	if acc == 0 {
		return error('degenerate X25519 shared secret')
	}
	mut salt := nonce_i.clone()
	salt << nonce_r
	prk := crypto_hkdf_extract('sha256', salt, ss) or { return error('hkdf-extract failed') }
	return XspAuthKeys{
		tag_i:   xsp_auth_expand(prk, xsp_auth_label_tag_i, 32)!
		tag_r:   xsp_auth_expand(prk, xsp_auth_label_tag_r, 32)!
		proof_i: xsp_auth_expand(prk, xsp_auth_label_proof_i, 32)!
		proof_r: xsp_auth_expand(prk, xsp_auth_label_proof_r, 32)!
		chan_id: xsp_auth_expand(prk, xsp_auth_label_chan, 16)!
	}
}

fn xsp_auth_expand(prk []u8, label string, length int) ![]u8 {
	n := crypto_hkdf_expand('sha256', prk, label.bytes(), length) or {
		return error('hkdf-expand failed')
	}
	return arg_bytes(n) or { return error('hkdf-expand yielded a non-bytes node') }
}

fn xsp_auth_keys_element(k XspAuthKeys) cx.Node {
	return xap_elem('xsp-auth-keys', [], [
		cx.Node(xap_elem('tag-i', [], [bytes_node(k.tag_i)])),
		cx.Node(xap_elem('tag-r', [], [bytes_node(k.tag_r)])),
		cx.Node(xap_elem('proof-i', [], [bytes_node(k.proof_i)])),
		cx.Node(xap_elem('proof-r', [], [bytes_node(k.proof_r)])),
		cx.Node(xap_elem('chan-id', [], [bytes_node(k.chan_id)])),
	])
}

fn xsp_auth_hmac_tag(key []u8, transcript cx.Element) ![]u8 {
	// data-bin over the transcript — wire-stable across the child→attr round
	// trip for the same reason the signatures are (xsp_auth_sign_bytes).
	msg := xsp_auth_sign_bytes(transcript)!
	return crypto_hmac('sha256', key, msg) or { return error('hmac failed') }
}

fn xsp_auth_ct_eq(a []u8, b []u8) bool {
	if a.len != b.len {
		return false
	}
	mut acc := u8(0)
	for i in 0 .. a.len {
		acc |= a[i] ^ b[i]
	}
	return acc == 0
}

// ── per-request possession proofs (§4.8 rule 2) ─────────────────────────────

fn xsp_auth_proof_bytes(key []u8, counter u64, frame []u8) ![]u8 {
	mut msg := []u8{cap: 40}
	for i := 7; i >= 0; i-- {
		msg << u8(counter >> (u64(i) * 8))
	}
	digest := sha256.sum(frame)
	msg << digest
	return crypto_hmac('sha256', key, msg) or { return error('hmac failed') }
}

// ── the calculus surface ─────────────────────────────────────────────────────

fn xsp_auth_stdlib_builtin(name string, args []cx.Node) ?cx.Node {
	match name {
		// [$xsp:auth-hello OPTS] → M1. OPTS: nonce (32B), eph (32B X25519 pub),
		// endpoint (string; '' on in-process channels), did? (initiator DID;
		// absent = anonymous, §4.7).
		'xsp-auth-hello' {
			if args.len != 1 {
				return none
			}
			opts := args[0]
			nonce := xsp_auth_opt_bytes(opts, 'nonce') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-hello: opts.nonce (32 bytes) required')
			}
			eph := xsp_auth_opt_bytes(opts, 'eph') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-hello: opts.eph (32 bytes) required')
			}
			if nonce.len != 32 || eph.len != 32 {
				return mk_err(xsp_auth_err_state, 'xsp/auth-hello: nonce/eph must be 32 bytes')
			}
			endpoint := xsp_auth_opt_string(opts, 'endpoint') or { '' }
			mut items := []cx.Node{}
			items << xap_elem('versions', [], [bytes_int_node(1)])
			if did := xsp_auth_opt_string(opts, 'did') {
				items << xap_elem('initiator', [], [crypto_string_node(did)])
			}
			items << xap_elem('nonce', [], [bytes_node(nonce)])
			items << xap_elem('eph', [], [bytes_node(eph)])
			items << xap_elem('endpoint', [], [crypto_string_node(endpoint)])
			return xap_elem('xsp-auth', [xap_attr('phase', 'hello')], items)
		}
		// [$xsp:auth-challenge M1 OPTS] → M2. OPTS: did (responder), nonce,
		// eph, key (32B Ed25519 seed), cb? (bytes, default empty).
		'xsp-auth-challenge' {
			if args.len != 2 {
				return none
			}
			m1 := xsp_auth_validate_hello(args[0]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-challenge: ${err.msg()}')
			}
			if !xsp_auth_versions_has(m1, 1) {
				return mk_err(xsp_auth_err_version, 'xsp/auth-challenge: no mutually supported version (need 1)')
			}
			opts := args[1]
			did := xsp_auth_opt_string(opts, 'did') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-challenge: opts.did (responder DID) required — there is no anonymous responder (N-IDENT-2)')
			}
			nonce := xsp_auth_opt_bytes(opts, 'nonce') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-challenge: opts.nonce (32 bytes) required')
			}
			eph := xsp_auth_opt_bytes(opts, 'eph') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-challenge: opts.eph (32 bytes) required')
			}
			if nonce.len != 32 || eph.len != 32 {
				return mk_err(xsp_auth_err_state, 'xsp/auth-challenge: nonce/eph must be 32 bytes')
			}
			seed := xsp_auth_opt_bytes(opts, 'key') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-challenge: opts.key (Ed25519 seed) required')
			}
			cb := xsp_auth_opt_bytes(opts, 'cb') or { []u8{} }
			m2sans := cx.Element{
				name:  'xsp-auth'
				attrs: [xap_attr('phase', 'challenge')]
				items: [
					cx.Node(xap_elem('version', [], [bytes_int_node(1)])),
					cx.Node(xap_elem('responder', [], [crypto_string_node(did)])),
					cx.Node(xap_elem('nonce', [], [bytes_node(nonce)])),
					cx.Node(xap_elem('eph', [], [bytes_node(eph)])),
					cx.Node(xap_elem('cb', [], [bytes_node(cb)])),
				]
			}
			t := xsp_auth_transcript(m1, m2sans)
			sig := xsp_auth_sign(seed, xsp_auth_sign_payload('responder', t, '')) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-challenge: ${err.msg()}')
			}
			mut items := m2sans.items.clone()
			items << xap_elem('sig', [], [crypto_string_node(sig)])
			return cx.Element{
				name:  m2sans.name
				attrs: m2sans.attrs
				items: items
			}
		}
		// [$xsp:auth-transcript M1 M2] → the §4.4 transcript element.
		'xsp-auth-transcript' {
			if args.len != 2 {
				return none
			}
			m1 := xsp_auth_validate_hello(args[0]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-transcript: ${err.msg()}')
			}
			m2 := xsp_auth_validate_challenge(args[1]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-transcript: ${err.msg()}')
			}
			return cx.Node(xsp_auth_transcript(m1, m2))
		}
		// [$xsp:auth-keys EPH-PRIV PEER-EPH-PUB NONCE-I NONCE-R] → the §4.5
		// schedule as an [xsp-auth-keys …] element.
		'xsp-auth-keys' {
			if args.len != 4 {
				return none
			}
			eph_priv := arg_bytes(args[0]) or { return none }
			peer_pub := arg_bytes(args[1]) or { return none }
			n_i := arg_bytes(args[2]) or { return none }
			n_r := arg_bytes(args[3]) or { return none }
			k := xsp_auth_derive(eph_priv, peer_pub, n_i, n_r) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-keys: ${err.msg()}')
			}
			return xsp_auth_keys_element(k)
		}
		// [$xsp:auth-prove M1 M2 OPTS] → M3 (initiator side; verifies M2 first).
		// OPTS: eph-priv (32B), attach (element), cb? (initiator's computed
		// binding value — MUST equal M2's), responder-key? (32B Ed25519 pub —
		// required unless the responder DID is offline-resolvable), did? +
		// key? (initiator DID + seed; both absent = anonymous).
		'xsp-auth-prove' {
			if args.len != 3 {
				return none
			}
			m1 := xsp_auth_validate_hello(args[0]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: ${err.msg()}')
			}
			m2 := xsp_auth_validate_challenge(args[1]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: ${err.msg()}')
			}
			opts := args[2]
			ver := xsp_auth_child_bytes_int(m2, 'version')
			if ver != 1 || !xsp_auth_versions_has(m1, ver) {
				return mk_err(xsp_auth_err_version, 'xsp/auth-prove: responder selected version ${ver}, not offered/supported')
			}
			// channel binding (§4.6): the initiator's own view must equal M2's.
			m2_cb := xsp_auth_child_bytes(m2, 'cb') or { []u8{} }
			my_cb := xsp_auth_opt_bytes(opts, 'cb') or { []u8{} }
			if !xsp_auth_ct_eq(m2_cb, my_cb) {
				return mk_err(xsp_auth_err_binding, 'xsp/auth-prove: channel-binding value mismatch')
			}
			resp_did := xsp_auth_child_text(m2, 'responder') or { '' }
			resp_key := xsp_auth_peer_key(opts, 'responder-key', resp_did) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: ${err.msg()}')
			}
			t := xsp_auth_transcript(m1, m2)
			sig_r := xsp_auth_child_text(m2, 'sig') or { '' }
			if !xsp_auth_sig_verify(resp_key, xsp_auth_sign_payload('responder', t, ''),
				sig_r) {
				return mk_err(xsp_auth_err_sig, 'xsp/auth-prove: responder transcript signature fails for ${resp_did}')
			}
			eph_priv := xsp_auth_opt_bytes(opts, 'eph-priv') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: opts.eph-priv required')
			}
			n_i := xsp_auth_child_bytes(m1, 'nonce') or { []u8{} }
			n_r := xsp_auth_child_bytes(m2, 'nonce') or { []u8{} }
			peer_eph := xsp_auth_child_bytes(m2, 'eph') or { []u8{} }
			k := xsp_auth_derive(eph_priv, peer_eph, n_i, n_r) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: ${err.msg()}')
			}
			tag := xsp_auth_hmac_tag(k.tag_i, t) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: ${err.msg()}')
			}
			attach := xap_map_get_node(opts, 'attach') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: opts.attach ([attach …] element) required')
			}
			if attach !is cx.Element || (attach as cx.Element).name != 'attach' {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: opts.attach must be an [attach …] element')
			}
			mut items := []cx.Node{}
			m1_did := xsp_auth_child_text(m1, 'initiator') or { '' }
			if seed := xsp_auth_opt_bytes(opts, 'key') {
				if m1_did == '' {
					return mk_err(xsp_auth_err_state, 'xsp/auth-prove: opts.key given but M1 carries no [initiator] DID')
				}
				sig := xsp_auth_sign(seed, xsp_auth_sign_payload('initiator', t, sig_r)) or {
					return mk_err(xsp_auth_err_state, 'xsp/auth-prove: ${err.msg()}')
				}
				items << xap_elem('sig', [], [crypto_string_node(sig)])
			} else if m1_did != '' {
				return mk_err(xsp_auth_err_state, 'xsp/auth-prove: M1 claims "${m1_did}" but opts.key (seed) is absent — a claimed DID must prove (N-IDENT-1)')
			}
			items << xap_elem('tag', [], [bytes_node(tag)])
			items << attach
			return xap_elem('xsp-auth', [xap_attr('phase', 'prove')], items)
		}
		// [$xsp:auth-confirm M1 M2 M3 OPTS] → M4 (responder side; verifies M3).
		// OPTS: eph-priv (responder's), session (element to return),
		// initiator-key? (32B pub — required for a non-offline initiator DID),
		// require-mutual? (bool — refuse anonymous, §4.7).
		'xsp-auth-confirm' {
			if args.len != 4 {
				return none
			}
			m1 := xsp_auth_validate_hello(args[0]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: ${err.msg()}')
			}
			m2 := xsp_auth_validate_challenge(args[1]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: ${err.msg()}')
			}
			m3 := xsp_auth_validate_prove(args[2]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: ${err.msg()}')
			}
			opts := args[3]
			eph_priv := xsp_auth_opt_bytes(opts, 'eph-priv') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: opts.eph-priv required')
			}
			n_i := xsp_auth_child_bytes(m1, 'nonce') or { []u8{} }
			n_r := xsp_auth_child_bytes(m2, 'nonce') or { []u8{} }
			peer_eph := xsp_auth_child_bytes(m1, 'eph') or { []u8{} }
			k := xsp_auth_derive(eph_priv, peer_eph, n_i, n_r) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: ${err.msg()}')
			}
			t := xsp_auth_transcript(m1, m2)
			want_tag := xsp_auth_hmac_tag(k.tag_i, t) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: ${err.msg()}')
			}
			got_tag := xsp_auth_child_bytes(m3, 'tag') or { []u8{} }
			if !xsp_auth_ct_eq(want_tag, got_tag) {
				return mk_err(xsp_auth_err_confirm, 'xsp/auth-confirm: initiator key-confirmation tag fails')
			}
			m1_did := xsp_auth_child_text(m1, 'initiator') or { '' }
			if m1_did != '' {
				sig_i := xsp_auth_child_text(m3, 'sig') or {
					return mk_err(xsp_auth_err_sig, 'xsp/auth-confirm: M1 claims "${m1_did}" but M3 carries no [sig] (N-IDENT-1)')
				}
				init_key := xsp_auth_peer_key(opts, 'initiator-key', m1_did) or {
					return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: ${err.msg()}')
				}
				sig_r := xsp_auth_child_text(m2, 'sig') or { '' }
				if !xsp_auth_sig_verify(init_key, xsp_auth_sign_payload('initiator', t,
					sig_r), sig_i) {
					return mk_err(xsp_auth_err_sig, 'xsp/auth-confirm: initiator transcript signature fails for ${m1_did}')
				}
			} else {
				if xsp_auth_opt_bool(opts, 'require-mutual') {
					return mk_err(xsp_auth_err_anonymous, 'xsp/auth-confirm: policy requires mutual authentication; anonymous initiator refused (§4.7)')
				}
				if _ := xsp_auth_child_text(m3, 'sig') {
					return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: anonymous M1 but M3 carries a [sig]')
				}
			}
			tag_r := xsp_auth_hmac_tag(k.tag_r, t) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-confirm: ${err.msg()}')
			}
			session := xap_map_get_node(opts, 'session') or {
				cx.Node(xap_elem('session', [], []))
			}
			return xap_elem('xsp-auth', [xap_attr('phase', 'confirm')], [
				cx.Node(xap_elem('tag', [], [bytes_node(tag_r)])),
				session,
			])
		}
		// [$xsp:auth-finish M1 M2 M4 OPTS] → [xsp-auth-established …]
		// (initiator side; verifies the responder key-confirmation tag).
		// OPTS: eph-priv (initiator's).
		'xsp-auth-finish' {
			if args.len != 4 {
				return none
			}
			m1 := xsp_auth_validate_hello(args[0]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-finish: ${err.msg()}')
			}
			m2 := xsp_auth_validate_challenge(args[1]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-finish: ${err.msg()}')
			}
			m4 := xsp_auth_validate_confirm(args[2]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-finish: ${err.msg()}')
			}
			opts := args[3]
			eph_priv := xsp_auth_opt_bytes(opts, 'eph-priv') or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-finish: opts.eph-priv required')
			}
			n_i := xsp_auth_child_bytes(m1, 'nonce') or { []u8{} }
			n_r := xsp_auth_child_bytes(m2, 'nonce') or { []u8{} }
			peer_eph := xsp_auth_child_bytes(m2, 'eph') or { []u8{} }
			k := xsp_auth_derive(eph_priv, peer_eph, n_i, n_r) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-finish: ${err.msg()}')
			}
			t := xsp_auth_transcript(m1, m2)
			want_tag := xsp_auth_hmac_tag(k.tag_r, t) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-finish: ${err.msg()}')
			}
			got_tag := xsp_auth_child_bytes(m4, 'tag') or { []u8{} }
			if !xsp_auth_ct_eq(want_tag, got_tag) {
				return mk_err(xsp_auth_err_confirm, 'xsp/auth-finish: responder key-confirmation tag fails')
			}
			resp_did := xsp_auth_child_text(m2, 'responder') or { '' }
			mut items := []cx.Node{}
			if session := xsp_auth_child(m4, 'session') {
				items << cx.Node(session)
			}
			return xap_elem('xsp-auth-established', [
				xap_attr('responder', resp_did),
				xap_attr('chan-id', k.chan_id.hex()),
			], items)
		}
		// [$xsp:auth-verify ROLE TRANSCRIPT SIG KEY RESPONDER-SIG?] → bool —
		// the low-level signature check (fixture/debug surface).
		'xsp-auth-verify' {
			if args.len < 4 {
				return none
			}
			role := arg_string(args[0]) or { return none }
			if role != 'initiator' && role != 'responder' {
				return mk_err(xsp_auth_err_state, 'xsp/auth-verify: role must be initiator|responder')
			}
			if args[1] !is cx.Element || (args[1] as cx.Element).name != 'xsp-auth-transcript' {
				return mk_err(xsp_auth_err_state, 'xsp/auth-verify: second arg must be an [xsp-auth-transcript …]')
			}
			t := args[1] as cx.Element
			sig := arg_string(args[2]) or { return none }
			key := arg_bytes(args[3]) or { return none }
			mut resp_sig := ''
			if args.len > 4 {
				resp_sig = arg_string(args[4]) or { '' }
			}
			if role == 'initiator' && resp_sig == '' {
				return mk_err(xsp_auth_err_state, 'xsp/auth-verify: role=initiator requires the responder signature (5th arg)')
			}
			return crypto_bool_node(xsp_auth_sig_verify(key, xsp_auth_sign_payload(role,
				t, resp_sig), sig))
		}
		// [$xsp:auth-rotate OLD-SEED NEW-DID PRIOR-CHAN-ID] → a rotation
		// continuity proof (§6.3): the OUTGOING key signs the incoming DID bound
		// to the prior channel id, so a verifier learns the new key's holder
		// provably held the old one. Paired with a fresh handshake under the new
		// key, this is the "dual-signed by old and new keys" rotation — the live
		// session and its streams survive; only the bound key advances.
		'xsp-auth-rotate' {
			if args.len != 3 {
				return none
			}
			old_seed := arg_bytes(args[0]) or { return none }
			new_did := arg_string(args[1]) or { return none }
			prior_chan := arg_string(args[2]) or { return none }
			if old_seed.len != 32 {
				return mk_err(xsp_auth_err_state, 'xsp/auth-rotate: old key seed must be 32 bytes')
			}
			payload := cx.Element{
				name:  'xsp-auth-rotate-sign'
				items: [
					cx.Node(xap_elem('new', [], [crypto_string_node(new_did)])),
					cx.Node(xap_elem('prior-chan', [], [crypto_string_node(prior_chan)])),
				]
			}
			sig := xsp_auth_sign(old_seed, payload) or {
				return mk_err(xsp_auth_err_rotate, 'xsp/auth-rotate: ${err.msg()}')
			}
			return xap_elem('xsp-auth-rotation', [
				xap_attr('new', new_did),
				xap_attr('prior-chan', prior_chan),
			], [cx.Node(xap_elem('sig', [], [crypto_string_node(sig)]))])
		}
		// [$xsp:auth-rotate-verify ROTATION OLD-DID OLD-KEY?] → bool. Verifies
		// the outgoing key (OLD-DID, offline-resolvable, or OLD-KEY supplied)
		// signed the continuity proof (§6.3). A failed check is the caller's
		// CXER-XSP-AUTH-ROTATE — the old binding stands until re-attach.
		'xsp-auth-rotate-verify' {
			if args.len < 2 {
				return none
			}
			rot := args[0]
			old_did := arg_string(args[1]) or { return none }
			if rot !is cx.Element || (rot as cx.Element).name != 'xsp-auth-rotation' {
				return crypto_bool_node(false)
			}
			rote := rot as cx.Element
			new_did := xap_elem_attr(rote, 'new')
			prior_chan := xap_elem_attr(rote, 'prior-chan')
			sig := xsp_auth_child_text(rote, 'sig') or { return crypto_bool_node(false) }
			mut old_key := []u8{}
			if args.len > 2 {
				old_key = arg_bytes(args[2]) or { []u8{} }
			}
			if old_key.len == 0 {
				old_key = did_key_bytes(old_did) or { return crypto_bool_node(false) }
			}
			payload := cx.Element{
				name:  'xsp-auth-rotate-sign'
				items: [
					cx.Node(xap_elem('new', [], [crypto_string_node(new_did)])),
					cx.Node(xap_elem('prior-chan', [], [crypto_string_node(prior_chan)])),
				]
			}
			return crypto_bool_node(xsp_auth_sig_verify(old_key, payload, sig))
		}
		// [$xsp:auth-frame-check SESSION-PRINCIPAL FRAME] → the authenticated
		// principal DID the frame commits under, or the §4.8 mismatch error.
		// This is the rule that DEMOTES the XSP `principal` field to a checked
		// label after the handshake (N-IDENT-1): a `principal-len 0` frame
		// INHERITS the session principal; a non-empty principal MUST equal it
		// byte-for-byte, else CXER-XSP-AUTH-PRINCIPAL-MISMATCH — the frame never
		// reaches the bus. FRAME is a decoded [frame … principal=…] element
		// (xsp:decode) or the principal string directly.
		'xsp-auth-frame-check' {
			if args.len != 2 {
				return none
			}
			session_principal := arg_string(args[0]) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-frame-check: session principal must be a string')
			}
			if session_principal == '' {
				return mk_err(xsp_auth_err_state, 'xsp/auth-frame-check: session principal is empty — the channel is not authenticated')
			}
			mut frame_principal := ''
			f := args[1]
			if f is cx.Element {
				frame_principal = xap_elem_attr(f, 'principal')
			} else {
				frame_principal = arg_string(f) or { '' }
			}
			if frame_principal == '' {
				// principal-len 0 → inherit the session principal (§4.8 rule 1)
				return crypto_string_node(session_principal)
			}
			if frame_principal != session_principal {
				return mk_err(xsp_auth_err_principal, 'xsp/auth-frame-check: frame principal "${frame_principal}" ≠ session principal "${session_principal}" (§4.8)')
			}
			return crypto_string_node(session_principal)
		}
		// [$xsp:auth-proof KEY COUNTER FRAME-BYTES] → 32-byte proof (§4.8).
		'xsp-auth-proof' {
			if args.len != 3 {
				return none
			}
			key := arg_bytes(args[0]) or { return none }
			counter := arg_int(args[1]) or { return none }
			frame := arg_bytes(args[2]) or { return none }
			if counter < 1 {
				return mk_err(xsp_auth_err_state, 'xsp/auth-proof: counter must be ≥ 1')
			}
			p := xsp_auth_proof_bytes(key, u64(counter), frame) or {
				return mk_err(xsp_auth_err_state, 'xsp/auth-proof: ${err.msg()}')
			}
			return bytes_node(p)
		}
		// [$xsp:auth-proof-verify KEY COUNTER FRAME-BYTES PROOF] → bool.
		'xsp-auth-proof-verify' {
			if args.len != 4 {
				return none
			}
			key := arg_bytes(args[0]) or { return none }
			counter := arg_int(args[1]) or { return none }
			frame := arg_bytes(args[2]) or { return none }
			proof := arg_bytes(args[3]) or { return none }
			if counter < 1 {
				return crypto_bool_node(false)
			}
			want := xsp_auth_proof_bytes(key, u64(counter), frame) or {
				return crypto_bool_node(false)
			}
			return crypto_bool_node(xsp_auth_ct_eq(want, proof))
		}
		else {
			return none
		}
	}
}

// xsp_auth_child_bytes_int reads a single int scalar field (M2 [version]) —
// attr-OR-child, like every other handshake field reader (a wire round trip
// atomizes the child form to an attribute).
fn xsp_auth_child_bytes_int(e cx.Element, name string) i64 {
	if n := xsp_auth_attr_node(e, name) {
		if s := vc_text_of(n) {
			return s.i64()
		}
		return -1
	}
	c := xsp_auth_child(e, name) or { return -1 }
	if c.items.len == 0 {
		return -1
	}
	it := c.items[0]
	if it is cx.ScalarNode {
		return cx.scalar_value_str_public(it.value).i64()
	}
	if it is cx.TextNode {
		return it.value.i64()
	}
	return -1
}
