// cli_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):
// the per-area test-binary umbrella. 7 source files merged verbatim (byte-identical
// helper dedupe only; the V compiler is the name-collision oracle). Fewer test
// files = fewer whole-module-graph compiles (V compilation was 99% of the gate).
// Regenerate: scripts/consolidate_tests.sh gen cli
// Manifest:   scripts/consolidation/cli.files

module main

import code
import cx
import os
import platform as _
import testenv

// ── source: vcx/tests/cli_demo_test.v ──
// #418 — `cx demo` demonstrates the CURRENT surface (double-colon types,
// [table[…]] block form), every section's output matches its narration,
// no internal step fails silently, and the retired `cx eval … --data=`
// advertisement is gone.

fn test_demo_exits_zero_with_no_errors() {
	r := os.execute('${testenv.cx_bin()} demo 2>&1')
	assert r.exit_code == 0, 'cx demo must exit 0, got ${r.exit_code}: ${r.output}'
	assert !r.output.to_lower().contains('error'), 'cx demo output contains an error: ${r.output}'
}

fn test_demo_shows_current_surface() {
	r := os.execute('${testenv.cx_bin()} demo 2>&1')
	out := r.output
	// Section 1: double-colon typed scalars, JSON round-trip with exact int64.
	assert out.contains('[port::u16 8080]'), 'typed-scalar section not on the :: surface'
	assert out.contains('"user_id": 9007199254740993'), 'int64 precision demo missing/wrong'
	// Section 2: the [table[…]] block form and a real CSV projection.
	assert out.contains('[table[name age::int city]]'), 'table section not on the [table[…]] surface'
	assert out.contains('name,age,city'), 'CSV header row missing — table conversion broke'
	assert out.contains('carol,40,lisbon'), 'CSV data rows missing — table conversion broke'
	// Section 3: the program actually EVALUATES (not just parses).
	assert out.contains("[greeting 'Hello, erik!']"), 'program section did not evaluate'
	// Retired single-colon annotations and the retired eval --data advert.
	assert !out.contains(' :u16 '), 'retired single-colon type annotation resurfaced'
	assert !out.contains('--data'), 'retired `cx eval … --data=` advertisement resurfaced (#415)'
}

// Determinism: the demo output is byte-for-byte the committed fixture
// (fixtures/expected_demo_output.txt — the smoke-eval gate diffs it too).
fn test_demo_matches_committed_fixture() {
	fixture := os.join_path(@VMODROOT, '..', 'fixtures', 'expected_demo_output.txt')
	want := os.read_file(fixture) or {
		assert false, 'cannot read ${fixture}: ${err}'
		return
	}
	r := os.execute('${testenv.cx_bin()} demo')
	assert r.exit_code == 0
	assert r.output == want, 'cx demo output drifted from fixtures/expected_demo_output.txt — regenerate it if the change is intentional'
}

// ── source: vcx/tests/cli_help_test.v ──
// #417 — the CLI help is generated from the ONE subcommand registry that
// also drives dispatch (vcx/cmd/main.v `subcommands`), the run surface and
// capability flags are documented, the --from/--to lists match the codec
// registry, and EVERY subcommand answers -h/--help with usage + exit 0.
//
// These tests drive the compiled `cx` binary as a subprocess. The expected
// sets below are deliberately hardcoded (NOT read from the binary) so a
// subcommand or capability dropped from the registry fails here instead of
// silently vanishing from both dispatch and help.

// The full dispatch surface — 23 subcommands (#417 inventory + `select` #462
// + `version` #426b + `schema` I5-s16).
const all_subcommands = ['fmt', 'canonical', 'hash', 'eq', 'diff', 'lint', 'schema', 'validate',
	'eval', 'version', 'select', 'diagram', 'code-diagram', 'code-tree', 'table', 'scaffold',
	'xap', 'demo', 'lock', 'lsp', 'store-serve', 'store-health', 'store-rotate-kek']

// The capability grant surface (code.capability_names + the two broad
// grants: `--allow-common` = the working set without secret-reveal, #833;
// `--allow-all` = the blanket opt-out).
const all_allow_flags = ['--allow-read', '--allow-write', '--allow-net', '--allow-env',
	'--allow-clock', '--allow-random', '--allow-subprocess', '--allow-eval',
	'--allow-secret-reveal', '--allow-common', '--allow-all']

// The text-convertible codec set (registry entries with a text parse half;
// the emit half is currently the same set).
const convert_formats = ['cx', 'xml', 'json', 'yaml', 'toml', 'md', 'csv', 'tsv', 'psv']

fn cx_bin() string {
	return testenv.cx_bin()
}

fn help_output() string {
	r := os.execute('${cx_bin()} --help 2>&1')
	assert r.exit_code == 0, 'cx --help must exit 0, got ${r.exit_code}: ${r.output}'
	return r.output
}

// ── (a) every dispatch-table subcommand appears in `cx --help` ───────────────

fn test_help_lists_every_subcommand() {
	out := help_output()
	for name in all_subcommands {
		assert out.contains('\n  ${name} '), 'subcommand `${name}` missing from cx --help'
	}
}

fn test_help_documents_the_run_surface() {
	out := help_output()
	// The primary run-a-program usage (#417: was absent entirely).
	// PYE-2 (#926): the run surface is `cx [flags] FILE.cx [args...]` —
	// flags bind before the resource, everything after it is program argv.
	assert out.contains('cx [flags] FILE.cx [args...]'), 'primary run usage missing from cx --help'
	assert out.contains('stdin'), 'stdin behavior missing from cx --help'
	assert out.contains("-e 'PROGRAM'"), 'inline-program usage missing from cx --help'
	// The separate data input (#415) and the unknown-flag contract.
	assert out.contains('--data='), 'run-surface --data flag missing from cx --help'
	assert out.contains('Unknown flags are hard usage errors'), 'unknown-flag contract missing from cx --help'
	// Every capability grant flag.
	for flag in all_allow_flags {
		assert out.contains(flag), 'capability flag ${flag} missing from cx --help'
	}
	// The old dangling parenthetical (`Public Table API surface ().`) is gone.
	assert !out.contains('().'), 'dangling empty parenthetical back in cx --help'
}

// ── (b) `cx <sub> --help` exits 0 with usage — uniformly, all 23 ─────────────

fn test_every_subcommand_help_exits_zero_with_usage() {
	for name in all_subcommands {
		for flag in ['--help', '-h'] {
			r := os.execute('${cx_bin()} ${name} ${flag} 2>&1')
			assert r.exit_code == 0, 'cx ${name} ${flag} must exit 0, got ${r.exit_code}: ${r.output}'
			assert r.output.starts_with('Usage: cx ${name}'), 'cx ${name} ${flag} must print its usage, got: ${r.output}'
		}
	}
}

// ── (c) the --from/--to lists in help match the accepted set ─────────────────

fn extract_format_list(out string, label string) []string {
	for line in out.split('\n') {
		t := line.trim_space()
		if t.starts_with(label) {
			return t.all_after(label).trim_space().split('|')
		}
	}
	assert false, '`${label}` line missing from cx --help'
	return []
}

fn test_help_from_to_lists_match_accepted_set() {
	out := help_output()
	from_list := extract_format_list(out, '--from:')
	to_list := extract_format_list(out, '--to:')
	assert from_list == convert_formats, 'help --from list ${from_list} != accepted ${convert_formats}'
	assert to_list == convert_formats, 'help --to list ${to_list} != accepted ${convert_formats}'
	// Behavior probe: every advertised format is accepted by the convert
	// pipeline (no "unknown source format" / "has no text parser"), …
	for f in from_list {
		r := os.execute("printf 'x' | ${cx_bin()} --from=${f} --to=cx - 2>&1")
		assert !r.output.contains('unknown source format'), '--from=${f} advertised but rejected: ${r.output}'
		assert !r.output.contains('has no text parser'), '--from=${f} advertised but has no parser: ${r.output}'
	}
	// … and a name outside the list is rejected with the registry error.
	r := os.execute("printf 'x' | ${cx_bin()} --from=nope --to=cx - 2>&1")
	assert r.exit_code != 0, '--from=nope must fail'
	assert r.output.contains('unknown source format'), 'unknown --from must name the registry error, got: ${r.output}'
}

// ── source: vcx/tests/scaffold_cli_test.v ──
// #448 — `cx scaffold <kind>` must emit CURRENT-surface CX for every kind.
//
// The retired single-colon type annotations (`port:u16=8080`,
// `[date :date …]`) parse on the current surface as namespace-qualified
// names (lexicon.ebnf [L50]/[L51]): `cx scaffold config | cx --json` showed
// a `"port:u16"` KEY instead of a u16-typed `port` — on the tool whose demo
// advertises exactly that pipeline to newcomers. These lanes drive the BUILT
// BINARY over every scaffold kind and assert (a) the output parses and
// round-trips (`--json`, `canonical`, `eq` self), (b) no retired surface
// pattern survives in the emitted text, and (c) a per-kind semantic probe
// (typed port / decimal price / ::date element / logfmt events / table
// info). AST-level assertions on the template constants live in
// vcx/cmd/scaffold_test.v.

const scaffold_kinds = ['config', 'data', 'doc', 'log', 'table']

fn scaffold_out(kind string) string {
	r := os.execute('${cx_bin()} scaffold ${kind}')
	assert r.exit_code == 0, 'cx scaffold ${kind} exited ${r.exit_code}: ${r.output}'
	assert r.output.len > 0, 'cx scaffold ${kind} emitted nothing'
	return r.output
}

fn tmp_scaffold_file(kind string) string {
	path := os.join_path(os.temp_dir(), 'cx_scaffold_${kind}_${os.getpid()}.cx')
	os.write_file(path, scaffold_out(kind)) or { panic(err) }
	return path
}

// Scalar type names that the RETIRED single-colon annotation could glue.
// Current surface glues types with a DOUBLE colon (`::u16`); a single glued
// colon is the namespace qualifier.
const retired_glued_types = ['u8', 'u16', 'u32', 'u64', 'i8', 'i16', 'i32', 'i64', 'f16', 'f32',
	'f64', 'int', 'float', 'bool', 'decimal', 'bigint', 'date', 'datetime', 'time', 'atom',
	'bytes', 'string', 'null']

// first_single_colon_type returns the first retired single-colon type
// annotation (`name:type=…`, `[name :type …]`) found in src, or none.
// A `::` never matches: the first colon is skipped because the NEXT char is
// a colon, the second because the PREVIOUS char is one.
fn first_single_colon_type(src string) ?string {
	for i := 0; i < src.len; i++ {
		if src[i] != `:` {
			continue
		}
		if i > 0 && src[i - 1] == `:` {
			continue
		}
		if i + 1 < src.len && src[i + 1] == `:` {
			continue
		}
		rest := src[i + 1..]
		for t in retired_glued_types {
			if !rest.starts_with(t) {
				continue
			}
			j := i + 1 + t.len
			if j >= src.len {
				return src[i..]
			}
			nc := src[j]
			if nc == `=` || nc == ` ` || nc == `]` || nc == `[` || nc == `\n` {
				return src[i..j]
			}
		}
	}
	return none
}

// ── (a) every kind parses and round-trips through the same binary ────────────

fn test_every_kind_parses_and_round_trips() {
	for kind in scaffold_kinds {
		f := tmp_scaffold_file(kind)
		j := os.execute('${cx_bin()} --json ${f}')
		assert j.exit_code == 0, 'cx --json on scaffold ${kind} exited ${j.exit_code}: ${j.output}'
		c := os.execute('${cx_bin()} canonical ${f}')
		assert c.exit_code == 0, 'cx canonical on scaffold ${kind} exited ${c.exit_code}: ${c.output}'
		e := os.execute('${cx_bin()} eq ${f} ${f}')
		assert e.exit_code == 0, 'cx eq self on scaffold ${kind} exited ${e.exit_code}: ${e.output}'
		os.rm(f) or {}
	}
}

// ── (b) no retired surface pattern in the emitted text ───────────────────────

fn test_every_kind_emits_no_retired_surface() {
	for kind in scaffold_kinds {
		out := scaffold_out(kind)
		assert !out.contains(':table['), 'cx scaffold ${kind} emits the retired :table[ block form'
		if hit := first_single_colon_type(out) {
			assert false, 'cx scaffold ${kind} emits a retired single-colon type annotation: `${hit}` (current surface glues types with `::`)'
		}
	}
}

// ── (c) per-kind semantic probes ──────────────────────────────────────────────

fn test_config_semantics() {
	f := tmp_scaffold_file('config')
	defer {
		os.rm(f) or {}
	}
	c := os.execute('${cx_bin()} canonical ${f}')
	assert c.exit_code == 0, c.output
	assert c.output.contains('port::u16=8080'), 'canonical config lost the typed port: ${c.output}'
	assert c.output.contains('pool_size::u8=16'), 'canonical config lost the typed pool_size: ${c.output}'
	assert c.output.contains('connect_timeout_ms::u32=5000'), 'canonical config lost the typed connect_timeout_ms: ${c.output}'
	assert c.output.contains('env=dev'), 'canonical config lost the env attribute: ${c.output}'
	assert !c.output.contains("' env=dev '"), 'env=dev mis-parsed as a TEXT child instead of an attribute: ${c.output}'
	j := os.execute('${cx_bin()} --json ${f}')
	assert j.exit_code == 0, j.output
	assert !j.output.contains('port:u16'), 'JSON view shows a namespace-qualified "port:u16" key: ${j.output}'
	assert j.output.contains('8080'), 'JSON view lost the port value: ${j.output}'
}

fn test_data_semantics() {
	f := tmp_scaffold_file('data')
	defer {
		os.rm(f) or {}
	}
	c := os.execute('${cx_bin()} canonical ${f}')
	assert c.exit_code == 0, c.output
	assert c.output.contains('price=12.50'), 'canonical data lost the decimal price (I1 2b: bare fixed-point IS decimal — annotation shed): ${c.output}'
	j := os.execute('${cx_bin()} --json ${f}')
	assert j.exit_code == 0, j.output
	assert !j.output.contains('price:decimal'), 'JSON view shows a namespace-qualified "price:decimal" key: ${j.output}'
	// decimal converts to a JSON STRING (precision-preserving, conversions.md)
	assert j.output.contains('"12.50"'), 'JSON view lost the decimal price (expected precision-preserving "12.50"): ${j.output}'
}

fn test_doc_semantics() {
	f := tmp_scaffold_file('doc')
	defer {
		os.rm(f) or {}
	}
	c := os.execute('${cx_bin()} canonical ${f}')
	assert c.exit_code == 0, c.output
	// I1 row 2: the redundant `::date` ascription strips in canonical — the
	// date-shaped bare image re-types on its own (one value, one spelling).
	assert c.output.contains('[date 2026-05-12]'), 'canonical doc changed the date element: ${c.output}'
	assert !c.output.contains('[date::date'), 'canonical doc kept the redundant ::date ascription: ${c.output}'
	j := os.execute('${cx_bin()} --json ${f}')
	assert j.exit_code == 0, j.output
	assert !j.output.contains('":date"'), 'JSON view shows the retired ` :date ` annotation as a child token: ${j.output}'
	assert j.output.contains('2026-05-12'), 'JSON view lost the date value: ${j.output}'
}

fn test_log_semantics() {
	f := tmp_scaffold_file('log')
	defer {
		os.rm(f) or {}
	}
	c := os.execute('${cx_bin()} canonical ${f}')
	assert c.exit_code == 0, c.output
	assert c.output.contains('level=info'), 'canonical log lost the logfmt attributes: ${c.output}'
	assert c.output.contains("err='connection refused'"), 'canonical log lost the quoted err value: ${c.output}'
}

fn test_table_semantics() {
	f := tmp_scaffold_file('table')
	defer {
		os.rm(f) or {}
	}
	r := os.execute('${cx_bin()} table info ${f}')
	assert r.exit_code == 0, 'cx table info on its own scaffold exited ${r.exit_code}: ${r.output}'
	assert r.output.contains('rows: 3'), r.output
	assert r.output.contains('cols: 5'), r.output
}

// ── source: vcx/tests/tooling_test.v ──
// Tests for the canonical-form tooling C ABI (Phase 6 / spec/abi.md §2.6):
//   cx_text_fmt        — lossless canonical (preserves comments)
//   cx_text_canonical  — strict canonical (strips presentation)
//   cx_text_hash       — SHA-256 hex of strict canonical bytes
//   cx_text_eq         — strict canonical equality

fn test_fmt_preserves_comments() {
	src := '[config
  [; a comment ]
  [server host=localhost port=8080]
]'
	out := cx.cx_text_fmt(src) or { panic(err) }
	assert out.contains('a comment'), 'fmt must preserve comments; got: ${out}'
	assert out.contains('host=localhost')
}

fn test_canonical_strips_comments() {
	src := '[config
  [; a comment ]
  [server host=localhost port=8080]
]'
	out := cx.cx_text_canonical(src) or { panic(err) }
	assert !out.contains('a comment'), 'canonical must strip comments; got: ${out}'
	assert out.contains('host=localhost')
}

fn test_canonical_normalizes_whitespace() {
	src1 := '[config
  [server host=localhost port=8080]
]'
	src2 := '[config [server host=localhost port=8080]]'
	c1 := cx.cx_text_canonical(src1) or { panic(err) }
	c2 := cx.cx_text_canonical(src2) or { panic(err) }
	assert c1 == c2, 'whitespace-equivalent inputs must canonicalize the same\nc1=${c1}\nc2=${c2}'
}

fn test_hash_is_tagged_address() {
	// I1 stream 19: self-describing addresses — `sha2-256:` + 64 hex.
	src := '[config [server host=localhost]]'
	h := cx.cx_text_hash(src) or { panic(err) }
	assert h.len == 73, 'tagged sha2-256 address is 73 chars; got len=${h.len}'
	algo, hex := cx.cx_parse_tagged_address(h) or { panic(err) }
	assert algo == 'sha2-256'
	for c in hex {
		ok := (c >= `0` && c <= `9`) || (c >= `a` && c <= `f`)
		assert ok, 'digest must be lowercase hex; got char ${rune(c).str()}'
	}
}

fn test_hash_is_stable() {
	src := '[config [server host=localhost port=8080]]'
	h1 := cx.cx_text_hash(src) or { panic(err) }
	h2 := cx.cx_text_hash(src) or { panic(err) }
	assert h1 == h2
}

fn test_hash_changes_when_data_changes() {
	a := '[config [server host=localhost port=8080]]'
	b := '[config [server host=localhost port=8081]]'
	ha := cx.cx_text_hash(a) or { panic(err) }
	hb := cx.cx_text_hash(b) or { panic(err) }
	assert ha != hb, 'different ports must hash differently'
}

fn test_eq_equivalent_inputs() {
	a := '[config
  [; comment one ]
  [server host=localhost port=8080]
]'
	b := '[config [server host=localhost port=8080]]'
	assert cx.cx_text_eq(a, b) or { panic(err) }
}

fn test_eq_different_inputs() {
	a := '[config [server host=a]]'
	b := '[config [server host=b]]'
	assert !cx.cx_text_eq(a, b) or { panic(err) }
}

fn test_fmt_idempotent() {
	src := '[config
  [server host=localhost port=8080 active=true]
  [database host=db.example.com]
]'
	once := cx.cx_text_fmt(src) or { panic(err) }
	twice := cx.cx_text_fmt(once) or { panic(err) }
	assert once == twice, 'fmt must be idempotent\nonce=${once}\ntwice=${twice}'
}

fn test_canonical_idempotent() {
	src := '[config
  [- ignore]
  [server host=localhost]
]'
	once := cx.cx_text_canonical(src) or { panic(err) }
	twice := cx.cx_text_canonical(once) or { panic(err) }
	assert once == twice, 'canonical must be idempotent'
}

// ── #455: a [; comment ] child must not terminate the attribute run ─────────
// Comments are lexical trivia (lexicon.ebnf §1 [L2]/[L3]: "skipped; never
// reach the parser"). A bare `key=value` line after a `[; … ]` child is the
// SAME attribute it is without the comment — pre-fix the data reader broke
// the ElementMeta loop at `[;` and read it as TEXT, splitting the strict-
// canonical (hash-bearing) lane away from fmt/--json/eval.

fn test_canonical_attr_after_comment_child() {
	src := '[config
 [; c ]
 env=dev
 [server host=localhost]
]'
	out := cx.cx_text_canonical(src) or { panic(err) }
	assert out.contains('env=dev'), 'env=dev must stay an attribute; got: ${out}'
	assert !out.contains("' env=dev '"), 'env=dev must not degrade to text; got: ${out}'
}

fn test_hash_is_comment_insensitive_around_attrs() {
	// Identical data, comment in three positions (absent / before the attr
	// line / after it) — strict canonical strips comments (canonical.md
	// §2.9), so all three MUST share one hash.
	bare := '[config
 env=dev
 [server host=localhost]
]'
	comment_first := '[config
 [; c ]
 env=dev
 [server host=localhost]
]'
	comment_after := '[config
 env=dev
 [; c ]
 [server host=localhost]
]'
	h0 := cx.cx_text_hash(bare) or { panic(err) }
	h1 := cx.cx_text_hash(comment_first) or { panic(err) }
	h2 := cx.cx_text_hash(comment_after) or { panic(err) }
	assert h0 == h2, 'comment after the attr line must not move the hash'
	assert h0 == h1, 'comment before the attr line must not move the hash (#455)'
	assert cx.cx_text_eq(comment_first, bare) or { panic(err) }
}

fn test_cx_text_fmt_attr_after_comment_child() {
	// The lossless data formatter's own reading of the doc: env=dev stays an
	// attribute and the comment survives on its own body line. (The CLI-lane
	// `cx fmt` quoting-flip regression is pinned in fmt_lossless_test.v,
	// which can exercise code.fmt_source.)
	src := '[config
 [; c ]
 env=dev
 [server host=localhost]
]'
	out := cx.cx_text_fmt(src) or { panic(err) }
	assert out.contains('[; c ]'), 'fmt must preserve the comment; got: ${out}'
	assert out.contains('env=dev'), 'fmt must keep the attr; got: ${out}'
	assert !out.contains("' env=dev '"), 'env=dev must not degrade to text; got: ${out}'
}

// ── #469 zone 1: a comment between bare text runs is canonical-inert ────────
// Comments are lexical trivia (lexicon.ebnf §1 [L2]/[L3]) — a bare text run
// interrupted by a `[; … ]` block comment or a `# …` line comment reads as
// the SAME single text node it is without the comment ("a b"), so strict
// canonical / hash / eq are those of the comment-free document. Pre-fix the
// body reader flushed the run at the comment, splitting it into two text
// nodes ('a ' / ' b') and moving the hash.

fn test_hash_is_comment_insensitive_in_text_runs() {
	bare := '[config a b]'
	block_mid := '[config a [; c ] b]'
	line_mid := '[config a\n # c\n b\n]'
	block_lead := '[config [; c ] a b]'
	block_trail := '[config a b [; c ]]'
	h0 := cx.cx_text_hash(bare) or { panic(err) }
	assert (cx.cx_text_hash(block_mid) or { panic(err) }) == h0, 'block comment mid-run must not move the hash (#469)'
	assert (cx.cx_text_hash(line_mid) or { panic(err) }) == h0, 'line comment mid-run must not move the hash (#469)'
	assert (cx.cx_text_hash(block_lead) or { panic(err) }) == h0, 'leading comment must not move the hash (#469)'
	assert (cx.cx_text_hash(block_trail) or { panic(err) }) == h0, 'trailing comment must not move the hash (#469)'
	assert cx.cx_text_eq(block_mid, bare) or { panic(err) }
}

fn test_canonical_text_run_not_split_by_comment() {
	out := cx.cx_text_canonical('[config a [; c ] b]') or { panic(err) }
	assert out.trim_space() == '[config a b]', 'comment must not split the text run; got: ${out}'
}

fn test_comment_erasure_glue_semantics_in_text_runs() {
	// The comment contributes NOTHING to the text; the real whitespace
	// around it is what separates. (A comment opener GLUED to the left
	// token — `a[; c ]b` — is not a comment at all: mid-token `[` stays
	// text under the body tokenizer, pre-existing surface.)
	left_ws := cx.cx_text_canonical('[config a [; c ]b]') or { panic(err) }
	assert left_ws.trim_space() == '[config a b]', 'pre-comment space survives erasure; got: ${left_ws}'
	both_ws := cx.cx_text_canonical('[config a [; c ] b]') or { panic(err) }
	assert both_ws.trim_space() == '[config a b]', 'ws on both sides joins once; got: ${both_ws}'
}

// ── #469 zone 2: ElementMeta `# …` line comments are hash-inert AND kept ────

fn test_hash_is_comment_insensitive_elementmeta_line_comment() {
	bare := '[config\n [child v]\n]'
	with_line := '[config\n # c\n [child v]\n]'
	h0 := cx.cx_text_hash(bare) or { panic(err) }
	assert (cx.cx_text_hash(with_line) or { panic(err) }) == h0, 'ElementMeta line comment must not move the hash'
}

fn test_cx_text_fmt_keeps_elementmeta_line_comment() {
	src := '[config\n # c\n [child v]\n]'
	out := cx.cx_text_fmt(src) or { panic(err) }
	assert out.contains('# c'), 'lossless fmt must keep the ElementMeta line comment (#469); got: ${out}'
	twice := cx.cx_text_fmt(out) or { panic(err) }
	assert twice == out, 'fmt must be idempotent on the retained line comment; got: ${twice}'
}

// ── #469 zone 3: the pooled table emitter re-emits retained head comments ───

fn test_cx_text_fmt_keeps_comment_before_table_head() {
	src := '[users [; c ] [table[name age]]\n alice 30\n bob 25\n]'
	out := cx.cx_text_fmt(src) or { panic(err) }
	assert out.contains('[; c ]'), 'table emit must keep the retained head comment (#469); got: ${out}'
	assert out.contains('[table[name age]]'), 'pooled table head must survive; got: ${out}'
	assert out.contains('alice 30'), 'rows must survive; got: ${out}'
	twice := cx.cx_text_fmt(out) or { panic(err) }
	assert twice == out, 'fmt must be idempotent on the comment-bearing table; got: ${twice}'
	// strict canonical still strips it — hash is comment-insensitive
	bare := '[users [table[name age]]\n alice 30\n bob 25\n]'
	h0 := cx.cx_text_hash(bare) or { panic(err) }
	assert (cx.cx_text_hash(src) or { panic(err) }) == h0, 'table head comment must not move the hash'
}

fn test_cx_text_fmt_keeps_line_comment_before_table_head() {
	src := '[users # c\n [table[name age]]\n alice 30\n]'
	out := cx.cx_text_fmt(src) or { panic(err) }
	assert out.contains('# c'), 'table emit must keep the retained line comment (#469); got: ${out}'
	twice := cx.cx_text_fmt(out) or { panic(err) }
	assert twice == out, 'fmt must be idempotent; got: ${twice}'
}

// ── source: vcx/tests/cx_lang_test.v ──
// Z-row — cx:lang attribute + inherited-scope semantics per
// spec/i18n.md §1. Verifies that resolve_namespaces (and its
// language-scope pass) populates Element.lang_resolved per the
// spec's inheritance rules:
//   §1.3 — descendant inherits ancestor's cx:lang until redeclared
//   §1.4 — cx:lang="" shadows without substituting (Some(""))
//   §1.1 — values are BCP 47 tags; parser does not validate against
//          the IANA registry (any well-formed tag passes)

fn find_element_named(items []cx.Node, name string) ?cx.Element {
	for it in items {
		if it is cx.Element {
			el := it as cx.Element
			if el.name == name {
				return el
			}
			if found := find_element_named(el.items, name) {
				return found
			}
		}
	}
	return none
}

fn test_cxlang_local_declaration() {
	doc := cx.parse('[para cx:lang=en Hello]') or { panic(err) }
	root := find_element_named(doc.elements, 'para') or {
		panic('no para element')
	}
	assert root.lang() == 'en', 'got: ${root.lang()}'
}

fn test_cxlang_inheritance() {
	src := '[doc cx:lang=en [title English] [body [span English content]]]'
	doc := cx.parse(src) or { panic(err) }
	span := find_element_named(doc.elements, 'span') or {
		panic('no span element')
	}
	assert span.lang() == 'en', 'span should inherit en, got: ${span.lang()}'
}

fn test_cxlang_redeclaration() {
	src := '[doc cx:lang=en [aside cx:lang=fr [deep Still French]]]'
	doc := cx.parse(src) or { panic(err) }
	deep := find_element_named(doc.elements, 'deep') or {
		panic('no deep element')
	}
	assert deep.lang() == 'fr', 'deep should inherit fr, got: ${deep.lang()}'
}

fn test_cxlang_empty_shadows() {
	src := "[doc cx:lang=en [secret cx:lang='' [data x]]]"
	doc := cx.parse(src) or { panic(err) }
	data := find_element_named(doc.elements, 'data') or {
		panic('no data element')
	}
	// Per spec §1.4, cx:lang="" means "no language declared for this
	// subtree" — Element.lang() flattens to "" (same as no scope).
	assert data.lang() == '', 'data should have shadowed scope, got: ${data.lang()}'
}

fn test_cxlang_no_declaration_anywhere() {
	src := '[doc [title plain] [body plain]]'
	doc := cx.parse(src) or { panic(err) }
	body := find_element_named(doc.elements, 'body') or {
		panic('no body element')
	}
	assert body.lang() == '', 'no cx:lang in scope, got: ${body.lang()}'
}

fn test_cxlang_bcp47_passthrough() {
	// BCP 47 forms per spec/i18n.md §1.1.
	cases := [
		'en',
		'zh-Hans',
		'en-US',
		'zh-Hans-CN',
		'de-1996',
		'x-klingon',
	]
	for tag in cases {
		src := '[el cx:lang=${tag} content]'
		doc := cx.parse(src) or { panic('parse failed for tag ${tag}: ${err}') }
		el := find_element_named(doc.elements, 'el') or {
			panic('no el element for tag ${tag}')
		}
		assert el.lang() == tag, 'tag ${tag}: got ${el.lang()}'
	}
}

fn test_cxlang_sibling_isolation() {
	// Sibling subtrees with different cx:lang values do not bleed into
	// each other.
	src := '[doc [en cx:lang=en [body english]] [fr cx:lang=fr [body french]]]'
	doc := cx.parse(src) or { panic(err) }
	root_doc := doc.elements[0] as cx.Element
	en_branch := root_doc.items[0] as cx.Element
	fr_branch := root_doc.items[1] as cx.Element
	en_body := en_branch.items[0] as cx.Element
	fr_body := fr_branch.items[0] as cx.Element
	assert en_body.lang() == 'en', 'en/body: ${en_body.lang()}'
	assert fr_body.lang() == 'fr', 'fr/body: ${fr_body.lang()}'
}

// ── source: vcx/tests/term_test.v ──
// term_test.v — #30 cx-x/term (Stage 1): the VT/ANSI key decoder (unit-tested
// directly with byte sequences — no tty needed), the real termios + poll-read
// path (exercised over a pseudo-terminal via term_pty_selftest), and the
// capability / non-tty error paths (via the CLI).

fn key_name(ev cx.Node) string {
	if ev is cx.Element {
		for a in ev.attrs {
			if a.name == 'name' {
				return cx.scalar_value_str_public(a.value)
			}
		}
	}
	return ''
}

fn decode_name(bytes string) string {
	ev, _ := code.cx_term_decode(bytes.bytes())
	return key_name(ev)
}

// ── VT/ANSI decoder (pure, no tty) ───────────────────────────────────────────

fn test_decode_arrows() {
	assert decode_name('\x1b[A') == 'up', 'up'
	assert decode_name('\x1b[B') == 'down', 'down'
	assert decode_name('\x1b[C') == 'right', 'right'
	assert decode_name('\x1b[D') == 'left', 'left'
}

fn test_decode_nav_and_fn() {
	assert decode_name('\x1b[H') == 'home', 'home'
	assert decode_name('\x1b[3~') == 'delete', 'delete'
	assert decode_name('\x1b[5~') == 'pageup', 'pageup'
	assert decode_name('\x1b[6~') == 'pagedown', 'pagedown'
	assert decode_name('\x1bOP') == 'f1', 'f1'
	assert decode_name('\x1b[15~') == 'f5', 'f5'
}

fn test_decode_controls() {
	assert decode_name('\r') == 'enter', 'enter (CR)'
	assert decode_name('\n') == 'enter', 'enter (LF)'
	assert decode_name('\t') == 'tab', 'tab'
	assert decode_name('\x7f') == 'backspace', 'backspace'
	assert decode_name('\x1b') == 'escape', 'lone escape'
}

fn test_decode_printable_and_chords() {
	assert decode_name('a') == 'a', 'printable a'
	assert decode_name('Z') == 'Z', 'printable Z'
	// ctrl-a is byte 0x01 → name "a" with the ctrl modifier.
	ev, _ := code.cx_term_decode('\x01'.bytes())
	assert key_name(ev) == 'a', 'ctrl-a name'
	// alt-a is ESC then 'a'.
	assert decode_name('\x1ba') == 'a', 'alt-a name'
}

fn test_decode_consumes_bytes() {
	_, n := code.cx_term_decode('\x1b[A'.bytes())
	assert n == 3, 'arrow consumes 3 bytes, got ${n}'
	_, n2 := code.cx_term_decode('ab'.bytes())
	assert n2 == 1, 'single printable consumes 1 byte, got ${n2}'
}

// ── real termios + poll-read path over a pseudo-terminal ─────────────────────

fn test_pty_roundtrip_real_termios() {
	// term_pty_selftest opens a pty, enters raw on the slave, writes the bytes
	// to the master, reads them back via the poll-gated cx_term_read, decodes.
	assert code.term_pty_selftest('\x1b[A') == 'up', 'pty: arrow up did not round-trip raw read+decode'
	assert code.term_pty_selftest('a') == 'a', 'pty: printable did not round-trip'
	assert code.term_pty_selftest('\r') == 'enter', 'pty: enter did not round-trip'
}

// ── term:select multi-source poll shim (real pipes, headless) ────────────────

fn test_select_first_ready_source() {
	// Two pipes; write to the second → the shim must report index 1 ready.
	assert code.term_select_selftest(1) == 'src1', 'select: did not pick the ready (2nd) source'
	// Write to the first → index 0.
	assert code.term_select_selftest(0) == 'src0', 'select: did not pick the ready (1st) source'
}

fn test_select_timeout_when_idle() {
	// Neither pipe written → the shim times out rather than blocking.
	assert code.term_select_selftest(-1) == 'timeout', 'select: should time out when no source is ready'
}

// ── capability / non-tty error paths (CLI) ───────────────────────────────────

fn cx_bin_tm() string {
	return testenv.cx_bin()
}

fn run_tm(src string, allow bool) os.Result {
	f := os.join_path(os.temp_dir(), 'cx_tm_${os.getpid()}_${src.len}.cx')
	os.write_file(f, src) or { panic('write: ${err}') }
	defer { os.rm(f) or {} }
	cap := if allow { '--allow-read ' } else { '' }
	return os.execute('${cx_bin_tm()} ${cap}${f}')
}

fn test_is_tty_false_headless() {
	r := run_tm("[?lib 'cx-x/term'] [\$term:is-tty]", false)
	assert r.exit_code == 0, 'errored: ${r.output}'
	assert r.output.trim_space() == 'false', 'headless is-tty should be false: ${r.output}'
}

fn test_size_cap_denied() {
	r := run_tm("[?lib 'cx-x/term'] [\$term:size]", false)
	assert r.output.contains('CXER0271'), 'no `read` cap → CXER0271: ${r.output}'
}

fn test_size_non_tty_errs() {
	r := run_tm("[?lib 'cx-x/term'] [\$term:size]", true)
	assert r.output.contains('CXER3450'), 'non-tty size → CXER3450: ${r.output}'
}

fn test_raw_mode_cap_denied() {
	r := run_tm("[?lib 'cx-x/term'] [\$term:raw-mode]", false)
	assert r.output.contains('CXER0271'), 'no `read` cap → CXER0271: ${r.output}'
}

fn test_select_cap_denied() {
	r := run_tm("[?lib 'cx-x/term'] [\$term:select {timeout: 10}]", false)
	assert r.output.contains('CXER0271'), 'no `read` cap → CXER0271: ${r.output}'
}

// #861 (R7.1): read-event forwards the primitive's optional timeout.
fn test_read_event_timeout_cap_denied() {
	// the widened call shape resolves and still hits the cap guard first.
	r := run_tm("[?lib 'cx-x/term'] [\$term:read-event timeout=10]", false)
	assert r.output.contains('CXER0271'), 'no `read` cap → CXER0271: ${r.output}'
}

fn test_read_event_timeout_returns_timeout_element() {
	// with the read cap and an exhausted stdin, the bounded read yields the
	// [timeout] element the fn-doc promises — unreachable before the widening
	// (the zero-arg wrapper always blocked). EOF and timer expiry share the
	// n==0 arm by design (spec x/term.md §1 note).
	f := os.join_path(os.temp_dir(), 'cx_tm861_${os.getpid()}.cx')
	os.write_file(f, "[?lib 'cx-x/term'] [\$term:read-event timeout=10]") or {
		panic('write: ${err}')
	}
	defer { os.rm(f) or {} }
	r := os.execute('${cx_bin_tm()} --allow-read ${f} < /dev/null')
	assert r.exit_code == 0, 'errored: ${r.output}'
	assert r.output.contains('timeout'), 'bounded read-event must yield [timeout]: ${r.output}'
}

fn test_select_timer_only_returns_timeout() {
	// keys:false, no sources, a short timer → a deterministic `[timeout]`.
	r := run_tm("[?lib 'cx-x/term'] [\$term:select {keys: false timeout: 10}]", true)
	assert r.exit_code == 0, 'errored: ${r.output}'
	assert r.output.contains('timeout'), 'timer-only select should yield [timeout]: ${r.output}'
}

// ── source: vcx/tests/directive_args_test.v ──
// ── §D7 directive-arg-array shapes (parser tests) ───────────────
//
// Covers the §F-parser landing of resolutions 1.d (slot-as-body) and
// 2.i (first-`[…]`-in-`[?Name …]`-is-always-Array). These tests pin
// the parse-level expectations of the new uniform directive shape
// before the program evaluator rewrite (§F-evaluator) ratifies them
// behaviorally.
//
// Companion specs: §D6/§D7, code.md.

fn parse_one(src string) cx.Node {
	d := cx.parse(src) or { panic('parse: ${err}') }
	assert d.elements.len > 0
	return d.elements[0]
}

// ── 2.i: single-slot `[?Name [arg]]` forces the body `[…]` to Array ──────────

fn test_include_single_slot() {
	// `[?include [path]]` — no comma in arg array; parser must still
	// route the inner `[…]` to Array (not Element named "path") per
	// resolution 2.i (2026-05-12) which implements.
	n := parse_one("[?include ['partials/card.cx']]")
	assert n is cx.EvalDirectiveNode
	d := n as cx.EvalDirectiveNode
	assert d.name == 'include'
	assert d.items.len == 1
	arg := d.items[0]
	assert arg is cx.ArrayNode
	arr := arg as cx.ArrayNode
	assert arr.items.len == 1
	slot0 := arr.items[0]
	// RE-DERIVED at the #795 batch (#790): a quoted ArgArray slot item
	// is a string SCALAR (kind-faithful; previously TextNode).
	assert slot0 is cx.ScalarNode
	s0 := slot0 as cx.ScalarNode
	assert s0.data_type == .string_type
	assert cx.scalar_value_str(s0.value) == 'partials/card.cx'
}

fn test_use_single_slot_bare_name() {
	// Per grammar [59] every directive child is a uniform BodyItem, so
	// `[card-row]` disambiguates exactly as it would in an element body
	// (D1): bare name, no commas → Element. (The retired ArgArray
	// machinery forced first-`[…]` to Array here; [59] supersedes.)
	//
	// Vehicle changed `?use` → `?include` (#760 / RULED 760-1a): `?use`
	// was a dead `[59a]` reservation with no evaluator dispatch and has
	// retired, so it now parses as a PI [32] exactly like any other name
	// outside the §4.1 registry — which is what grammar [59a]'s own
	// deletion note already said should happen. The property under test is
	// about a directive's BODY-ITEM disambiguation, not about which head
	// carries it, so a head that is still registered carries it unchanged.
	n := parse_one("[?include [card-row]]")
	d := n as cx.EvalDirectiveNode
	assert d.items.len == 1
	el := d.items[0] as cx.Element
	assert el.name == 'card-row'
	assert el.attrs.len == 0
	assert el.items.len == 0
}

fn test_empty_arg_array() {
	// `[?if []]` — explicit empty arg array. Distinct from `[?if]`
	// (no arg array at all).
	n := parse_one('[?if []]')
	d := n as cx.EvalDirectiveNode
	assert d.items.len == 1
	arg := d.items[0] as cx.ArrayNode
	assert arg.items.len == 0
}

fn test_no_arg_array() {
	// `[?if]` — ε ArgArray case. EvalDirective.items is empty.
	n := parse_one('[?if]')
	d := n as cx.EvalDirectiveNode
	assert d.items.len == 0
}

// ── 1.d: whitespace-bearing slot bodies (expression text) ────────────────────

fn test_whitespace_expr_slot() {
	// `[?if [@stock > 0, in stock, out]]` — slot 0 is a CXPath
	// comparison with internal whitespace. Pre-1.d the slot parser
	// stopped at whitespace; 1.d coalesces consecutive bare tokens
	// into a single TextNode preserving CXPath shape for evaluator
	// re-parse at eval time.
	n := parse_one('[?if [@stock > 0, in stock, out]]')
	d := n as cx.EvalDirectiveNode
	arr := d.items[0] as cx.ArrayNode
	assert arr.items.len == 3
	assert (arr.items[0] as cx.TextNode).value == '@stock > 0'
	assert (arr.items[1] as cx.TextNode).value == 'in stock'
	assert (arr.items[2] as cx.TextNode).value == 'out'
}

fn test_quoted_string_slots() {
	// Quoted strings remain valid slot content; quotes are stripped
	// at parse time per existing read_quoted_text behavior.
	n := parse_one("[?if [@stock > 0, 'in stock', 'out']]")
	d := n as cx.EvalDirectiveNode
	arr := d.items[0] as cx.ArrayNode
	assert arr.items.len == 3
	// RE-DERIVED at the #795 batch (#790, RULED: 790-1a): a quoted slot
	// item is a string SCALAR (kind-faithful parse typing; previously
	// TextNode).
	s1 := arr.items[1] as cx.ScalarNode
	assert s1.data_type == .string_type
	assert cx.scalar_value_str(s1.value) == 'in stock'
	s2 := arr.items[2] as cx.ScalarNode
	assert s2.data_type == .string_type
	assert cx.scalar_value_str(s2.value) == 'out'
}

// ── 1.d: mixed-content body slots wrap in SequenceNode ───────────────────────

fn test_mixed_content_slot_wraps_sequence() {
	// Slot 2 is mixed text + interpolation. Per 1.d, multi-item
	// slots wrap in SequenceNode (the "slot encoding" for mixed
	// content). The evaluator unwraps at use-site.
	n := parse_one('[?if [@stock > 0, In stock: [?=@stock], out of stock]]')
	d := n as cx.EvalDirectiveNode
	arr := d.items[0] as cx.ArrayNode
	assert arr.items.len == 3
	// Slot 1: mixed body → SequenceNode.
	slot1 := arr.items[1]
	assert slot1 is cx.SequenceNode
	seq := slot1 as cx.SequenceNode
	assert seq.items.len == 2
	assert seq.items[0] is cx.TextNode
	assert (seq.items[0] as cx.TextNode).value == 'In stock: '
	assert seq.items[1] is cx.InterpolationNode
	assert (seq.items[1] as cx.InterpolationNode).expr == '@stock'
	// Slot 2: single-token body stays unwrapped.
	assert arr.items[2] is cx.TextNode
}

// ── RULED: ASP-2 (#903) — discrete-token arrays + the slot-fill rule ─────────
// A comma-less DATA bracket of 2+ ws-delimited discrete values is an array;
// inside a comma slot a ws-adjacent sequence/map literal refuses; glued runs
// stay one item. These pins are the shapes from the #903 decision packet.

fn asp2_inner_array(src string) cx.ArrayNode {
	el := parse_one(src) as cx.Element
	k := el.items[0] as cx.Element
	return k.items[0] as cx.ArrayNode
}

fn test_asp2_discrete_token_array_types_intact() {
	// This exact shape used to come back as ONE item with the int mangled
	// to the STRING '1 ' (trailing space and all) — silently, and stably
	// under canonicalization.
	arr := asp2_inner_array('[doc [k [1 (2, 3)]]]')
	assert arr.items.len == 2
	s0 := arr.items[0] as cx.ScalarNode
	assert s0.data_type == .int_type
	assert arr.items[1] is cx.SequenceNode
}

fn test_asp2_discrete_token_array_maps_and_singletons() {
	m := asp2_inner_array('[doc [k [1 {a: 1}]]]')
	assert m.items.len == 2
	assert (m.items[0] as cx.ScalarNode).data_type == .int_type
	assert m.items[1] is cx.MapNode
	// The singleton paren refusal (`expected , or ]`) is gone: a token
	// position has no prose lane (#810), so `(2)` is the singleton sequence.
	s := asp2_inner_array('[doc [k [1 (2)]]]')
	assert s.items.len == 2
	assert s.items[1] is cx.SequenceNode
	two := asp2_inner_array('[doc [k [{a: 1} {b: 2}]]]')
	assert two.items.len == 2
	assert two.items[0] is cx.MapNode && two.items[1] is cx.MapNode
}

fn test_asp2_element_guard_and_glued_span() {
	// A name-shaped first token keeps the element reading (ASP-1 scope
	// note stands): `[true (2, 3)]` is the ELEMENT `true`, not an array.
	el := parse_one('[doc [k [true (2, 3)]]]') as cx.Element
	k := el.items[0] as cx.Element
	inner := k.items[0] as cx.Element
	assert inner.name == 'true'
	// A structure span NOT ws-delimited on both sides is not a token:
	// glued `[(1, 2)[0]]` keeps its historical one-item mixed reading —
	// the same "glued runs are one item" rule that keeps CXPath kind
	// tests (`$c/node()`, fmt-013) parsing byte-identically.
	g := asp2_inner_array('[doc [k [(1, 2)[0]]]]')
	assert g.items.len == 1
	assert g.items[0] is cx.SequenceNode
}

fn test_asp2_slot_fill_refusals_are_loud() {
	// Inside one comma slot, a ws-adjacent literal refuses with a message
	// that names the fix — never the silent nested-sequence glue.
	for src in ['[doc [k [1, weight (kg, lbs)]]]', '[doc [k [(1, 2) three]]]',
		'[doc [k {m: 1 (2, 3)}]]', '[doc [k (1, (2, 3) (4, 5))]]',
		'[?if [@x, use (a, b) now, else]]'] {
		if _ := cx.parse(src) {
			assert false, 'expected ASP-2 slot refusal for: ${src}'
		} else {
			assert err.msg().contains('collection slot'), 'wrong refusal for ${src}: ${err.msg()}'
		}
	}
}

fn test_asp2_mixed_content_slots_untouched() {
	// The load-bearing mixed-content shapes parse exactly as before —
	// the collision that killed ASP-1.
	n := parse_one('[?if [@stock > 0, In stock: [?=@stock], out of stock]]')
	arr := (n as cx.EvalDirectiveNode).items[0] as cx.ArrayNode
	assert arr.items.len == 3
	assert arr.items[1] is cx.SequenceNode
	kt := parse_one('[?for [in $c //c] [yield ($c/node(), $c//text())]]')
	assert kt is cx.EvalDirectiveNode // glued kind-test parens still parse
}

// ── RULED: ASP-3 (#909) — element bodies read discrete values ────────────────
// The ASP-2 discrete-token rule extends to ELEMENT BODIES: a comma-less body
// whose 2+ ws-delimited tokens are all discrete values yields them as discrete
// children. The decisive shape is ENGINE OUTPUT — ux-016 renders
// `[list false (verb, …) …]`, which failed its own re-parse (#704 class).

fn asp3_body(src string) cx.Element {
	el := parse_one(src) as cx.Element
	return el.items[0] as cx.Element
}

fn test_asp3_element_body_discrete_structures() {
	// `[k 1 (2, 3)]` came back `[k '1' (2, 3)]` — the int restringified to
	// '1 ' (trailing space and all) by the prose lane, silently and stably
	// under canonicalization.
	k := asp3_body('[doc [k 1 (2, 3)]]')
	assert k.items.len == 2
	s0 := k.items[0] as cx.ScalarNode
	assert s0.data_type == .int_type
	assert k.items[1] is cx.SequenceNode
	m := asp3_body('[doc [k {a: 1} {b: 2}]]')
	assert m.items.len == 2
	assert m.items[0] is cx.MapNode && m.items[1] is cx.MapNode
}

fn test_asp3_ux016_shape_reparses_with_types_intact() {
	// The ruling's decisive evidence, and the body-position difference from
	// the headless guard (case 042 `h` / test_asp2_element_guard_and_glued_span):
	// there is NO name-shaped first-token guard in body position — a body has
	// no element reading to protect, and ux-016's body starts with the bool.
	l := asp3_body('[doc [list false (verb, label, target) (label, open, url)]]')
	assert l.name == 'list'
	assert l.items.len == 3
	b0 := l.items[0] as cx.ScalarNode
	assert b0.data_type == .bool_type
	assert l.items[1] is cx.SequenceNode
	assert l.items[2] is cx.SequenceNode
}

fn test_asp3_rendered_output_is_a_reparse_fixed_point() {
	// #704 class closed for this shape: the canonical render survives its
	// own re-parse at a byte fixed point, bool unmangled.
	src := '[doc [list false (verb, label, target) (label, open, url)]]'
	r1 := code.render_canonical(parse_one(src))
	r2 := code.render_canonical(parse_one(r1))
	assert r1 == r2
	assert !r1.contains("'false'")
}

// ── RULED: TA-1 (#911) — the type annotation is GLUED, enforced ──────────────
// lexicon [L50]: a TypeAnnotation binds glued to the token on its left. The
// DATA reader used to accept the spaced form and silently normalize it to the
// glued spelling the PROGRAM reader demands — two readers disagreeing about a
// spelling the spec does not define (the reader asymmetry behind #910). The
// spaced form now refuses loudly, naming the one-character fix.

fn test_ta1_spaced_annotation_refuses_loudly() {
	for src in ['[port ::u16 8080]', '[data ::[] 1 2.5 3]', '[tags ::string[] a b]'] {
		if _ := cx.parse(src) {
			assert false, 'expected the spaced-annotation refusal for: ${src}'
		} else {
			assert err.msg().contains('must be glued'), 'wrong refusal for ${src}: ${err.msg()}'
			assert err.msg().contains('::'), 'the fix must be named for ${src}: ${err.msg()}'
		}
	}
}

fn test_ta1_glued_and_atom_forms_untouched() {
	// The glued spelling parses (it always did — it is the canonical emit)…
	el := parse_one('[port::u16 8080]') as cx.Element
	if dt := el.data_type() {
		assert dt == 'u16'
	} else {
		assert false, 'expected the glued annotation to carry u16'
	}
	// …and the spaced single-colon atom body is NOT an annotation: it keeps
	// its [L25b] atom reading exactly as before.
	atoms := parse_one('[k :on :off]') as cx.Element
	assert atoms.items.len == 2
	a0 := atoms.items[0] as cx.ScalarNode
	assert a0.data_type == .atom_type
}

fn test_asp3_guards_keep_historical_readings() {
	// A bareword anywhere keeps the WHOLE body its historical prose/mixed
	// reading, byte-identically.
	assert code.render_canonical(parse_one('[doc [p weight (kg, lbs) shown]]')) == "[doc [p 'weight' (kg, lbs) ' shown']]"
	// A glued span is not a token — historical one-item mixed reading.
	assert code.render_canonical(parse_one('[doc [k (1, 2)[0]]]')) == '[doc [k (1, 2) [0]]]'
	// A single structure token (<2 tokens) keeps its reading.
	assert code.render_canonical(parse_one('[doc [k (2, 3)]]')) == '[doc [k (2, 3)]]'
	// A non-map-shaped brace stays prose.
	r := code.render_canonical(parse_one('[doc [k {oops} 1]]'))
	assert r.contains('{oops} 1'), 'non-map brace body moved: ${r}'
	// An annotated head keeps the [L25d] path untouched.
	assert code.render_canonical(parse_one('[doc [k::[] 1 (2, 3)]]')).contains('::[]')
}

fn test_for_three_slot_with_body_element() {
	// `[?for ['var', iterable, body]]` — body slot is a single Element.
	// Single-item slots keep their natural Item kind without wrapping. The
	// leading slot is QUOTED: a bare-word leading array item is reserved for
	// the element head and is a parse error (3a / lexicon §collections [L83]).
	n := parse_one("[?for ['v', //variant, [?=v/@sku]]]")
	d := n as cx.EvalDirectiveNode
	arr := d.items[0] as cx.ArrayNode
	assert arr.items.len == 3
	// RE-DERIVED (#790, RULED: 790-1a): the QUOTED leading slot 'v' is a
	// string SCALAR; the bare //variant stays Text.
	s0 := arr.items[0] as cx.ScalarNode
	assert s0.data_type == .string_type
	assert cx.scalar_value_str(s0.value) == 'v'
	assert (arr.items[1] as cx.TextNode).value == '//variant'
	assert arr.items[2] is cx.InterpolationNode
	assert (arr.items[2] as cx.InterpolationNode).expr == 'v/@sku'
}

fn test_with_two_slot_mixed_body() {
	// `[?if [context, body]]` — body is mixed interp + literal.
	// Vehicle changed `?with` → `?if` (#760 / RULED 760-1a) for the same
	// reason as test_use_single_slot_bare_name above: `?with` was a dead
	// `[59a]` reservation and now parses as a PI. What is pinned here is
	// the two-slot mixed interp+literal body, which is head-agnostic.
	n := parse_one('[?if [//meta, [?=@owner]/[?=@region]]]')
	d := n as cx.EvalDirectiveNode
	arr := d.items[0] as cx.ArrayNode
	assert arr.items.len == 2
	assert (arr.items[0] as cx.TextNode).value == '//meta'
	slot1 := arr.items[1]
	assert slot1 is cx.SequenceNode
	seq := slot1 as cx.SequenceNode
	// Sequence: Interp, Text("/"), Interp
	assert seq.items.len == 3
	assert seq.items[0] is cx.InterpolationNode
	assert (seq.items[1] as cx.TextNode).value == '/'
	assert seq.items[2] is cx.InterpolationNode
}

// ── §D8 wildcard sentinel `*` in array slot ──────────────────────────────────

fn test_multi_branch_if_with_wildcard() {
	// `[?if [[c1, b1], [c2, b2], [*, default]]]` — multi-branch
	// form. Each inner pair is itself an array (comma-marker
	// disambiguates). The `*` sentinel parses as a CXPath wildcard
	// per §D8 — the parse_bracket_node sigil reorder ensures the
	// comma-marker rule wins over the `*` alias-element sigil.
	n := parse_one('[?if [[@stock > 100, Plenty], [@stock > 10, Some], [*, None]]]')
	d := n as cx.EvalDirectiveNode
	arr := d.items[0] as cx.ArrayNode
	assert arr.items.len == 3
	// Each item is a pair-array.
	for i in 0 .. 3 {
		pair := arr.items[i]
		assert pair is cx.ArrayNode
		p := pair as cx.ArrayNode
		assert p.items.len == 2
	}
	// Third pair: condition is `*`, body is `None`.
	last_pair := arr.items[2] as cx.ArrayNode
	assert (last_pair.items[0] as cx.TextNode).value == '*'
	assert (last_pair.items[1] as cx.TextNode).value == 'None'
}

// ── Atomic-array baseline: 1.d must NOT regress data-array semantics ─────────

fn test_atomic_array_scalars_preserved() {
	// `[1, 2, 3]` outside a directive — scalar autotyping still
	// applies per 1.d "single bare-token slot autotypes" rule.
	n := parse_one('[1, 2, 3]')
	arr := n as cx.ArrayNode
	assert arr.items.len == 3
	for i in 0 .. 3 {
		s := arr.items[i] as cx.ScalarNode
		assert s.data_type == .int_type
	}
}

fn test_atomic_array_nested_preserves_shape() {
	n := parse_one('[[1, 2], [3, 4]]')
	arr := n as cx.ArrayNode
	assert arr.items.len == 2
	inner0 := arr.items[0] as cx.ArrayNode
	assert inner0.items.len == 2
	assert (inner0.items[0] as cx.ScalarNode).data_type == .int_type
}

// ── Legacy surfaces now round-trip as opaque data (grammar [59]) ─────────────
//
// Per [59] the data parser treats directive children as uniform BodyItems and
// performs no clause/slot interpretation (that is the program-AST layer's job,
// [127]). Surfaces that the retired labeled-slot machinery once rejected now
// parse as ordinary data and round-trip idempotently. Program-level validity
// of these forms is the code parser's concern, not the data parser's.

fn test_legacy_attribute_slot_form_round_trips() {
	src := '[?if cond :then=[yes] :else=[no]]'
	d := cx.parse(src) or { panic('parse: ${err}') }
	out := cx.emit_cx(d).trim_right('\n')
	// Re-parse + re-emit reaches a fixed point (idempotent round-trip).
	d2 := cx.parse(out) or { panic('reparse: ${err}') }
	assert cx.emit_cx(d2).trim_right('\n') == out
}

fn test_legacy_positional_for_form_round_trips() {
	src := '[?for v in //variant [card [?=v/@sku]]]'
	d := cx.parse(src) or { panic('parse: ${err}') }
	out := cx.emit_cx(d).trim_right('\n')
	d2 := cx.parse(out) or { panic('reparse: ${err}') }
	assert cx.emit_cx(d2).trim_right('\n') == out
}

// ── Round-trip: parse → emit_cx → re-parse → identical AST ───────────────────

fn test_round_trip_three_slot_if() {
	// Leading slot quoted per 3a (a bare-word leading array item is reserved
	// for the element head — lexicon §collections [L83]).
	src := "[?if ['cond', [yes], [no]]]"
	d := cx.parse(src) or { panic(err) }
	out := cx.emit_cx(d).trim_right('\n')
	assert out == src, 'round-trip mismatch: got "${out}"'
}

fn test_round_trip_for_with_interp_body() {
	// Leading slot quoted per 3a (lexicon §collections [L83]).
	src := "[?for ['v', //variant, [?=v/@sku]]]"
	d := cx.parse(src) or { panic(err) }
	out := cx.emit_cx(d).trim_right('\n')
	assert out == src, 'round-trip mismatch: got "${out}"'
}

// ── cx schema infer — the Ring-0 corpus synthesis verb (I5-s16 W3) ───────────

fn test_schema_infer_cli_end_to_end() {
	dir := os.join_path(os.temp_dir(), 'cx_schema_infer_cli_${os.getpid()}')
	os.mkdir_all(dir) or { panic(err) }
	defer { os.rmdir_all(dir) or {} }
	os.write_file(os.join_path(dir, 'a.cx'), '[o sku=SKU-1 [line q=1]]') or { panic(err) }
	os.write_file(os.join_path(dir, 'b.cx'), '[o sku=SKU-2 [line q=2] [line q=3]]') or { panic(err) }
	r := os.execute('${cx_bin()} schema infer ${os.join_path(dir, 'a.cx')} ${os.join_path(dir, 'b.cx')}')
	assert r.exit_code == 0, r.output
	assert r.output.contains('[schema of=o mode=open]'), r.output
	assert r.output.contains('[elem line [card "1..2"]]'), r.output
	// Determinism: argument order must not matter (the verb sorts).
	r2 := os.execute('${cx_bin()} schema infer ${os.join_path(dir, 'b.cx')} ${os.join_path(dir, 'a.cx')}')
	assert r2.exit_code == 0, r2.output
	assert r2.output == r.output
	// The inferred schema validates its own corpus (the §8 property,
	// end-to-end through the CLI pair).
	sp := os.join_path(dir, 'o.cxs')
	rw := os.execute('${cx_bin()} schema infer --output=${sp} ${os.join_path(dir, 'a.cx')} ${os.join_path(dir, 'b.cx')}')
	assert rw.exit_code == 0, rw.output
	for f in ['a.cx', 'b.cx'] {
		rv := os.execute('${cx_bin()} validate ${os.join_path(dir, f)} --schema=${sp}')
		assert rv.exit_code == 0, '${f}: ${rv.output}'
	}
}

fn test_schema_infer_cli_refusals() {
	r := os.execute('${cx_bin()} schema frobnicate')
	assert r.exit_code == 2
	r2 := os.execute('${cx_bin()} schema infer --sample=0 x.cx')
	assert r2.exit_code == 2
}

// ── cx lock --pin-schema — module-level schema pins (I5-s16 W4) ──────────────

fn test_lock_pin_schema_roundtrip() {
	dir := os.join_path(os.temp_dir(), 'cx_lock_pin_${os.getpid()}')
	os.mkdir_all(dir) or { panic(err) }
	defer { os.rmdir_all(dir) or {} }
	os.write_file(os.join_path(dir, 'p.cxs'), '[schema of=ports mode=open]\n[ports [body [list u16] [req]]]\n') or { panic(err) }
	os.write_file(os.join_path(dir, 'main.cx'), "[?lib 'cx-stdlib/validate']\n[ok]\n") or { panic(err) }
	r := os.execute('cd ${dir} && ${cx_bin()} lock --pin-schema Ports=p.cxs main.cx')
	assert r.exit_code == 0, r.output
	lock_text := os.read_file(os.join_path(dir, 'main.cx').all_before('main.cx') + 'cx.lock') or { panic(err) }
	assert lock_text.contains('[schemas'), lock_text
	assert lock_text.contains('name="Ports"'), lock_text
	assert lock_text.contains('hash="'), lock_text
	// Regeneration WITHOUT the flag carries the pin forward (pins are
	// authored state, not derivable from source scanning).
	r2 := os.execute('cd ${dir} && ${cx_bin()} lock main.cx')
	assert r2.exit_code == 0, r2.output
	lock_text2 := os.read_file(os.join_path(dir, 'cx.lock')) or { panic(err) }
	assert lock_text2.contains('name="Ports"'), lock_text2
	// Re-pinning the same name replaces the hash, not duplicates.
	os.write_file(os.join_path(dir, 'p.cxs'), '[schema of=ports mode=open]\n[ports [body [list u32] [req]]]\n') or { panic(err) }
	r3 := os.execute('cd ${dir} && ${cx_bin()} lock --pin-schema Ports=p.cxs main.cx')
	assert r3.exit_code == 0, r3.output
	lock_text3 := os.read_file(os.join_path(dir, 'cx.lock')) or { panic(err) }
	assert lock_text3.count('name="Ports"') == 1, lock_text3
	assert lock_text3 != lock_text2, 'hash must move with the content'
}

// ── --strict on run + eval — the ONE §12.7 dial (I5-s16 W5) ──────────────────

fn test_strict_flag_run_and_eval() {
	dir := os.join_path(os.temp_dir(), 'cx_strict_cli_${os.getpid()}')
	os.mkdir_all(dir) or { panic(err) }
	defer { os.rmdir_all(dir) or {} }
	prog := "[?def double [returns int] (\$x::int) [* \$x 2]]\n[\$double 'nope']\n"
	f := os.join_path(dir, 'p.cx')
	os.write_file(f, prog) or { panic(err) }
	// Default: annotations erased (documentation only) — the body runs
	// and fails on its own arithmetic, never on the annotation.
	r0 := os.execute('${cx_bin()} ${f}')
	assert !r0.output.contains('CXER0206'), r0.output
	// --strict: the call boundary refuses.
	r1 := os.execute('${cx_bin()} --strict ${f}')
	assert r1.output.contains('CXER0206'), r1.output
	assert r1.exit_code != 0
	// eval surface — same flag.
	r2 := os.execute("${cx_bin()} eval --strict -e \"[?do [?def d [returns int] (\$x::int) \$x] [\$d 'no']]\"")
	assert r2.output.contains('CXER0206') || r2.output.contains('CXER0100'), r2.output
	// CX_STRICT_TYPES is RETIRED — it no longer flips the dial.
	r3 := os.execute('CX_STRICT_TYPES=1 ${cx_bin()} ${f}')
	assert !r3.output.contains('CXER0206'), r3.output
}

// ── cx schema export --to=json-schema — golden files (I5-s16 W6, ─────────────
// the stream-18 MCP handoff). The export describes the LOSSLESS JSON
// projection (the $tag envelope), byte-stable per schema identity.

fn test_schema_export_golden_files() {
	dir := os.join_path(os.dir(os.dir(cx_bin())), '..', 'conformance', 'schema_export')
	entries := os.ls(dir) or { panic(err) }
	mut n := 0
	for e in entries {
		if !e.ends_with('.cxs') {
			continue
		}
		base := e.all_before_last('.cxs')
		golden := os.read_file(os.join_path(dir, base + '.golden.json')) or {
			panic('missing golden for ${e}: ${err}')
		}
		r := os.execute('${cx_bin()} schema export --to=json-schema ${os.join_path(dir, e)}')
		assert r.exit_code == 0, '${e}: ${r.output}'
		assert r.output == golden, '${e}: export drifted from its golden — review deliberately and regenerate'
		// Determinism: a second run is byte-identical.
		r2 := os.execute('${cx_bin()} schema export --to=json-schema ${os.join_path(dir, e)}')
		assert r2.output == r.output
		n++
	}
	assert n >= 3, 'golden corpus must not silently shrink (found ${n})'
}

fn test_schema_export_refusals() {
	r := os.execute('${cx_bin()} schema export --to=xsd x.cxs')
	assert r.exit_code == 2
	assert r.output.contains('json-schema'), r.output
	r2 := os.execute('${cx_bin()} schema export --to=json-schema')
	assert r2.exit_code == 2
}

// ── #833 — `--allow-common`, the broad grant docs can recommend ──────────
//
// Capabilities are deny-by-default, so every effectful example needs a
// grant; the only broad grant CX shipped was `--allow-all`, which includes
// `secret-reveal` — the capability that DECLASSIFIES a secret. A
// getting-started page cannot hand a newcomer the flag that also turns off
// secret protection, so the docs were stuck enumerating capabilities per
// example. `--allow-common` is that set minus `secret-reveal`.

// The grant set is DERIVED, never a second hand-maintained list that can
// drift from `capability_names()`.
fn test_allow_common_is_the_working_set_minus_secret_reveal() {
	common := code.common_capability_names()
	all := code.capability_names()
	assert 'secret-reveal' !in common, '--allow-common must NOT grant secret-reveal — that is its whole reason to exist'
	assert common.len == all.len - 1, 'the common set must be the full set minus exactly one capability: ${common}'
	for cap in all {
		if cap == 'secret-reveal' {
			continue
		}
		assert cap in common, 'the common working set is missing `${cap}`: ${common}'
	}
}

// The behavioural half: an effect in the working set runs, and a
// declassification refuses with the same CXER0271 an ungranted run gets.
fn test_allow_common_grants_effects_but_refuses_declassification() {
	dir := os.join_path(os.temp_dir(), 'cx_833_${os.getpid()}')
	os.mkdir_all(dir) or {
		assert false, 'mkdir: ${err}'
		return
	}
	defer {
		os.rmdir_all(dir) or {}
	}

	// write — in the common set.
	target := os.join_path(dir, 'written.txt')
	wprog := os.join_path(dir, 'w.cx')
	os.write_file(wprog, "[?lib 'cx-stdlib/io']\n[\$io:write-file '${target}' 'ok']\n") or {
		assert false, 'write program: ${err}'
		return
	}
	rw := os.execute('${cx_bin()} --allow-common ${wprog}')
	assert !rw.output.contains('CXER0271'),
		'--allow-common must grant `write`: ${rw.output}'
	assert os.exists(target), '--allow-common granted write but nothing was written'

	// secret-reveal — NOT in the common set.
	sprog := os.join_path(dir, 's.cx')
	os.write_file(sprog, "[?let [= \$s [?secret 'hunter2']] [out [?reveal \$s]]]\n") or {
		assert false, 'write program: ${err}'
		return
	}
	rs := os.execute('${cx_bin()} --allow-common ${sprog}')
	assert rs.output.contains('CXER0271'),
		'--allow-common must REFUSE a declassification: ${rs.output}'
	assert !rs.output.contains('hunter2'),
		'a secret leaked through --allow-common: ${rs.output}'

	// …and `--allow-all` still declassifies, unchanged.
	ra := os.execute('${cx_bin()} --allow-all ${sprog}')
	assert ra.output.contains('hunter2'),
		'--allow-all must keep revealing secrets — its behaviour is load-bearing and must not change: ${ra.output}'
}

// `--allow-common` is a NEW spelling, so a misspelling of it must still be a
// hard usage error rather than a silent no-grant (cli.md §3.7): the
// `--allow-<cap>` branch must not swallow it as a capability named "commn".
fn test_misspelled_broad_grant_is_a_hard_error() {
	r := os.execute('${cx_bin()} --allow-commn -e "[ok]"')
	assert r.exit_code == 2, 'a misspelled grant must exit 2, got ${r.exit_code}: ${r.output}'
	assert r.output.contains('unknown flag'), r.output
	assert r.output.contains('--allow-common'), 'the hint must name the real flag: ${r.output}'
}
