// cxparse_forks_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):
// the per-area test-binary umbrella. 4 source files merged verbatim (byte-identical
// helper dedupe only; the V compiler is the name-collision oracle). Fewer test
// files = fewer whole-module-graph compiles (V compilation was 99% of the gate).
// Regenerate: scripts/consolidate_tests.sh gen cxparse_forks
// Manifest:   scripts/consolidation/cxparse_forks.files

module main

import code
import cx
import platform as _

// ── source: vcx/tests/cxparse_namechar_fork_test.v ──
// cxparse_namechar_fork_test — pins the ONE deliberate name-char mode fork and
// proves the DATA path is an equivalent realization of lexicon [L11].
//
// `is_name_start` is byte-identical across both parsers and is shared with no
// behavior change. The CONTINUATION rule genuinely differs by mode and stays
// two named predicates (each defined once — that is not duplication, it is the
// mode boundary N1 admits):
//   • DATA   `cx.is_name_char`  — folds `.` and `:` into the name token
//                                  (dotted names + `prefix:local` QNames).
//   • PROGRAM `cx.is_ident_part` — excludes `.`/`:` (the program lexer emits
//                                  them as their own tokens: path step / colon).
//
// [L11] describes `:` as its own token that the parser FOLDS into a QName. The
// scannerless data path has no token stream; it realizes the SAME fold by
// accepting `:` mid-name. This is the RATIFIED end-state (the single-tokenizer
// flip was ruled architecturally unsound — PLAN §4.3), NOT a way-point. The
// equivalence is observable, so this test pins it directly:
// `[svg:rect]` folds to one element AND renders BARE (a regression that dropped
// `:` from `is_name_char` without re-adding it everywhere would quote the QName
// — the bijection break this fork guards against), while `[a:b:c]` is rejected.

fn test_name_start_is_shared_and_ascii() {
	for b in [u8(`a`), `z`, `A`, `Z`, `_`] {
		assert cx.is_name_start(b)
	}
	for b in [u8(`0`), `9`, `-`, `.`, `:`, ` `, `[`] {
		assert !cx.is_name_start(b)
	}
}

fn test_data_namechar_folds_dot_and_colon() {
	assert cx.is_name_char(`.`)
	assert cx.is_name_char(`:`)
	assert cx.is_name_char(`-`)
	assert cx.is_name_char(`0`)
	assert cx.is_name_char(`a`)
}

fn test_program_ident_part_excludes_dot_and_colon() {
	assert !cx.is_ident_part(`.`)
	assert !cx.is_ident_part(`:`)
	assert cx.is_ident_part(`-`)
	assert cx.is_ident_part(`0`)
	assert cx.is_ident_part(`a`)
}

fn test_program_lexer_splits_dotted_name() {
	// Behavioral consequence of `is_ident_part`: the program lexer breaks `a.b`
	// at the dot, so it yields strictly more tokens than the gap-free `ab`.
	dotted := cx.tokenize('a.b') or { panic('tokenize a.b: ${err}') }
	plain := cx.tokenize('ab') or { panic('tokenize ab: ${err}') }
	assert dotted.len > plain.len
}

fn test_data_parser_admits_dotted_name() {
	// Behavioral consequence of `is_name_char`: a dotted element name parses as
	// a single data element.
	doc := cx.parse('[a.b hello]') or { panic('data parse [a.b hello]: ${err}') }
	assert doc.elements.len == 1
}

fn test_qname_folds_to_one_element_and_renders_bare() {
	// [L11] realization: `prefix:local` folds into ONE element name on the data
	// path, and the canonical renderer prints it BARE (not quoted). This is the
	// bijection-critical observable the fork guards: a regression that dropped
	// `:` from `is_name_char` without re-adding the fold at the renderer would
	// emit `'svg:rect'`, breaking CX⇄XML round-tripping.
	doc := cx.parse('[svg:rect x=1]') or { panic('data parse [svg:rect x=1]: ${err}') }
	assert doc.elements.len == 1
	rendered := code.render_canonical(doc.elements[0])
	assert rendered.contains('svg:rect')
	assert !rendered.contains("'svg:rect'")
}

fn test_double_colon_qname_rejected() {
	// At most one `:` per [L11]: `a:b:c` is not a valid QName.
	if _ := cx.parse('[a:b:c]') {
		assert false, '[a:b:c] must be rejected as an invalid QName'
	}
}

// ── source: vcx/tests/cxparse_number_fork_test.v ──
// cxparse Phase 4.2 — the program number grammar converges to lexicon [L20]
// (the same grammar the data parser already implements): hex ints (`0x…` with
// optional `_` separators), `_` separators in decimal int / float, and the
// [L20c] leading-zero rule. Before convergence the program lexer rejected
// `0xFF` ("invalid duration suffix 'xFF'") and `1_000`; after, both parsers
// agree. These cases pin the converged behavior.

fn body_scalar(src string) cx.ScalarNode {
	mut env := code.new_env()
	prog := cx.parse_program(src) or { panic('parse failed: ${src} — ${err}') }
	n := code.eval(prog.body, mut env) or { panic('eval failed: ${src} — ${err}') }
	if n is cx.Element {
		if n.items.len == 1 {
			it := n.items[0]
			if it is cx.ScalarNode {
				return it
			}
		}
	}
	panic('expected single-scalar body for ${src}')
}

fn int_body(src string) i64 {
	s := body_scalar(src)
	assert s.data_type == cx.ScalarType.int_type, '${src}: expected int, got ${s.data_type}'
	v := s.value
	return if v is i64 { v } else { i64(-999999) }
}

fn test_hex_int() {
	assert int_body('[x 0xFF]') == 255
	assert int_body('[x 0X10]') == 16
	assert int_body('[x -0x10]') == -16
}

fn test_hex_underscore() {
	assert int_body('[x 0xDEAD_BEEF]') == i64(0xDEADBEEF)
}

fn test_decimal_underscore() {
	assert int_body('[x 1_000]') == 1000
	assert int_body('[x 1_000_000]') == 1000000
}

fn test_fraction_underscore_is_decimal() {
	// I1 2b: a bare fixed-point fraction is a DECIMAL (underscores strip).
	s := body_scalar('[x 1_000.5]')
	assert s.data_type == cx.ScalarType.decimal_type
	v := s.value
	assert (if v is string { v } else { '' }) == '1000.5'
}

fn test_exponent_form_is_float() {
	s := body_scalar('[x 1.5e3]')
	assert s.data_type == cx.ScalarType.float_type
	v := s.value
	assert (if v is f64 { v } else { 0.0 }) == 1500.0
}

fn test_leading_zero_stays_string() {
	// [L20c]: a leading-zero decimal int is NOT an int — it stays a string
	// (ZIP codes / SKUs). Regression guard; this already held pre-4.2.
	s := body_scalar('[x 02134]')
	assert s.data_type == cx.ScalarType.string_type
	v := s.value
	assert (if v is string { v } else { '' }) == '02134'
}

// ── source: vcx/tests/cxparse_temporal_fork_test.v ──
// cxparse_temporal_fork_test — the date/datetime recognizers unified into
// cx/lexical.v (cxparse Phase 1, batch 4). The strictness fork is now CONVERGED
// (Phase 3): all three derive from the ONE strict temporal grammar.
//
//   cx.temporal_len  — STRICT byte scanner (full [L23]/[L24] + glued-name guard);
//                      the program lexer's token-boundary recognizer.
//   cx.is_date       — derived from temporal_len (the single date grammar).
//   cx.is_datetime   — DATA classification, now STRICT: a token is a datetime iff
//                      it scans as a clean temporal run of datetime length.
//
// Formerly data is_datetime was LOOSE — it accepted a malformed
// `YYYY-MM-DDT<garbage>` run as a datetime. [L24] and the program scanner reject
// it; Phase 3 converged the data side onto the strict scanner (lexicon-mandated),
// reclassifying those runs to text. This test now asserts the AGREEMENT.

fn tlen(s string) int {
	return cx.temporal_len(s.bytes(), 0) or { -1 }
}

fn test_is_date_strict() {
	assert cx.is_date('2024-01-15')
	assert !cx.is_date('0000-00-00') // calendar-gated now (@CHOICE-3): month/day 00 invalid
	assert !cx.is_date('2024-1-15') // wrong widths
	assert !cx.is_date('2024-01-15 ') // length != 10
	assert !cx.is_date('24-01-15')
	assert !cx.is_date('abcd-ef-gh')
}

// @CHOICE-3 / LX-DATE — a shape-valid but calendar-INVALID date or datetime is
// NOT a date/datetime token; it falls through to a string. calendar_ok gates the
// CLASSIFICATION (is_date/is_datetime), while temporal_len (the extent scanner)
// stays shape-only so the program lexer keeps the full run as one token.
fn test_calendar_ok_gates_classification() {
	// Bad calendar fields → not a date/datetime (the LX-DATE-BAD witness).
	assert !cx.is_date('2024-13-45') // month 13, day 45
	assert !cx.is_date('2024-02-30') // Feb 30 — shape-valid, calendar-invalid
	assert !cx.is_date('2023-02-29') // 2023 is not a leap year
	assert !cx.is_datetime('2024-01-15T25:00:00') // hour 25
	assert !cx.is_datetime('2024-01-15T10:60:00') // minute 60
	// Good calendar fields → still classify.
	assert cx.is_date('2024-02-29') // 2024 IS a leap year
	assert cx.is_date('2000-02-29') // 2000 divisible by 400 → leap
	assert !cx.is_date('1900-02-29') // 1900 divisible by 100 not 400 → not leap
	assert cx.is_datetime('2024-01-15T10:30:00+05:30')
	assert cx.is_datetime('2024-01-15T23:59:59Z')
	// temporal_len (extent recognizer) is shape-only and UNCHANGED — it still
	// spans the calendar-invalid run as one token (no fragmentation).
	assert tlen('2024-13-45') == 10
	assert tlen('2024-01-15T25:00:00') == 19
}

fn test_temporal_len_date_and_datetime() {
	assert tlen('2024-01-15') == 10
	assert tlen('2024-01-15T10:30:00') == 19
	assert tlen('2024-01-15T10:30:00Z') == 20
	assert tlen('2024-01-15T10:30:00.500') == 23
	assert tlen('2024-01-15T10:30:00+05:30') == 25
	// glued to a name char → not a clean token
	assert tlen('2024-01-15abc') == -1
	assert tlen('not-a-date') == -1
}

fn test_datetime_strictness_converged() {
	// A well-formed datetime: data classification and the strict scanner agree.
	good := '2024-01-15T10:30:00'
	assert cx.is_datetime(good)
	assert tlen(good) == good.len

	// A MALFORMED `YYYY-MM-DDT<garbage>` run, length >= 19. Post-convergence the
	// data classifier is STRICT and agrees with the scanner — both reject it, so
	// it falls through to text:
	bad := '2024-01-15Tgarbage1' // len 19, date + 'T' + non-time tail
	assert bad.len >= 19
	assert !cx.is_datetime(bad) // strict (was LOOSE-accept before Phase 3)
	assert tlen(bad) == -1 // strict scanner: not a temporal token

	// A well-formed datetime with trailing junk is likewise not a datetime token.
	assert !cx.is_datetime('2024-01-15T10:30:00xyz')
}

fn test_is_datetime_min_length() {
	assert !cx.is_datetime('2024-01-15T10:30') // < 19 chars
	assert !cx.is_datetime('2024-01-15') // no 'T'
}

// ── source: vcx/tests/cxparse_tokenization_spike_test.v ──
// ════════════════════════════════════════════════════════════════════════════
//  cxparse Phase-0 SPIKE — data-surface tokenization (gates D-ARCH)
// ════════════════════════════════════════════════════════════════════════════
//
// D-ARCH (spec/02-inprogress/cxparse_unification_PLAN.md §3) chose
// tokenize-then-parse with LEXER MODES. Its ONE acknowledged risk: the
// data-only surface — raw text, triple-quote, block-content / fenced-code
// injection, Markdown — is context-sensitive and does NOT tokenize cleanly
// into a flat stream of fine-grained tokens. The plan's mitigation: the
// tokenizer emits a single COARSE "raw-span" token per such region, and the
// PARSER (or a later mode pass) expands it. This spike must confirm that
// mitigation is tractable BEFORE Phase 1.
//
// THESIS PROVEN HERE: every context-sensitive data region is a DELIMITED RAW
// SPAN with an open + close marker that a single forward lexer pass can find
// using only BOUNDED LOOKAHEAD. A mode lexer therefore segments the input
// losslessly into coarse spans (raw regions stay verbatim; everything else is
// ordinary token soup). Round-trip = the spans tile the input exactly.
//
// Regions and their delimiters:
//   • quoted string   '…'  /  "…"     close = matching quote (\\-escaped)
//   • triple-quote    '''…'''/"""…""" close = matching triple (lookahead-on-close)
//   • raw text        [# … #]         close = `#]`  (disambiguated from [#-heading)
//   • block content   [| … |]         close = `|]`  (the fenced-code payload carrier)
//
// This is a STANDALONE prototype lexer (it deliberately does NOT import the
// production lexer) — the point is to demonstrate the segmentation algorithm
// in isolation, the way Phase 2's real tokenizer modes will work. The fact
// that code/lexer.v ALREADY reads triple-quotes + strings as raw spans today
// (read_triple_string / read_string) is independent corroboration that the
// mode-emits-raw-span pattern is real, not hypothetical.

enum SpanKind {
	normal        // ordinary CX token soup — tokenized normally by the real lexer
	quoted_str    // '…' or "…"
	triple_str    // '''…''' or """…"""
	raw_text      // [# … #]
	block_content // [| … |]
}

struct Span {
mut:
	kind  SpanKind
	start int // inclusive byte offset
	end   int // exclusive byte offset
}

// raw_payload returns the verbatim content of a raw region with its open/close
// delimiters stripped — what the unified parser would hand downstream.
fn (s Span) raw_payload(src string) string {
	return match s.kind {
		.quoted_str { src[s.start + 1..s.end - 1] }          // strip the 1-char quotes
		.triple_str { src[s.start + 3..s.end - 3] }          // strip the 3-char fences
		.raw_text { src[s.start + 2..s.end - 2] }            // strip `[#` … `#]`
		.block_content { src[s.start + 2..s.end - 2] }       // strip `[|` … `|]`
		.normal { src[s.start..s.end] }
	}
}

// is_triple reports a triple-quote opener `'''` / `"""` at pos.
fn is_triple(src string, pos int, q u8) bool {
	return pos + 3 <= src.len && src[pos] == q && src[pos + 1] == q && src[pos + 2] == q
}

// raw_text_close: starting just after `[#`, is this a `[# … #]` raw region
// (vs a `[#`-heading)? Scan for a depth-0 `#]` before a depth-0 closing `]`.
// Returns the index just past the closing `#]`, or -1 if not raw. This is the
// bounded-lookahead disambiguation the data parser uses (parser.v ~947).
fn raw_text_close(src string, after_hash int) int {
	mut scan := after_hash
	mut depth := 0
	for scan < src.len {
		b := src[scan]
		if b == `[` {
			depth++
		} else if b == `#` && depth == 0 && scan + 1 < src.len && src[scan + 1] == `]` {
			return scan + 2
		} else if b == `]` {
			if depth == 0 {
				return -1 // closed without a `#]` → it was a heading/element, not raw
			}
			depth--
		}
		scan++
	}
	return -1
}

// block_content_close: starting just after `[|`, find the `|]` terminator.
fn block_content_close(src string, after_pipe int) int {
	mut scan := after_pipe
	for scan < src.len {
		if src[scan] == `|` && scan + 1 < src.len && src[scan + 1] == `]` {
			return scan + 2
		}
		scan++
	}
	return -1
}

// quoted_close: starting just after the opening quote, find the matching close,
// honouring `\`-escapes (so `\'` does not close a `'…'`).
fn quoted_close(src string, after_quote int, q u8) int {
	mut scan := after_quote
	for scan < src.len {
		b := src[scan]
		if b == `\\` {
			scan += 2
			continue
		}
		if b == q {
			return scan + 1
		}
		scan++
	}
	return -1
}

// triple_close: starting just after the opening triple, find the matching
// closing triple, with the lookahead-on-close rule (a 4th quote → the first is
// content). Mirrors code/lexer.v read_triple_string.
fn triple_close(src string, after_triple int, q u8) int {
	mut scan := after_triple
	for scan < src.len {
		if src[scan] == q && scan + 3 <= src.len && src[scan + 1] == q && src[scan + 2] == q {
			if scan + 3 < src.len && src[scan + 3] == q {
				scan++ // 4th quote: this triple is content, re-scan past one
				continue
			}
			return scan + 3
		}
		scan++
	}
	return -1
}

// lex_spans is the prototype MODE LEXER. One forward pass; emits a coarse span
// per region. Normal bytes accumulate into `normal` spans between regions. The
// spans tile [0, len) exactly (lossless).
fn lex_spans(src string) []Span {
	mut spans := []Span{}
	mut pos := 0
	mut normal_start := 0

	flush_normal := fn (mut spans []Span, normal_start int, pos int) {
		if pos > normal_start {
			spans << Span{ kind: .normal, start: normal_start, end: pos }
		}
	}

	for pos < src.len {
		b := src[pos]
		mut region_end := -1
		mut kind := SpanKind.normal

		if b == `'` && is_triple(src, pos, `'`) {
			region_end = triple_close(src, pos + 3, `'`)
			kind = .triple_str
		} else if b == `"` && is_triple(src, pos, `"`) {
			region_end = triple_close(src, pos + 3, `"`)
			kind = .triple_str
		} else if b == `'` {
			region_end = quoted_close(src, pos + 1, `'`)
			kind = .quoted_str
		} else if b == `"` {
			region_end = quoted_close(src, pos + 1, `"`)
			kind = .quoted_str
		} else if b == `[` && pos + 1 < src.len && src[pos + 1] == `#` {
			rc := raw_text_close(src, pos + 2)
			if rc > 0 {
				region_end = rc
				kind = .raw_text
			}
		} else if b == `[` && pos + 1 < src.len && src[pos + 1] == `|` {
			region_end = block_content_close(src, pos + 2)
			kind = .block_content
		}

		if region_end > 0 {
			flush_normal(mut spans, normal_start, pos)
			spans << Span{ kind: kind, start: pos, end: region_end }
			pos = region_end
			normal_start = pos
		} else {
			pos++
		}
	}
	flush_normal(mut spans, normal_start, src.len)
	return spans
}

// reassemble proves the lossless property: concatenating every span's source
// slice (in order) reconstructs the input byte-for-byte.
fn reassemble(src string, spans []Span) string {
	mut b := []u8{}
	for s in spans {
		b << src[s.start..s.end].bytes()
	}
	return b.bytestr()
}

fn first_of(spans []Span, k SpanKind) ?Span {
	for s in spans {
		if s.kind == k {
			return s
		}
	}
	return none
}

// ── round-trip over a document that mixes ALL four context-sensitive regions ──
fn test_spike_roundtrip_all_regions() {
	src := "[doc\n" + "  [name 'Alice']\n" + "  [bio '''\n  multi\n  line\n''']\n" +
		"  [# verbatim <xml> & 1<2 #]\n" + "  [snippet [| code(); a|b |]]\n" +
		"  [p plain words here]\n" + "]"
	spans := lex_spans(src)
	// LOSSLESS: the coarse spans tile the input exactly.
	assert reassemble(src, spans) == src, 'round-trip mismatch'
	// Each raw region was found and its verbatim payload preserved.
	q := first_of(spans, .quoted_str) or { assert false, 'no quoted_str'; return }
	assert q.raw_payload(src) == 'Alice'
	t := first_of(spans, .triple_str) or { assert false, 'no triple_str'; return }
	assert t.raw_payload(src) == '\n  multi\n  line\n' // verbatim (dedent is a later pass)
	r := first_of(spans, .raw_text) or { assert false, 'no raw_text'; return }
	assert r.raw_payload(src) == ' verbatim <xml> & 1<2 ' // raw: angle/amp un-tokenized
	bc := first_of(spans, .block_content) or { assert false, 'no block_content'; return }
	assert bc.raw_payload(src) == ' code(); a|b ' // single `|` inside is content
}

// ── the [# heading] vs [# raw #] disambiguation is decidable by lookahead ──
fn test_spike_raw_vs_heading_disambiguation() {
	// `[# raw #]` → raw_text; `[# heading]` (no `#]`) → NOT raw (normal soup).
	raw := lex_spans('[# this is raw #]')
	assert first_of(raw, .raw_text) != none, 'expected raw_text span'

	heading := lex_spans('[# Heading One]')
	assert first_of(heading, .raw_text) == none, 'a [#-heading must NOT be a raw span'
	// still lossless even when classified as normal soup
	assert reassemble('[# Heading One]', heading) == '[# Heading One]'
}

// ── nested brackets inside a raw region do not fool the close scan ──
fn test_spike_nested_brackets_in_raw() {
	src := '[# a [b] c #]'
	spans := lex_spans(src)
	r := first_of(spans, .raw_text) or { assert false, 'no raw_text'; return }
	assert r.raw_payload(src) == ' a [b] c ' // the inner `]` did not close the region
	assert reassemble(src, spans) == src
}

// ── escapes inside quoted strings do not prematurely close ──
fn test_spike_escaped_quote_in_string() {
	src := r"[m 'it\'s fine']"
	spans := lex_spans(src)
	q := first_of(spans, .quoted_str) or { assert false, 'no quoted_str'; return }
	assert q.raw_payload(src) == r"it\'s fine"
	assert reassemble(src, spans) == src
}

// ── triple-quote lookahead-on-close (embedded trailing quotes) ──
fn test_spike_triple_embedded_quote() {
	// 5 trailing quotes = 2 content quotes + the 3-quote close (the
	// lookahead-on-close rule, matching code/lexer.v read_triple_string).
	src := "[m '''he said ''''']"
	spans := lex_spans(src)
	t := first_of(spans, .triple_str) or { assert false, 'no triple_str'; return }
	assert t.raw_payload(src) == "he said ''"
	assert reassemble(src, spans) == src
}
