// diagram_vector_golden_test.v — the WAVE-2 DR-8 bit-for-bit gate
// (#758, RULED 2026-08-20; ledger/rulings_2026_08_20_diagram_renderer.md).
//
// The corpus under vcx/tests/testdata/diagram_vector_golden/ was
// captured from the UNMODIFIED V renderer BEFORE the wave-2 cutover.
// It pins the DETERMINISTIC halves of the SVG/PNG path — the DOT text,
// both dot-less envelopes, and both metadata splices over FIXED inputs
// — so the CX port is byte-checkable without graphviz. graphviz's own
// output is version- and font-dependent and is therefore NOT goldened;
// the live end-to-end hop is gate 9's job.
//
// This lane is hermetic: it never spawns `dot` and needs no
// capability. Regenerating the corpus is golden movement — forbidden
// except under a DR-8 mini-ruling recorded in the ledger first.

module main

import os
import cx
import code
import fixtures
import platform as _

const fixed_svg_input = '<?xml version="1.0"?>\n<svg width="10" height="10" xmlns="http://www.w3.org/2000/svg">\n  <g id="graph0"><title>CX</title></g>\n</svg>\n'

// The GRAPHVIZ-SHAPED input (RULED: DSC-1a, #890) — XML declaration,
// then a DOCTYPE, then comments, then the root element: the document
// shape `dot -Tsvg` really emits, and the shape that made the old
// "splice after the first `>`" rule produce a malformed document. The
// short fixed_svg_input above cannot expose the defect on its own
// (it has no DOCTYPE and no comments), so validity is gated over BOTH.
const graphviz_shaped_svg_input = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"\n "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n<!-- Generated by graphviz version 14.1.3 (20260303.0454)\n -->\n<!-- Title: CX Pages: 1 -->\n<svg width="98pt" height="332pt"\n viewBox="0.00 0.00 98.00 332.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 328)">\n<title>CX</title>\n</g>\n</svg>\n'

const fixed_source = '[?retry max=3 [?timeout 500ms [?async [?http-client target=\$url]]]]'

fn golden_dir() string {
	return os.real_path(os.join_path(os.dir(@FILE), 'testdata', 'diagram_vector_golden'))
}

fn read_golden(name string) string {
	return os.read_file(os.join_path(golden_dir(), name)) or {
		assert false, 'missing golden ${name}: ${err}'
		return ''
	}
}

fn fixture_path() string {
	return os.real_path(os.join_path(os.dir(@FILE), '..', '..', 'conformance', 'code.cxd'))
}

// (i) the DOT text for every supported viz fixture, byte-for-byte.
fn test_dot_text_matches_pre_cutover_goldens() {
	mut ran := 0
	mut failures := []string{}
	for c in fixtures.load_fixtures(fixture_path()) {
		if !c.name.starts_with('program-viz-') {
			continue
		}
		if (c.sections['out_err'] or { '' }).trim_space() != '' {
			continue
		}
		golden_file := os.join_path(golden_dir(), '${c.name}.dot')
		if !os.exists(golden_file) {
			continue
		}
		expected := os.read_file(golden_file) or {
			failures << '${c.name}: read golden: ${err}'
			continue
		}
		prog := cx.parse_program(c.sections['in_code']) or {
			failures << '${c.name}: parse: ${err}'
			continue
		}
		got := code.render_dot_cx(prog) or {
			failures << '${c.name}: render-dot: ${err}'
			continue
		}
		if got != expected {
			failures << '${c.name}: DOT BYTE DIVERGENCE\n--- got ---\n${got}\n--- golden ---\n${expected}'
		}
		ran++
	}
	if failures.len > 0 {
		println('${failures.len} DOT failure(s):')
		for f in failures {
			println('  ${f}')
		}
	}
	assert failures.len == 0
	assert ran >= 20, 'expected the 20 supported viz fixtures, ran ${ran}'
}

// (ii) the two dot-less envelopes — DR-3a's named normative contract.
fn test_dot_less_envelopes_match_pre_cutover_goldens() {
	svg := code.diagram_svg_envelope_cx(fixed_source) or {
		assert false, 'svg-envelope: ${err}'
		return
	}
	assert svg == read_golden('envelope.svg'), 'SVG envelope byte divergence'
	png := code.diagram_png_envelope_cx(fixed_source) or {
		assert false, 'png-envelope: ${err}'
		return
	}
	assert png == read_golden('envelope.png'), 'PNG envelope byte divergence'
	// The envelope must round-trip through the module's own extractor.
	back := code.reverse_parse_diagram(svg, 'svg') or {
		assert false, 'svg envelope extract: ${err}'
		return
	}
	assert back == fixed_source
	back_png := code.reverse_parse_diagram(png, 'png') or {
		assert false, 'png envelope extract: ${err}'
		return
	}
	assert back_png == fixed_source
}

// (iii) the two splices over fixed inputs — the SVG "first >" rule and
// the PNG IHDR-offset walk + CRC-32, pinned without graphviz.
fn test_metadata_splices_match_pre_cutover_goldens() {
	svg := code.diagram_svg_splice_cx(fixed_svg_input, fixed_source) or {
		assert false, 'svg splice: ${err}'
		return
	}
	assert svg == read_golden('splice.svg'), 'SVG splice byte divergence'
	png_in := code.diagram_png_envelope_cx('') or {
		assert false, 'png input: ${err}'
		return
	}
	png := code.diagram_png_splice_cx(png_in, fixed_source) or {
		assert false, 'png splice: ${err}'
		return
	}
	assert png == read_golden('splice.png'), 'PNG splice byte divergence'
	// Both spliced forms recover the source.
	assert code.reverse_parse_diagram(svg, 'svg')! == fixed_source
	assert code.reverse_parse_diagram(png, 'png')! == fixed_source
}

// ── (v) SVG DOCUMENT VALIDITY — the DSC-1a gate (#890) ──────────────
//
// Before DSC-1a the metadata carrier was spliced after the FIRST `>`
// in the document, which on real graphviz output is the end of the
// `<?xml …?>` declaration. The block therefore landed in the PROLOG,
// and XML 1.0 §2.1 admits neither an element before the doctype
// (`prolog ::= XMLDecl? Misc* (doctypedecl Misc*)?`) nor a second
// top-level element (`document ::= prolog element Misc*`); libxml2
// reported `Extra content at the end of the document` on every SVG
// `cx diagram` ever emitted. The carrier now goes inside the root.
//
// This is a GATE, not a one-time repair: it holds for every emitted
// SVG form, and every one must still recover the source byte-for-byte.
// It is hermetic — the graphviz-shaped input is a fixture, not a spawn.

// svg_document_violation encodes the two XML 1.0 §2.1 clauses the old
// splice broke, plus the SVG 1.1 §5.10 containment the fix relies on.
// Returns '' for a well-formed carrier document, else the violation.
//
// Deliberately NOT `cx.parse_xml`: that reader layers CX document
// policy on top of XML (it refuses a re-bound `cx:` prefix, E213,
// which the carrier's own `xmlns:cx` declaration trips), so it would
// answer a different question than "is this a valid XML document".
//
// Returning the reason rather than asserting inline is what lets the
// NEGATIVE case below prove the check is not vacuous: the pre-DSC-1
// bytes must be REJECTED by this same function.
fn svg_document_violation(svg string) string {
	root := svg.index('<svg') or { return 'no <svg> root element' }
	// (1) The prolog admits only declarations, PIs and comments — every
	//     `<` before the root must open `<?` or `<!`. A stray element
	//     here IS the DRW2-2 defect.
	prolog := svg[..root]
	mut at := 0
	for {
		lt := prolog.index_after('<', at) or { break }
		nxt := if lt + 1 < prolog.len { prolog[lt + 1] } else { u8(0) }
		if nxt != `?` && nxt != `!` {
			return 'element in the prolog at byte ${lt} — XML 1.0 §2.1 admits no element before the root: ${prolog[lt..]}'
		}
		at = lt + 1
	}
	// (2) A doctype, when present, precedes the root element.
	if dt := svg.index('<!DOCTYPE') {
		if dt > root {
			return '<!DOCTYPE> follows the root element'
		}
	}
	// (3) Exactly one root: the document ends at the root close.
	close := svg.last_index('</svg>') or { return 'root element never closed' }
	if svg[close + 6..].trim_space() != '' {
		return 'content after the root element close: ${svg[close + 6..]}'
	}
	// (4) SVG 1.1 §5.10 — the carrier is a CHILD of the root, not a
	//     sibling: it sits between the root start tag and its close.
	carrier := svg.index('<cx:source') or { return 'no <cx:source> carrier' }
	if carrier < root {
		return 'the carrier precedes the root element'
	}
	if carrier > close {
		return 'the carrier follows the root element close'
	}
	if (svg.index('<metadata>') or { -1 }) < root {
		return 'the <metadata> wrapper is outside the root element'
	}
	return ''
}

fn assert_svg_document_wellformed(label string, svg string) {
	v := svg_document_violation(svg)
	assert v == '', '${label}: ${v}'
}

// The NEGATIVE half of the gate: the exact bytes the renderer emitted
// BEFORE DSC-1a — the carrier spliced after the first `>`, i.e. into
// the prolog — must be REJECTED. Without this case a checker that
// silently passed everything would look green forever.
const pre_dsc1_malformed_splice = '<?xml version="1.0"?>\n  <metadata><cx:source xmlns:cx="https://cx.lang/v1">Wz9d</cx:source></metadata>\n<svg width="10" height="10" xmlns="http://www.w3.org/2000/svg">\n  <g id="graph0"><title>CX</title></g>\n</svg>\n'

fn test_the_validity_check_rejects_the_pre_dsc1_form() {
	v := svg_document_violation(pre_dsc1_malformed_splice)
	assert v != '', 'the pre-DSC-1 prolog splice must be REJECTED — the gate is vacuous otherwise'
	assert v.contains('prolog'), 'expected the prolog violation, got: ${v}'
	// …and the fixed emitter must not produce anything like it.
	assert svg_document_violation(code.diagram_svg_splice_cx(fixed_svg_input, fixed_source)!) == ''
}

fn test_every_emitted_svg_form_is_a_wellformed_document() {
	envelope := code.diagram_svg_envelope_cx(fixed_source) or {
		assert false, 'svg-envelope: ${err}'
		return
	}
	splice := code.diagram_svg_splice_cx(fixed_svg_input, fixed_source) or {
		assert false, 'svg splice: ${err}'
		return
	}
	graphviz := code.diagram_svg_splice_cx(graphviz_shaped_svg_input, fixed_source) or {
		assert false, 'graphviz-shaped svg splice: ${err}'
		return
	}
	forms := {
		'dot-less envelope':      envelope
		'splice (fixed input)':   splice
		'splice (graphviz-shaped input)': graphviz
	}
	for label, svg in forms {
		assert_svg_document_wellformed(label, svg)
		// Validity is worthless if the carrier stopped carrying: the
		// gate-9 contract must hold on the fixed form, byte-for-byte.
		back := code.reverse_parse_diagram(svg, 'svg') or {
			assert false, '${label}: extract: ${err}'
			continue
		}
		assert back == fixed_source, '${label}: the recovered source is not byte-identical'
	}
	// The carrier must be spliced ONCE, and the drawing must survive it
	// intact — a splice that ate document bytes would still parse.
	assert graphviz.count('<cx:source') == 1
	assert graphviz.contains('<g id="graph0"'), 'the drawing was damaged by the splice'
	assert graphviz.contains('<!DOCTYPE svg PUBLIC'), 'the doctype was damaged by the splice'
}

// A self-closing root (`<svg …/>`) has no child position; the splice
// opens it into a container so the carrier has somewhere valid to live
// rather than landing outside the document element.
fn test_self_closing_root_is_opened_for_the_carrier() {
	out := code.diagram_svg_splice_cx('<?xml version="1.0"?>\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"/>\n',
		fixed_source) or {
		assert false, 'self-closing splice: ${err}'
		return
	}
	assert_svg_document_wellformed('self-closing root', out)
	assert code.reverse_parse_diagram(out, 'svg')! == fixed_source
}

// A `>` inside a quoted attribute value does not end the start tag
// (XML 1.0 `AttValue`), so the carrier must still land after the REAL
// tag end — not in the middle of an attribute.
fn test_quoted_gt_in_the_root_start_tag_does_not_split_it() {
	out := code.diagram_svg_splice_cx('<?xml version="1.0"?>\n<svg xmlns="http://www.w3.org/2000/svg" data-note="a &gt; b > c" viewBox="0 0 1 1">\n  <g/>\n</svg>\n',
		fixed_source) or {
		assert false, 'quoted-gt splice: ${err}'
		return
	}
	assert_svg_document_wellformed('quoted > in the start tag', out)
	assert out.contains('data-note="a &gt; b > c"'), 'the attribute value was split'
	assert code.reverse_parse_diagram(out, 'svg')! == fixed_source
}

// (iv) the PNG CRC-32 in CX agrees with the known RFC vectors — the
// one piece of the port that reimplements an algorithm rather than a
// byte layout, so it is pinned independently of the corpus.
fn test_png_crc32_matches_known_vectors() {
	assert code.diagram_crc32_cx('abc')! == 891568578 // 0x352441C2
	assert code.diagram_crc32_cx('IEND')! == 2923585666 // 0xAE426082
	assert code.diagram_crc32_cx('')! == 0
}

// ── (vi) PNG STRUCTURE — the DSC-1b verdict, pinned (#890) ──────────
//
// The SVG carrier was malformed; the PNG carrier was checked for the
// analogous defect and found CLEAN — `tEXt` is an ancillary chunk that
// RFC 2083 §4.2.3 admits anywhere between IHDR and IEND, and the
// splice puts it right after IHDR with a correct CRC. This case keeps
// that true rather than leaving it a one-time observation.

struct PngChunk {
	ctype  string
	data   []u8
	crc_ok bool
}

fn png_walk(png string) ([]PngChunk, bool) {
	b := png.bytes()
	mut out := []PngChunk{}
	mut pos := 8
	for pos + 12 <= b.len {
		ln := int(u32(b[pos]) << 24 | u32(b[pos + 1]) << 16 | u32(b[pos + 2]) << 8 | u32(b[pos + 3]))
		if ln < 0 || pos + 12 + ln > b.len {
			return out, false // a length that overruns the file
		}
		stored := u32(b[pos + 8 + ln]) << 24 | u32(b[pos + 9 + ln]) << 16 | u32(b[pos + 10 + ln]) << 8 | u32(b[pos + 11 + ln])
		calc := u32(code.diagram_crc32_cx(b[pos + 4..pos + 8 + ln].bytestr()) or { -1 })
		out << PngChunk{
			ctype:  b[pos + 4..pos + 8].bytestr()
			data:   b[pos + 8..pos + 8 + ln].clone()
			crc_ok: stored == calc
		}
		pos += 12 + ln
	}
	return out, pos == b.len // the walk must land exactly on the end
}

fn assert_png_structurally_valid(label string, png string, want_carriers int) {
	assert png.len > 8, '${label}: too short for a signature'
	assert png.bytes()[..8] == [u8(0x89), 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a],
		'${label}: bad PNG signature'
	chunks, exact := png_walk(png)
	assert exact, '${label}: the chunk walk did not land on the end of the file'
	assert chunks.len >= 3, '${label}: ${chunks.len} chunks'
	assert chunks[0].ctype == 'IHDR', '${label}: first chunk is ${chunks[0].ctype}, must be IHDR'
	assert chunks[chunks.len - 1].ctype == 'IEND',
		'${label}: last chunk is ${chunks[chunks.len - 1].ctype}, must be IEND'
	mut carriers := 0
	for c in chunks {
		assert c.crc_ok, '${label}: ${c.ctype} chunk CRC-32 mismatch'
		if c.ctype == 'tEXt' {
			sep := c.data.index(u8(0))
			assert sep > 0, '${label}: tEXt chunk has no keyword separator'
			kw := c.data[..sep].bytestr()
			assert kw == 'cx-source', '${label}: tEXt keyword ${kw}, expected cx-source'
			carriers++
		}
	}
	assert carriers == want_carriers, '${label}: ${carriers} cx-source chunks, expected ${want_carriers}'
}

fn test_png_forms_are_structurally_valid() {
	envelope := code.diagram_png_envelope_cx(fixed_source) or {
		assert false, 'png-envelope: ${err}'
		return
	}
	// The splice's fixed input is the EMPTY-source envelope (case iii's
	// input, kept so both cases describe the same bytes), which already
	// carries one `cx-source` chunk — hence two after the splice. The
	// spliced one lands first (immediately after IHDR), which is why
	// the extractor's first-match walk recovers the real source.
	blank := code.diagram_png_envelope_cx('') or {
		assert false, 'png input: ${err}'
		return
	}
	spliced := code.diagram_png_splice_cx(blank, fixed_source) or {
		assert false, 'png splice: ${err}'
		return
	}
	assert_png_structurally_valid('dot-less envelope', envelope, 1)
	assert_png_structurally_valid('tEXt splice', spliced, 2)
	for label, png in {
		'dot-less envelope': envelope
		'tEXt splice':       spliced
	} {
		back := code.reverse_parse_diagram(png, 'png') or {
			assert false, '${label}: extract: ${err}'
			continue
		}
		assert back == fixed_source, '${label}: the recovered source is not byte-identical'
	}
}
