// identity_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):
// the per-area test-binary umbrella. 4 source files merged verbatim (byte-identical
// helper dedupe only; the V compiler is the name-collision oracle). Fewer test
// files = fewer whole-module-graph compiles (V compilation was 99% of the gate).
// Regenerate: scripts/consolidate_tests.sh gen identity
// Manifest:   scripts/consolidation/identity.files

module main

import code
import cx
import os
import platform as _

// ── source: vcx/tests/identity_tier2_code_test.v ──
// #79 — Tier-2 code identity (pre-Phase-1 floor): alpha-equivalence,
// name-independence, comment/format insensitivity, and semantic distinctness
// at the hash level. Dependency-by-hash + mutual-recursion SCC are subsequent
// increments; these cases use leaf defs whose only free refs are builtins.

fn h(def_source string) string {
	return code.cx_code_tier2_hash(def_source) or {
		panic('tier2 hash failed for `${def_source}`: ${err}')
	}
}

// ── alpha-equivalence: bound-variable renaming must collide ──────────────────

fn test_tier2_alpha_equivalent_param() {
	a := '[?def f (\$x) [+ \$x 1]]'
	b := '[?def f (\$y) [+ \$y 1]]'
	assert h(a) == h(b), 'alpha-equivalent param rename must collide'
}

fn test_tier2_name_independence() {
	// The def NAME is an alias, excluded from identity.
	a := '[?def foo (\$x) [+ \$x 1]]'
	b := '[?def bar (\$x) [+ \$x 1]]'
	assert h(a) == h(b), 'def name must not affect Tier-2 identity'
}

fn test_tier2_alpha_and_name_together() {
	a := '[?def foo (\$x) [+ \$x 1]]'
	b := '[?def bar (\$z) [+ \$z 1]]'
	assert h(a) == h(b), 'name + alpha rename must collide'
}

fn test_tier2_nested_fn_alpha() {
	a := '[?def f (\$x) [?fn (\$g) [+ \$g \$x]]]'
	b := '[?def f (\$a) [?fn (\$b) [+ \$b \$a]]]'
	assert h(a) == h(b), 'nested fn + param alpha rename must collide'
}

fn test_tier2_nested_let_alpha() {
	a := '[?def f (\$x) [?let [= \$y 5] [+ \$y \$x]]]'
	b := '[?def f (\$p) [?let [= \$q 5] [+ \$q \$p]]]'
	assert h(a) == h(b), 'nested let + param alpha rename must collide'
}

// ── comment / formatting insensitivity ──────────────────────────────────────

fn test_tier2_comment_insensitive() {
	a := '[?def f (\$x) [+ \$x 1]]'
	b := '[?def f (\$x) [; this comment is identity-irrelevant ;] [+ \$x 1]]'
	assert h(a) == h(b), 'comments must not affect Tier-2 identity'
}

fn test_tier2_whitespace_insensitive() {
	a := '[?def f (\$x) [+ \$x 1]]'
	b := '[?def f   (\$x)\n  [+   \$x   1]]'
	assert h(a) == h(b), 'whitespace/formatting must not affect Tier-2 identity'
}

// ── semantic difference must NOT collide ─────────────────────────────────────

fn test_tier2_semantic_difference_distinct() {
	a := '[?def f (\$x) [+ \$x 1]]'
	b := '[?def f (\$x) [+ \$x 2]]'
	assert h(a) != h(b), 'different literal → different Tier-2 identity'
}

fn test_tier2_param_use_difference_distinct() {
	// Same arity, but one ignores the param — different computation.
	a := '[?def f (\$x) [+ \$x 1]]'
	b := '[?def f (\$x) [+ 9 1]]'
	assert h(a) != h(b), 'different body structure → different Tier-2 identity'
}

fn test_tier2_operator_difference_distinct() {
	a := '[?def f (\$x) [+ \$x 1]]'
	b := '[?def f (\$x) [* \$x 1]]'
	assert h(a) != h(b), 'different operator → different Tier-2 identity'
}

// ── well-formedness: every hash is a tagged sha2-256 (73 chars) ───────────────────────────

fn test_tier2_hash_shape() {
	assert h('[?def f (\$x) [+ \$x 1]]').len == 73
}

// ── #769 — injectivity: fields that distinguish computations must be IN the
// stream (RULED (a) 2026-08-10, W7 checkpoint). Each pair below collided on
// the pre-fix encoding (verified live); the encoding contract says an
// omission may only ever miss a dedup, never merge two computations.

fn test_tier2_slice_access_bounds_distinct() {
	a := '[?def f (\$x) \$x[0:2]]'
	b := '[?def f (\$x) \$x[1:4]]'
	assert h(a) != h(b), 'slice bounds are part of the computation (#769 arm 1)'
}

fn test_tier2_slice_access_open_side_distinct() {
	// Presence-marked bounds: open-start vs open-stop must not collide.
	a := '[?def f (\$x) \$x[2:]]'
	b := '[?def f (\$x) \$x[:2]]'
	assert h(a) != h(b), 'open-start vs open-stop slices differ (#769 arm 1)'
}

fn test_tier2_slice_access_step_distinct() {
	a := '[?def f (\$x) \$x[1:4]]'
	b := '[?def f (\$x) \$x[1:4:2]]'
	assert h(a) != h(b), 'a step bound is part of the computation (#769 arm 1)'
}

fn test_tier2_slice_literal_bounds_distinct() {
	a := '[?def w () [2:5]]'
	b := '[?def w () [3:6]]'
	assert h(a) != h(b), 'slice-literal bounds are part of the computation (#769 arm 1)'
}

fn test_tier2_slice_alpha_still_collides() {
	// The bounds ride the normal emit pipeline: de Bruijn binders keep
	// alpha-equivalent expression bounds collapsing.
	a := '[?def f (\$x \$a \$b) \$x[\$a:\$b]]'
	b := '[?def f (\$y \$p \$q) \$y[\$p:\$q]]'
	assert h(a) == h(b), 'alpha-renamed slice bounds must still collide'
}

fn test_tier2_pattern_attr_value_distinct() {
	a := '[?def f (\$d) [?match \$d [case [user @role="admin"] 1] [else 0]]]'
	b := '[?def f (\$d) [?match \$d [case [user @role="guest"] 1] [else 0]]]'
	assert h(a) != h(b), 'pattern-attr comparison values are part of the computation (#769 arm 2)'
}

fn test_tier2_pattern_attr_type_test_distinct() {
	// Same arm as the value omission: the type-test TYPE NAME never entered
	// the stream (found at the W7 checkpoint, same defect class).
	a := '[?def f (\$d) [?match \$d [case [user @role::str] 1] [else 0]]]'
	b := '[?def f (\$d) [?match \$d [case [user @role::int] 1] [else 0]]]'
	assert h(a) != h(b), 'pattern-attr type-test names are part of the computation (#769)'
}

fn test_tier2_predicate_attr_kind_distinct() {
	// emit_predicate omitted attr_kind: existence and absence collided
	// (found at the W7 checkpoint, same defect class).
	a := '[?def f (\$d) \$d//x[@k]]'
	b := '[?def f (\$d) \$d//x[@!k]]'
	assert h(a) != h(b), 'attr existence vs absence predicates differ (#769)'
}

// ── #769 continuation (the W7 adversarial audit, same ruled class): five
// more AST fields that distinguish computations were absent from the
// stream — each pair below collided live on the pre-fix encoding.

fn test_tier2_order_by_direction_distinct() {
	a := '[?def f (\$s) [?for [in \$o \$s] [order-by \$o/k asc] [yield \$o]]]'
	b := '[?def f (\$s) [?for [in \$o \$s] [order-by \$o/k desc] [yield \$o]]]'
	assert h(a) != h(b), 'sort direction is part of the computation (#769 audit)'
}

fn test_tier2_duration_literal_distinct() {
	// duration/period payloads ride dur_val, not str_val — the emitter
	// wrote the empty str_val, merging EVERY duration and EVERY period.
	a := '[?def f () 100ms]'
	b := '[?def f () 200ms]'
	assert h(a) != h(b), 'duration values are part of the computation (#769 audit)'
}

fn test_tier2_period_literal_distinct() {
	a := '[?def f () 1mo]'
	b := '[?def f () 2mo]'
	assert h(a) != h(b), 'period values are part of the computation (#769 audit)'
}

fn test_tier2_map_pattern_typed_bind_distinct() {
	a := '[?def f (\$d) [?match \$d [case {k: \$v::int} \$v] [else 0]]]'
	b := '[?def f (\$d) [?match \$d [case {k: \$v::str} \$v] [else 0]]]'
	assert h(a) != h(b), 'a typed-bind type test is part of the computation (#769 audit)'
}

fn test_tier2_seq_pattern_rest_capture_distinct() {
	// rest-capture vs a single-item bind = different match arities.
	a := '[?def f (\$d) [?match \$d [case (\$x, *\$r) \$r] [else 0]]]'
	b := '[?def f (\$d) [?match \$d [case (\$x, \$r) \$r] [else 0]]]'
	assert h(a) != h(b), 'a rest-capture is part of the computation (#769 audit)'
}

fn test_tier2_predicate_type_test_distinct() {
	// #772 identity rider: once the predicate AST carries ::T (and eval
	// honors it), identity must distinguish it in the same landing.
	a := '[?def f (\$d) \$d//x[@age::int]]'
	b := '[?def f (\$d) \$d//x[@age::str]]'
	assert h(a) != h(b), 'a predicate type test is part of the computation (#772 rider)'
}

fn test_tier2_implicit_asc_bytes_unmoved() {
	// direction is presence-marked: an implicit-asc [order-by] keeps its
	// exact pre-fix bytes (only explicit asc/desc spellings gain the field).
	stream := code.tier2_normalize_def('[?def f (\$s) [?for [in \$o \$s] [order-by \$o/k] [yield \$o]]]') or {
		panic('normalize failed: ${err}')
	}
	assert stream.contains('|order_by0:e'), 'implicit-asc clause row must keep the pre-fix byte shape, got: ${stream}'
}

// ── W7 — the Tier-2 comprehension traversal rides THE ONE walk (L100 tail).
// These byte-pins were captured on the PRE-retirement emitter (post-#769) and
// prove the retirement moved nothing: clause rows in order, hint clauses as
// metadata-only rows (mid-stream AND trailing), source-before-expr, yield
// then the map-yield value. The full-corpus proof is the address-baseline
// gate (C9); these are the local drift guards.

fn pin_stream(def_source string, want string) {
	got := code.tier2_normalize_def(def_source) or {
		panic('normalize failed for `${def_source}`: ${err}')
	}
	assert got == want, 'Tier-2 stream moved (C9 — a moved hash is a defect):\n got: ${got}\nwant: ${want}'
}

fn test_tier2_walk_pin_m5_multi_clause() {
	pin_stream('[?def f (\$s) [?for [in \$o [\$store:source \$s "//order"]] [in \$l \$o/line] [= \$r [* \$l@qty \$l@price]] [group-by \$o/customer/@region] [yield [row region=\$key revenue=[\$sum \$group/r]]]]]',
		'def:1p|(forsequencesequence|generator1:os(c12:store:source.2 0:\$b0 0:(Lstring_lit7://order))|generator1:ls\$r1:o/child4:line|binding1:re(Lcx_element1:*0:a0i2 \$r1:l/attr3:qty \$r1:l/attr5:price)|group_by0:e\$r1:o/child8:customer/attr6:region|y(Lcx_element3:row0:a2 6:region\$r3:key 7:revenue(c3:sum.1 0:\$r5:group/child1:r)i0))')
}

fn test_tier2_walk_pin_hint_clauses_interleaved() {
	pin_stream('[?def f (\$s) [?for [in \$o [\$store:source \$s "//o"]] [par] [where [= \$o/status "open"]] [ordered] [take 3] [yield \$o]]]',
		'def:1p|(forsequencesequence|generator1:os(c12:store:source.2 0:\$b0 0:(Lstring_lit3://o))|par0:|filter0:e(Lcx_element1:=0:a0i2 \$r1:o/child6:status (Lstring_lit4:open))|ordered0:|take0:e(Lint_lit1:3)|y\$r1:o)')
}

fn test_tier2_walk_pin_trailing_hint_clause() {
	pin_stream('[?def f (\$s) [?for [in \$o [\$store:source \$s "//o"]] [par] [yield \$o]]]',
		'def:1p|(forsequencesequence|generator1:os(c12:store:source.2 0:\$b0 0:(Lstring_lit3://o))|par0:|y\$r1:o)')
}

fn test_tier2_walk_pin_for_map_yield_value() {
	pin_stream('[?def f (\$s) [?for-map [in \$o [\$store:source \$s "//o"]] [yield-map \$o@k \$o/v]]]',
		'def:1p|(formapmap|generator1:os(c12:store:source.2 0:\$b0 0:(Lstring_lit3://o))|y\$r1:o/attr1:kv\$r1:o/child1:v)')
}

fn test_tier2_walk_pin_bare_pattern_generator() {
	pin_stream('[?def f () [?for [u] [yield 1]]]',
		'def:0|(forsequencesequence|generator1:_s(pnamed1:u)|y(Lint_lit1:1))')
}

fn test_tier2_pattern_attr_no_value_unmoved() {
	// The additions are presence-marked: an existence-only pattern attr keeps
	// its EXACT pre-fix bytes — `@` kind name op, immediately closed (no value
	// or type-test marker inserted), so the corpus blast radius is exactly the
	// previously-invisible content.
	stream := code.tier2_normalize_def('[?def f (\$d) [?match \$d [case [user @role] 1] [else 0]]]') or {
		panic('normalize failed: ${err}')
	}
	assert stream.contains('@existence4:role0:)'), 'existence-only pattern attr must keep the pre-fix byte shape, got: ${stream}'
}

// ── source: vcx/tests/identity_tier2_program_test.v ──
// #79 increment 2 — dependency-by-hash (Merkle-DAG) + mutual-recursion SCC.
// cx_program_tier2_hashes resolves sibling references to their Tier-2 hashes,
// so a caller's identity depends transitively on its callees' bodies (not
// their names), and mutual-recursion cycles hash as one component.

fn prog(src string) map[string]string {
	return code.cx_program_tier2_hashes(src) or {
		panic('program tier2 hashes failed: ${err}')
	}
}

// ── dependency sensitivity ───────────────────────────────────────────────────

fn test_tier2_caller_depends_on_callee_body() {
	// Same caller, callee bodies differ → caller hashes must differ.
	a := '[?def helper (\$x) [+ \$x 1]]
[?def main (\$y) [helper \$y]]'
	b := '[?def helper (\$x) [+ \$x 2]]
[?def main (\$y) [helper \$y]]'
	ha := prog(a)
	hb := prog(b)
	assert ha['main'] != hb['main'], 'caller hash must change when callee body changes'
}

fn test_tier2_caller_stable_when_callee_unchanged() {
	// Renaming the callee (alias) but keeping its body must NOT change the
	// caller's identity — names are aliases, dependency is by hash.
	a := '[?def helper (\$x) [+ \$x 1]]
[?def main (\$y) [helper \$y]]'
	b := '[?def aux (\$x) [+ \$x 1]]
[?def main (\$y) [aux \$y]]'
	ha := prog(a)
	hb := prog(b)
	assert ha['main'] == hb['main'], 'caller identity must be independent of callee NAME (hash-keyed dep)'
}

fn test_tier2_builtin_not_a_dependency() {
	// `+` is a builtin, not a sibling def — calling it is not a dep edge, and a
	// leaf def's program hash equals its standalone hash.
	src := '[?def f (\$x) [+ \$x 1]]'
	ph := prog(src)
	standalone := code.cx_code_tier2_hash('[?def f (\$x) [+ \$x 1]]') or { panic(err) }
	assert ph['f'] == standalone, 'leaf def program hash == standalone hash'
}

// ── mutual recursion: hashed as one component ────────────────────────────────

fn test_tier2_mutual_recursion_name_independent() {
	// even-p/odd-p mutually recurse; renaming the pair (and their bound vars)
	// must collide — the SCC is hashed positionally, name-free.
	a := '[?def even-p (\$n) [?match \$n [zero] true \$_ [odd-p [dec \$n]]]]
[?def odd-p (\$n) [?match \$n [zero] false \$_ [even-p [dec \$n]]]]'
	b := '[?def ev (\$m) [?match \$m [zero] true \$_ [od [dec \$m]]]]
[?def od (\$m) [?match \$m [zero] false \$_ [ev [dec \$m]]]]'
	ha := prog(a)
	hb := prog(b)
	assert ha['even-p'] == hb['ev'], 'mutual-recursion member must be name-independent'
	assert ha['odd-p'] == hb['od'], 'mutual-recursion member must be name-independent'
}

fn test_tier2_mutual_recursion_behavior_sensitive() {
	// Changing the cycle's behavior (swap true/false) must change the hashes.
	a := '[?def even-p (\$n) [?match \$n [zero] true \$_ [odd-p [dec \$n]]]]
[?def odd-p (\$n) [?match \$n [zero] false \$_ [even-p [dec \$n]]]]'
	b := '[?def even-p (\$n) [?match \$n [zero] false \$_ [odd-p [dec \$n]]]]
[?def odd-p (\$n) [?match \$n [zero] true \$_ [even-p [dec \$n]]]]'
	ha := prog(a)
	hb := prog(b)
	assert ha['even-p'] != hb['even-p'], 'changing cycle behavior must change the component hash'
}

fn test_tier2_mutual_recursion_members_distinct() {
	// The two members of the cycle are different computations → distinct hashes.
	src := '[?def even-p (\$n) [?match \$n [zero] true \$_ [odd-p [dec \$n]]]]
[?def odd-p (\$n) [?match \$n [zero] false \$_ [even-p [dec \$n]]]]'
	h := prog(src)
	assert h['even-p'] != h['odd-p'], 'distinct cycle members must hash distinctly'
}

fn test_tier2_self_recursion_is_cyclic() {
	// A directly self-recursive def is a singleton cycle; it still produces a
	// well-formed hash (its self-reference becomes positional, not its name).
	a := '[?def fact (\$n) [?match \$n [zero] 1 \$_ [* \$n [fact [dec \$n]]]]]'
	b := '[?def f2 (\$m) [?match \$m [zero] 1 \$_ [* \$m [f2 [dec \$m]]]]]'
	ha := prog(a)
	hb := prog(b)
	assert ha['fact'].len == 73
	assert ha['fact'] == hb['f2'], 'self-recursive def must be name-independent'
}

// ── well-formedness ──────────────────────────────────────────────────────────

fn test_tier2_program_all_hashes_well_formed() {
	src := '[?def helper (\$x) [+ \$x 1]]
[?def main (\$y) [helper \$y]]'
	h := prog(src)
	assert h.len == 2
	assert h['helper'].len == 73
	assert h['main'].len == 73
}

// ── source: vcx/tests/schema_hash_basis_test.v ──
// I1 row 6 (stream 1, E2/L82, forced by S0 L19a): the schema content-hash
// basis is the strict CANONICAL TEXT bytes — a schema's identity IS its
// Tier-1 document identity, one primitive, no second hashing machinery.
// The former CXCol-encoding basis (and the #724 framing ambiguity that
// rode it) is superseded; 0x10/0x12 embedded digests move once, at I1.

const schema_src = '[schema of=server]
[server
  [body elem]
  [attr host::string [req]]
  [attr port::u16 [req]]
]
'

// A reformatted-but-equivalent spelling (extra blank line + indentation).
const schema_src_reformatted = '[schema of=server]

[server
    [body elem]
    [attr host::string [req]]
    [attr port::u16 [req]]
]
'

// A semantically different schema (one more attribute).
const schema_src_other = '[schema of=server]
[server
  [body elem]
  [attr host::string [req]]
  [attr port::u16 [req]]
  [attr active::bool [default true]]
]
'

fn test_schema_hash_is_the_tier1_digest() {
	h := cx.schema_content_hash(schema_src) or {
		assert false, 'hash failed: ${err}'
		return
	}
	assert h.len == 32
	tagged := cx.cx_text_hash(schema_src) or {
		assert false, 'cx_text_hash failed: ${err}'
		return
	}
	// One basis: the 32 raw bytes embedded in 0x10/0x12 slots ARE the
	// digest inside the schema's tagged Tier-1 address.
	assert tagged == 'sha2-256:' + h.hex()
}

fn test_formatting_invariance_survives_the_basis_change() {
	a := cx.schema_content_hash(schema_src) or {
		assert false, '${err}'
		return
	}
	b := cx.schema_content_hash(schema_src_reformatted) or {
		assert false, '${err}'
		return
	}
	// sd-006 property under the new basis: canonical text normalizes
	// formatting, so equivalent spellings share one identity.
	assert a.hex() == b.hex()
}

fn test_semantic_change_moves_the_hash() {
	a := cx.schema_content_hash(schema_src) or {
		assert false, '${err}'
		return
	}
	b := cx.schema_content_hash(schema_src_other) or {
		assert false, '${err}'
		return
	}
	assert a.hex() != b.hex()
}

// RESIDUAL RESOLVED (ledger entry 25 → I5 stream 1 R1): schema
// metadata moved into the `[schema …]` header ELEMENT — ordinary body
// data — so `of` / `mode` / `name` / `version` all ride in the
// canonical text and the content-hash. Two schemas differing only in
// mode are two schemas with two identities, exactly as E2's
// "schema-mode rides in the hash as document bytes" requires. This is
// the pinned flip of the former
// test_mode_does_not_survive_canonical_text_named_residual.
fn test_mode_rides_in_canonical_text_and_hash() {
	with_mode := '[schema of=server mode=closed]\n[server [body elem]]\n'
	without_mode := '[schema of=server]\n[server [body elem]]\n'
	a := cx.schema_content_hash(with_mode) or {
		assert false, '${err}'
		return
	}
	b := cx.schema_content_hash(without_mode) or {
		assert false, '${err}'
		return
	}
	assert a.hex() != b.hex()
}

// The retired pragma spellings are rejected at schema LOAD (fail-loud,
// never silently unhashed metadata). schema_content_hash itself stays
// pure text canonicalization; no anchoring surface can reach a hash
// through a schema that fails to load.
fn test_retired_schema_pragmas_rejected() {
	legacy := '[?cx schema-of server]\n[server [body elem]]\n'
	if _ := cx.parse_schema(legacy) {
		assert false, 'retired [?cx schema-of] spelling must fail schema load'
	} else {
		assert err.msg().contains('S009')
	}
}

// ── source: vcx/tests/formal_witness_harness_test.v ──
// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  FORMAL PARSE-LAYER WITNESS HARNESS                                         ║
// ╚══════════════════════════════════════════════════════════════════════════╝
// Turns the CX→XML / CX→<cx:err> witnesses in spec/02-inprogress/formal/ into
// executable conformance tests (cxparse unification "implement-against-the-
// witnesses" convergence phase).
//
// The witness corpus is vcx/tests/formal/witnesses.txt (transcribed verbatim).
// This file carries a DEDICATED conformance emitter (emit_formal_*) that maps
// the EXISTING cx parse tree to the contract's canonical XML per the M-* rules
// in parser-rules-for-cx-meaning.txt. It is intentionally SEPARATE from the
// shipping cx.emit_xml (which uses a different canonical form: <cx:arr>/<item>
// wrappers, xml:id, indentation) — the point is to test "what tree does the
// parser produce", expressed in the contract's image, WITHOUT disturbing the
// shipping serialization surface (N2).
//
// Pass 1 runs the DATA-mode witnesses; program-mode rows (calls/bindings/paths/
// slices) are deferred to the program-mode emitter pass. Each row's result is
// classified and written to a triage report; the test itself never fails (the
// report is the convergence signal — every mismatch is either an impl bug or a
// spec corner the contract got wrong, triaged by hand against the invariants).
// ── XML escaping (the contract's escape(), local to the harness) ──────────────

fn esc_text(s string) string {
	// The contract's escape() renders control whitespace as numeric character
	// references (witness LX-ESCAPE-1: '\n' decodes to a newline, imaged &#10;).
	return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('\n',
		'&#10;').replace('\r', '&#13;').replace('\t', '&#9;')
}

fn esc_attr(s string) string {
	return s.replace('&', '&amp;').replace('<', '&lt;').replace('"', '&quot;')
}

// ── render(Scalar{T,v}) — canonical scalar printer (§HELPERS) ─────────────────

fn render_scalar(n cx.ScalarNode) string {
	return cx.scalar_value_str_public(n.value)
}

// ── ximg_wrapped: a node's image in COLLECTION-ITEM / isolation position ──────
// (strings wrap as <cx:string>; this is also the node-in-isolation image used
// for kind=node witnesses and for M-DOC's wrapped roots).

fn ximg_wrapped(n cx.Node) string {
	match n {
		cx.Element {
			return emit_formal_element(n)
		}
		cx.ScalarNode {
			if n.data_type == .atom_type {
				return '<cx:atom>${esc_text(render_scalar(n))}</cx:atom>'
			}
			if n.data_type == .null_type {
				return '<cx:null/>'
			}
			if n.data_type == .string_type {
				return '<cx:string>${esc_text(render_scalar(n))}</cx:string>'
			}
			tn := cx.scalar_type_name_public(n.data_type)
			return '<cx:${tn}>${esc_text(render_scalar(n))}</cx:${tn}>'
		}
		cx.TextNode {
			return '<cx:string>${esc_text(n.value)}</cx:string>'
		}
		cx.ArrayNode {
			mut b := ''
			for it in n.items {
				b += ximg_wrapped(it)
			}
			return '<cx:array>${b}</cx:array>'
		}
		cx.SequenceNode {
			mut b := ''
			for it in n.items {
				b += ximg_wrapped(it)
			}
			return '<cx:seq>${b}</cx:seq>'
		}
		cx.MapNode {
			mut b := ''
			for e in n.entries {
				key := cx.ScalarNode{
					data_type: e.key_type
					value:     e.key_value
				}
				b += '<cx:entry><cx:key>${ximg_wrapped(key)}</cx:key><cx:val>${ximg_wrapped(e.value)}</cx:val></cx:entry>'
			}
			return '<cx:map>${b}</cx:map>'
		}
		cx.AliasNode {
			return '<cx:alias cx:name="${esc_attr(n.name)}"/>'
		}
		cx.CommentNode {
			// LX-WS: a `#` LINE comment is trivia (skipped, never a token) — it
			// is dropped from the semantic image (LX-WS-2). The impl preserves it
			// as a CommentNode{is_line:true} in the parse tree for lossless
			// `cx fmt` round-trip, but it carries no CX→XML meaning. A `[- … ]`
			// BLOCK comment is a real Comment NODE and images via M-COMMENT.
			if n.is_line {
				return ''
			}
			return comment_img(n)
		}
		cx.RawTextNode {
			return raw_img(n)
		}
		cx.EntityRefNode {
			return '<cx:entity-ref cx:name="${esc_attr(n.name)}"/>'
		}
		cx.PINode {
			return pi_img(n)
		}
		cx.XMLDeclNode {
			// M-PI: the reserved `xml` target falls back to the PI CARRIER
			// (`<?xml?>` is an illegal PI target). The data parser captures the
			// pseudo-attributes structurally as an XMLDeclNode; reconstruct the
			// source-form data string (`version=… encoding=… standalone=…`) and
			// image it through the carrier (M-PI-3).
			mut parts := ['version=${n.version}']
			if enc := n.encoding {
				parts << 'encoding=${enc}'
			}
			if sa := n.standalone {
				parts << 'standalone=${sa}'
			}
			return '<cx:pi cx:target="xml">${esc_text(parts.join(' '))}</cx:pi>'
		}
		cx.EvalDirectiveNode {
			mut b := ''
			for it in n.items {
				b += ximg_wrapped(it)
			}
			return '<cx:directive cx:head="${esc_attr(n.name)}">${b}</cx:directive>'
		}
		cx.EntityDeclNode {
			// M-DECL: ENTITY images as native XML, raw-preserved.
			marker := if n.kind == .pe { '% ' } else { '' }
			def := n.def
			ds := if def is string { "'${def}'" } else { 'EXTERNAL' }
			return '<!ENTITY ${marker}${n.name} ${ds}>'
		}
		else {
			return '<cx:UNHANDLED-NODE(${typeof(n).name})/>'
		}
	}
}

// ── ximg_body: a node's image as an ELEMENT BODY child (strings are BARE text) ─

fn ximg_body(n cx.Node) string {
	if n is cx.TextNode {
		return esc_text(n.value)
	}
	if n is cx.ScalarNode {
		if n.data_type == .string_type {
			return esc_text(render_scalar(n))
		}
	}
	return ximg_wrapped(n)
}

// ── M-COMMENT / M-RAW / M-PI images ───────────────────────────────────────────

fn comment_img(c cx.CommentNode) string {
	if c.value.contains('--') {
		return '<cx:comment>${esc_text(c.value)}</cx:comment>'
	}
	return '<!--${c.value}-->'
}

fn raw_img(r cx.RawTextNode) string {
	content := r.value.replace(']]>', ']]><![CDATA[>')
	return '<![CDATA[${content}]]>'
}

fn pi_img(p cx.PINode) string {
	data := p.data or { '' }
	if data == '' {
		return '<?${p.target}?>'
	}
	if p.target != 'xml' && !data.contains('?>') {
		return '<?${p.target} ${data}?>'
	}
	return '<cx:pi cx:target="${esc_attr(p.target)}">${esc_text(data)}</cx:pi>'
}

// ── elem_cx_type: the cx:type value for an element's A(m) (head ann OR sole) ───

fn elem_cx_type(e cx.Element) string {
	if hd := e.data_type() {
		return hd
	}
	if e.items.len == 1 {
		it := e.items[0]
		if it is cx.ScalarNode {
			if it.data_type == .string_type || it.data_type == .atom_type {
				return ''
			}
			if it.data_type == .null_type {
				return 'null'
			}
			return cx.scalar_type_name_public(it.data_type)
		}
	}
	return ''
}

// ── sidecar: the cx:attr-types value (D3 + M-NULL mandatory null) ─────────────

fn sidecar(attrs []cx.Attribute) ?string {
	mut parts := []string{}
	for a in attrs {
		if a.is_ref {
			continue
		}
		if dt := a.data_type() {
			if dt == 'null' {
				parts << '${a.name}=null'
			} else if dt == 'string' {
				if cx.cx_would_autotype(cx.scalar_value_str_public(a.value)) {
					parts << '${a.name}=string'
				}
			} else if !cx.type_name_is_auto_recoverable(dt) {
				parts << '${a.name}=${dt}'
			}
		} else {
			if cx.cx_would_autotype(cx.scalar_value_str_public(a.value)) {
				parts << '${a.name}=string'
			}
		}
	}
	if parts.len == 0 {
		return none
	}
	return parts.join(' ')
}

// ── A(m): the canonical-order attribute section ───────────────────────────────

fn attr_section(e cx.Element) string {
	mut s := ''
	if a := e.anchor() {
		s += ' cx:anchor="${esc_attr(a)}"'
	}
	if m := e.merge() {
		s += ' cx:merge="${esc_attr(m)}"'
	}
	if id := e.id() {
		s += ' cx:id="${esc_attr(id)}"'
	}
	ct := elem_cx_type(e)
	if ct != '' {
		s += ' cx:type="${ct}"'
	}
	for at in e.attrs {
		dt := at.data_type() or { '' }
		if dt == 'null' {
			continue
		}
		s += ' ${at.name}="${esc_attr(cx.scalar_value_str_public(at.value))}"'
	}
	if sc := sidecar(e.attrs) {
		s += ' cx:attr-types="${esc_attr(sc)}"'
	}
	return s
}

// ── M-ELEMENT / M-SCALAR-SOLE / M-TYPED-ARRAY ─────────────────────────────────

fn emit_formal_element(e cx.Element) string {
	a := attr_section(e)
	head_dt := e.data_type() or { '' }

	// M-TYPED-ARRAY: head ::T[] / ::[]
	if head_dt.ends_with('[]') {
		base := head_dt#[..-2]
		mut b := ''
		for it in e.items {
			if base == '' {
				// ::[] inferred array (P2-INFERARR): items keep their OWN type —
				// image each via its self type (`<cx:int>`, `<cx:float>`, …), with
				// cx:type="[]" carried in the attr section. NOT `<cx:>`.
				b += ximg_wrapped(it)
			} else if it is cx.ScalarNode {
				b += '<cx:${base}>${esc_text(render_scalar(it))}</cx:${base}>'
			} else {
				b += ximg_wrapped(it)
			}
		}
		return '<${e.name}${a}>${b}</${e.name}>'
	}

	if e.items.len == 0 {
		return '<${e.name}${a}/>'
	}

	// sole-child shapes
	if e.items.len == 1 {
		it := e.items[0]
		if it is cx.ScalarNode {
			if it.data_type == .null_type {
				return '<${e.name}${a}/>' // M-NULL (cx:type="null" in A)
			}
			if it.data_type == .atom_type {
				return '<${e.name}${a}><cx:atom>${esc_text(render_scalar(it))}</cx:atom></${e.name}>'
			}
			if it.data_type == .string_type {
				return '<${e.name}${a}>${esc_text(render_scalar(it))}</${e.name}>'
			}
			// non-string scalar sole → bare render, cx:type in A (M-SCALAR-SOLE)
			return '<${e.name}${a}>${esc_text(render_scalar(it))}</${e.name}>'
		}
	}

	// general body
	mut b := ''
	for it in e.items {
		b += ximg_body(it)
	}
	return '<${e.name}${a}>${b}</${e.name}>'
}

// ── M-DOC: whole-document image ───────────────────────────────────────────────

fn emit_formal_doc(doc cx.Document) string {
	mut roots := []cx.Node{}
	roots << doc.prolog
	roots << doc.elements
	if roots.len == 1 {
		r := roots[0]
		if r is cx.Element {
			return emit_formal_element(r)
		}
		return '<cx:docs>${ximg_wrapped(r)}</cx:docs>'
	}
	mut b := ''
	for r in roots {
		b += ximg_wrapped(r)
	}
	return '<cx:docs>${b}</cx:docs>'
}

// ── M-DOC multidoc image ('---'-separated documents) ─────────────────────────

fn emit_formal_multidoc(docs []cx.Document) string {
	mut b := ''
	for d in docs {
		mut roots := []cx.Node{}
		roots << d.prolog
		roots << d.elements
		mut inner := ''
		for r in roots {
			inner += ximg_wrapped(r)
		}
		b += '<cx:doc>${inner}</cx:doc>'
	}
	return '<cx:docs>${b}</cx:docs>'
}

// ── node-in-isolation image (kind=node) ───────────────────────────────────────

fn emit_formal_single_node(doc cx.Document) !string {
	mut roots := []cx.Node{}
	roots << doc.prolog
	roots << doc.elements
	if roots.len != 1 {
		return error('expected exactly one root node, got ${roots.len}')
	}
	return ximg_wrapped(roots[0])
}

// ── M-PROGRAM: the program-AST conformance emitter ────────────────────────────
//
// Program-mode witnesses parse with `cx.parse_program` and image the resulting
// ProgramNode tree per the M-PROGRAM rule in parser-rules-for-cx-meaning.txt:
//   Form{call,h,b}      ⇒ <cx:call cx:head="h">map(ximg,b)</cx:call>
//   Form{directive,h,b} ⇒ <cx:directive cx:head="h" A(m)>map(ximg,b)</cx:directive>
//   Binding{n}          ⇒ <cx:var cx:name="n"/>
//   Path{steps}         ⇒ <cx:path>…</cx:path>
//   Slice{axes}         ⇒ <cx:slice>…</cx:slice>
// Like the data emitter this is SEPARATE from the shipping program XML codec —
// it tests "what tree does parse_program produce", expressed in the contract image.

// program_op_heads: the OpSym ∪ reserved-word-op set whose appearance as a
// bracket head ([G-BRACKET]) makes the form a CALL, not an element construction.
// (`OpSym ::= '+'|'-'|'*'|'/'|'='|'!='|'<'|'<='|'>'|'>='`; reserved word ops
// `and|or|not|cast` per grammar.ebnf line 60.) The data parser represents these
// as a `.cx_element` ProgramLiteral whose `name` is the operator string.
const program_op_heads = ['+', '-', '*', '/', '=', '!=', '<', '<=', '>', '>=', 'and', 'or',
	'not', 'cast']

fn ximg_program(n cx.ProgramNode) string {
	match n {
		cx.Program {
			return ximg_program(n.body)
		}
		cx.ProgramCall {
			mut b := ''
			for a in n.args {
				b += ximg_program(a)
			}
			return '<cx:call cx:head="${esc_attr(n.name)}">${b}</cx:call>'
		}
		cx.ProgramBinding {
			// Binding{n} ⇒ <cx:var cx:name="n"/>. A binding carrying path steps
			// would image as <cx:path> (no witness exercises it yet).
			return '<cx:var cx:name="${esc_attr(n.name)}"/>'
		}
		cx.ProgramLiteral {
			return ximg_program_literal(n)
		}
		cx.ProgramDirective {
			mut b := ''
			for s in n.slots {
				b += ximg_program(s.value)
			}
			return '<cx:directive cx:head="${esc_attr(n.name)}">${b}</cx:directive>'
		}
		else {
			return '<cx:UNHANDLED-PROGRAM(${typeof(n).name})/>'
		}
	}
}

fn ximg_program_literal(l cx.ProgramLiteral) string {
	match l.kind {
		.int_lit {
			return '<cx:int>${l.int_val}</cx:int>'
		}
		.float_lit {
			return '<cx:float>${l.flt_val}</cx:float>'
		}
		.bool_lit {
			return '<cx:bool>${l.bool_val}</cx:bool>'
		}
		.string_lit {
			return '<cx:string>${esc_text(l.str_val)}</cx:string>'
		}
		.atom_lit {
			return '<cx:atom>${esc_text(l.str_val)}</cx:atom>'
		}
		.cx_element {
			// [G-BRACKET]: an operator / reserved-word-op head ⇒ op-Form ⇒ call.
			if l.name in program_op_heads {
				mut b := ''
				for it in l.items {
					b += ximg_program(it)
				}
				return '<cx:call cx:head="${esc_attr(l.name)}">${b}</cx:call>'
			}
			// QName head ⇒ element construction (no program-mode element witness
			// yet; image best-effort as a bare element).
			mut b := ''
			for it in l.items {
				b += ximg_program(it)
			}
			return '<${l.name}>${b}</${l.name}>'
		}
		else {
			return '<cx:UNHANDLED-LITERAL(${l.kind})/>'
		}
	}
}

fn emit_formal_program(prog cx.Program) string {
	return ximg_program(prog.body)
}

// ── error-code extraction (code token out of the CxError message) ─────────────
//
// Handles both the program `CXER…` range (`core/code.md` §9.5) and the
// data-parse `E…` range (`core/cxdm.md` §11). Both ride the `cx-err:` carrier
// in the message (e.g. `… (cx-err:E210)` / `… (cx-err:CXER0241)`); keying on
// the carrier avoids matching a stray `CXER`/`E` word in prose.
fn extract_code(msg string) string {
	if ci := msg.index('cx-err:') {
		start := ci + 'cx-err:'.len
		mut end := start
		for end < msg.len {
			c := msg[end]
			if (c >= `A` && c <= `Z`) || (c >= `0` && c <= `9`) || c == `-` {
				end++
			} else {
				break
			}
		}
		return msg[start..end]
	}
	// Fallback: a bare `CXER…` token with no `cx-err:` carrier.
	idx := msg.index('CXER') or { return '' }
	mut end := idx
	for end < msg.len {
		c := msg[end]
		if (c >= `A` && c <= `Z`) || (c >= `0` && c <= `9`) || c == `-` {
			end++
		} else {
			break
		}
	}
	return msg[idx..end]
}

fn expected_code(expect string) string {
	// expect like: <cx:err code="CXER0100" offset="4"/>
	marker := 'code="'
	idx := expect.index(marker) or { return '' }
	rest := expect[idx + marker.len..]
	q := rest.index('"') or { return rest }
	return rest[..q]
}

fn expected_offset(expect string) string {
	marker := 'offset="'
	idx := expect.index(marker) or { return '' }
	rest := expect[idx + marker.len..]
	q := rest.index('"') or { return rest }
	return rest[..q]
}

// ── the runner ────────────────────────────────────────────────────────────────

struct Row {
	id     string
	mode   string
	kind   string
	input  string
	expect string
}

fn load_rows() []Row {
	path := os.join_path(@VMODROOT, 'tests', 'formal', 'witnesses.txt')
	raw := os.read_file(path) or { panic('cannot read witness corpus: ${err}') }
	mut rows := []Row{}
	for line in raw.split_into_lines() {
		t := line.trim_space()
		if t == '' || t.starts_with('#') {
			continue
		}
		parts := line.split('\t')
		if parts.len != 5 {
			continue
		}
		rows << Row{
			id:     parts[0]
			mode:   parts[1]
			kind:   parts[2]
			input:  parts[3].replace('<NL>', '\n')
			expect: parts[4]
		}
	}
	return rows
}

fn test_formal_witnesses() {
	rows := load_rows()
	mut report := []string{}
	report << '# Formal parse-layer witness triage (cxparse implement-against-witnesses)'
	report << ''
	report << 'Generated by vcx/tests/formal_witness_harness_test.v over'
	report << 'vcx/tests/formal/witnesses.txt. PASS = the existing cx parse tree, imaged'
	report << 'through the contract emitter, matches the witness exactly.'
	report << ''

	mut n_pass := 0
	mut n_fail := 0
	// evaluation-layer witnesses (kind = eval/trace) are ENFORCED —
	// they pin the SHIPPED evaluator (stream 22 W1), unlike the
	// exploratory parse-convergence triage.
	mut n_eval_fail := 0
	n_deferred := 0 // program-mode rows now run (pass 2); none deferred
	mut fails := []string{}

	for r in rows {
		// ── kind = eval / trace (stream 22 W1, clean-room §3-C): the
		// EVALUATION-layer witnesses. eval compares the §11.1a result
		// image (code.render_canonical); trace compares the ordered
		// admitted-effect-point sequence (';'-joined — the out-effects
		// channel's vocabulary). Each EV-* rule is discharged by a
		// DISCRIMINATOR PAIR of these rows.
		if r.kind == 'eval' || r.kind == 'trace' {
			code.caps_set_all()
			mut wenv := code.new_env()
			prog := cx.parse_program(r.input) or {
				n_eval_fail++
				fails << '- **${r.id}** PARSE-ERR(${r.kind})  input=`${vis(r.input)}`  (${err.msg()})'
				continue
			}
			result := code.eval(prog.body, mut wenv) or {
				n_eval_fail++
				fails << '- **${r.id}** EVAL-ERR(${r.kind})  input=`${vis(r.input)}`  (${err.msg()})'
				continue
			}
			got := if r.kind == 'eval' {
				code.render_canonical(result).trim_space()
			} else {
				code.effects_trace_snapshot().join(';')
			}
			if got == r.expect {
				n_pass++
			} else {
				n_eval_fail++
				fails << '- **${r.id}** MISMATCH(${r.kind})  input=`${vis(r.input)}`\n    want: `${r.expect}`\n    got:  `${got}`'
			}
			continue
		}
		if r.mode == 'program' {
			// Program-mode pass: parse with cx.parse_program; err rows compare the
			// CXER code, node rows image the ProgramNode tree via emit_formal_program.
			if r.kind == 'err' {
				want := expected_code(r.expect)
				prog := cx.parse_program(r.input) or {
					got := extract_code(err.msg())
					if got == want {
						n_pass++
					} else {
						n_fail++
						fails << '- **${r.id}** ERR-CODE(program)  input=`${vis(r.input)}`  want=`${want}` got=`${got}`  (msg: ${err.msg()})'
					}
					continue
				}
				_ := prog
				n_fail++
				fails << '- **${r.id}** ERR-ACCEPTED(program)  input=`${vis(r.input)}`  contract rejects with `${want}` but parse_program ACCEPTED'
				continue
			}
			// node / doc
			prog := cx.parse_program(r.input) or {
				n_fail++
				fails << '- **${r.id}** PARSE-ERR(program)  input=`${vis(r.input)}`  (${err.msg()})  want=`${r.expect}`'
				continue
			}
			got := emit_formal_program(prog)
			if got == r.expect {
				n_pass++
			} else {
				n_fail++
				fails << '- **${r.id}** MISMATCH(program)  input=`${vis(r.input)}`\n    want: `${r.expect}`\n    got:  `${got}`'
			}
			continue
		}
		if r.kind == 'err' {
			want := expected_code(r.expect)
			want_off := expected_offset(r.expect)
			cx.parse(r.input) or {
				got := extract_code(err.msg())
				if got == want {
					n_pass++
				} else {
					n_fail++
					fails << '- **${r.id}** ERR-CODE  input=`${vis(r.input)}`  want=`${want}` got=`${got}`  (msg: ${err.msg()})'
				}
				continue
			}
			// parse SUCCEEDED but contract rejects
			n_fail++
			fails << '- **${r.id}** ERR-ACCEPTED  input=`${vis(r.input)}`  contract rejects with `${want}`@${want_off} but impl ACCEPTED'
			continue
		}

		// multi-document ('---'-separated) — uses the stream entry, M-DOC multidoc image
		if r.kind == 'doc' && r.input.contains('\n---') {
			docs := cx.parse_stream(r.input) or {
				n_fail++
				fails << '- **${r.id}** MULTIDOC-PARSE-ERR  input=`${vis(r.input)}`  (${err.msg()})'
				continue
			}
			got := emit_formal_multidoc(docs)
			if got == r.expect {
				n_pass++
			} else {
				n_fail++
				fails << '- **${r.id}** MISMATCH(multidoc)  input=`${vis(r.input)}`\n    want: `${r.expect}`\n    got:  `${got}`'
			}
			continue
		}

		// doc / node
		doc := cx.parse(r.input) or {
			n_fail++
			fails << '- **${r.id}** PARSE-ERR  input=`${vis(r.input)}`  (${err.msg()})  want=`${r.expect}`'
			continue
		}
		got := if r.kind == 'node' {
			emit_formal_single_node(doc) or {
				n_fail++
				fails << '- **${r.id}** NODE-EXTRACT  input=`${vis(r.input)}`  (${err.msg()})'
				continue
			}
		} else {
			emit_formal_doc(doc)
		}
		if got == r.expect {
			n_pass++
		} else {
			n_fail++
			fails << '- **${r.id}** MISMATCH  input=`${vis(r.input)}`\n    want: `${r.expect}`\n    got:  `${got}`'
		}
	}

	total_run := n_pass + n_fail
	report << '## Summary'
	report << ''
	report << '- witnesses run (data + program): **${total_run}**'
	report << '- PASS: **${n_pass}**'
	report << '- FAIL (triage): **${n_fail}**'
	report << '- program-mode deferred: **${n_deferred}**'
	report << '- total corpus rows: **${rows.len}**'
	report << ''
	report << '## Failures (each is an impl bug OR a spec corner — triaged by hand)'
	report << ''
	for f in fails {
		report << f
	}
	report << ''

	out_dir := os.join_path(@VMODROOT, '..', '_gate_evidence')
	os.mkdir_all(out_dir) or {}
	os.write_file(os.join_path(out_dir, 'formal_witness_triage.md'), report.join('\n')) or {
		panic('cannot write triage report: ${err}')
	}

	// Pass 1 is exploratory for the PARSE-layer rows — the report is the
	// artifact; a regression guard (assert n_fail <= baseline) lands once
	// convergence starts. The EVALUATION-layer rows (kind = eval/trace)
	// are enforced: they pin the shipped evaluator.
	assert n_eval_fail == 0, 'evaluation-layer witness failure(s):\n' + fails.join('\n')
	assert n_pass + n_fail + n_eval_fail + n_deferred == rows.len
}

// vis renders control chars in an input for the report (newline → \n).
fn vis(s string) string {
	return s.replace('\n', '\\n')
}

// ── [131b] kind tests are IDENTITY-DISTINCT (issue-809) ─────────────────────
//
// POST-APPLY umbrella addition — not in
// scripts/consolidation/identity.files; reconcile it into the manifest
// inputs before any future regeneration.
//
// A kind test carries no name, so before it entered the identity stream
// every kind-test step hashed like every other kind-test step on the
// same axis: `$x/text()` and `$x/element()` are DIFFERENT queries that
// would have shared one Tier-2 address (and one plan address) — a false
// merge, which the caching identity contract does not allow. The field
// is written PRESENCE-MARKED off `.none`, so a step WITHOUT a kind test
// contributes zero bytes and every pre-existing address is byte-for-byte
// where it was; the corpus golden hashes in conformance/identity.cxd and
// identity_hash.cxd are the other half of that guard.

fn test_tier2_kind_tests_do_not_collide() {
	node := h('[?def f (\$x) \$x/node()]')
	text := h('[?def f (\$x) \$x/text()]')
	elem := h('[?def f (\$x) \$x/element()]')
	attr := h('[?def f (\$x) \$x/attribute()]')
	all := [node, text, elem, attr]
	for i in 0 .. all.len {
		for j in i + 1 .. all.len {
			assert all[i] != all[j],
				'kind tests ${i} and ${j} share a Tier-2 address; they are different queries'
		}
	}
}

fn test_tier2_kind_test_distinct_from_name_test() {
	// A step named `node` is not the kind test `node()`.
	assert h('[?def f (\$x) \$x/node]') != h('[?def f (\$x) \$x/node()]'),
		'the NAME `node` and the KIND TEST `node()` must not share an address'
}

fn test_tier2_kind_test_axis_is_part_of_identity() {
	assert h('[?def f (\$x) \$x/text()]') != h('[?def f (\$x) \$x//text()]'),
		'child and descendant kind-test steps must not share an address'
}

fn test_tier2_rooted_kind_tests_do_not_collide() {
	assert h('[?def f () //text()]') != h('[?def f () //element()]'),
		'rooted kind tests must not share a Tier-2 address'
}
