// lint_lsp_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):
// the per-area test-binary umbrella. 2 source files merged verbatim (byte-identical
// helper dedupe only; the V compiler is the name-collision oracle). Fewer test
// files = fewer whole-module-graph compiles (V compilation was 99% of the gate).
// Regenerate: scripts/consolidate_tests.sh gen lint_lsp
// Manifest:   scripts/consolidation/lint_lsp.files

module main

import cx
import os
import testenv
import time as vtime
import x.json2

// ── source: vcx/tests/lint_lsp_umbrella_test.v ──
// ── source: vcx/tests/lint_field_read_test.v ──
// lint_field_read_test.v — #610: CX-L007 flags $count/$empty/$exists over a
// SIMPLE FIELD ACCESSOR (a pure /name child chain — the code.md §6.2
// field-read shape, whose aggregation reports the field's CONTENT arity,
// ruled by-design in #584) and teaches the sanctioned match-counting idioms.
// Warning severity, detect-only. Node-set forms (//, /*, predicates),
// bare bindings, dot-chains, and non-aggregation reads never fire.

fn l7_bin() string {
	return testenv.cx_bin()
}

fn l7_out(src string) string {
	f := os.join_path(os.temp_dir(), 'cx_l007_${os.getpid()}_${src.len}.cx')
	os.write_file(f, src) or { panic('write: ${err}') }
	defer { os.rm(f) or {} }
	r := os.execute('${l7_bin()} lint ${f}')
	return r.output
}

fn l7_count(out string) int {
	mut n := 0
	for line in out.split('\n') {
		if line.contains('CX-L007') {
			n++
		}
	}
	return n
}

fn test_lint_dispatch_agrees_with_fmt_on_program_docs() {
	// #921: a call-shaped PROGRAM document the DATA reading refuses is not
	// a lint parse failure — the dispatch must agree with fmt/run (#391).
	// This exact shape (a call head + a ws-entry map argument) false-failed
	// with the data reader's collection-slot refusal before.
	prog := "[\$xap:component order-card {props: {order: ::string compact: ::bool} view: 'v'}]"
	fs := cx.cx_text_lint(prog, cx.LintOptions{}) or {
		assert false, 'lint refused a program document fmt/run accept: ${err.msg()}'
		return
	}
	assert fs.len == 0, 'no data tree, no doc-shaped findings: ${fs}'
	// A document BOTH readings refuse keeps reporting the data diagnostic.
	if _ := cx.cx_text_lint('{a ::int}', cx.LintOptions{}) {
		assert false, 'both-readings-refused input must still refuse'
	}
}

fn test_l007_fires_on_field_read_aggregation() {
	// the #584 shape verbatim: count over a pure child chain.
	out := l7_out('[?let [= \$b [box [life [evidence [id "e1"]]]]] [\$count \$b/life]]')
	assert l7_count(out) == 1, 'count over a field read must warn: ${out}'
	assert out.contains('§6.2') || out.contains('content'), 'finding must teach the composition: ${out}'
	assert out.contains('//life') || out.contains('predicate'), 'finding must name the sanctioned idioms: ${out}'

	// $empty and $exists share the trap; deeper chains fire too.
	out2 := l7_out('[?let [= \$x [a [b [c 1]]]] [\$empty \$x/a/b]]')
	assert l7_count(out2) == 1, 'empty over a deep field chain must warn: ${out2}'
	out3 := l7_out('[?let [= \$r [res [v [thing]]]] [\$exists \$r/v]]')
	assert l7_count(out3) == 1, 'exists over a field read must warn: ${out3}'

	// nested positions (inside a view literal / for-comp) still fire.
	out4 := l7_out('[?let [= \$b [w [k 1]]] [?for [in \$i (1,2)] [yield [item [\$count \$b/k]]]]]')
	assert l7_count(out4) == 1, 'nested aggregation must warn: ${out4}'
}

fn test_l007_silent_on_sanctioned_forms() {
	// the sanctioned match-counting idioms never fire.
	out := l7_out('[?let [= \$b [box [life [e 1]]]] [\$count \$b//life]]')
	assert l7_count(out) == 0, 'descendant counting must not warn: ${out}'
	out2 := l7_out('[?let [= \$b [box [life [e 1]]]] [\$count \$b/*]]')
	assert l7_count(out2) == 0, 'wildcard counting must not warn: ${out2}'
	out3 := l7_out('[?let [= \$b [box [life [e 1]]]] [\$count \$b/life[= \$_@x 1]]]')
	assert l7_count(out3) == 0, 'predicate step must not warn: ${out3}'

	// bare bindings, dot-chains, and non-aggregation reads are fine.
	out4 := l7_out('[?let [= \$s (1, 2, 3)] [\$count \$s]]')
	assert l7_count(out4) == 0, 'bare-binding count must not warn: ${out4}'
	out5 := l7_out('[?let [= \$m {a: {b: 7}}] [\$count \$m.a]]')
	assert l7_count(out5) == 0, 'map dot-chain must not warn: ${out5}'
	out6 := l7_out('[?let [= \$b [box [life 1]]] \$b/life]')
	assert l7_count(out6) == 0, 'a plain field read must not warn: ${out6}'
}

fn test_l007_suppressable() {
	src := '[?let [= \$b [box [life [e 1]]]] [\$count \$b/life]]'
	out := l7_out(src)
	assert l7_count(out) == 1
	f := os.join_path(os.temp_dir(), 'cx_l007_off_${os.getpid()}.cx')
	os.write_file(f, src) or { panic('write: ${err}') }
	defer { os.rm(f) or {} }
	r := os.execute('${l7_bin()} lint --disable CX-L007 ${f}')
	assert l7_count(r.output) == 0, 'disable flag must suppress: ${r.output}'
}

// ── source: vcx/tests/lint_let_staircase_test.v ──
// lint_let_staircase_test.v — #65: the CX-L006 detect-only lint rule flags a
// PURE nested single-binding [?let] staircase (>= 3 levels) and suggests the
// flat [?let] (let*) form. Detect-only (info severity, no rewrite); non-pure
// nestings and shallow chains are left alone.

fn cx_bin_lint() string {
	return testenv.cx_bin()
}

fn lint_out(src string, extra string) string {
	f := os.join_path(os.temp_dir(), 'cx_l006_${os.getpid()}_${src.len}.cx')
	os.write_file(f, src) or { panic('write: ${err}') }
	defer { os.rm(f) or {} }
	r := os.execute('${cx_bin_lint()} lint ${extra} ${f}')
	return r.output
}

fn count_l006(out string) int {
	mut n := 0
	for line in out.split('\n') {
		if line.contains('CX-L006') {
			n++
		}
	}
	return n
}

fn test_three_deep_staircase_flagged() {
	out := lint_out('[?let [= \$a 1] [?let [= \$b 2] [?let [= \$c 3] [+ \$a \$b \$c]]]]', '')
	assert count_l006(out) == 1, 'expected one CX-L006, got: ${out}'
	assert out.contains('3 levels'), 'expected "3 levels", got: ${out}'
}

fn test_flat_let_not_flagged() {
	out := lint_out('[?let [= \$a 1] [= \$b 2] [= \$c 3] [+ \$a \$b \$c]]', '')
	assert count_l006(out) == 0, 'flat let* should not be flagged: ${out}'
}

fn test_two_deep_below_threshold_not_flagged() {
	out := lint_out('[?let [= \$a 1] [?let [= \$b 2] [+ \$a \$b]]]', '')
	assert count_l006(out) == 0, '2-deep is below the threshold, should not flag: ${out}'
}

fn test_non_pure_if_body_not_flagged() {
	// outer [?let] body is an [?if] (lets live in its branches) — not a pure
	// chain, must not be flagged.
	out := lint_out('[?let [= \$a 1] [?if true [then [?let [= \$b 2] [?let [= \$c 3] \$b]]] [else 0]]]',
		'')
	assert count_l006(out) == 0, 'non-pure ([?if]-bodied) let must not flag: ${out}'
}

fn test_multi_binding_breaks_chain() {
	// a middle [?let] with two bindings is not single-binding → no pure
	// 3-chain → no flag.
	out := lint_out('[?let [= \$a 1] [?let [= \$b 2] [= \$b2 3] [?let [= \$c 4] \$a]]]', '')
	assert count_l006(out) == 0, 'multi-binding middle breaks the staircase: ${out}'
}

fn test_four_deep_reports_outermost_once() {
	out := lint_out('[?let [= \$a 1] [?let [= \$b 2] [?let [= \$c 3] [?let [= \$d 4] [+ \$a \$b]]]]]',
		'')
	assert count_l006(out) == 1, 'a 4-deep staircase should flag once (outermost), got: ${out}'
	assert out.contains('4 levels'), 'expected "4 levels", got: ${out}'
}

fn test_disable_suppresses_l006() {
	out := lint_out('[?let [= \$a 1] [?let [= \$b 2] [?let [= \$c 3] \$a]]]', '--disable=CX-L006')
	assert count_l006(out) == 0, '--disable=CX-L006 should suppress it: ${out}'
}

fn test_severity_is_info_not_failing() {
	// info severity must not trip the default --fail-on=error (exit 0).
	f := os.join_path(os.temp_dir(), 'cx_l006_exit_${os.getpid()}.cx')
	os.write_file(f, '[?let [= \$a 1] [?let [= \$b 2] [?let [= \$c 3] \$a]]]') or { panic(err) }
	defer { os.rm(f) or {} }
	r := os.execute('${cx_bin_lint()} lint ${f}')
	assert r.exit_code == 0, 'CX-L006 is info severity — must not fail the default gate, got exit ${r.exit_code}: ${r.output}'
	assert r.output.contains('CX-L006'), 'expected the finding in output: ${r.output}'
}

// ── source: vcx/tests/lsp_for_walk_test.v ──
// lsp_for_walk_test.v — stream-2 W2 pins for the L100 ONE-traversal
// contract (`cx.for_comp_children`, vcx/cx/program_for_walk.v) as seen
// through the LSP, plus the #711 item-5 / item-6 surface repairs.
//
// THE DEFECT THESE PIN. Every `[?for]` consumer used to hand-roll the
// clause walk. L100 predicted the walkers would diverge; they had. The
// LSP diagnostic walkers all descended into `clause.source`,
// `clause.expr` and `f.yield` and then STOPPED — none of them ever
// looked at `f.yield_value`, the `[yield-map K V]` VALUE node. So a
// `[?for-map]` whose value expression contained a diagnosable defect
// produced NO diagnostic at all: the editor was silently blind to an
// entire syntactic position.
//
// Measured on the pre-migration binary (stream-2 W2 negative control):
// the CXLS006 infinite-range advisory fired 0 times for a comprehension
// nested in `[yield-map K V]` value position and 1 time after the
// migration. That is the pin below.
//
// The surface pins guard the #711 item-5 repair (the LSP advertised
// colon-slot spellings — `[?let :x 1 :in body]`, `[?for … :return …]` —
// that the PARSER REJECTS, so completion inserted uncompilable syntax)
// and the item-6 / L98 retirement of the `[?for-tumbling]` /
// `[?for-sliding]` head reservations.

fn cx_bin() string {
	return testenv.cx_bin()
}

// ── #1004 — these pins run on the BOUNDED request-level harness ──────
//
// What stood here until #1004: `lsp_session`, plus `frame` / `esc_json` /
// `count_code` / `json_escape`, which drove `cx lsp` through an UNBOUNDED
// `os.execute` and then grepped raw stdout for `"code":"CXLS006"` /
// `"insertText":"` / `"label":"` / `"data":[`. That helper never un-framed
// the response stream, never decoded a body, and never matched a response
// to the id that asked for it — so a substring appearing anywhere in the
// byte stream (a diagnostic MESSAGE quoting a code, a `label` nested in
// some other frame, a hover body echoing `:return` as prose) satisfied the
// pin, and a server that stopped answering while still printing something
// passed. Worse, the probe was unbounded: a server regression that fails to
// terminate on `exit`/EOF hangs the whole gate lane rather than failing one
// test — exactly the failure mode #973 and #956 taught, and the reason
// `lsph_run` exists (30s wall bound, killed by PROCESS GROUP).
//
// Every pin below now goes through `lsph_run`: framed request stream in,
// framed response stream un-framed and JSON-decoded out, each response
// matched to its request id, and `lsph_healthy` asserting the session
// terminated inside its bound with the handshake and shutdown both
// answered. Each migrated assertion is strictly stronger than the substring
// match it replaces — see the per-test notes.

// lsph_diagnostics returns every diagnostic the server PUSHED for `uri`
// across the whole session, decoded. The retired `count_code` counted a
// substring over the raw stream and so could not tell a published
// diagnostic from the same bytes anywhere else, nor which document the
// diagnostics belonged to.
fn lsph_diagnostics(run LspRun, uri string) []map[string]json2.Any {
	mut out := []map[string]json2.Any{}
	for note in lsph_notifications(run, 'textDocument/publishDiagnostics') {
		params := lsph_obj(note['params'] or { json2.Any(json2.Null{}) })
		if (params['uri'] or { json2.Any('') }).str() != uri {
			continue
		}
		// Hoisted: V's parser cannot take a `for … in` operand whose
		// expression carries a brace-bearing `or {}` block.
		published := lsph_arr(params['diagnostics'] or { json2.Any(json2.Null{}) })
		for d in published {
			out << lsph_obj(d)
		}
	}
	return out
}

// lsph_open_diagnostics runs one bounded didOpen-only session over `text`
// and returns the run plus the diagnostics published against the harness
// document. The `notes.len >= 1` guard is what stops a code-count pin from
// passing vacuously when the push contract itself breaks — the old raw-grep
// form counted 0 and, for a `== 0` expectation, would have called that a
// pass.
fn lsph_open_diagnostics(text string, what string) (LspRun, []map[string]json2.Any) {
	mut msgs := lsph_prelude(lsp_harness_uri, text)
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, what)
	notes := lsph_notifications(run, 'textDocument/publishDiagnostics')
	assert notes.len >= 1, '${what}: didOpen published NO diagnostics notification at all — the push contract is broken, so every code-count pin over it is vacuous: ${run.raw}'
	return run, lsph_diagnostics(run, lsp_harness_uri)
}

// lsph_with_code filters decoded diagnostics on their `code` FIELD — an
// exact match on a decoded value, where the retired helper matched the
// bytes `"code":"CXLS006"` anywhere in the stream.
fn lsph_with_code(diags []map[string]json2.Any, code string) []map[string]json2.Any {
	mut out := []map[string]json2.Any{}
	for d in diags {
		if (d['code'] or { json2.Any('') }).str() == code {
			out << d
		}
	}
	return out
}

// lsph_assert_cxls006_shape pins what the advisory IS, not merely that its
// code appears somewhere: hint severity, the cx-lsp attribution, a message
// that names the remedy, and a placeable 0-based range. None of that was
// reachable through a substring count.
fn lsph_assert_cxls006_shape(d map[string]json2.Any) {
	assert lsph_int(d['severity'] or { json2.Any(i64(0)) }) == 4, 'CXLS006 is an ADVISORY — severity 4 (Hint). Anything louder makes an unbounded range read as an error in the editor: ${d}'
	assert (d['source'] or { json2.Any('') }).str() == 'cx-lsp', 'CXLS006 must be attributed to the cx-lsp analyser, not the parser: ${d}'
	assert (d['message'] or { json2.Any('') }).str().contains('take'), 'the CXLS006 message must name the `[take]` / `[take-while]` remedy — an advisory with no remedy is noise: ${d}'
	rng := lsph_obj(d['range'] or { json2.Any(json2.Null{}) })
	start := lsph_obj(rng['start'] or { json2.Any(json2.Null{}) })
	assert lsph_int(start['line'] or { json2.Any(i64(-1)) }) >= 0, 'CXLS006 needs a placeable 0-based start line: ${d}'
	assert lsph_int(start['character'] or { json2.Any(i64(-1)) }) >= 0, 'CXLS006 needs a placeable 0-based start character: ${d}'
}

// lsph_completion_items drives ONE bounded completion request over `text`
// at line 0 / character 1 — the position the retired probe used — and
// returns the decoded CompletionItem objects. The retired path scanned raw
// stdout for `"insertText":"` / `"label":"` and hand-walked JSON escapes to
// find each closing quote: a JSON parser, re-implemented, over an unframed
// byte stream, with no way to know the items came from the completion
// response at all.
fn lsph_completion_items(text string, what string) []map[string]json2.Any {
	mut msgs := lsph_prelude(lsp_harness_uri, text)
	msgs << lsph_req(20, 'textDocument/completion', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)}},"position":{"line":0,"character":1}}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, what)
	resp := lsph_response(run, 20)
	assert resp.len > 0, '${what}: textDocument/completion (id 20) drew NO response — the editor waits forever (${run.raw.len} bytes of stream)'
	assert 'error' !in resp, '${what}: completion answered with an error: ${resp}'
	result := lsph_obj(resp['result'] or { json2.Any(json2.Null{}) })
	items := lsph_arr(result['items'] or { json2.Any(json2.Null{}) })
	assert items.len > 0, '${what}: the completion response carried no items — every pin over it would pass vacuously: ${resp}'
	mut out := []map[string]json2.Any{}
	for entry in items {
		o := lsph_obj(entry)
		assert o.len > 0, '${what}: a completion item did not decode as an object: ${resp}'
		out << o
	}
	return out
}

// ── L100 — the ONE traversal reaches [yield-map K V] VALUE position ──

// The CXLS006 infinite-range advisory must fire for an unbounded
// comprehension nested in the `[yield-map K V]` VALUE expression. The
// hand-rolled walk this replaces stopped at `f.yield` and never saw
// that node — 0 diagnostics on the pre-migration binary.
fn test_cxls006_reaches_yield_map_value() {
	prog := '[?for-map [in \$x (1, 2)] [yield-map \$x [?for [in \$y [\$range 1 *]] [yield \$y]]]]'
	run, diags := lsph_open_diagnostics(prog, 'CXLS006 yield-map VALUE')
	hits := lsph_with_code(diags, 'CXLS006')
	assert hits.len == 1, 'CXLS006 must fire for the unbounded comprehension in [yield-map K V] VALUE position — the walker is blind to f.yield_value. Got ${hits.len} across ${diags.len} published diagnostics:\n${run.raw}'
	lsph_assert_cxls006_shape(hits[0])
}

// Control: the SAME unbounded comprehension in KEY position (already
// covered pre-migration) still fires exactly once. Guards against the
// migration double-visiting a node.
fn test_cxls006_in_yield_map_key_fires_once() {
	prog := '[?for-map [in \$x (1, 2)] [yield-map [?for [in \$y [\$range 1 *]] [yield \$y]] \$x]]'
	run, diags := lsph_open_diagnostics(prog, 'CXLS006 yield-map KEY')
	hits := lsph_with_code(diags, 'CXLS006')
	assert hits.len == 1, 'CXLS006 must fire exactly once for [yield-map K V] KEY position (no double-visit). Got ${hits.len} across ${diags.len} published diagnostics:\n${run.raw}'
	lsph_assert_cxls006_shape(hits[0])
}

// Both positions unbounded → exactly two advisories, one per node.
fn test_cxls006_key_and_value_both_counted() {
	prog := '[?for-map [in \$x (1, 2)] [yield-map [?for [in \$k [\$range 1 *]] [yield \$k]] [?for [in \$v [\$range 1 *]] [yield \$v]]]]'
	run, diags := lsph_open_diagnostics(prog, 'CXLS006 yield-map KEY+VALUE')
	hits := lsph_with_code(diags, 'CXLS006')
	assert hits.len == 2, 'CXLS006 must fire once per unbounded comprehension across BOTH [yield-map K V] slots. Got ${hits.len} across ${diags.len} published diagnostics:\n${run.raw}'
	// Two DISTINCT nodes, so two distinct ranges — a double-visit of one
	// slot would also produce a count of 2, and the retired substring count
	// could not tell the two apart.
	first := lsph_obj(hits[0]['range'] or { json2.Any(json2.Null{}) })
	second := lsph_obj(hits[1]['range'] or { json2.Any(json2.Null{}) })
	assert first.str() != second.str(), 'both CXLS006 advisories point at the SAME range — that is one node visited twice, not one advisory per slot: ${hits}'
	lsph_assert_cxls006_shape(hits[0])
	lsph_assert_cxls006_shape(hits[1])
}

// ── #711 item 5 — the completion surface must PARSE ─────────────────

// Every directive completion snippet, stripped of its LSP tab-stops,
// must be accepted by the parser. The retired colon-slot snippets
// (`[?let :name value :in body]`, `[?for x in coll :return body]`)
// failed this: the parser raises CXER0100 on them, so accepting the
// completion produced source that could not compile.
fn test_completion_snippets_parse() {
	// #1004: the insertTexts come from the DECODED completion response now.
	// The retired form scanned raw stdout for `"insertText":"` and walked
	// JSON escapes by hand to find the closing quote — which is why the
	// comment below used to have to explain that `\"` is not a terminator.
	// json2 owns that, and an insertText can no longer come from any frame
	// but the one answering request id 20.
	items := lsph_completion_items('[doc]', 'completion snippets')
	mut checked := 0
	for item in items {
		raw := (item['insertText'] or { json2.Any('') }).str()
		if !raw.starts_with('[?') {
			continue
		}
		// Snippet-flavoured items must SAY so, or the editor inserts the
		// tab-stop syntax literally. Unreachable through a substring grep.
		assert lsph_int(item['insertTextFormat'] or { json2.Any(i64(0)) }) == 2, 'an item carrying an insertText snippet must declare insertTextFormat 2 (Snippet), or the editor pastes `\${1:…}` verbatim: ${item}'
		src := snippet_to_source(raw)
		if src == '' {
			continue
		}
		// PER-DIRECTIVE exemption, each with a stated reason. Deliberately
		// NOT a substring filter on placeholder text: the earlier draft
		// skipped anything containing `path.cx`, and that MASKED the live
		// `?include` surface question entirely.
		//
		// `?include` is a PARSE-time directive in DATA documents (code.md
		// §13, vcx/tests/include_test.v). `cx PROGRAM.cx` drives the CODE
		// path, which refuses it — so it cannot be checked through this
		// CLI harness even though it is a real, spec-approved surface.
		if src.starts_with('[?include') {
			checked++
			continue
		}
		checked++
		f := os.join_path(os.temp_dir(), 'cx_lsp_snip_${checked}.cx')
		os.write_file(f, src) or { panic('write ${f}: ${err}') }
		r := os.execute('${cx_bin()} ${f}')
		assert !r.output.contains('CXER0100'), 'completion snippet does not parse — the LSP is advertising uncompilable syntax (#711 item 5).\n  snippet: ${raw}\n  source:  ${src}\n  output:  ${r.output}'
	}
	assert checked >= 6, 'expected >=6 directive snippets in the completion response, saw ${checked} across ${items.len} items'
}

// snippet_to_source strips LSP snippet syntax from a DECODED insertText:
// `${N:placeholder}` → `placeholder`, `$0`/`$N` → '', `\$` → `$` (the
// escaped CX sigil). #1004 removed the leading JSON-unescape pass — json2
// hands back the decoded string value, so re-unescaping it here would
// corrupt any snippet containing a literal backslash.
//
// NO prose-placeholder escape hatch: an earlier draft skipped snippets
// containing `path.cx` / `cx-source` as "not parse-checkable", and that
// filter MASKED the live `[?include "path.cx"]` defect (`?include` is
// not a directive head at all — inclusion is `[?cx include "path.cx"]`).
// Every snippet the server offers must parse, placeholders and all; a
// snippet that cannot is a snippet that should not be offered.
fn snippet_to_source(raw string) string {
	mut s := raw
	// `${N:placeholder}` → `placeholder`
	for {
		open := s.index('\${') or { break }
		close := s.index_after('}', open) or { break }
		inner := s[open + 2..close]
		colon := inner.index(':') or { -1 }
		repl := if colon >= 0 { inner[colon + 1..] } else { '' }
		s = s[..open] + repl + s[close + 1..]
	}
	// Bare `$0` / `$1` … tab-stops (not the escaped `\$` sigil).
	mut out := ''
	mut k := 0
	for k < s.len {
		if s[k] == `\\` && k + 1 < s.len && s[k + 1] == `$` {
			out += '\$'
			k += 2
			continue
		}
		if s[k] == `$` {
			k++
			for k < s.len && s[k] >= `0` && s[k] <= `9` {
				k++
			}
			continue
		}
		out += s[k].ascii_str()
		k++
	}
	return out
}

// The hover tables must not resurrect the retired colon-slot surface.
fn test_for_hover_shows_clause_children_not_colon_slots() {
	// #1004: the NEGATIVE pins below are the reason this one had to move.
	// Over raw stdout, `!out.contains(':return')` was satisfied by the whole
	// byte stream — the initialize result, the published diagnostics, any
	// frame at all — so a hover body that DID advertise `:return` would
	// still have to compete with unrelated frames for the match, and an
	// absent hover response passed the negative pins vacuously. They now
	// bind to the hover MarkupContent value and nothing else, and the
	// response must exist and carry a body before any of them are reached.
	prog := '[?for [in \$x (1, 2)] [yield \$x]]'
	mut msgs := lsph_prelude(lsp_harness_uri, prog)
	msgs << lsph_req(30, 'textDocument/hover', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)}},"position":{"line":0,"character":2}}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, '?for hover')
	resp := lsph_response(run, 30)
	assert resp.len > 0, '?for hover (id 30) drew NO response — the editor waits forever (${run.raw.len} bytes of stream)'
	assert 'error' !in resp, '?for hover answered with an error: ${resp}'
	result := lsph_obj(resp['result'] or { json2.Any(json2.Null{}) })
	contents := lsph_obj(result['contents'] or { json2.Any(json2.Null{}) })
	assert (contents['kind'] or { json2.Any('') }).str() == 'markdown', 'hover contents must be a MarkupContent the editor can render: ${resp}'
	out := (contents['value'] or { json2.Any('') }).str()
	assert out.len > 0, 'hovering `?for` must return documentation, not an empty body — every negative pin below would otherwise pass vacuously: ${resp}'
	assert out.contains('[in '), '?for hover must document the clause-child surface `[in \$x SRC]`:\n${out}'
	assert !out.contains(':return'), '?for hover still advertises the retired `:return` colon slot (#711 item 5):\n${out}'
	assert !out.contains('tumbling'), '?for hover still advertises windows — retired by L98 (#711 item 6):\n${out}'
	assert !out.contains('on-error'), '?for hover still advertises the retired `[on-error]` clause — the parser refuses it with the §9.3 guidance (#711 items 4/5):\n${out}'
	assert !out.contains('[stream]'), '?for hover still advertises the retired `[stream]` spelling — renamed [lazy] by U1.1a (#763):\n${out}'
	assert out.contains('[lazy]'), '?for hover must document the [lazy] evaluation hint (U1.1a, #763):\n${out}'
}

// ── #711 item 6 / L98 + #760 / RULED 760-1a — retired head reservations ──

// A head whose `[59a]` reservation has been RETIRED must be refused exactly
// the way any unreserved `[?name …]` head is. That is the whole safety
// argument for retiring one: the reservation bought no loudness, because a
// reserved-but-undispatched head and an unknown head raise the identical
// CXER0100. What must NOT happen is a silent downgrade to a processing
// instruction, which would turn a refused program into quiet data.
//
//   L98  — `for-tumbling` / `for-sliding`, the A13/A14 FLWOR window heads.
//   760-1a — `with` / `use` / `cond` / `try`, which parsed as EvalDirectives
//            and were then refused by the §4.1 registry. `try` is
//            additionally a deliberately-retired surface (`make
//            check-no-legacy-try`).
//
// `include` and `def` are deliberately NOT here: both dispatch.
fn test_retired_head_reservations_refused_like_any_unknown_directive() {
	baseline := run_src('[?nosuchdirective a b]')
	assert baseline.contains('CXER0100'), 'expected an unknown-directive CXER0100 baseline, got: ${baseline}'
	for head in ['for-tumbling', 'for-sliding'] {
		out := run_src('[?${head} w [in \$x (1, 2)] [yield \$x]]')
		assert out.contains('CXER0100'), '[?${head}] must be refused LOUDLY after the L98 reservation retirement (never fall through to a PI): ${out}'
		assert out.contains('unknown directive'), '[?${head}] must be refused with the unknown-directive message, matching every other unreserved head: ${out}'
	}
	for head in ['with', 'use', 'cond', 'try'] {
		out := run_src('[?${head} a b]')
		assert out.contains('CXER0100'), '[?${head}] must be refused LOUDLY after the 760-1a reservation retirement (never fall through to a PI): ${out}'
		assert out.contains('unknown directive'), '[?${head}] must be refused with the unknown-directive message, matching every other unreserved head: ${out}'
	}
}

fn run_src(src string) string {
	f := os.join_path(os.temp_dir(), 'cx_l98_probe.cx')
	os.write_file(f, src) or { panic('write ${f}: ${err}') }
	return os.execute('${cx_bin()} ${f}').output
}

// ── source: vcx/tests/lsp_parser_parity_test.v ──
// LSP diagnostic / parser parity.
//
// One cxparse ENGINE, two reading MODES. A `.cx` resource is well-formed if it
// parses under EITHER:
//   • the DATA reading   (cx.parse)         — scannerless; prose, `[- … ]`
//     comments, mixed-content markup (a tour / doc);
//   • the PROGRAM reading (cx.parse_program) — tokenised; `[$call]`, directives,
//     operator heads, program map literals.
// These are modes of the SAME engine, NOT two separate parsers. The LSP
// (vcx/cmd/lsp.v `publish_diagnostics`) therefore raises a syntax diagnostic
// only when BOTH readings fail — exactly the rule this test pins.
//
// Regression history:
//   • Operator heads `[> a b]` / program maps `{k: v k: v}` were flagged as
//     false errors when nvim ran a stale pre-unification binary (its program
//     parser rejected them). Fixed by pointing the editor at the trunk build.
//   • Collapsing the LSP to program-ONLY then wrongly flagged valid DATA
//     documents — a `;` or em-dash in prose / a `[- … ]` comment is fine under
//     the data reading but is not a program token. Hence: accept-under-EITHER.

// Valid under the PROGRAM reading (data reading may reject — that's fine).
const valid_programs = [
	'[> 1 0]',
	'[?if [> [$count 3] 0] [then "yes"] [else "no"]]',
	'{a: 1, b: 2}',
	'{a: 1 b: 2}',
	'{observe: "errors" intents: ([do :add-stock [sym "AAPL"]])}',
	'[?for [in $g $s//group] [where [= $g@name "n"]] [yield $g]]',
	'[?lib \'./x.cx\' as=wl]',
	'[card total=[$count $items]]',
]

// Valid under the DATA reading (program reading rejects the prose/markup —
// `;`, em-dash bytes, mixed content — and that MUST NOT produce a diagnostic).
const valid_data_docs = [
	'[- a block comment with ; and , punctuation ]',
	'[doc [li bare prose with a ; semicolon]]',
	'[doc [p plain mixed content [strong bold] tail]]',
	'[server host=localhost [port::u16 8080]]',
	'[tags::string[] admin user]',
	'[- top comment ]\n[a 1]',
]

// Fails under BOTH readings → a genuine syntax error the LSP SHOULD flag.
const broken_both = [
	'[?if [> 1 0]',   // unterminated
	'[a 1',           // unterminated element
	'{a: 1,,b: 2}',   // empty map slot (rejected by program reading; data too)
]

fn parses_either(src string) bool {
	if _ := cx.parse(src) { return true }
	if _ := cx.parse_program(src) { return true }
	return false
}

fn test_valid_programs_accepted() {
	for src in valid_programs {
		assert parses_either(src), 'LSP would FALSE-flag a valid program: |${src}|'
		// specifically the program reading accepts it
		if _ := cx.parse_program(src) {} else {
			assert false, 'program reading rejected a valid program: |${src}|'
		}
	}
}

fn test_valid_data_docs_accepted() {
	for src in valid_data_docs {
		assert parses_either(src), 'LSP would FALSE-flag a valid data document: |${src}|'
		// specifically the data reading accepts it
		if _ := cx.parse(src) {} else {
			assert false, 'data reading rejected a valid data document: |${src}|'
		}
	}
}

fn test_broken_flagged() {
	for src in broken_both {
		assert !parses_either(src), 'expected BOTH readings to reject (LSP should flag): |${src}|'
	}
}

// ── source: vcx/tests/lsp_semantic_comment_test.v ──

// lsp_semantic_comment_test.v — regression guard for `[; … ]` block-comment
// dimming (cx-private). The LSP semantic-token tokenizer must emit COMMENT
// tokens for the whole `[; … ]` span, not descend into it and emit code tokens
// (atoms / types / directives / bindings). Those code tokens override the
// editor's tmLanguage (VS Code) and tree-sitter (Neovim) comment highlighting —
// which are themselves correct — so the comment interior showed UN-dimmed (the
// repeatedly-reported bug). This drives the real `cx lsp` over JSON-RPC and
// asserts the semantic-token TYPE ids.
//
// tt_comment is index 7 in the semanticTokens legend (vcx/cmd/lsp_content.v).
const tt_comment = 7

// semantic_token_types drives `cx lsp` on `program` and returns the flat list of
// semantic-token TYPE ids (one per token).
//
// #1004: migrated off the retired `lsp_session` family onto `lsph_run`. It
// was the same defect class — an unbounded `os.execute`, and a raw-stdout
// grep for the marker `"data":[` up to the first `]`, which is not JSON
// parsing: it assumed the semanticTokens response is the ONLY frame in the
// stream carrying a `data` key, and it took whatever integers happened to
// precede the next `]` byte. The array is now read out of the decoded
// `result.data` of the response to id 40, and a session that fails to
// terminate is a bounded test failure rather than a hung gate lane.
fn semantic_token_types(program string) []int {
	mut msgs := lsph_prelude(lsp_harness_uri, program)
	msgs << lsph_req(40, 'textDocument/semanticTokens/full', lsph_doc_params(lsp_harness_uri))
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'semantic tokens')
	resp := lsph_response(run, 40)
	assert resp.len > 0, 'semanticTokens/full (id 40) drew NO response — the editor waits forever (${run.raw.len} bytes of stream)'
	assert 'error' !in resp, 'semanticTokens/full answered with an error: ${resp}'
	result := lsph_obj(resp['result'] or { json2.Any(json2.Null{}) })
	data := lsph_arr(result['data'] or { json2.Any(json2.Null{}) })
	// Each token is 5 ints: [deltaLine, deltaStart, length, TYPE, modifiers].
	assert data.len % 5 == 0, 'the semanticTokens data array is 5 ints per token — a length of ${data.len} means the encoding drifted and every TYPE below is read from the wrong slot: ${resp}'
	mut types := []int{}
	mut k := 3
	for k < data.len {
		types << lsph_int(data[k])
		k += 5
	}
	return types
}

// A `[; … ]` comment — multi-line, with a nested bracket, an atom, a binding,
// and a directive head — each of which WOULD get a code token if the tokenizer
// descended into the comment. The whole span must be comment.
fn test_block_comment_interior_is_all_comment() {
	prog := '[; header [tbl col:int]\n   :atom \$bind and ?key here ]'
	types := semantic_token_types(prog)
	assert types.len > 0, 'expected >=1 semantic token for the [; … ] comment (got none)'
	for t in types {
		assert t == tt_comment, 'a token inside [; … ] is type ${t}, not comment (${tt_comment}) — interior leaked as code: ${types}'
	}
}

// Guard against over-dimming: real code around a `[; … ]` comment must keep its
// (non-comment) tokens; only the comment dims.
fn test_code_around_block_comment_keeps_code_tokens() {
	prog := '[greet name=x]\n[; just :atom \$b ]\n[other]'
	types := semantic_token_types(prog)
	assert tt_comment in types, 'expected the [; … ] line to emit a comment token: ${types}'
	mut has_code := false
	for t in types {
		if t != tt_comment {
			has_code = true
		}
	}
	assert has_code, 'expected code tokens for the [greet]/[other] lines — over-dimmed: ${types}'
}

// ── CX-L008 — declared [?pipe] stage flow (I5-s16 W5, Layer B at the ──
// lint dial): warn default, --fail-on escalation; the runtime refusal
// is --strict's job.

const l8_bad = "[?def to-text [returns string] (\$x::int) 'n']\n[?def shout [returns string] (\$s::string) \$s]\n[?pipe 3 to-text shout to-text]\n"

const l8_ok = "[?def to-text [returns string] (\$x::int) 'n']\n[?def double [returns int] (\$x::int) [* \$x 2]]\n[?pipe 3 double to-text]\n"

fn l8_run(src string, flags string) (string, int) {
	f := os.join_path(os.temp_dir(), 'cx_l008_${os.getpid()}_${src.len}.cx')
	os.write_file(f, src) or { panic('write: ${err}') }
	defer { os.rm(f) or {} }
	r := os.execute('${l7_bin()} lint ${flags} ${f}')
	return r.output, r.exit_code
}

fn test_l008_fires_on_declared_stage_mismatch() {
	out, rc := l8_run(l8_bad, '')
	assert out.contains('CX-L008'), out
	assert out.contains('shout') && out.contains('to-text'), 'must name both stages: ${out}'
	assert rc == 0, 'warn severity — default run exits 0'
}

fn test_l008_fail_on_warn_escalates() {
	_, rc := l8_run(l8_bad, '--fail-on=warn')
	assert rc == 1
}

fn test_l008_silent_on_composing_and_undeclared_boundaries() {
	out, _ := l8_run(l8_ok, '')
	assert !out.contains('CX-L008'), out
	// An undeclared boundary (no [returns]) is silent — declarations
	// are the contract, absence is not a finding.
	out2, _ := l8_run("[?def f (\$x) \$x]\n[?def g [returns int] (\$s::string) 1]\n[?pipe 3 f g]\n", '')
	assert !out2.contains('CX-L008'), out2
}

fn test_l008_disable_honored() {
	out, _ := l8_run(l8_bad, '--disable CX-L008')
	assert !out.contains('CX-L008'), out
}

// ── #705 — the LSP directive surface is the REGISTRY, exactly ─────────
//
// POST-APPLY umbrella addition — not in
// scripts/consolidation/lint_lsp.files; reconcile it into the manifest
// inputs before any future regeneration.
//
// The hand-kept completion list had drifted into a different language:
// four advertised heads did not exist at either layer (`?xpath`,
// `?xquery`, `?cxpath` were pure LSP invention; `?include` is a
// DATA-document assembly directive, not an eval-time head), and the
// snippets documented an abolished slot syntax. governance.md §10.2
// requires an LSP update on every grammar change — nothing enforced it.
//
// The set is now DERIVED from cx.directive_names, and this gate proves it
// over the SHIPPED binary rather than the source: a completion response
// is parsed and its directive labels compared to the registry in both
// directions. Advertising a head no parser knows is the same defect class
// the shell-completion drift gate exists to prevent.
fn test_lsp_directive_surface_equals_the_registry() {
	// #1004: `offered` is now built from the `label` FIELD of each decoded
	// CompletionItem in the response to id 20. The retired form grepped
	// `"label":"` across the whole raw stream, which would have swept in a
	// `label` nested anywhere else the server ever emits one — and, being a
	// both-directions set comparison, an over-collected label reads as a
	// phantom directive and an under-collected one as a missing directive.
	items := lsph_completion_items('[doc]', 'directive surface')
	mut offered := map[string]bool{}
	for item in items {
		label := (item['label'] or { json2.Any('') }).str()
		if label.starts_with('?') {
			offered[label] = true
		}
	}
	assert offered.len > 0, 'the completion response advertised no directives — the gate has nothing to enforce'

	mut registry := map[string]bool{}
	for n in cx.directive_names {
		registry['?' + n] = true
	}

	mut phantom := []string{}
	for label, _ in offered {
		if label !in registry {
			phantom << label
		}
	}
	assert phantom.len == 0, 'the LSP advertises directives that are NOT in cx.directive_names — ' +
		'a head no parser knows (#705): ${phantom.join(', ')}'

	mut missing := []string{}
	for name, _ in registry {
		if name !in offered {
			missing << name
		}
	}
	assert missing.len == 0, 'these registry directives are missing from the LSP completion set — ' +
		'the surface lags the grammar, which governance.md §10.2 forbids (#705): ${missing.join(', ')}'
}

// ── source: vcx/tests/lsp_harness_test.v ──
// lsp_harness_test.v — the REQUEST-LEVEL LSP harness (#996).
//
// Until this file there was no test that spoke the protocol. Every LSP
// behaviour was reasoned-not-pinned: the handlers were unit-reachable, the
// WIRE was not. #980 measured what that costs — `textDocument/formatting`
// built its whole-document TextEdit from `fmt_source`, whose contract is
// UNTERMINATED text, and never re-supplied the terminator, so every `:w`
// through the LSP silently stripped the file's trailing newline. Nothing
// could see it: the defect lives between two components that were each
// individually correct. The same lineage produced the v0.12 `:w` crash —
// `textDocument/didSave` is a NOTIFICATION, the dispatcher classified it as
// a request on a zero-value `id`, and the bogus `id:[]` error reply tripped
// Neovim's `assert(tonumber(decoded.id))`. Both are wire-level faults, and
// only a wire-level harness reaches them.
//
// What this harness is: `cx lsp` spawned as a real subprocess, driven with
// real `Content-Length`-framed JSON-RPC 2.0 over stdio, its response stream
// parsed back out of the wire bytes. No handler is called directly; nothing
// is stubbed.
//
// TWO DELIBERATE CONSTRUCTION CHOICES, both about not hanging:
//
//   1. stdio is redirected to FILES, never pipes. The server reads a whole
//      request stream and writes a response stream that is unbounded in
//      principle (the completion response alone carries ~800 stdlib entries),
//      so a pipe pair deadlocks on the 64 KiB kernel buffer — the harness
//      blocked in `stdin_write` while the server blocks in `write` — before
//      any timeout could fire. Files have no such coupling, and they leave
//      the raw wire bytes on disk for the failure message.
//   2. EVERY session is wall-clock BOUNDED and killed by PROCESS GROUP
//      (#973's lesson, and #956's before it): a regression in a server that
//      reads until EOF is precisely a hang, and an unbounded probe would take
//      the whole gate down instead of reporting a failure. `lsph_run` polls
//      `is_alive` against a deadline and `signal_pgkill`s past it; a killed
//      session is a hard test failure, never a silent pass.
//
// The session is batched — the full request stream is written up front and
// the response stream read back after exit — which is sound here because the
// protocol's request ids make responses self-identifying and none of the pins
// below need request N to depend on response N-1. Termination is the `exit`
// notification (run_lsp breaks the loop), with EOF as the backstop.

const lsp_probe_budget_ms = i64(30000)

const lsp_harness_uri = 'file:///tmp/cx-lsp-harness/doc.cx'

// ── Wire plumbing ────────────────────────────────────────────────────

struct LspRun {
mut:
	frames  []json2.Any // every message the server wrote, in order
	raw     string      // the response stream verbatim, for failure messages
	stderr  string
	code    int
	killed  bool
	elapsed i64
}

// lsph_frame wraps a JSON body in LSP's `Content-Length` header framing.
// The length is the BODY BYTE count — the same quantity the server writes —
// so a framing regression on either side shows up as a decode failure here.
fn lsph_frame(body string) string {
	return 'Content-Length: ${body.len}\r\n\r\n${body}'
}

// lsph_jstr renders s as a JSON string literal (quotes + escaping), so
// document text with newlines and quotes crosses the wire intact.
fn lsph_jstr(s string) string {
	return json2.Any(s).json_str()
}

fn lsph_open(uri string, text string) string {
	return '{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":${lsph_jstr(uri)},"languageId":"cx","version":1,"text":${lsph_jstr(text)}}}}'
}

fn lsph_req(id int, method string, params string) string {
	return '{"jsonrpc":"2.0","id":${id},"method":${lsph_jstr(method)},"params":${params}}'
}

fn lsph_note(method string, params string) string {
	return '{"jsonrpc":"2.0","method":${lsph_jstr(method)},"params":${params}}'
}

fn lsph_doc_params(uri string) string {
	return '{"textDocument":{"uri":${lsph_jstr(uri)}}}'
}

// lsph_run drives one whole `cx lsp` session and returns everything the
// server put on the wire. Bounded; a session that outlives the budget is
// pgkilled and reported as killed, which every caller asserts against.
fn lsph_run(msgs []string, budget_ms i64) LspRun {
	bin := testenv.cx_bin()
	dir := os.join_path(os.temp_dir(), 'cx_lsp_harness_${os.getpid()}_${vtime.ticks()}')
	os.mkdir_all(dir) or { panic('lsp harness: mkdir: ${err}') }
	in_f := os.join_path(dir, 'in.bin')
	out_f := os.join_path(dir, 'out.bin')
	err_f := os.join_path(dir, 'err.log')
	mut payload := ''
	for m in msgs {
		payload += lsph_frame(m)
	}
	os.write_file(in_f, payload) or { panic('lsp harness: write ${in_f}: ${err}') }
	mut p := os.new_process('/bin/sh')
	p.set_args(['-c', "exec '${bin}' lsp < '${in_f}' > '${out_f}' 2> '${err_f}'"])
	p.use_pgroup = true
	t0 := vtime.ticks()
	p.run()
	mut killed := false
	for p.is_alive() {
		if vtime.ticks() - t0 > budget_ms {
			p.signal_pgkill()
			killed = true
			break
		}
		vtime.sleep(5 * vtime.millisecond)
	}
	p.wait()
	elapsed := vtime.ticks() - t0
	raw := os.read_file(out_f) or { '' }
	serr := os.read_file(err_f) or { '' }
	code := p.code
	os.rmdir_all(dir) or {}
	return LspRun{
		frames: lsph_split(raw)
		raw: raw
		stderr: serr
		code: code
		killed: killed
		elapsed: elapsed
	}
}

// lsph_split un-frames the response stream the same way an editor would:
// header up to `\r\n\r\n`, then exactly Content-Length bytes of body. A
// truncated or mis-counted final frame simply stops the scan — and the
// caller's frame-count assertion is what turns that into a failure.
fn lsph_split(raw string) []json2.Any {
	mut out := []json2.Any{}
	mut i := 0
	for i < raw.len {
		hdr_end := raw.index_after('\r\n\r\n', i) or { break }
		mut n := 0
		for hl in raw[i..hdr_end].split('\n') {
			l := hl.trim_space()
			if l.to_lower().starts_with('content-length:') {
				n = l.all_after(':').trim_space().int()
			}
		}
		body_start := hdr_end + 4
		if n <= 0 || body_start + n > raw.len {
			break
		}
		body := raw[body_start..body_start + n]
		out << json2.decode[json2.Any](body) or { json2.Any(json2.Null{}) }
		i = body_start + n
	}
	return out
}

fn lsph_obj(v json2.Any) map[string]json2.Any {
	if v is map[string]json2.Any {
		return v
	}
	return map[string]json2.Any{}
}

fn lsph_arr(v json2.Any) []json2.Any {
	if v is []json2.Any {
		return v
	}
	return []json2.Any{}
}

fn lsph_int(v json2.Any) int {
	if v is i64 {
		return int(v)
	}
	if v is f64 {
		return int(v)
	}
	if v is f32 {
		return int(v)
	}
	return 0
}

// lsph_response returns the response frame carrying `id`, or an empty map.
// A frame with a `method` key is a server-initiated notification, never a
// response, so it can never be mistaken for one.
fn lsph_response(run LspRun, id int) map[string]json2.Any {
	for f in run.frames {
		o := lsph_obj(f)
		if 'method' in o {
			continue
		}
		idv := o['id'] or { continue }
		if lsph_int(idv) == id {
			return o
		}
	}
	return map[string]json2.Any{}
}

fn lsph_notifications(run LspRun, method string) []map[string]json2.Any {
	mut out := []map[string]json2.Any{}
	for f in run.frames {
		o := lsph_obj(f)
		m := o['method'] or { continue }
		if m.str() == method {
			out << o
		}
	}
	return out
}

// lsph_prelude is the handshake every session opens with: initialize (id 1),
// the `initialized` notification, then didOpen for the document under test.
fn lsph_prelude(uri string, text string) []string {
	return [
		lsph_req(1, 'initialize', '{"processId":null,"rootUri":null,"capabilities":{}}'),
		lsph_note('initialized', '{}'),
		lsph_open(uri, text),
	]
}

fn lsph_epilogue() []string {
	return [
		lsph_req(99, 'shutdown', '{}'),
		'{"jsonrpc":"2.0","method":"exit"}',
	]
}

// lsph_healthy asserts the invariants that hold of EVERY session regardless
// of what it asked for: it terminated inside its bound, the handshake and
// shutdown both answered, and nothing in the response stream failed to decode.
fn lsph_healthy(run LspRun, what string) {
	assert !run.killed, '${what}: session exceeded ${lsp_probe_budget_ms}ms bound — the server did not terminate on `exit`/EOF (raw ${run.raw.len} bytes, stderr: ${run.stderr})'
	assert run.code == 0, '${what}: cx lsp exited ${run.code} — a clean session must exit 0 (stderr: ${run.stderr})'
	init := lsph_response(run, 1)
	assert init.len > 0, '${what}: no response to initialize (id 1); raw: ${run.raw}'
	down := lsph_response(run, 99)
	assert down.len > 0, '${what}: no response to shutdown (id 99) — the server stopped answering mid-session; raw: ${run.raw}'
	for f in run.frames {
		o := lsph_obj(f)
		assert o.len > 0, '${what}: a response frame did not decode as a JSON object; raw: ${run.raw}'
		jr := o['jsonrpc'] or { json2.Any('') }
		assert jr.str() == '2.0', '${what}: frame is not JSON-RPC 2.0: ${o}'
	}
}

// ── Pin (a): textDocument/formatting round-trip ──────────────────────
//
// #980's exact class. The formatting response is a SINGLE whole-document
// TextEdit; what the buffer becomes after the edit is `newText`, because the
// edit's range spans line 0 through the phantom line AFTER the file's final
// newline. So `newText` IS the saved file, byte for byte, and every property
// of the saved file is assertable here.

const lsp_unformatted_doc = '[order  [id  "1"]\n   [qty 2]]\n'

// lsph_format_edit drives one format request over `text` and returns the
// single TextEdit's newText plus the edit's end line.
fn lsph_format_edit(text string, what string) (string, int) {
	mut msgs := lsph_prelude(lsp_harness_uri, text)
	msgs << lsph_req(10, 'textDocument/formatting', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)},"options":{"tabSize":2,"insertSpaces":true}}}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, what)
	resp := lsph_response(run, 10)
	assert 'error' !in resp, '${what}: formatting returned an error: ${resp}'
	edits := lsph_arr(resp['result'] or { json2.Any(json2.Null{}) })
	assert edits.len == 1, '${what}: expected exactly one whole-document TextEdit, got ${edits.len}: ${resp}'
	edit := lsph_obj(edits[0])
	new_text := (edit['newText'] or { json2.Any('') }).str()
	rng := lsph_obj(edit['range'] or { json2.Any(json2.Null{}) })
	start := lsph_obj(rng['start'] or { json2.Any(json2.Null{}) })
	end_pos := lsph_obj(rng['end'] or { json2.Any(json2.Null{}) })
	assert lsph_int(start['line'] or { json2.Any(i64(-1)) }) == 0, '${what}: whole-document edit must start at line 0: ${edit}'
	assert lsph_int(start['character'] or { json2.Any(i64(-1)) }) == 0, '${what}: whole-document edit must start at character 0: ${edit}'
	assert lsph_int(end_pos['character'] or { json2.Any(i64(-1)) }) == 0, '${what}: whole-document edit must end at character 0 of the end line: ${edit}'
	return new_text, lsph_int(end_pos['line'] or { json2.Any(i64(-1)) })
}

fn test_lsp_formatting_preserves_the_file_terminator() {
	// #980, ON THE WIRE. `fmt_source` returns UNTERMINATED text as a total
	// contract; this edit is one of its two callers and must re-supply the
	// newline. Before the fix the saved file lost its trailing newline on
	// every single `:w` — silently, because the edit still "succeeded".
	new_text, end_line := lsph_format_edit(lsp_unformatted_doc, 'terminator')
	assert new_text.ends_with('\n'), 'the formatting edit must terminate the file — a `:w` through the LSP wrote it back UNTERMINATED (#980). newText: ${new_text.bytes()}'
	assert !new_text.ends_with('\n\n'), 'the formatting edit must supply EXACTLY one terminator — a doubled newline grows the file one line per save. newText: ${new_text.bytes()}'

	// The edit's range must cover the phantom line past the final newline,
	// or the old terminator survives ALONGSIDE the new one and the file
	// grows anyway. `lines` is source.split('\n').len — for terminated
	// source that is one past the last content line, i.e. the phantom line.
	assert end_line == lsp_unformatted_doc.split('\n').len, 'the edit must span through the line after the final newline so it OWNS the terminator, got end line ${end_line} for a ${lsp_unformatted_doc.split('\n').len}-line span'

	// The formatting actually happened (this input is not already canonical),
	// so the pin cannot be satisfied by echoing the source back.
	assert new_text != lsp_unformatted_doc, 'the probe document must actually reformat, else the terminator pin is vacuous'
	assert new_text.contains('[order'), 'the formatted result must still be the document: ${new_text}'
}

fn test_lsp_formatting_is_idempotent_over_the_wire() {
	// formatting.md §7: fmt(fmt(x)) == fmt(x). Pinned END-TO-END, not at the
	// `fmt_source` boundary — the LSP adds a terminator on top, and it is
	// exactly that composed function which runs on every save. #980's
	// unbounded growth (57 → 58 → 59 lines) was a failure of the COMPOSED
	// function while each half looked defensible.
	once, _ := lsph_format_edit(lsp_unformatted_doc, 'idempotent/1')
	twice, _ := lsph_format_edit(once, 'idempotent/2')
	assert twice == once, 'formatting is not idempotent over the wire: save #2 changed the file again.\n once:  ${once.bytes()}\n twice: ${twice.bytes()}'
	thrice, _ := lsph_format_edit(twice, 'idempotent/3')
	assert thrice == once, 'formatting oscillates or drifts by the third save.\n once:   ${once.bytes()}\n thrice: ${thrice.bytes()}'
}

// lsph_cx_fmt runs `cx fmt <file>` over `text` and returns its stdout
// VERBATIM — stdout captured to a file, so no layer between the CLI and this
// assertion can normalise a terminator out of existence. Bounded like every
// other probe here.
fn lsph_cx_fmt(text string) string {
	bin := testenv.cx_bin()
	dir := os.join_path(os.temp_dir(), 'cx_lsp_fmt_${os.getpid()}_${vtime.ticks()}')
	os.mkdir_all(dir) or { panic('lsp harness: mkdir: ${err}') }
	src_f := os.join_path(dir, 'doc.cx')
	out_f := os.join_path(dir, 'out.cx')
	os.write_file(src_f, text) or { panic('lsp harness: write ${src_f}: ${err}') }
	mut p := os.new_process('/bin/sh')
	p.set_args(['-c', "exec '${bin}' fmt '${src_f}' > '${out_f}' 2>/dev/null"])
	p.use_pgroup = true
	t0 := vtime.ticks()
	p.run()
	mut killed := false
	for p.is_alive() {
		if vtime.ticks() - t0 > lsp_probe_budget_ms {
			p.signal_pgkill()
			killed = true
			break
		}
		vtime.sleep(5 * vtime.millisecond)
	}
	p.wait()
	code := p.code
	out := os.read_file(out_f) or { '' }
	os.rmdir_all(dir) or {}
	assert !killed, 'cx fmt exceeded ${lsp_probe_budget_ms}ms'
	assert code == 0, 'cx fmt exited ${code}'
	return out
}

fn test_lsp_formatting_is_byte_faithful_on_an_already_formatted_file() {
	// The strongest form of the pin, and the one that makes #980 unrepeatable:
	// the already-formatted file is produced by `cx fmt` — fmt_source's OTHER
	// caller — and the LSP save must reproduce it BYTE FOR BYTE.
	//
	// Seeding this from the LSP's own previous answer would be self-consistent
	// under exactly the defect being pinned: the strip is deterministic, so an
	// unterminated result formats to itself and a same-caller no-op check stays
	// green through the whole regression (measured — it did). #980 was a
	// DISAGREEMENT between fmt_source's two callers, so the pin has to hold
	// them against each other.
	canonical := lsph_cx_fmt(lsp_unformatted_doc)
	assert canonical.ends_with('\n'), '`cx fmt` itself must emit a terminated file: ${canonical.bytes()}'
	again, _ := lsph_format_edit(canonical, 'noop')
	assert again == canonical, 'a `:w` through the LSP does not agree byte-for-byte with `cx fmt` on an already-formatted file — this is #980 exactly.\n cx fmt: ${canonical.bytes()}\n lsp:    ${again.bytes()}'
	assert again.len == canonical.len, 'byte length changed on a no-op save: ${canonical.len} → ${again.len}'

	// And on the unformatted source the two callers must also agree — the LSP
	// edit IS the saved file, so any divergence is a file the two entry points
	// write differently.
	lsp_first, _ := lsph_format_edit(lsp_unformatted_doc, 'noop/first')
	assert lsp_first == canonical, '`cx fmt` and the LSP whole-document edit produce different files from the same source.\n cx fmt: ${canonical.bytes()}\n lsp:    ${lsp_first.bytes()}'
}

fn test_lsp_formatting_leaves_an_unparseable_buffer_untouched() {
	// Fail-closed: a parse error yields ZERO edits, never a partial rewrite.
	// The buffer belongs to the user; a formatter that cannot read it has
	// nothing to say about it.
	mut msgs := lsph_prelude(lsp_harness_uri, '[order [id "1"]\n')
	msgs << lsph_req(10, 'textDocument/formatting', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)},"options":{"tabSize":2,"insertSpaces":true}}}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'fail-closed')
	resp := lsph_response(run, 10)
	edits := lsph_arr(resp['result'] or { json2.Any(json2.Null{}) })
	assert edits.len == 0, 'formatting an unparseable buffer must yield zero edits, got ${edits.len}: ${resp}'
}

fn test_lsp_formatting_on_an_unopened_document_is_zero_edits() {
	// A format request naming a uri the server never saw must answer with
	// zero edits — not hang, not error, not fabricate a buffer.
	mut msgs := [
		lsph_req(1, 'initialize', '{"processId":null,"rootUri":null,"capabilities":{}}'),
		lsph_note('initialized', '{}'),
	]
	msgs << lsph_req(10, 'textDocument/formatting', '{"textDocument":{"uri":"file:///tmp/cx-lsp-harness/never-opened.cx","options":{}}}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'unopened')
	resp := lsph_response(run, 10)
	assert resp.len > 0, 'an unopened-document format must still answer: ${run.raw}'
	assert lsph_arr(resp['result'] or { json2.Any(json2.Null{}) }).len == 0, 'unopened document must format to zero edits: ${resp}'
}

// ── Pin (b): didSave on a broken file — the v0.12 `:w` crash class ───

const lsp_broken_doc = '[order [id "1"]\n [qty 2]\n'

fn test_lsp_did_save_on_a_syntax_error_does_not_break_the_server() {
	// The v0.12 lineage: `:w` fires textDocument/didSave, a NOTIFICATION.
	// The dispatcher tested `msg.id is json2.Null` — but an absent id leaves
	// json2.Any's zero value, which is an empty ARRAY, so every notification
	// read as a request and drew an error reply carrying `id:[]`. Neovim's
	// `assert(tonumber(decoded.id), 'response id must be a number')` then
	// killed the client on the user's first save. Two independent pins here:
	// the notifications draw NO reply at all, and the server keeps serving
	// afterwards.
	mut msgs := lsph_prelude(lsp_harness_uri, lsp_broken_doc)
	msgs << lsph_note('textDocument/didSave', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)}},"text":${lsph_jstr(lsp_broken_doc)}}')
	msgs << lsph_note('textDocument/didChange', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)},"version":2},"contentChanges":[{"text":${lsph_jstr(lsp_broken_doc)}}]}')
	msgs << lsph_note('textDocument/didSave', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)}}}')
	// …and the server must still be answering requests after all of it.
	msgs << lsph_req(20, 'textDocument/documentSymbol', lsph_doc_params(lsp_harness_uri))
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'didSave/broken')

	// (1) No frame may carry a non-numeric id. This is the crash byte-for-byte:
	//     the id the editor asserts on.
	for f in run.frames {
		o := lsph_obj(f)
		if 'method' in o {
			continue // server notification — carries no id by construction
		}
		idv := o['id'] or {
			assert false, 'a response frame carried no id at all: ${o}'
			continue
		}
		is_numeric := idv is i64 || idv is f64 || idv is f32
		assert is_numeric, 'a response carried a NON-NUMERIC id — this is the v0.12 `:w` crash verbatim (Neovim: `assert(tonumber(decoded.id))`): ${o}'
		id := lsph_int(idv)
		assert id in [1, 20, 99], 'a response answered an id the client never sent (${id}): ${o}'
	}

	// (2) Nothing in the session drew a JSON-RPC error. Notifications in
	//     particular must fall through to their no-op arms, never to the
	//     dispatcher's `method not found`.
	for f in run.frames {
		o := lsph_obj(f)
		assert 'error' !in o, 'a notification-only exchange produced an error reply: ${o}'
	}

	// (3) Exactly as many responses as requests — three requests, three
	//     responses, no phantom fourth from a misclassified notification.
	mut responses := 0
	for f in run.frames {
		o := lsph_obj(f)
		if 'method' !in o {
			responses++
		}
	}
	assert responses == 3, 'sent 3 requests amid 3 notifications; got ${responses} responses — a notification was answered as a request: ${run.raw}'
}

fn test_lsp_publishes_a_diagnostic_for_a_syntax_error() {
	// didOpen on a broken file must PUSH a diagnostic, and it must point at
	// the fault rather than defaulting to 0:0.
	mut msgs := lsph_prelude(lsp_harness_uri, lsp_broken_doc)
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'diagnostics')
	notes := lsph_notifications(run, 'textDocument/publishDiagnostics')
	assert notes.len >= 1, 'didOpen on a broken file published no diagnostics: ${run.raw}'
	params := lsph_obj(notes[0]['params'] or { json2.Any(json2.Null{}) })
	assert (params['uri'] or { json2.Any('') }).str() == lsp_harness_uri, 'diagnostics were published against the wrong uri: ${params}'
	diags := lsph_arr(params['diagnostics'] or { json2.Any(json2.Null{}) })
	assert diags.len >= 1, 'a file that parses under NEITHER reading must produce a diagnostic: ${params}'
	mut saw_parse_error := false
	for d in diags {
		o := lsph_obj(d)
		if (o['source'] or { json2.Any('') }).str() == 'cx-parse' {
			saw_parse_error = true
			assert lsph_int(o['severity'] or { json2.Any(i64(0)) }) == 1, 'a syntax error is severity 1 (Error): ${o}'
			assert (o['message'] or { json2.Any('') }).str().len > 0, 'a diagnostic must carry a message: ${o}'
			rng := lsph_obj(o['range'] or { json2.Any(json2.Null{}) })
			start := lsph_obj(rng['start'] or { json2.Any(json2.Null{}) })
			assert 'line' in start && 'character' in start, 'a diagnostic range needs a start position: ${o}'
			assert lsph_int(start['line'] or { json2.Any(i64(-1)) }) >= 0, 'diagnostic line must be a valid 0-based position: ${o}'
		}
	}
	assert saw_parse_error, 'no cx-parse diagnostic among ${diags.len} diagnostics: ${params}'
}

fn test_lsp_publishes_an_empty_diagnostic_set_for_a_clean_file() {
	// The other half of the push contract: a clean file must publish an
	// EMPTY set, not stay silent — silence leaves the editor showing the
	// previous file's stale squiggles forever.
	mut msgs := lsph_prelude(lsp_harness_uri, lsp_unformatted_doc)
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'clean diagnostics')
	notes := lsph_notifications(run, 'textDocument/publishDiagnostics')
	assert notes.len >= 1, 'a clean file must still publish (an empty) diagnostic set: ${run.raw}'
	params := lsph_obj(notes[0]['params'] or { json2.Any(json2.Null{}) })
	diags := lsph_arr(params['diagnostics'] or { json2.Any(json2.Null{}) })
	assert diags.len == 0, 'a well-formed document must produce no diagnostics, got ${diags.len}: ${params}'
}

// ── Pin (c): initialize capability drift ─────────────────────────────
//
// Two directions, both real defects seen in this tree's history (#423, #940,
// a14c60d6d): advertising a capability with no handler behind it, and
// quietly gaining or losing one. The literal roster below is the snapshot;
// the probe underneath it is the behavioural half — every advertised
// capability is EXERCISED and must not answer `method not found`.

// lsp_expected_capabilities — read off vcx/cmd/lsp.v's handle_initialize.
// Changing this list is a deliberate act; drifting it is not possible.
const lsp_expected_capabilities = [
	'codeActionProvider',
	'codeLensProvider',
	'completionProvider',
	'definitionProvider',
	'documentFormattingProvider',
	'documentSymbolProvider',
	'foldingRangeProvider',
	'hoverProvider',
	'inlayHintProvider',
	'referencesProvider',
	'renameProvider',
	'selectionRangeProvider',
	'semanticTokensProvider',
	'signatureHelpProvider',
	'textDocumentSync',
]

fn test_lsp_initialize_advertises_exactly_the_known_capability_set() {
	mut msgs := lsph_prelude(lsp_harness_uri, lsp_unformatted_doc)
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'initialize')
	result := lsph_obj(lsph_response(run, 1)['result'] or { json2.Any(json2.Null{}) })
	caps := lsph_obj(result['capabilities'] or { json2.Any(json2.Null{}) })
	mut got := caps.keys()
	got.sort()
	mut want := lsp_expected_capabilities.clone()
	want.sort()
	assert got == want, 'the advertised capability set drifted from the pinned roster.\n want: ${want}\n got:  ${got}\nUpdate lsp_expected_capabilities ONLY together with handle_initialize, and add the matching probe below.'

	// Shapes that clients branch on, not just presence.
	assert lsph_int(caps['textDocumentSync'] or { json2.Any(i64(-1)) }) == 1, 'the server uses FULL text sync (kind 1); didChange takes the last full text: ${caps}'
	completion := lsph_obj(caps['completionProvider'] or { json2.Any(json2.Null{}) })
	assert lsph_arr(completion['triggerCharacters'] or { json2.Any(json2.Null{}) }).len > 0, 'completionProvider must declare its trigger characters: ${completion}'
	sem := lsph_obj(caps['semanticTokensProvider'] or { json2.Any(json2.Null{}) })
	legend := lsph_obj(sem['legend'] or { json2.Any(json2.Null{}) })
	types := lsph_arr(legend['tokenTypes'] or { json2.Any(json2.Null{}) })
	assert types.len == 12, 'the semanticTokens legend is INDEX-ENCODED into every token — its length and order are wire contract, expected 12 types, got ${types.len}: ${legend}'
	assert types[0].str() == 'namespace' && types[11].str() == 'function', 'the semanticTokens legend order changed; every previously-emitted token now decodes to a different type: ${types}'
	rename := lsph_obj(caps['renameProvider'] or { json2.Any(json2.Null{}) })
	assert (rename['prepareProvider'] or { json2.Any(false) }).str() == 'true', 'renameProvider advertises prepareProvider, so prepareRename must stay live: ${rename}'

	// serverInfo.version is DERIVED from the repo VERSION define, never a
	// literal — a hardcoded version here was a real drift class (#984).
	info := lsph_obj(result['serverInfo'] or { json2.Any(json2.Null{}) })
	assert (info['name'] or { json2.Any('') }).str() == 'cx lsp', 'serverInfo.name: ${info}'
	assert (info['version'] or { json2.Any('') }).str().len > 0, 'serverInfo.version must be present and derived: ${info}'
}

// lsph_capability_probes maps each advertised capability to a request that
// exercises it. textDocumentSync is driven by the notifications in every
// session's prelude and has no request of its own.
fn lsph_capability_probes(uri string) map[string]string {
	pos := '{"textDocument":{"uri":${lsph_jstr(uri)}},"position":{"line":0,"character":2}}'
	return {
		'hoverProvider':              lsph_req(101, 'textDocument/hover', pos)
		'completionProvider':         lsph_req(102, 'textDocument/completion', pos)
		'definitionProvider':         lsph_req(103, 'textDocument/definition', pos)
		'documentFormattingProvider': lsph_req(104, 'textDocument/formatting', '{"textDocument":{"uri":${lsph_jstr(uri)}},"options":{"tabSize":2,"insertSpaces":true}}')
		'semanticTokensProvider':     lsph_req(105, 'textDocument/semanticTokens/full', lsph_doc_params(uri))
		'documentSymbolProvider':     lsph_req(106, 'textDocument/documentSymbol', lsph_doc_params(uri))
		'foldingRangeProvider':       lsph_req(107, 'textDocument/foldingRange', lsph_doc_params(uri))
		'selectionRangeProvider':     lsph_req(108, 'textDocument/selectionRange', '{"textDocument":{"uri":${lsph_jstr(uri)}},"positions":[{"line":0,"character":2}]}')
		'referencesProvider':         lsph_req(109, 'textDocument/references', '{"textDocument":{"uri":${lsph_jstr(uri)}},"position":{"line":0,"character":2},"context":{"includeDeclaration":true}}')
		'renameProvider':             lsph_req(110, 'textDocument/rename', '{"textDocument":{"uri":${lsph_jstr(uri)}},"position":{"line":0,"character":2},"newName":"renamed"}')
		'codeActionProvider':         lsph_req(111, 'textDocument/codeAction', '{"textDocument":{"uri":${lsph_jstr(uri)}},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":1}},"context":{"diagnostics":[]}}')
		'codeLensProvider':           lsph_req(112, 'textDocument/codeLens', lsph_doc_params(uri))
		'inlayHintProvider':          lsph_req(113, 'textDocument/inlayHint', '{"textDocument":{"uri":${lsph_jstr(uri)}},"range":{"start":{"line":0,"character":0},"end":{"line":3,"character":0}}}')
		'signatureHelpProvider':      lsph_req(114, 'textDocument/signatureHelp', pos)
	}
}

fn test_lsp_every_advertised_capability_answers_its_request() {
	// The drift pin with teeth: an advertised capability whose handler was
	// never wired (or was removed) falls through the dispatcher's `else` arm
	// to error -32601. Advertising is a promise to the editor; this asserts
	// the promise is kept for each one, and that prepareRename — advertised
	// as a SUB-capability of renameProvider — is live too.
	probes := lsph_capability_probes(lsp_harness_uri)
	mut msgs := lsph_prelude(lsp_harness_uri, lsp_unformatted_doc)
	mut ids := map[int]string{}
	for cap_name in lsp_expected_capabilities {
		if cap_name == 'textDocumentSync' {
			continue // exercised by didOpen/didChange/didClose, not a request
		}
		req := probes[cap_name] or {
			assert false, 'capability ${cap_name} is advertised but has NO probe — add one to lsph_capability_probes so the promise is tested'
			continue
		}
		msgs << req
		ids[lsph_req_id(req)] = cap_name
	}
	msgs << lsph_req(115, 'textDocument/prepareRename', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)}},"position":{"line":0,"character":2}}')
	ids[115] = 'renameProvider.prepareProvider'
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'capability probes')
	for id, cap_name in ids {
		resp := lsph_response(run, id)
		assert resp.len > 0, '${cap_name} is advertised in initialize but its request (id ${id}) drew NO response — the editor waits forever: ${run.raw.len} bytes of stream'
		if e := resp['error'] {
			eo := lsph_obj(e)
			code := lsph_int(eo['code'] or { json2.Any(i64(0)) })
			assert code != -32601, '${cap_name} is ADVERTISED but the dispatcher has no handler for it (-32601 method not found): ${eo}'
			assert false, '${cap_name} answered with an error: ${eo}'
		}
		assert 'result' in resp, '${cap_name} answered with neither result nor error: ${resp}'
	}
}

// ── Pin (c2): what the list-returning providers actually PUT ON THE WIRE ──
//
// The roster pin above says a capability is advertised; the probe pin says it
// answers. Neither says WHAT it answers, and for a list-returning provider the
// difference between `[]` and `null` is not cosmetic: LSP permits both, and a
// client that branches on `.length` throws on the second. So the shape is its
// own contract.
//
// This is the coverage tooling/lsp/tests/check_capabilities.cx carried that
// nothing else did. #1003 retired that script: it drained only the spawned
// server's stdout and left its stderr in an undrained 64 KiB pipe, so a server
// that said anything substantial on stderr wedged parent and child forever —
// and it was wired into no make target, so nothing would ever have noticed.
// Its one real assertion lands here instead, inside the lane, on a bounded
// file-fed session.
//
// It lands CORRECTED. That script asserted `[]` from BOTH codeAction and
// inlayHint because tooling/lsp/README.md's two 🚧 rows said so, and it probed
// with a document that happens to contain no pipes. Only codeAction is
// actually a stub (lsp_features.v handle_code_action writes `[]`
// unconditionally). inlayHint has been live since Phase 4.5 — it emits a
// declared-return hint at each `[?pipe …]` stage — so "returns a well-formed
// empty list, populated hints pending" was stale README text that the old
// script's own fixture agreed with by accident. Pinning the stale claim would
// have frozen the drift in place, so the inlayHint half pins the live
// behaviour on a document that HAS pipe stages.
// Three stages, not two: inlay_walk_pipes gates on `node.slots.len >= 3` and
// hints every stage after the first, so a two-stage pipe is silent by design.
const lsp_pipe_doc = '[?def parse scope=public [returns [sequence string]] (\$s) \$s]\n[?def clean scope=public [returns [sequence string]] (\$s) \$s]\n[?def total scope=public [returns int] (\$s) [\$count \$s]]\n\n[?pipe [\$parse \'a\'] [\$clean] [\$total]]\n'

fn test_lsp_code_action_answers_a_well_formed_empty_list() {
	uri := lsp_harness_uri
	mut msgs := lsph_prelude(uri, lsp_unformatted_doc)
	msgs << lsph_req(201, 'textDocument/codeAction', '{"textDocument":{"uri":${lsph_jstr(uri)}},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":5}},"context":{"diagnostics":[]}}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'codeAction shape')
	resp := lsph_response(run, 201)
	assert resp.len > 0, 'textDocument/codeAction drew NO response; raw: ${run.raw}'
	assert 'error' !in resp, 'textDocument/codeAction answered with an error: ${resp}'
	res := resp['result'] or {
		assert false, 'textDocument/codeAction answered with neither result nor error: ${resp}'
		return
	}
	assert res is []json2.Any, 'textDocument/codeAction answered ${res} — the provider is advertised, so it owes the editor a JSON ARRAY, never null and never an object'
	assert lsph_arr(res).len == 0, 'codeAction returned actions — tooling/lsp/README.md still documents it as 🚧 "returns a well-formed empty list, recipes pending". Landing recipes is a deliberate act: update the README row in the same change, and rewrite this pin to assert what the recipes are.'
}

fn test_lsp_inlay_hint_populates_declared_pipe_stage_returns() {
	uri := lsp_harness_uri
	mut msgs := lsph_prelude(uri, lsp_pipe_doc)
	msgs << lsph_req(202, 'textDocument/inlayHint', '{"textDocument":{"uri":${lsph_jstr(uri)}},"range":{"start":{"line":0,"character":0},"end":{"line":9,"character":0}}}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'inlayHint shape')
	resp := lsph_response(run, 202)
	assert resp.len > 0, 'textDocument/inlayHint drew NO response; raw: ${run.raw}'
	assert 'error' !in resp, 'textDocument/inlayHint answered with an error: ${resp}'
	res := resp['result'] or {
		assert false, 'textDocument/inlayHint answered with neither result nor error: ${resp}'
		return
	}
	assert res is []json2.Any, 'textDocument/inlayHint answered ${res} — the provider is advertised, so it owes the editor a JSON ARRAY, never null and never an object'
	hints := lsph_arr(res)
	assert hints.len > 0, 'inlayHint returned [] for a document with a `[?pipe …]` of two declared-return defs. The provider is LIVE (lsp_features.v inlay_walk_pipes) and this is the document shape it exists for; an empty answer here means the hint path regressed: ${run.raw}'
	first := lsph_obj(hints[0])
	label := (first['label'] or { json2.Any('') }).str()
	assert label.contains('sequence string'), 'the pipe-stage hint must carry the UPSTREAM stage\'s declared return type, got label ${label}: ${first}'
	pos := lsph_obj(first['position'] or { json2.Any(json2.Null{}) })
	assert 'line' in pos && 'character' in pos, 'every InlayHint needs a {line, character} position or the editor cannot place it: ${first}'
}

// lsph_req_id pulls the id back out of a request this file just built, so
// the probe table stays a single source of truth for method + id.
fn lsph_req_id(req string) int {
	o := lsph_obj(json2.decode[json2.Any](req) or { json2.Any(json2.Null{}) })
	return lsph_int(o['id'] or { json2.Any(i64(0)) })
}

fn test_lsp_unadvertised_method_is_method_not_found() {
	// The negative control that proves the probe above can DETECT drift:
	// a method the server does not advertise must answer -32601, and must
	// answer it as a proper error rather than by going silent.
	mut msgs := lsph_prelude(lsp_harness_uri, lsp_unformatted_doc)
	msgs << lsph_req(30, 'textDocument/typeDefinition', '{"textDocument":{"uri":${lsph_jstr(lsp_harness_uri)}},"position":{"line":0,"character":2}}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'unadvertised')
	resp := lsph_response(run, 30)
	assert resp.len > 0, 'an unsupported REQUEST must still be answered, or the editor hangs: ${run.raw}'
	e := lsph_obj(resp['error'] or { json2.Any(json2.Null{}) })
	assert lsph_int(e['code'] or { json2.Any(i64(0)) }) == -32601, 'an unadvertised method must answer -32601 method-not-found: ${resp}'
}

fn test_lsp_unknown_notification_is_never_answered() {
	// The dispatcher's `else` arm must answer requests and stay silent for
	// notifications. Replying to an unknown NOTIFICATION is the v0.12 crash's
	// other face — a reply with an id the client never issued.
	mut msgs := lsph_prelude(lsp_harness_uri, lsp_unformatted_doc)
	msgs << lsph_note('$/setTrace', '{"value":"verbose"}')
	msgs << lsph_note('workspace/didChangeConfiguration', '{"settings":{}}')
	msgs << lsph_note('$/cancelRequest', '{"id":1}')
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'unknown notifications')
	for f in run.frames {
		o := lsph_obj(f)
		assert 'error' !in o, 'an unknown NOTIFICATION drew an error reply — nothing may answer a notification: ${o}'
	}
	mut responses := 0
	for f in run.frames {
		if 'method' !in lsph_obj(f) {
			responses++
		}
	}
	assert responses == 2, 'sent 2 requests (initialize, shutdown) plus 3 notifications; got ${responses} responses: ${run.raw}'
}

// ── Framing itself ───────────────────────────────────────────────────

fn test_lsp_response_framing_is_byte_exact() {
	// The harness un-frames by trusting Content-Length exactly; this asserts
	// the server's own count matches its body, with no stray bytes between
	// frames. A framing drift desynchronises every editor on the first
	// message and is invisible to any handler-level test.
	mut msgs := lsph_prelude(lsp_harness_uri, lsp_unformatted_doc)
	msgs << lsph_epilogue()
	run := lsph_run(msgs, lsp_probe_budget_ms)
	lsph_healthy(run, 'framing')
	// Re-walk the raw stream and require it to be consumed EXACTLY.
	mut i := 0
	mut n_frames := 0
	for i < run.raw.len {
		hdr_end := run.raw.index_after('\r\n\r\n', i) or {
			assert false, 'frame ${n_frames} has no header terminator; ${run.raw.len - i} trailing bytes: ${run.raw[i..]}'
			break
		}
		header := run.raw[i..hdr_end]
		assert header.starts_with('Content-Length: '), 'frame ${n_frames} header is not a bare Content-Length line: ${header}'
		n := header.all_after(':').trim_space().int()
		body_start := hdr_end + 4
		assert body_start + n <= run.raw.len, 'frame ${n_frames} declares ${n} body bytes but only ${run.raw.len - body_start} remain — Content-Length overcounts the body'
		body := run.raw[body_start..body_start + n]
		json2.decode[json2.Any](body) or {
			assert false, 'frame ${n_frames} body is not valid JSON at its declared length (Content-Length is a BYTE count): ${body}'
		}
		i = body_start + n
		n_frames++
	}
	assert i == run.raw.len, 'the response stream did not un-frame exactly: ${run.raw.len - i} bytes left over after ${n_frames} frames'
	assert n_frames == run.frames.len, 'framing walk disagrees with the harness split: ${n_frames} vs ${run.frames.len}'
	assert n_frames >= 3, 'expected at least initialize + publishDiagnostics + shutdown, got ${n_frames} frames'
}

fn test_lsp_terminates_on_eof_without_an_exit_notification() {
	// An editor that dies takes its pipe with it. The server must fall out of
	// its read loop on EOF rather than spin — an unbounded probe would be the
	// only thing that noticed, which is why this one is bounded like the rest.
	msgs := lsph_prelude(lsp_harness_uri, lsp_unformatted_doc)
	run := lsph_run(msgs, lsp_probe_budget_ms)
	assert !run.killed, 'cx lsp did not terminate on stdin EOF within ${lsp_probe_budget_ms}ms — it must exit when its client goes away'
	assert run.code == 0, 'an EOF-terminated session must still exit 0, got ${run.code} (stderr: ${run.stderr})'
	assert lsph_response(run, 1).len > 0, 'the session still had to answer initialize: ${run.raw}'
}
