// platform_netwire_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):
// the per-area test-binary umbrella. 3 source files merged verbatim (byte-identical
// helper dedupe only; the V compiler is the name-collision oracle). Fewer test
// files = fewer whole-module-graph compiles (V compilation was 99% of the gate).
// Regenerate: scripts/consolidate_tests.sh gen platform_netwire
// Manifest:   scripts/consolidation/platform_netwire.files

module platform

import code { caps_set_all, is_err_value, render_canonical }
import cx
import net
import net.http
import os
import testenv
import time

// ── source: vcx/platform/store_grpc_concurrency_test.v ──
// store_grpc_concurrency_test.v — #123 brick D: the gRPC listener serves
// connections CONCURRENTLY (a bounded worker pool, not one-at-a-time), and
// reassembles + dispatches multiple HTTP/2 streams on a single connection. Two
// raw-socket clients (built from the same H2/HPACK/proto primitives as the live
// test) hit the daemon at once; each must get ITS OWN correct response — no
// crossing of responses across connections under concurrency. A third check
// drives two streams on one connection and asserts both are dispatched. Skips
// when the cx binary is absent.

fn grpc_conc_bin() string {
	return os.real_path(os.join_path(os.dir(os.dir(@FILE)), 'target', 'cx'))
}

fn grpc_conc_free_port() int {
	mut l := net.listen_tcp(.ip, '127.0.0.1:0') or { return 0 }
	port := l.addr() or { return 0 }.port() or { return 0 }
	l.close() or {}
	return port
}

// grpc_put_frames / grpc_get_frames build the H2 frames for one gRPC call on a
// given stream id (HEADERS + a single END_STREAM DATA frame).
fn grpc_put_frames(stream_id u32, store string, body string) []u8 {
	mut req := []u8{}
	req << h2_frame_encode(H2Frame{
		typ:       h2_headers
		flags:     h2_flag_end_headers
		stream_id: stream_id
		payload:   hpack_encode_header_list([
			HpackHeader{':method', 'POST'},
			HpackHeader{':scheme', 'http'},
			HpackHeader{':path', '/cxstore.v1.CxStore/Put'},
			HpackHeader{'content-type', 'application/grpc'},
			HpackHeader{'te', 'trailers'},
		])
	})
	req << h2_frame_encode(H2Frame{
		typ:       h2_data
		flags:     h2_flag_end_stream
		stream_id: stream_id
		payload:   grpc_frame_encode(pb_encode_put_request(GrpcPutRequest{
			store:    store
			body:     body.bytes()
			encoding: 'cxd'
		}))
	})
	return req
}

fn grpc_get_frames(stream_id u32, store string, hash string) []u8 {
	mut req := []u8{}
	req << h2_frame_encode(H2Frame{
		typ:       h2_headers
		flags:     h2_flag_end_headers
		stream_id: stream_id
		payload:   hpack_encode_header_list([
			HpackHeader{':method', 'POST'},
			HpackHeader{':scheme', 'http'},
			HpackHeader{':path', '/cxstore.v1.CxStore/Get'},
			HpackHeader{'content-type', 'application/grpc'},
			HpackHeader{'te', 'trailers'},
		])
	})
	req << h2_frame_encode(H2Frame{
		typ:       h2_data
		flags:     h2_flag_end_stream
		stream_id: stream_id
		payload:   grpc_frame_encode(pb_encode_get_request(GrpcGetRequest{
			store: store
			hash:  hash
		}))
	})
	return req
}

// grpc_read_until reads server frames until every wanted stream has its
// grpc-status trailer, returning per-stream (status, last gRPC message bytes).
fn grpc_read_until(mut conn net.TcpConn, want []u32) (map[u32]string, map[u32][]u8) {
	mut r := H2FrameReader{}
	mut cli := new_hpack_decoder(4096)
	mut status := map[u32]string{}
	mut data := map[u32][]u8{}
	mut buf := []u8{len: 16384}
	deadline := time.now().add(4 * time.second)
	for time.now() < deadline {
		n := conn.read(mut buf) or { break }
		if n <= 0 {
			break
		}
		r.feed(buf[..n].clone())
		for {
			f := r.next() or { break }
			match f.typ {
				h2_headers {
					hdrs := cli.decode(f.payload) or { []HpackHeader{} }
					for h in hdrs {
						if h.name == 'grpc-status' {
							status[f.stream_id] = h.value
						}
					}
				}
				h2_data {
					mut fr := GrpcFrameReader{}
					fr.feed(f.payload)
					if gf := fr.next() {
						data[f.stream_id] = gf.data
					}
				}
				else {}
			}
		}
		mut all := true
		for sid in want {
			if sid !in status {
				all = false
			}
		}
		if all {
			break
		}
	}
	return status, data
}

struct GrpcRt {
mut:
	put_status string
	put_hash   string
	get_status string
	get_body   string
	dialed     bool
}

// grpc_put_get_roundtrip is one client's full exchange on its own connection: Put
// a uniquely-marked doc (stream 1), then Get it back by the returned hash
// (stream 3). Returned so the caller can assert this client got ITS doc — the
// concurrency-correctness proof.
fn grpc_put_get_roundtrip(gport int, store string, marker string) GrpcRt {
	mut rt := GrpcRt{}
	mut conn := net.dial_tcp('127.0.0.1:${gport}') or { return rt }
	rt.dialed = true
	defer {
		conn.close() or {}
	}
	conn.set_read_timeout(4 * time.second)

	mut hello := []u8{}
	hello << h2_preface.bytes()
	hello << h2_frame_encode(h2_settings_frame([]H2Setting{}))
	hello << grpc_put_frames(1, store, '[note [body "${marker}"]]')
	conn.write(hello) or { return rt }

	st1, d1 := grpc_read_until(mut conn, [u32(1)])
	rt.put_status = st1[1] or { '' }
	if b := d1[1] {
		pr := pb_decode_put_response(b) or { GrpcPutResponse{} }
		rt.put_hash = pr.hash
	}
	if !rt.put_hash.starts_with('sha2-256:') {
		return rt
	}

	conn.write(grpc_get_frames(3, store, rt.put_hash)) or { return rt }
	st3, d3 := grpc_read_until(mut conn, [u32(3)])
	rt.get_status = st3[3] or { '' }
	if b := d3[3] {
		gr := pb_decode_get_response(b) or { GrpcGetResponse{} }
		rt.get_body = gr.body.bytestr()
	}
	return rt
}

fn grpc_conc_spawn_daemon(cport int, gport int) (string, string) {
	bin := grpc_conc_bin()
	cfg := os.join_path(os.temp_dir(), 'cx_grpc_conc_${gport}.cx')
	os.write_file(cfg, '[cxstore-service\n  [bind addr="127.0.0.1:${cport}"]\n  [grpc enabled=true addr="127.0.0.1:${gport}"]\n  [stores\n    [store name="t" url="mem://grpc-conc"]]]\n') or {
		return '', ''
	}
	pid_s := os.execute('${bin} store-serve --config ${cfg} --allow-net=127.0.0.1:${cport} --allow-net=127.0.0.1:${gport} >/tmp/cx-grpc-conc.${gport}.out 2>&1 & echo \$!')
	if pid_s.exit_code != 0 {
		os.rm(cfg) or {}
		return '', ''
	}
	return pid_s.output.trim_space(), cfg
}

fn test_grpc_two_concurrent_clients() {
	bin := grpc_conc_bin()
	if !os.exists(bin) {
		eprintln('SKIP: cx binary not found at ${bin} — run `make build-vcx`')
		return
	}
	cport := grpc_conc_free_port()
	gport := grpc_conc_free_port()
	if cport == 0 || gport == 0 || cport == gport {
		eprintln('SKIP: could not allocate ports')
		return
	}
	pid, cfg := grpc_conc_spawn_daemon(cport, gport)
	if pid == '' {
		eprintln('SKIP: could not spawn cx store-serve')
		return
	}
	defer {
		os.execute('kill ${pid} 2>/dev/null')
		os.rm(cfg) or {}
	}
	time.sleep(800 * time.millisecond) // let both listeners bind

	// Two clients, each its own connection + uniquely-marked doc, dispatched at
	// the SAME time. Each must get its own doc back — not the other's.
	t1 := spawn grpc_put_get_roundtrip(gport, 't', 'concurrent-alpha-AAA')
	t2 := spawn grpc_put_get_roundtrip(gport, 't', 'concurrent-beta-BBB')
	r1 := t1.wait()
	r2 := t2.wait()

	srv_log := os.read_file('/tmp/cx-grpc-conc.${gport}.out') or { '' }
	if !r1.dialed || !r2.dialed {
		eprintln('SKIP: a client could not dial the gRPC port | srv: ${srv_log}')
		return
	}
	assert r1.put_status == '0', 'client1 put grpc-status ${r1.put_status} | srv: ${srv_log}'
	assert r2.put_status == '0', 'client2 put grpc-status ${r2.put_status} | srv: ${srv_log}'
	assert r1.get_status == '0', 'client1 get grpc-status ${r1.get_status} | srv: ${srv_log}'
	assert r2.get_status == '0', 'client2 get grpc-status ${r2.get_status} | srv: ${srv_log}'
	// Connection isolation under concurrency: each client got ITS marker back.
	assert r1.get_body.contains('concurrent-alpha-AAA'), 'client1 did not get its own doc: ${r1.get_body} | srv: ${srv_log}'
	assert r2.get_body.contains('concurrent-beta-BBB'), 'client2 did not get its own doc: ${r2.get_body} | srv: ${srv_log}'
	// And NOT the other client's doc (no response crossing).
	assert !r1.get_body.contains('beta-BBB'), 'client1 response crossed with client2: ${r1.get_body}'
	assert !r2.get_body.contains('alpha-AAA'), 'client2 response crossed with client1: ${r2.get_body}'
}

fn test_grpc_multiplexed_streams_one_conn() {
	bin := grpc_conc_bin()
	if !os.exists(bin) {
		eprintln('SKIP: cx binary not found at ${bin}')
		return
	}
	cport := grpc_conc_free_port()
	gport := grpc_conc_free_port()
	if cport == 0 || gport == 0 || cport == gport {
		eprintln('SKIP: could not allocate ports')
		return
	}
	pid, cfg := grpc_conc_spawn_daemon(cport, gport)
	if pid == '' {
		eprintln('SKIP: could not spawn cx store-serve')
		return
	}
	defer {
		os.execute('kill ${pid} 2>/dev/null')
		os.rm(cfg) or {}
	}
	time.sleep(800 * time.millisecond)

	mut conn := net.dial_tcp('127.0.0.1:${gport}') or {
		eprintln('SKIP: could not dial gRPC port: ${err}')
		return
	}
	defer {
		conn.close() or {}
	}
	conn.set_read_timeout(4 * time.second)

	// Two Put calls on streams 1 and 3, BOTH sent before reading any response —
	// the single connection must reassemble + dispatch each stream independently.
	mut req := []u8{}
	req << h2_preface.bytes()
	req << h2_frame_encode(h2_settings_frame([]H2Setting{}))
	req << grpc_put_frames(1, 't', '[note [body "mux-stream-one"]]')
	req << grpc_put_frames(3, 't', '[note [body "mux-stream-three"]]')
	conn.write(req) or {
		assert false, 'write multiplexed request: ${err}'
		return
	}

	status, data := grpc_read_until(mut conn, [u32(1), u32(3)])
	srv_log := os.read_file('/tmp/cx-grpc-conc.${gport}.out') or { '' }
	assert status[1] or { '' } == '0', 'stream 1 grpc-status ${status[1] or { "<none>" }} | srv: ${srv_log}'
	assert status[3] or { '' } == '0', 'stream 3 grpc-status ${status[3] or { "<none>" }} | srv: ${srv_log}'
	h1 := (pb_decode_put_response(data[1] or { []u8{} }) or { GrpcPutResponse{} }).hash
	h3 := (pb_decode_put_response(data[3] or { []u8{} }) or { GrpcPutResponse{} }).hash
	assert h1.starts_with('sha2-256:') && h1.len == 73, 'stream 1 hash: ${h1} | srv: ${srv_log}'
	assert h3.starts_with('sha2-256:') && h3.len == 73, 'stream 3 hash: ${h3} | srv: ${srv_log}'
	// Distinct doc bodies → distinct content addresses: each stream got its own.
	assert h1 != h3, 'multiplexed streams must yield distinct hashes (each dispatched independently): ${h1} == ${h3}'
}

// ── source: vcx/platform/store_g13_parity_test.v ──
// store_g13_parity_test.v — the G13 store-protocol parity families (the W7
// gate delivered as S6.5; RULED: R4.4(a-revised) / L167 / R2.5). The profile's
// fixture families run IDENTICALLY across the TWO live listeners — the XSP
// store profile and the gRPC edge (pipeline="profile" synthesis) — with the
// LOCAL EMBEDDED ENGINE as the correctness oracle: byte-identical content
// addresses and values, CXER-code error identity (cxstore-grpc.md §3), and
// identical stream result sets. #718 items 2/3 close here: the gRPC lanes
// drive Aliases/AliasesSet/Reload (+ the S6.5 blob pair) explicitly, the
// list result sets are compared cross-wire, and the capabilities advert's
// compression claim is pinned honest.
//
// Focused test fns, one daemon boot each, node locals kept in tight blocks
// (the #749 -gc e autofree scope discipline).

const g13_fold_src = '[?def sum-amounts (\$acc \$e) [+ \$acc \$e//amount]]'

fn g13_str(s string) cx.Node {
	return cx.ScalarNode{
		value:     cx.ScalarValue(s)
		data_type: cx.ScalarType.string_type
	}
}

fn g13_free_port() int {
	mut l := net.listen_tcp(.ip, '127.0.0.1:0') or { return 0 }
	port := l.addr() or { return 0 }.port() or { return 0 }
	l.close() or {}
	return port
}

// g13_boot brings up ONE daemon with BOTH listeners (gRPC edge + XSP profile)
// over a shared file:// store, plus a mem:// oracle handle, and opens a
// client handle per wire — both carrying the SAME client identity (the admin
// lanes need it: the XSP open-posture mutual gate, the gRPC CxCall analog).
// Returns (oracle, xsp, grpc, proc, tmp, cport).
fn g13_boot(tag string) (cx.Node, cx.Node, cx.Node, &os.Process, string, int) {
	cport := g13_free_port()
	gport := g13_free_port()
	xport := g13_free_port()
	if cport == 0 || gport == 0 || xport == 0 {
		panic('g13: could not allocate ports')
	}
	tmp := os.join_path(os.temp_dir(), 'cx-g13-${tag}-${os.getpid()}')
	os.rmdir_all(tmp) or {}
	os.mkdir_all(tmp) or { panic('mkdir: ${err}') }
	sseed := []u8{len: 32, init: 0x06}
	sdid := did_key_from_seed(sseed) or { panic('sdid: ${err}') }
	os.setenv('CX_G13_SEED', sseed.hex(), true)
	cseed := []u8{len: 32, init: 0x05}
	cdid := did_key_from_seed(cseed) or { panic('cdid: ${err}') }
	os.setenv('CX_G13_CSEED', cseed.hex(), true)
	cfg := '[cxstore-service
  [bind addr="127.0.0.1:${cport}"]
  [grpc enabled=true addr="127.0.0.1:${gport}"]
  [stores [store name="main" url="file://${tmp}/store"]]
  [xsp enabled=true addr="127.0.0.1:${xport}"
    [identity did="${sdid}" seed-env="CX_G13_SEED"]
    [policy mode=floor floor="guest"]]
  [workers query-pool=2]]'
	cfg_path := os.join_path(tmp, 'svc.cx')
	os.write_file(cfg_path, cfg) or { panic('cfg: ${err}') }
	cxbin := testenv.cx_bin()
	mut proc := os.new_process('/bin/sh')
	proc.set_args(['-c',
		// --allow-eval: the L99 quoted-planar query op executes through the
		// sandboxed [?eval] server-side — the daemon operator's grant (family
		// 5; without it comp= fails CLOSED with CXER0271).
		'exec "${cxbin}" store-serve --config "${cfg_path}" --exit-on-stdin-eof --allow-read --allow-write --allow-net=127.0.0.1:${cport} --allow-net=127.0.0.1:${gport} --allow-net=127.0.0.1:${xport} --allow-env --allow-eval >"${tmp}/daemon.log" 2>&1'])
	proc.set_redirect_stdio()
	proc.run()
	mut up := false
	for _ in 0 .. 100 {
		time.sleep(100 * time.millisecond)
		r0 := http.get('http://127.0.0.1:${cport}/cx-store/v1/ready') or { continue }
		if r0.status_code == 200 && r0.body.contains('[accepting true]') {
			up = true
			break
		}
	}
	if !up {
		proc.signal_kill()
		panic('g13 daemon never came up: ${os.read_file(os.join_path(tmp, 'daemon.log')) or {
			''
		}}')
	}
	caps_set_all()
	idopts := cx.Node(cx.Element{
		name:  code.map_marker_name
		items: [
			session_kv('xsp-did', g13_str(cdid)),
			session_kv('xsp-seed-env', g13_str('CX_G13_CSEED')),
		]
	})
	oracle := store_stdlib_builtin_inner('store-open', [
		g13_str('mem://g13-${tag}'),
	]) or { panic('oracle open: ${err}') }
	hx := store_stdlib_builtin_inner('store-open-opts', [
		g13_str('cx-store+xsp://127.0.0.1:${xport}/'),
		idopts,
	]) or { panic('xsp open: ${err}') }
	hg := store_stdlib_builtin_inner('store-open-opts', [
		g13_str('cx-store+grpc://127.0.0.1:${gport}/main/'),
		idopts,
	]) or { panic('grpc open: ${err}') }
	if is_err_value(oracle) || is_err_value(hx) || is_err_value(hg) {
		proc.signal_kill()
		panic('g13 open: ${render_canonical(oracle)} / ${render_canonical(hx)} / ${render_canonical(hg)}')
	}
	return oracle, hx, hg, proc, tmp, cport
}

fn g13_op1(h cx.Node, op string, a string) cx.Node {
	r := store_stdlib_builtin_inner(op, [h, g13_str(a)]) or { panic('${op}: ${err}') }
	return r
}

fn g13_code(r cx.Node) string {
	if r is cx.Element {
		return sw_attr(r, 'code')
	}
	return ''
}

// g13_strings extracts every string scalar in a (possibly nested) result and
// returns them sorted — the stream result-set comparator (order across wires
// is not part of the contract; the SET is).
fn g13_strings(r cx.Node) []string {
	mut out := []string{}
	if r is cx.ScalarNode {
		v := r.value
		if v is string {
			out << v
		}
	} else if r is cx.Element {
		for it in r.items {
			out << g13_strings(it)
		}
	}
	out.sort()
	return out
}

// ── family 1: docs + the F1' blob pair + delete (op-for-op + error identity) ──
fn test_g13_docs_blobs_delete_parity() {
	oracle, hx, hg, mut proc, tmp, _ := g13_boot('doc')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	doc := '[invoice [amount 42] [customer "acme"]]'
	mut addr := ''
	{
		oa := g13_op1(oracle, 'store-put-doc-text', doc)
		xa := g13_op1(hx, 'store-put-doc-text', doc)
		ga := g13_op1(hg, 'store-put-doc-text', doc)
		assert !is_err_value(oa) && !is_err_value(xa) && !is_err_value(ga), 'put: ${render_canonical(xa)} / ${render_canonical(ga)}'
		addr = sw_scalar(oa)
		assert sw_scalar(xa) == addr && sw_scalar(ga) == addr, 'content address identity: ${addr} / ${sw_scalar(xa)} / ${sw_scalar(ga)}'
	}
	{
		og := g13_op1(oracle, 'store-get-doc-text', addr)
		xg := g13_op1(hx, 'store-get-doc-text', addr)
		gg := g13_op1(hg, 'store-get-doc-text', addr)
		assert sw_scalar(og) == sw_scalar(xg) && sw_scalar(xg) == sw_scalar(gg), 'get round-trip byte identity'
	}
	// the F1' OPAQUE pair: deliberately NON-canonical raw bytes — a
	// canonicalizing path would change them, so byte-exactness IS the proof.
	blob := '[greet   "  spaced\n\traw"  ]\n[; trailing comment ]'
	mut key := ''
	{
		ok0 := g13_op1(oracle, 'store-put-blob', blob)
		xk := g13_op1(hx, 'store-put-blob', blob)
		gk := g13_op1(hg, 'store-put-blob', blob)
		assert !is_err_value(ok0) && !is_err_value(xk) && !is_err_value(gk), 'put-blob: ${render_canonical(xk)} / ${render_canonical(gk)}'
		key = sw_scalar(ok0)
		assert sw_scalar(xk) == key && sw_scalar(gk) == key, 'blob key identity: ${key} / ${sw_scalar(xk)} / ${sw_scalar(gk)}'
	}
	{
		ob := g13_op1(oracle, 'store-get-blob', key)
		xb := g13_op1(hx, 'store-get-blob', key)
		gb := g13_op1(hg, 'store-get-blob', key)
		assert sw_scalar(ob) == blob && sw_scalar(xb) == blob && sw_scalar(gb) == blob, 'blob byte-exact round-trip on all three'
	}
	{
		// absence: the blob surface's CXER1121 contract — CODE identity across
		// the oracle and both wires (#194 / cxstore-grpc.md §3).
		absent := 'sha2-256:${'0'.repeat(64)}'
		oa := g13_op1(oracle, 'store-get-blob', absent)
		xa := g13_op1(hx, 'store-get-blob', absent)
		ga := g13_op1(hg, 'store-get-blob', absent)
		assert g13_code(oa) == 'cx-err:CXER1121', 'oracle absent: ${render_canonical(oa)}'
		assert g13_code(xa) == 'cx-err:CXER1121', 'xsp absent: ${render_canonical(xa)}'
		assert g13_code(ga) == 'cx-err:CXER1121', 'grpc absent: ${render_canonical(ga)}'
	}
	{
		// delete parity: present → the same answer everywhere; repeat → the
		// same absent answer everywhere (the oracle defines the shape).
		od := g13_op1(oracle, 'store-delete-doc', addr)
		xd := g13_op1(hx, 'store-delete-doc', addr)
		od2 := g13_op1(oracle, 'store-delete-doc', addr)
		gd2 := g13_op1(hg, 'store-delete-doc', addr)
		assert render_canonical(od) == render_canonical(xd), 'delete present parity'
		assert render_canonical(od2) == render_canonical(gd2), 'delete absent parity'
	}
}

// ── family 2: alias remoting (set / read / explicit absence / absent target) ──
fn test_g13_alias_parity() {
	oracle, hx, hg, mut proc, tmp, _ := g13_boot('ali')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	doc := '[release [version "1.2.3"]]'
	mut addr := ''
	{
		oa := g13_op1(oracle, 'store-put-doc-text', doc)
		xa := g13_op1(hx, 'store-put-doc-text', doc)
		addr = sw_scalar(oa)
		assert sw_scalar(xa) == addr
	}
	{
		// set via the gRPC edge (AliasesSet — #718 item 2's missing lane),
		// read back over BOTH wires + the oracle.
		or0 := store_stdlib_builtin_inner('store-set-alias', [oracle, g13_str('rel'),
			g13_str(addr)]) or { panic('set: ${err}') }
		gr := store_stdlib_builtin_inner('store-set-alias', [hg, g13_str('rel'),
			g13_str(addr)]) or { panic('set: ${err}') }
		assert !is_err_value(or0) && !is_err_value(gr), 'alias set: ${render_canonical(gr)}'
		og := g13_op1(oracle, 'store-get-alias', 'rel')
		xg := g13_op1(hx, 'store-get-alias', 'rel')
		gg := g13_op1(hg, 'store-get-alias', 'rel')
		assert sw_scalar(og) == addr && sw_scalar(xg) == addr && sw_scalar(gg) == addr, 'alias read identity (set over gRPC, read over XSP): ${render_canonical(xg)}'
	}
	{
		// explicit absence — the server-asserted absent alias renders the SAME
		// absence the local surface renders (#264 posture).
		oa := g13_op1(oracle, 'store-get-alias', 'ghost')
		xa := g13_op1(hx, 'store-get-alias', 'ghost')
		ga := g13_op1(hg, 'store-get-alias', 'ghost')
		assert render_canonical(oa) == render_canonical(xa), 'absent alias parity xsp: ${render_canonical(xa)}'
		assert render_canonical(oa) == render_canonical(ga), 'absent alias parity grpc: ${render_canonical(ga)}'
	}
	{
		// an alias to an ABSENT target refuses CXER1121 everywhere (the
		// daemon-side target-presence rule ≡ the local one).
		absent := 'sha2-256:${'1'.repeat(64)}'
		oe := store_stdlib_builtin_inner('store-set-alias', [oracle, g13_str('bad'),
			g13_str(absent)]) or { panic('set: ${err}') }
		xe := store_stdlib_builtin_inner('store-set-alias', [hx, g13_str('bad'),
			g13_str(absent)]) or { panic('set: ${err}') }
		ge := store_stdlib_builtin_inner('store-set-alias', [hg, g13_str('bad'),
			g13_str(absent)]) or { panic('set: ${err}') }
		assert g13_code(oe) == 'cx-err:CXER1121' && g13_code(xe) == 'cx-err:CXER1121'
			&& g13_code(ge) == 'cx-err:CXER1121', 'absent-target identity: ${render_canonical(xe)} / ${render_canonical(ge)}'
	}
}

// ── family 3: stream result sets (list / query) are IDENTICAL sets cross-wire ──
fn test_g13_stream_result_parity() {
	oracle, hx, hg, mut proc, tmp, _ := g13_boot('str')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	// Roots wrap the queried entities: the query scan anchors at the root's
	// CHILDREN (the shipped root-as-context convention, #768), so a doc whose
	// ROOT is [user …] never matches //user — the pre-W3 walker only appeared
	// to match because it looked up the LAST path segment's name anywhere
	// (the multi-segment defect the W3 stepwise walk fixed).
	docs := ['[rec [user [name "ada"]]]', '[rec [user [name "bob"]]]',
		'[rec [order [sku "x1"] [qty 2]]]']
	for d in docs {
		_ := g13_op1(oracle, 'store-put-doc-text', d)
		x := g13_op1(hx, 'store-put-doc-text', d)
		assert !is_err_value(x), 'seed: ${render_canonical(x)}'
	}
	{
		ol := store_stdlib_builtin_inner('store-list-docs', [oracle]) or { panic('list: ${err}') }
		xl := store_stdlib_builtin_inner('store-list-docs', [hx]) or { panic('list: ${err}') }
		gl := store_stdlib_builtin_inner('store-list-docs', [hg]) or { panic('list: ${err}') }
		os_ := g13_strings(ol)
		xs := g13_strings(xl)
		gs := g13_strings(gl)
		assert os_.len == 3, 'oracle list: ${os_}'
		assert xs == os_, 'list set parity xsp: ${xs} vs ${os_}'
		assert gs == os_, 'list set parity grpc (#718 item 3 list-shape): ${gs} vs ${os_}'
	}
	{
		oq := store_stdlib_builtin_inner('store-query', [oracle, g13_str('//user/name')]) or {
			panic('query: ${err}')
		}
		xq := store_stdlib_builtin_inner('store-query', [hx, g13_str('//user/name')]) or {
			panic('query: ${err}')
		}
		gq := store_stdlib_builtin_inner('store-query', [hg, g13_str('//user/name')]) or {
			panic('query: ${err}')
		}
		// L97 flat relation: parity compares (doc=, cxpath part of source=,
		// payload) — the source= STORE-URL half legitimately differs per handle
		// (the oracle is its own mem:// store; each wire handle rebases source=
		// to ITS handle URL, caller-coherent provenance), so the comparator
		// normalizes it while separate asserts pin each side's own prefix.
		os_ := g13_rendered_set(g13_normalize_source(oq))
		xs := g13_rendered_set(g13_normalize_source(xq))
		gs := g13_rendered_set(g13_normalize_source(gq))
		assert os_.len == 2, 'oracle query: ${render_canonical(oq)}'
		assert xs == os_ && gs == os_, 'query result-set parity: ${xs} / ${gs} vs ${os_}'
		assert g13_source_prefixes(xq, 'cx-store+xsp://'), 'xsp tuples must carry the caller handle URL in source=: ${render_canonical(xq)}'
		assert g13_source_prefixes(gq, 'cx-store+grpc://'), 'grpc tuples must carry the caller handle URL in source=: ${render_canonical(gq)}'
	}
}

// g13_normalize_source rewrites every tuple's source= to its `#cxpath` part —
// the cross-handle comparator for the L97 relation (store identity differs by
// design between the oracle and the wire handles).
fn g13_normalize_source(r cx.Node) cx.Node {
	if r is cx.Element {
		mut items := []cx.Node{cap: r.items.len}
		for it in r.items {
			if it is cx.Element && it.name == 'result' {
				mut attrs := []cx.Attribute{cap: it.attrs.len}
				for a in it.attrs {
					if a.name == 'source' {
						sv := cx.scalar_value_str_public(a.value)
						mut frag := sv
						if i := sv.index('#') {
							frag = sv[i..]
						}
						attrs << cx.Attribute{
							name:  'source'
							value: cx.ScalarValue(frag)
						}
					} else {
						attrs << a
					}
				}
				items << cx.Element{
					...it
					attrs: attrs
				}
			} else {
				items << it
			}
		}
		return cx.Element{
			...r
			items: items
		}
	}
	return r
}

// g13_source_prefixes asserts every tuple's source= starts with `prefix` —
// the caller-coherent provenance pin (the client rebases the server's local
// URL to the handle URL the caller actually opened).
fn g13_source_prefixes(r cx.Node, prefix string) bool {
	if r is cx.Element {
		for it in r.items {
			if it is cx.Element && it.name == 'result' {
				for a in it.attrs {
					if a.name == 'source' {
						if !cx.scalar_value_str_public(a.value).starts_with(prefix) {
							return false
						}
					}
				}
			}
		}
	}
	return true
}

// g13_rendered_set renders each top-level item of a sequence result canonical
// and sorts — the per-match identity comparator (matches carry parsed rows,
// whose leaves are text nodes; the render IS the identity).
fn g13_rendered_set(r cx.Node) []string {
	mut out := []string{}
	if r is cx.Element {
		for it in r.items {
			out << render_canonical(it)
		}
	} else {
		out << render_canonical(r)
	}
	out.sort()
	return out
}

// ── family 4: journal over BOTH wires — one chain, byte-identical reads,
//    CAS error identity, fold ≡ oracle, and the S6.4 signer surface ──────────
fn test_g13_journal_parity() {
	oracle, hx, hg, mut proc, tmp, _ := g13_boot('jrn')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	attribution := cx.Node(cx.Element{
		name:  code.map_marker_name
		items: [
			cx.Node(cx.Element{
				name:  'actor'
				items: [g13_str('did:key:g13-writer')]
			}),
			cx.Node(cx.Element{
				name:  'authority'
				items: [g13_str('operator')]
			}),
		]
	})
	amounts := [i64(5), 7, 11]
	// append over the XSP-attached journal; the SAME chain serves both wires.
	jx := jrn_attach([hx, g13_str('ledger')]) or { panic('jx: ${err}') }
	jo := jrn_attach([oracle, g13_str('ledger')]) or { panic('jo: ${err}') }
	for a in amounts {
		ev := cx.Node(cx.Element{
			name:  'amount'
			items: [cx.Node(cx.ScalarNode{
				value:     cx.ScalarValue(a)
				data_type: cx.ScalarType.int_type
			})]
		})
		xr := journal_stdlib_builtin('journal-append', [jx, ev, attribution]) or {
			panic('append: ${err}')
		}
		assert !is_err_value(xr), 'append: ${render_canonical(xr)}'
		or0 := journal_stdlib_builtin('journal-append', [jo, ev, attribution]) or {
			panic('append: ${err}')
		}
		assert !is_err_value(or0)
	}
	// stale-tail CAS: expect-pos=1 against head=3 → the ONE ref-conflict
	// code (CXER1114) with IDENTICAL identity over both wires.
	jg := jrn_attach([hg, g13_str('ledger')]) or { panic('jg: ${err}') }
	{
		stale := cx.Node(cx.Element{
			name:  code.map_marker_name
			items: [
				cx.Node(cx.Element{
					name:  'actor'
					items: [g13_str('did:key:g13-writer')]
				}),
				cx.Node(cx.Element{
					name:  'authority'
					items: [g13_str('operator')]
				}),
				cx.Node(cx.Element{
					name:  'expect-pos'
					items: [cx.Node(cx.ScalarNode{
						value:     cx.ScalarValue(i64(1))
						data_type: cx.ScalarType.int_type
					})]
				}),
			]
		})
		ev := cx.Node(cx.Element{
			name:  'amount'
			items: [cx.Node(cx.ScalarNode{
				value:     cx.ScalarValue(i64(99))
				data_type: cx.ScalarType.int_type
			})]
		})
		xe := journal_stdlib_builtin('journal-append', [jx, ev, stale]) or {
			panic('stale x: ${err}')
		}
		ge := journal_stdlib_builtin('journal-append', [jg, ev, stale]) or {
			panic('stale g: ${err}')
		}
		assert g13_code(xe) == 'cx-err:CXER1114', 'stale-tail xsp: ${render_canonical(xe)}'
		assert g13_code(ge) == 'cx-err:CXER1114', 'stale-tail grpc: ${render_canonical(ge)}'
	}
	{
		// one chain, byte-identical entries through either wire.
		x2 := journal_stdlib_builtin('journal-read', [jx, cx.Node(cx.ScalarNode{
			value:     cx.ScalarValue(i64(2))
			data_type: cx.ScalarType.int_type
		})]) or { panic('read: ${err}') }
		g2 := journal_stdlib_builtin('journal-read', [jg, cx.Node(cx.ScalarNode{
			value:     cx.ScalarValue(i64(2))
			data_type: cx.ScalarType.int_type
		})]) or { panic('read: ${err}') }
		assert render_canonical(x2) == render_canonical(g2), 'entry-2 byte identity across wires'
	}
	// fold: pushed-through-either-wire ≡ the local oracle's state (the events
	// are equal; ts/hash differences live in the entries, never the state).
	mut env := code.new_env()
	prog := cx.parse_program(g13_fold_src) or { panic('parse: ${err}') }
	code.eval(prog.body, mut env) or { panic('reg: ${err}') }
	fv := code.mk_closure_sentinel('sum-amounts')
	zero := cx.Node(cx.ScalarNode{
		value:     cx.ScalarValue(i64(0))
		data_type: cx.ScalarType.int_type
	})
	{
		fo := journal_stdlib_builtin_env('journal-fold', [jo, fv, zero], mut env) or {
			panic('fold: ${err}')
		}
		fx := journal_stdlib_builtin_env('journal-fold', [jx, fv, zero], mut env) or {
			panic('fold: ${err}')
		}
		fg := journal_stdlib_builtin_env('journal-fold', [jg, fv, zero], mut env) or {
			panic('fold: ${err}')
		}
		assert render_canonical(fo) == render_canonical(fx), 'fold parity xsp'
		assert render_canonical(fo) == render_canonical(fg), 'fold parity grpc'
	}
	{
		vx := journal_stdlib_builtin('journal-verify', [jx]) or { panic('verify: ${err}') }
		vg := journal_stdlib_builtin('journal-verify', [jg]) or { panic('verify: ${err}') }
		assert render_canonical(vx) == render_canonical(vg), 'verify finding identity across wires'
		assert sw_attr(vx as cx.Element, 'valid') == 'true'
	}
	// S6.4 over both wires: snapshot signs CLIENT-side on the gRPC handle; the
	// default signer= is the handle identity (rb.did — the same slot both
	// wires fill); verification rides the pushdown verb on XSP and the
	// wire-read local check on gRPC — ONE finding, both paths.
	cseed := []u8{len: 32, init: 0x05}
	cdid := did_key_from_seed(cseed) or { panic('cdid: ${err}') }
	mut snap := cx.Node(cx.Element{})
	{
		sopts := cx.Node(cx.Element{
			name:  code.map_marker_name
			items: [session_kv('signing-key', g13_str(cseed.hex()))]
		})
		sn := journal_stdlib_builtin_env('journal-snapshot', [jg, fv, zero, sopts], mut env) or {
			panic('snapshot: ${err}')
		}
		assert !is_err_value(sn), 'snapshot: ${render_canonical(sn)}'
		assert sw_attr(sn as cx.Element, 'signer') == cdid, 'default signer= on the gRPC handle: ${render_canonical(sn)}'
		snap = sn
	}
	{
		rx := journal_stdlib_builtin('journal-snapshot-verify', [jx, snap]) or {
			panic('sv x: ${err}')
		}
		rg := journal_stdlib_builtin('journal-snapshot-verify', [jg, snap]) or {
			panic('sv g: ${err}')
		}
		assert sw_attr(rx as cx.Element, 'valid') == 'true', 'pushdown verify: ${render_canonical(rx)}'
		assert render_canonical(rx) == render_canonical(rg), 'snapshot-verify finding identity (pushdown ≡ wire-read local): ${render_canonical(rx)} vs ${render_canonical(rg)}'
	}
	{
		// forged signer over both wires — identical :signature-invalid finding.
		fdid := did_key_from_seed([]u8{len: 32, init: 0x07}) or { panic('fdid: ${err}') }
		fopts := cx.Node(cx.Element{
			name:  code.map_marker_name
			items: [
				session_kv('signing-key', g13_str(cseed.hex())),
				session_kv('signer', g13_str(fdid)),
			]
		})
		fsn := journal_stdlib_builtin_env('journal-snapshot', [jx, fv, zero, fopts], mut env) or {
			panic('fsn: ${err}')
		}
		rx := journal_stdlib_builtin('journal-snapshot-verify', [jx, fsn]) or {
			panic('fsv x: ${err}')
		}
		rg := journal_stdlib_builtin('journal-snapshot-verify', [jg, fsn]) or {
			panic('fsv g: ${err}')
		}
		assert sw_attr(rx as cx.Element, 'reason') == ':signature-invalid', 'forged: ${render_canonical(rx)}'
		assert render_canonical(rx) == render_canonical(rg), 'forged-signer finding identity across wires'
	}
	jrn_close([jx]) or {}
	jrn_close([jg]) or {}
	jrn_close([jo]) or {}
}

// ── family 5: the admin plane (Reload — #718 item 2) + advert honesty (item 3) ──
fn test_g13_admin_and_advert_parity() {
	_, hx, hg, mut proc, tmp, cport := g13_boot('adm')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	{
		sx := store_stdlib_builtin_inner('store-status', [hx]) or { panic('status: ${err}') }
		sg := store_stdlib_builtin_inner('store-status', [hg]) or { panic('status: ${err}') }
		assert !is_err_value(sx) && !is_err_value(sg), 'status: ${render_canonical(sx)} / ${render_canonical(sg)}'
		assert (sx as cx.Element).name == (sg as cx.Element).name, 'status shape parity'
	}
	{
		// config-reload of the UNCHANGED config is deterministic
		// (applied=false, gen unmoved) — byte-identical across wires.
		rx := store_stdlib_builtin_inner('store-config-reload', [hx]) or {
			panic('reload: ${err}')
		}
		rg := store_stdlib_builtin_inner('store-config-reload', [hg]) or {
			panic('reload: ${err}')
		}
		assert !is_err_value(rx) && !is_err_value(rg), 'reload: ${render_canonical(rx)} / ${render_canonical(rg)}'
		assert render_canonical(rx) == render_canonical(rg), 'reload parity (Reload — the #718 item-2 lane): ${render_canonical(rx)} vs ${render_canonical(rg)}'
	}
	{
		// #718 item 3: the per-store capabilities advert claims ONLY what the
		// daemon does — no compression lane exists, so "none" is the whole set.
		r := http.get('http://127.0.0.1:${cport}/cx-store/v1/main/capabilities') or {
			panic('capabilities: ${err}')
		}
		assert r.status_code == 200
		assert r.body.contains('[compressions [supported "none"] [default "none"]]'), 'advert honesty: ${r.body}'
		assert !r.body.contains('"zst"'), 'advert must not claim unimplemented compression: ${r.body}'
	}
}

// ── family 5 (stream-2 W6, L99): quoted planar query parity ──────────────────
// The SAME quoted planar comprehension executes over the embedded oracle and
// both wire listeners (comp= on the XSP query op; the comp field on the gRPC
// Query rpc) and yields the byte-identical relation — the comprehension's OWN
// rows carry no store-URL provenance, so the comparator is direct. The wire
// membership deny (typed CXER0120 riding the error frame) is pinned on both
// listeners.
fn g13_quoted(src string) cx.Node {
	return cx.Element{
		name:  'cx:expr'
		items: [cx.Node(g13_str(src))]
	}
}

fn g13_planar_query(h cx.Node, src string) cx.Node {
	mut env := code.new_env()
	return store_query_planar([h, g13_quoted(src)], mut env)
}

fn test_g13_planar_query_parity() {
	oracle, hx, hg, mut proc, tmp, _ := g13_boot('plq')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	// per-entity roots (document-node anchoring, #768) — the planar scan shape.
	docs := ['[order [line qty=2 price=10] [customer region=east]]',
		'[order [line qty=4 price=25] [customer region=east]]',
		'[order [line qty=1 price=12] [customer region=west]]']
	for d in docs {
		_ := g13_op1(oracle, 'store-put-doc-text', d)
		x := g13_op1(hx, 'store-put-doc-text', d)
		assert !is_err_value(x), 'seed: ${render_canonical(x)}'
	}
	src := '[?for [in \$o [\$store:source \$srv "//order"]] [in \$l \$o/line]
		[= \$r [* \$l@qty \$l@price]]
		[group-by \$o/customer/@region]
		[yield [row region=\$key revenue=[\$sum \$group/r]]]]'
	{
		oq := g13_planar_query(oracle, src)
		xq := g13_planar_query(hx, src)
		gq := g13_planar_query(hg, src)
		assert !is_err_value(oq), 'oracle planar: ${render_canonical(oq)}'
		assert !is_err_value(xq), 'xsp planar: ${render_canonical(xq)}'
		assert !is_err_value(gq), 'grpc planar: ${render_canonical(gq)}'
		os_ := g13_rendered_set(oq)
		xs := g13_rendered_set(xq)
		gs := g13_rendered_set(gq)
		assert os_.len == 2, 'oracle planar relation: ${render_canonical(oq)}'
		assert xs == os_, 'planar relation parity xsp: ${xs} vs ${os_}'
		assert gs == os_, 'planar relation parity grpc: ${gs} vs ${os_}'
	}
	{
		// the wire membership deny: the ambient generator refuses typed
		// CXER0120 on BOTH listeners (the error frame carries the code
		// verbatim — error identity, cxstore-grpc.md §3).
		bad := '[?for [user] [yield 1]]'
		xq := g13_planar_query(hx, bad)
		gq := g13_planar_query(hg, bad)
		assert is_err_value(xq), 'xsp must refuse the non-member: ${render_canonical(xq)}'
		assert is_err_value(gq), 'grpc must refuse the non-member: ${render_canonical(gq)}'
		assert render_canonical(xq).contains('CXER0120'), 'xsp deny code: ${render_canonical(xq)}'
		assert render_canonical(gq).contains('CXER0120'), 'grpc deny code: ${render_canonical(gq)}'
	}
	{
		// scalar rows survive the [item …] wire envelope losslessly.
		ssrc := '[?for [in \$o [\$store:source \$srv "//order"]] [yield \$o/customer/@region]]'
		oq := g13_planar_query(oracle, ssrc)
		xq := g13_planar_query(hx, ssrc)
		gq := g13_planar_query(hg, ssrc)
		os_ := g13_rendered_set(oq)
		assert os_.len == 3, 'oracle scalar rows: ${render_canonical(oq)}'
		assert g13_rendered_set(xq) == os_, 'scalar-row parity xsp'
		assert g13_rendered_set(gq) == os_, 'scalar-row parity grpc'
	}
}

// ── source: vcx/platform/store_xsp_journal_test.v ──
// store_xsp_journal_test.v — the S6 §4.3 journal pushdown family, live over a
// daemon (RULED: F3+F4+F5+R1.1(b)). The correctness ORACLE is the local
// embedded engine per R4.4(a-revised): the same journal folded CLIENT-EVAL
// (the shipped v1 object-wire carriage) and PUSHED-DOWN (the wire verbs) must
// give BYTE-IDENTICAL state.
//
// The coverage is split across three focused test fns — parity, reads, and
// refusals — each booting its own daemon. This is deliberate: a single
// mega-function accumulating every lane's owned cx.Node locals tripped a V
// autofree double-free of an aliased element tree at function-scope exit
// (ASAN under -gc none was clean, and VGC_NEXT_GC_MB pinning did not help —
// it is the compile-time free path, not the tracing collector). Focused fns
// keep each scope's live-local set small and the free set unaliased.

const sxjt_fold_src = '[?def sum-amounts (\$acc \$e) [+ \$acc \$e//amount]]'

// sxjt_boot brings up one xsp daemon (pushdown budget steps=4000 — the F4
// refusal fixture) and returns (remote-backend-carrying open handle, proc,
// tmp). The caller defers signal_kill + rmdir.
fn sxjt_boot(tag string) (cx.Node, &os.Process, string) {
	return sxjt_boot_as(tag, '', '')
}

// sxjt_boot_as is sxjt_boot with a MUTUAL client identity (open-opts
// xsp-did + xsp-seed-env) — the S6.4 porcelain's default signer= stamping
// is the handle identity, so it needs a non-floor session to engage.
fn sxjt_boot_as(tag string, cdid string, cseed_env string) (cx.Node, &os.Process, string) {
	port := 37000 + (os.getpid() % 900) * 2 + (tag.len % 5) * 2
	xport := port + 1
	tmp := os.join_path(os.temp_dir(), 'cx-xsp-jrn-${tag}-${os.getpid()}')
	os.rmdir_all(tmp) or {}
	os.mkdir_all(tmp) or { panic('mkdir: ${err}') }
	cfg := '[cxstore-service
  [bind addr="127.0.0.1:${port}"]
  [stores [store name="main" url="file://${tmp}/store"]]
  [xsp enabled=true addr="127.0.0.1:${xport}"
    [identity did="did:key:z6MkiaMbhXHNA4eJVCCj8dbzKzTgYDKf6crKgHVHid1F1WCT" seed-env="CX_SXJT_SEED"]
    [policy mode=floor floor="guest"]
    [limits [pushdown steps=4000 memory-mb=64]]]
  [workers query-pool=2]]'
	cfg_path := os.join_path(tmp, 'svc.cx')
	os.write_file(cfg_path, cfg) or { panic('cfg: ${err}') }
	os.setenv('CX_SXJT_SEED', '4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb',
		true)
	cxbin := testenv.cx_bin()
	mut proc := os.new_process('/bin/sh')
	proc.set_args(['-c',
		'exec "${cxbin}" store-serve --config "${cfg_path}" --exit-on-stdin-eof --allow-read --allow-write --allow-net=127.0.0.1:${port} --allow-net=127.0.0.1:${xport} --allow-env >"${tmp}/daemon.log" 2>&1'])
	proc.set_redirect_stdio()
	proc.run()
	mut up := false
	for _ in 0 .. 100 {
		time.sleep(100 * time.millisecond)
		r0 := http.get('http://127.0.0.1:${port}/cx-store/v1/ready') or { continue }
		if r0.status_code == 200 && r0.body.contains('[accepting true]') {
			up = true
			break
		}
	}
	if !up {
		proc.signal_kill()
		panic('daemon never came up: ${os.read_file(os.join_path(tmp, 'daemon.log')) or { '' }}')
	}
	caps_set_all()
	url_node := cx.Node(cx.ScalarNode{
		value:     cx.ScalarValue('cx-store+xsp://127.0.0.1:${xport}/')
		data_type: cx.ScalarType.string_type
	})
	h := if cdid != '' {
		oopts := cx.Node(cx.Element{
			name:  code.map_marker_name
			items: [
				session_kv('xsp-did', sxjt_str(cdid)),
				session_kv('xsp-seed-env', sxjt_str(cseed_env)),
			]
		})
		store_stdlib_builtin_inner('store-open-opts', [url_node, oopts]) or { panic('open: ${err}') }
	} else {
		store_stdlib_builtin_inner('store-open', [url_node]) or { panic('open: ${err}') }
	}
	if is_err_value(h) {
		proc.signal_kill()
		panic('open: ${render_canonical(h)}')
	}
	return h, proc, tmp
}

fn sxjt_str(s string) cx.Node {
	return cx.ScalarNode{
		value:     cx.ScalarValue(s)
		data_type: cx.ScalarType.string_type
	}
}

fn sxjt_attribution() cx.Node {
	return cx.Element{
		name:  code.map_marker_name
		items: [
			cx.Node(cx.Element{
				name:  'actor'
				items: [sxjt_str('did:key:test-writer')]
			}),
			cx.Node(cx.Element{
				name:  'authority'
				items: [sxjt_str('operator')]
			}),
		]
	}
}

// sxjt_seed appends `n` amount events and returns the remote backend.
fn sxjt_seed(h cx.Node, n int) &RemoteBackend {
	mut msp := store_for_guard(h) or { panic('no guard') }
	amounts := [i64(5), 7, 11, 13, 17, 19, 23, 29]
	j := jrn_attach([h, sxjt_str('ledger')]) or { panic('jrn attach: ${err}') }
	if is_err_value(j) {
		panic('jrn attach: ${render_canonical(j)}')
	}
	for i in 0 .. n {
		ar := journal_stdlib_builtin('journal-append', [j,
			cx.Node(cx.Element{
				name:  'amount'
				items: [cx.Node(sxj_int(amounts[i]))]
			}), cx.Node(sxjt_attribution())]) or { panic('append: ${err}') }
		if is_err_value(ar) {
			panic('append: ${render_canonical(ar)}')
		}
	}
	jrn_close([j]) or {}
	return msp.remote
}

// sxjt_put_fn stores a def document as an opaque blob and returns its address.
fn sxjt_put_fn(h cx.Node, src string) string {
	r := store_stdlib_builtin_inner('store-put-blob', [h, sxjt_str(src)]) or {
		panic('put-blob: ${err}')
	}
	if is_err_value(r) {
		panic('put-blob: ${render_canonical(r)}')
	}
	return sw_scalar(r)
}

// ── the F1' blob pair over the wire + the parity property (§4.3) ────────────
fn test_store_xsp_journal_parity() {
	h, mut proc, tmp := sxjt_boot('par')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}

	// F1' blob round-trip byte-exact over the wire (the fn-doc transport)
	fnaddr := sxjt_put_fn(h, sxjt_fold_src)
	assert fnaddr.starts_with('sha2-256:'), 'blob key: ${fnaddr}'
	bgot := store_stdlib_builtin_inner('store-get-blob', [h, sxjt_str(fnaddr)]) or {
		panic('get-blob: ${err}')
	}
	assert !is_err_value(bgot) && sw_scalar(bgot) == sxjt_fold_src, 'remote blob must be byte-exact'

	rb := sxjt_seed(h, 6)
	init_hex := sxj_image(cx.Node(sxj_int(0)))
	entry_name, hash0 := code.cx_program_entry_computation_id(sxjt_fold_src, '') or {
		panic('claim: ${err}')
	}
	assert entry_name == 'sum-amounts'
	claim := 'computes-as:${hash0}'

	// the ORACLE: client-eval folds over the SAME journal (v1 path)
	mut oenv := code.new_env()
	oprog := cx.parse_program(sxjt_fold_src) or { panic('parse: ${err}') }
	code.eval(oprog.body, mut oenv) or { panic('oracle reg: ${err}') }
	ofv := code.mk_closure_sentinel('sum-amounts')
	jh := jrn_attach([h, sxjt_str('ledger')]) or { panic('reattach: ${err}') }
	of := journal_stdlib_builtin_env('journal-fold', [jh, ofv, cx.Node(sxj_int(0))], mut oenv) or {
		panic('oracle fold: ${err}')
	}
	oracle_full := sxj_image(of)
	oslice := journal_stdlib_builtin_env('journal-fold-slice', [jh, ofv, cx.Node(sxj_int(0)),
		cx.Node(sxj_int(2)), cx.Node(sxj_int(4))], mut oenv) or { panic('oracle slice: ${err}') }
	oracle_slice := sxj_image(oslice)
	orep := journal_stdlib_builtin_env('journal-fold-slice', [jh, ofv, cx.Node(sxj_int(0)),
		cx.Node(sxj_int(1)), cx.Node(sxj_int(3))], mut oenv) or { panic('oracle replay: ${err}') }
	oracle_replay := sxj_image(orep)
	jrn_close([jh]) or {}

	// PUSHED-DOWN ≡ CLIENT-EVAL, byte-identical
	{
		wr, wok := xcl_exchange(rb, 'journal-fold', '[journal-fold tenant="ledger" fn="${fnaddr}" claim="${claim}" [init::bytes 0x${init_hex}]]')
		assert wok && !is_err_value(wr), 'wire fold: ${render_canonical(wr)}'
		wr_e := wr as cx.Element
		assert wr_e.name == 'fold-result' && sw_attr(wr_e, 'to-seq') == '6', 'fold reply: ${render_canonical(wr)}'
		wstate := sx_bytes_child(wr_e, 'state') or { panic('no state') }
		assert wstate.hex() == oracle_full, 'fold parity: pushed-down MUST equal client-eval'
	}
	{
		rs, oks := xcl_exchange(rb, 'journal-fold-slice', '[journal-fold-slice tenant="ledger" from=2 to=4 fn="${fnaddr}" claim="${claim}" [init::bytes 0x${init_hex}]]')
		assert oks && !is_err_value(rs), 'wire fold-slice: ${render_canonical(rs)}'
		sstate := sx_bytes_child(rs as cx.Element, 'state') or { panic('no slice state') }
		assert sstate.hex() == oracle_slice, 'fold-slice parity'
	}
	{
		rr, okr := xcl_exchange(rb, 'journal-replay', '[journal-replay tenant="ledger" at-seq=3 fn="${fnaddr}" claim="${claim}" [init::bytes 0x${init_hex}]]')
		assert okr && !is_err_value(rr), 'wire replay: ${render_canonical(rr)}'
		rstate := sx_bytes_child(rr as cx.Element, 'state') or { panic('no replay state') }
		assert rstate.hex() == oracle_replay, 'replay at-seq parity'
	}
	{
		// dry-run: provisional entry rides back; NOTHING persists
		ev_hex := sxj_image(cx.Node(cx.Element{
			name:  'amount'
			items: [cx.Node(sxj_int(100))]
		}))
		attr_hex := sxj_image(sxjt_attribution())
		rd, okd := xcl_exchange(rb, 'journal-dry-run', '[journal-dry-run tenant="ledger" fn="${fnaddr}" claim="${claim}" [init::bytes 0x${init_hex}] [event::bytes 0x${ev_hex}] [attribution::bytes 0x${attr_hex}]]')
		assert okd && !is_err_value(rd), 'wire dry-run: ${render_canonical(rd)}'
		prov := sx_bytes_child(rd as cx.Element, 'provisional-entry') or { panic('no provisional') }
		pdoc := cx.bin_to_doc(prov) or { panic('provisional decode: ${err}') }
		assert sw_attr(pdoc.elements[0] as cx.Element, 'seq') == '7', 'provisional seq'
		r7, ok7 := xcl_exchange(rb, 'journal-read', '[journal-read tenant="ledger" seq=7]')
		assert ok7 && sw_attr(r7 as cx.Element, 'present') == 'false', 'dry-run must persist NOTHING'
	}
}

// ── read / stream / verify lanes ────────────────────────────────────────────
fn test_store_xsp_journal_reads() {
	h, mut proc, tmp := sxjt_boot('rd')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	rb := sxjt_seed(h, 6)

	{
		r1, ok1 := xcl_exchange(rb, 'journal-read', '[journal-read tenant="ledger" seq=1]')
		assert ok1 && sw_attr(r1 as cx.Element, 'present') == 'true', 'read 1 present'
		body1 := sx_bytes_child(r1 as cx.Element, 'body') or { panic('no body') }
		d1 := cx.bin_to_doc(body1) or { panic('decode: ${err}') }
		assert sw_attr(d1.elements[0] as cx.Element, 'seq') == '1', 'entry 1 seq'
	}
	{
		// absence channel: seq past head
		r9, ok9 := xcl_exchange(rb, 'journal-read', '[journal-read tenant="ledger" seq=99]')
		assert ok9 && sw_attr(r9 as cx.Element, 'present') == 'false', 'out-of-range = absence'
	}
	// #749 RE-VERIFICATION: the COLLECTING client restored — a held
	// []cx.Element from xcl_stream previously crashed the -gc e free
	// walk at scope exit (cx__Element_free); the cx-home/v#2 nil-guard
	// (reference fields with `unsafe { nil }` defaults) is the ruled
	// root-cause suspect, and this held slice is the live witness. The
	// count-only dodge helper (xcl_stream_count) retired with it.
	{
		sl, serr, oksl := xcl_stream(rb, 'journal-slice', '[journal-slice tenant="ledger" from=2 to=4]')
		assert oksl && !is_err_value(serr) && sl.len == 3, 'slice 3, got ${sl.len}'
		// Content probe through the §4.3 event imaging: each frame is
		// [entry [body::bytes …]] — decode the first body and check seq.
		assert sl[0].name == 'entry', 'event frames are entries'
		b0 := sx_bytes_child(sl[0], 'body') or { panic('no body on the first slice entry') }
		d0 := cx.bin_to_doc(b0) or { panic('decode: ${err}') }
		assert sw_attr(d0.elements[0] as cx.Element, 'seq') == '2', 'slice starts at seq 2'
	}
	{
		q, qerr, okq := xcl_stream(rb, 'journal-query', '[journal-query tenant="ledger" path="//amount"]')
		assert okq && !is_err_value(qerr) && q.len == 6, 'query 6, got ${q.len}'
	}
	{
		n, nerr, okn := xcl_stream(rb, 'journal-since', '[journal-since tenant="ledger" from=5]')
		assert okn && !is_err_value(nerr) && n.len == 2, 'since 5 → 2, got ${n.len}'
	}
	{
		rv, okv := xcl_exchange(rb, 'journal-verify', '[journal-verify tenant="ledger"]')
		assert okv && !is_err_value(rv), 'verify: ${render_canonical(rv)}'
		rv_e := rv as cx.Element
		assert rv_e.name == 'verification' && sw_attr(rv_e, 'valid') == 'true', 'chain verifies'
	}
	{
		rvs, okvs := xcl_exchange(rb, 'journal-verify-slice', '[journal-verify-slice tenant="ledger" from=2 to=5]')
		assert okvs && !is_err_value(rvs) && sw_attr(rvs as cx.Element, 'valid') == 'true', 'slice verifies'
	}
	{
		junk_hex := sxj_image(cx.Node(cx.Element{
			name: 'snapshot'
		}))
		rsv, oksv := xcl_exchange(rb, 'journal-snapshot-verify', '[journal-snapshot-verify tenant="ledger" [snapshot::bytes 0x${junk_hex}]]')
		assert oksv, 'snapshot-verify answers'
		mut refused := is_err_value(rsv)
		if !refused && rsv is cx.Element {
			refused = sw_attr(rsv as cx.Element, 'valid') == 'false'
		}
		assert refused, 'junk snapshot never verifies: ${render_canonical(rsv)}'
	}
}

// ── the refusal lanes: claim / budget / purity / carriage ───────────────────
fn test_store_xsp_journal_refusals() {
	h, mut proc, tmp := sxjt_boot('ref')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	rb := sxjt_seed(h, 3)
	fnaddr := sxjt_put_fn(h, sxjt_fold_src)
	init_hex := sxj_image(cx.Node(sxj_int(0)))
	_, hash0 := code.cx_program_entry_computation_id(sxjt_fold_src, '') or { panic('claim: ${err}') }
	claim := 'computes-as:${hash0}'

	{
		// CXER5023: claim mismatch (tamper / version skew)
		rc, okc := xcl_exchange(rb, 'journal-fold', '[journal-fold tenant="ledger" fn="${fnaddr}" claim="computes-as:sha2-256:${'0'.repeat(64)}" [init::bytes 0x${init_hex}]]')
		assert okc && is_err_value(rc) && sw_attr(rc as cx.Element, 'code') == 'cx-err:CXER5023', 'claim mismatch: ${render_canonical(rc)}'
	}
	{
		// CXER5024: the F4 budget refusal (steps=4000 configured)
		burn := '[?def burn (\$acc \$e) [\$count [?for [in \$i [\$range 1 100000]] [yield \$i]]]]'
		baddr := sxjt_put_fn(h, burn)
		_, bhash := code.cx_program_entry_computation_id(burn, '') or { panic('burn claim: ${err}') }
		rbg, okb := xcl_exchange(rb, 'journal-fold', '[journal-fold tenant="ledger" fn="${baddr}" claim="computes-as:${bhash}" [init::bytes 0x${init_hex}]]')
		assert okb && is_err_value(rbg), 'budget must refuse'
		rbg_e := rbg as cx.Element
		assert sw_attr(rbg_e, 'code') == 'cx-err:CXER5024' && sw_attr(rbg_e, 'conjunct') == ':steps', 'budget: ${render_canonical(rbg)}'
	}
	{
		// CXER4611 VERBATIM: server-side fold purity, identical to local. A
		// DECLARED-impure def registers (a pure def calling an impure builtin
		// is a definition-time CXER0233 that never reaches the fold); the
		// journal's own fold-purity gate then rejects → CXER4611.
		impure := '[?def leak impure (\$acc \$e) [\$random:int 1 2]]'
		iaddr := sxjt_put_fn(h, impure)
		_, ihash := code.cx_program_entry_computation_id(impure, '') or { panic('i claim: ${err}') }
		ri, oki := xcl_exchange(rb, 'journal-fold', '[journal-fold tenant="ledger" fn="${iaddr}" claim="computes-as:${ihash}" [init::bytes 0x${init_hex}]]')
		assert oki && is_err_value(ri) && sw_attr(ri as cx.Element, 'code') == 'cx-err:CXER4611', 'impure verbatim: ${render_canonical(ri)}'
	}
	{
		// CXER5025: defs-only carriage
		naddr := sxjt_put_fn(h, '[+ 1 2]')
		rn, okn := xcl_exchange(rb, 'journal-fold', '[journal-fold tenant="ledger" fn="${naddr}" claim="${claim}" [init::bytes 0x${init_hex}]]')
		assert okn && is_err_value(rn) && sw_attr(rn as cx.Element, 'code') == 'cx-err:CXER5025', 'defs-only: ${render_canonical(rn)}'
	}
	{
		// CXER5025: entry= names no def
		rne, okne := xcl_exchange(rb, 'journal-fold', '[journal-fold tenant="ledger" fn="${fnaddr}" claim="${claim}" entry="nope" [init::bytes 0x${init_hex}]]')
		assert okne && is_err_value(rne) && sw_attr(rne as cx.Element, 'code') == 'cx-err:CXER5025', 'bad entry: ${render_canonical(rne)}'
	}
}

// ── the S6.4 snapshot porcelain over the wire (F5b custody + signer hint) ───
// `snapshot` is CLIENT-EVAL: it folds the wire-read chain and signs LOCALLY
// (the key never travels); with a mutual session, the default signer= hint is
// the handle's own identity (engaged only when it IS the signing key's did).
// `snapshot-verify` rides the pushdown journal-snapshot-verify — one exchange,
// the daemon checking anchor+signature against its AUTHORITATIVE chain, with
// the S6.4 signer-hint key resolution running daemon-side (shared check).
fn test_store_xsp_journal_snapshot_porcelain() {
	cseed := []u8{len: 32, init: 0x03}
	cdid := did_key_from_seed(cseed) or { panic('cdid: ${err}') }
	os.setenv('CX_SXJT_CSEED', cseed.hex(), true)
	h, mut proc, tmp := sxjt_boot_as('snap', cdid, 'CX_SXJT_CSEED')
	defer {
		proc.signal_kill()
		os.rmdir_all(tmp) or {}
	}
	sxjt_seed(h, 4)

	mut env := code.new_env()
	prog := cx.parse_program('[?def sum1 (\$a \$e) [+ \$a 1]]') or { panic('parse: ${err}') }
	code.eval(prog.body, mut env) or { panic('reg: ${err}') }
	fv := code.mk_closure_sentinel('sum1')
	j := jrn_attach([h, sxjt_str('ledger')]) or { panic('attach: ${err}') }
	{
		// self-signed default: signer= stamps the session identity because the
		// signing seed IS the session seed (did equality gate).
		sopts := cx.Node(cx.Element{
			name:  code.map_marker_name
			items: [session_kv('signing-key', sxjt_str(cseed.hex()))]
		})
		sn := journal_stdlib_builtin_env('journal-snapshot', [j, fv, cx.Node(sxj_int(0)),
			sopts], mut env) or { panic('snapshot: ${err}') }
		assert !is_err_value(sn), 'snapshot: ${render_canonical(sn)}'
		sne := sn as cx.Element
		assert sw_attr(sne, 'signer') == cdid, 'default signer= must be the session identity: ${render_canonical(sn)}'
		assert sw_attr(sne, 'sig-algo') == 'ed25519' && sw_attr(sne, 'at-seq') == '4', 'snapshot shape: ${render_canonical(sn)}'
		rv := journal_stdlib_builtin('journal-snapshot-verify', [j, sn]) or {
			panic('verify: ${err}')
		}
		assert !is_err_value(rv), 'verify: ${render_canonical(rv)}'
		assert sw_attr(rv as cx.Element, 'valid') == 'true', 'self-signed pushdown verify: ${render_canonical(rv)}'
	}
	{
		// forged signer: an explicit opts.signer overrides the default; the
		// daemon resolves the verify key FROM it and the signature dies —
		// :signature-invalid VERBATIM across the wire (a finding, not a fault).
		fdid := did_key_from_seed([]u8{len: 32, init: 0x04}) or { panic('fdid: ${err}') }
		fopts := cx.Node(cx.Element{
			name:  code.map_marker_name
			items: [
				session_kv('signing-key', sxjt_str(cseed.hex())),
				session_kv('signer', sxjt_str(fdid)),
			]
		})
		fsn := journal_stdlib_builtin_env('journal-snapshot', [j, fv, cx.Node(sxj_int(0)),
			fopts], mut env) or { panic('forged snapshot: ${err}') }
		assert !is_err_value(fsn), 'forged snapshot: ${render_canonical(fsn)}'
		rf := journal_stdlib_builtin('journal-snapshot-verify', [j, fsn]) or {
			panic('fverify: ${err}')
		}
		rf_e := rf as cx.Element
		assert sw_attr(rf_e, 'valid') == 'false' && sw_attr(rf_e, 'reason') == ':signature-invalid', 'forged signer: ${render_canonical(rf)}'
	}
	jrn_close([j]) or {}
}
