// platform_store_core_umbrella_test.v -- GENERATED by scripts/consolidate_tests.sh (#700):
// the per-area test-binary umbrella. 15 source files merged verbatim (byte-identical
// helper dedupe only; the V compiler is the name-collision oracle). Fewer test
// files = fewer whole-module-graph compiles (V compilation was 99% of the gate).
// Regenerate: scripts/consolidate_tests.sh gen platform_store_core
// Manifest:   scripts/consolidation/platform_store_core.files

module platform

import code { caps_set_all, caps_set_empty, is_err_value, render_canonical }
import cx
import cxstore
import hash.crc32
import os
import sync

// ── source: vcx/platform/store_anchor_identity_test.v ──
// Tier-1 anchor/alias/merge expansion (#82, spec/core/canonical.md §2.8) seen
// through a LIVE [$store] consumer: the store keys docs on the strict canonical
// hash, so two documents that differ only in data-sharing (inline vs
// anchored/merged) get the SAME store-key and dedup to one logical doc. This is
// the store-level proof that §2.8 resolution is on the store's identity path.

fn sa_put_text(handle cx.Node, text string) string {
	r := store_stdlib_builtin_inner('store-put-doc-text', [handle, store_str(text)]) or {
		panic('put-doc-text: ${err.msg()}')
	}
	if is_err_value(r) {
		panic('put-doc-text returned error: ${sw_err_code(r)}')
	}
	return sw_scalar(r)
}

fn test_store_alias_equivalent_to_inline() {
	handle := store_open_impl('mem://anchor-id', '', '', false, true, map[string]string{})
	aliased := '[root [defaults &def timeout=30 retries=3] [*def]]'
	inline := '[root [defaults timeout=30 retries=3] [defaults timeout=30 retries=3]]'

	h_alias := sa_put_text(handle, aliased)
	h_inline := sa_put_text(handle, inline)
	assert h_alias == h_inline, 'an aliased doc must share the store-key of its inlined form (${h_alias} vs ${h_inline})'

	// The second put was a content-addressed no-op: exactly one logical doc.
	mut ms, _, ok := store_get_open(handle)
	assert ok, 'store handle must resolve'
	assert ms.doc_order.len == 1, 'alias-equivalent puts must dedup to one doc, got ${ms.doc_order.len}'
}

fn test_store_merge_equivalent_to_inline() {
	handle := store_open_impl('mem://anchor-id-merge', '', '', false, true, map[string]string{})
	merged := '[root [defaults &def timeout=30 retries=3] [production *def host=prod retries=5]]'
	inline := '[root [defaults timeout=30 retries=3] [production timeout=30 retries=5 host=prod]]'

	assert sa_put_text(handle, merged) == sa_put_text(handle, inline), 'a merged doc must share the store-key of its inlined form'
}

fn test_store_anchor_doc_round_trips() {
	handle := store_open_impl('mem://anchor-rt', '', '', false, true, map[string]string{})
	h := sa_put_text(handle, '[root [defaults &def timeout=30] [*def]]')
	r := store_stdlib_builtin_inner('store-get-doc-text', [handle, store_str(h)]) or {
		panic('get-doc-text: ${err.msg()}')
	}
	assert r is cx.ScalarNode, 'stored anchored doc must round-trip'
	got := sw_scalar(r)
	// The reconstructed doc is the resolved (anchor-free) form.
	assert !got.contains('&def'), 'round-trip must be the resolved form: ${got}'
	assert !got.contains('[*def]'), 'round-trip must be the resolved form: ${got}'
}

// ── source: vcx/platform/store_blob_surface_test.v ──
// F1' blob-surface battery (RULED 2026-08-08): the OPAQUE-document pair —
// identity = hash of the RAW bytes, byte-exact round-trip, verify-on-read.
// Covers the lanes the capability-free corpus matrix cannot reach: file://
// persistence across reopen on BOTH models (pack manifest 'B' records +
// flat-index 'B' records), migrate carrying blobs kind-preserving, and the
// read-boundary integrity check refusing a corrupted flat record.

const bs_greet = "[?def greet (\$name) [str-format 'hello, {}' \$name]]"

fn bs_root(tag string) string {
	return os.join_path(os.temp_dir(), 'cx-blob-surface-${os.getpid()}-${tag}')
}

fn bs_open(url string) cx.Node {
	caps_set_all() // file substrates gate on the write capability
	h := store_open_impl(url, '', '', false, true, map[string]string{})
	if is_err_value(h) {
		panic('open ${url} failed: ${render_canonical(h)}')
	}
	return h
}

fn bs_str_of(n cx.Node) string {
	if n is cx.ScalarNode {
		return cx.scalar_value_str_public(n.value)
	}
	if n is cx.TextNode {
		return n.value
	}
	return ''
}

// pack (subtree) model: blob survives close/reopen via the 'B' manifest
// record, byte-exact, and the load path rehash-verifies.
fn test_blob_persists_pack_model() {
	root := bs_root('pack')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	h := bs_open('file://${root}')
	put := store_stdlib_builtin_inner('store-put-blob', [h, store_str(bs_greet)]) or {
		panic('put: ${err}')
	}
	key := bs_str_of(put)
	assert key.starts_with('sha2-256:'), 'blob key shape: ${render_canonical(put)}'
	store_stdlib_builtin_inner('store-close', [h]) or { panic('close: ${err}') }

	h2 := bs_open('file://${root}')
	got := store_stdlib_builtin_inner('store-get-blob', [h2, store_str(key)]) or {
		panic('get after reopen: ${err}')
	}
	assert bs_str_of(got) == bs_greet, 'pack reopen not byte-exact: ${bs_str_of(got)}'
}

// flat (document) model: same contract via the flat-index 'B' record.
fn test_blob_persists_flat_model() {
	root := bs_root('flat')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	h := bs_open('document+file://${root}')
	put := store_stdlib_builtin_inner('store-put-blob', [h, store_str(bs_greet)]) or {
		panic('put: ${err}')
	}
	key := bs_str_of(put)
	store_stdlib_builtin_inner('store-close', [h]) or { panic('close: ${err}') }

	h2 := bs_open('document+file://${root}')
	got := store_stdlib_builtin_inner('store-get-blob', [h2, store_str(key)]) or {
		panic('get after reopen: ${err}')
	}
	assert bs_str_of(got) == bs_greet, 'flat reopen not byte-exact: ${bs_str_of(got)}'
}

// migrate carries blobs kind-preserving: same key on the destination,
// byte-exact bytes, structured docs unaffected alongside.
fn test_blob_migrate_kind_preserving() {
	src := bs_open('mem://blob-mig-src')
	put := store_stdlib_builtin_inner('store-put-blob', [src, store_str(bs_greet)]) or {
		panic('put: ${err}')
	}
	key := bs_str_of(put)
	store_stdlib_builtin_inner('store-put-doc-text', [src, store_str('[order id=1 total=99.5]')]) or {
		panic('put doc: ${err}')
	}
	dst := bs_open('mem://blob-mig-dst')
	store_stdlib_builtin_inner('store-migrate', [src, dst]) or { panic('migrate: ${err}') }
	got := store_stdlib_builtin_inner('store-get-blob', [dst, store_str(key)]) or {
		panic('get on dest: ${err}')
	}
	assert bs_str_of(got) == bs_greet, 'migrated blob not byte-exact'
}

// the read boundary REFUSES a corrupted blob: flip a byte in the flat index
// payload and the next get must be an integrity error, never silent bytes.
fn test_blob_read_verify_refuses_corruption() {
	root := bs_root('corrupt')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	h := bs_open('document+file://${root}')
	put := store_stdlib_builtin_inner('store-put-blob', [h, store_str(bs_greet)]) or {
		panic('put: ${err}')
	}
	key := bs_str_of(put)
	store_stdlib_builtin_inner('store-close', [h]) or { panic('close: ${err}') }

	// corrupt the stored payload on disk (flip 'greet' -> 'gr33t' keeps length)
	idx := os.join_path(root, 'store.cxstore')
	mut files := []string{}
	if os.exists(idx) {
		files << idx
	} else {
		for e in os.ls(root) or { []string{} } {
			files << os.join_path(root, e)
		}
	}
	mut corrupted := false
	for f in files {
		raw := os.read_file(f) or { continue }
		if raw.contains('greet') {
			os.write_file(f, raw.replace('greet', 'gr33t')) or { continue }
			corrupted = true
		}
	}
	assert corrupted, 'test setup: found no on-disk payload to corrupt in ${files}'

	h2 := bs_open('document+file://${root}')
	if got := store_stdlib_builtin_inner('store-get-blob', [h2, store_str(key)]) {
		// an err VALUE is the expected refusal shape
		rendered := render_canonical(got)
		assert rendered.contains('CXER1120'), 'corrupted blob must refuse CXER1120, got: ${rendered}'
	} else {
		// a thrown error is also a loud refusal — acceptable
		assert true
	}
}

// ── source: vcx/platform/store_cluster_residuals_test.v ──
// store_cluster_residuals_test.v — the CODE residuals of the W0 spec-cluster
// issues #203/#204/#205 (the spec halves graduated in #225). #204 unknown-store
// wire code, #205 subtree+ reject / unsupported-param / compression fail-closed.

fn wr_req(method string, path string) cx.Element {
	// S3 (G3a): data ops reach the daemon ONLY as the gRPC edge's synthesized
	// pipeline="profile" requests — a raw HTTP data op is bootstrap-404. This
	// harness drives the data path, so it carries the pipeline attr; the
	// store-name RESOLUTION (unknown → CXER1710) is what it pins.
	return cx.Element{
		name:  'request'
		attrs: [
			cx.Attribute{
				name:  'method'
				value: cx.ScalarValue(method)
			},
			cx.Attribute{
				name:  'path'
				value: cx.ScalarValue(path)
			},
			cx.Attribute{
				name:  'pipeline'
				value: cx.ScalarValue('profile')
			},
		]
		items: [
			cx.Node(cx.Element{
				name:  'headers'
				items: []
			}),
		]
	}
}

fn wr_err_code(n cx.Node) string {
	if n is cx.Element && n.name == 'err' {
		for a in n.attrs {
			if a.name == 'code' {
				return cx.scalar_value_str_public(a.value)
			}
		}
	}
	return ''
}

fn wr_body(n cx.Node) string {
	if n is cx.Element {
		for it in n.items {
			if it is cx.Element && it.name == 'body' {
				for b in it.items {
					if b is cx.ScalarNode {
						return sw_scalar(b)
					}
				}
			}
		}
	}
	return ''
}

fn wr_status(n cx.Node) int {
	if n is cx.Element {
		for a in n.attrs {
			if a.name == 'status' {
				return cx.scalar_value_str_public(a.value).int()
			}
		}
	}
	return 0
}

// ── #204: data-op on an unknown store-name → 404 CXER1710 (not std-lib 1121) ──

fn test_dataop_unknown_store_1710() {
	mut s := new_service_state()
	s.mark_ready()
	caps_set_all()
	ctx := ServeContext{
		mounts: {
			'docs': store_open_impl('mem://wr-204', '', '', false, true, map[string]string{})
		}
	}
	resp := svc_handle_request(wr_req("POST", '/cx-store/v1/nope/list'),
		mut s, ctx)
	assert wr_status(resp) == 404, 'unknown-store data op → 404'
	assert wr_body(resp).contains('CXER1710'), 'unknown-store wire code is CXER1710 (#204, not std-lib 1121): ${wr_body(resp)}'
	assert !wr_body(resp).contains('CXER1121'), 'std-lib CXER1121 must not ride the wire'
}

// ── #205.5: subtree+ is never written → hard error ────────────────────────────

fn test_subtree_prefix_rejected() {
	caps_set_all()
	r := store_open_impl('subtree+mem://wr-205-sub', '', '', false, true, map[string]string{})
	assert wr_err_code(r) == 'cx-err:CXER1100', 'subtree+ must be rejected (#205.5), got ${wr_err_code(r)}'
}

// ── #205.4: unsupported URI query param → hard error (not silently ignored) ───

fn test_unsupported_query_param_rejected() {
	caps_set_all()
	r := store_open_impl('mem://wr-205-cache?cache=file:///tmp/c', '', '', false, true,
		map[string]string{})
	assert wr_err_code(r) == 'cx-err:CXER1100', '?cache= (unimplemented) must be rejected (#205.4), got ${wr_err_code(r)}'
	// recognized params still work
	ok := store_open_impl('mem://wr-205-enc?encoding=cxbin', '', '', false, true, map[string]string{})
	assert wr_err_code(ok) == '', 'recognized ?encoding= must open: ${wr_err_code(ok)}'
}

// ── #205.2: non-none compression fail-closed on a durable substrate ───────────

fn test_compression_fail_closed() {
	caps_set_all()
	root := '/tmp/wr-205-comp-${cx.cx_text_hash('c') or { 'x' }[..8]}'
	r := store_open_impl('file://${root}', 'zst', '', false, true, map[string]string{})
	assert wr_err_code(r) == 'cx-err:CXER1100', 'non-none compression on file:// must fail-closed (#205.2), got ${wr_err_code(r)}'
	// none (and unset) open fine
	ok := store_open_impl('file://${root}-none', 'none', '', false, true, map[string]string{})
	assert wr_err_code(ok) == '', 'compression=none opens: ${wr_err_code(ok)}'
}

// ── #203.2: attr-exact config validation (unknown attr → fast-fail) ───────────

fn test_config_attr_exact() {
	// an unknown attribute in a known section is rejected (not silently dropped).
	if _ := parse_service_config('[cxstore-service [bind addr="h:1" bogus="x"] [stores [store name="s" url="mem://s"]]]') {
		assert false, 'unknown [bind] attr `bogus` must fail-fast (#203.2)'
	}
	// a well-formed config still parses
	c := parse_service_config('[cxstore-service [bind addr="h:1"] [timeouts read-ms=5000] [stores [store name="s" url="mem://s"]]]') or {
		panic('valid config rejected: ${err}')
	}
	assert c.read_timeout_ms == 5000
}

// ── #205.4: document+ftp:// no longer trips CXER1100 on the model prefix ──────
// (the prefix is stripped before store_remote_parse; ftp then needs net, absent
// here → the honest net-denial, NOT an unresolved-backend model-prefix error).

fn test_document_ftp_prefix_stripped() {
	caps_set_empty() // no net → the ftp open is net-denied, proving the prefix parsed
	r := store_open_impl('document+ftp://ftp.example.invalid/store/', '', '', false, true,
		map[string]string{})
	ec := wr_err_code(r)
	// must NOT be the model-prefix-rejection CXER1100 "unresolved backend"; it is
	// the net capability denial (CXER0271) — i.e. the prefix was accepted.
	assert ec == 'cx-err:CXER0271', 'document+ftp:// must strip the prefix and reach the net gate (#205.4), got ${ec}'
}

// ── source: vcx/platform/store_crash_consistency_test.v ──
// store_crash_consistency_test.v — #624: a file:// cxpack store survives an
// unclean shutdown at ANY point with a clean verdict — either it opens (at
// worst discarding the torn, never-acknowledged tail record) or it refuses
// with a typed integrity error. Never a crash, never data loss of an acked
// record, never a silently partial view. Pins the three crash windows the
// pre-#624 write path lost to, plus the WAL torn-tail discard.

fn cc_root(tag string) string {
	return os.join_path(os.temp_dir(), 'cxpack_crash_${tag}_${os.getpid()}')
}

fn cc_new(root string) &MemStore {
	return &MemStore{
		url:     'file://${root}'
		backend: 'cxpack'
		root:    root
		is_open: true
	}
}

fn cc_put(mut ms MemStore, text string) string {
	doc := cx.parse(text) or { panic('parse: ${text}') }
	c := render_canonical(doc.elements[0])
	h := cx.cx_text_hash(c) or { panic('hash') }
	store_put_canonical(mut ms, h, c) or { panic('put: ' + err.msg()) }
	store_cxpack_flush(mut ms) or { panic('flush: ${err.msg()}') }
	return h
}

// The pre-#624 compaction CRASH WINDOW: the pack fold had already destroyed
// GC'd objects while the OLD append-log manifest (with its superseded /
// tombstoned lines) was still on disk. With the reordered compaction the
// window no longer exists going forward, and the two-pass replay makes a
// store already damaged that way load cleanly: its dangling doc references
// are all tombstoned later in the same log, and only the FINAL live state is
// verified.
fn test_pre624_compaction_crash_window_store_recovers() {
	root := cc_root('window')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	mut ms := cc_new(root)
	keep := cc_put(mut ms, '[keep [k 1]]')
	doomed := cc_put(mut ms, '[doomed [unique "not-shared-with-keep"] [deep [x "y"]]]')
	store_delete_local(mut ms, doomed)
	store_cxpack_flush(mut ms) or { panic('flush: ${err.msg()}') } // T tombstone appended
	// Simulate the old-ordering crash: objects GC'd (compacted pack + segments
	// replaced by the live set) while the APPEND-LOG manifest survives.
	old_manifest := os.read_file(os.join_path(root, cxpack_manifest)) or { panic('read manifest') }
	store_cxpack_compact(mut ms) or { panic('compact: ${err.msg()}') }
	os.write_file(os.join_path(root, cxpack_manifest), old_manifest) or { panic('write manifest') }

	mut ms2 := cc_new(root)
	store_cxpack_load(mut ms2) or {
		panic('a pre-#624 crash-window store must RECOVER, got: ${err.msg()}')
	}
	assert ms2.doc_order == [keep], 'live doc must survive recovery (got ${ms2.doc_order})'
	assert store_doc_present(ms2, keep)
	assert !store_doc_present(ms2, doomed), 'tombstoned doc must stay gone'
}

// TORN TAIL: a kill mid-append tears the manifest's final line structurally.
// The record was never acknowledged (its flush never returned) — the loader
// discards it loudly and opens at the last whole state. An acked (whole)
// record is never dropped.
fn test_torn_manifest_tail_is_discarded_not_fatal() {
	root := cc_root('torn')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	mut ms := cc_new(root)
	h1 := cc_put(mut ms, '[a [x 1]]')
	h2 := cc_put(mut ms, '[b [y 2]]')
	mp := os.join_path(root, cxpack_manifest)
	whole := os.read_file(mp) or { panic('read manifest') }
	// tear the final record mid-hash (what a kill mid-write leaves)
	assert whole.ends_with('\n')
	torn := whole[..whole.len - 20]
	os.write_file(mp, torn) or { panic('write torn') }

	mut ms2 := cc_new(root)
	store_cxpack_load(mut ms2) or { panic('torn tail must not refuse the store: ${err.msg()}') }
	// h1's records are earlier lines — the acked doc survives; the torn final
	// record is discarded (whichever doc/alias it carried).
	assert store_doc_present(ms2, h1), 'acked doc lost to a torn tail'
	assert ms2.doc_order.len >= 1
	// a torn line ANYWHERE ELSE stays a hard integrity error
	mut mid := whole.split_into_lines().filter(it.trim_space() != '')
	assert mid.len >= 2
	mid[0] = mid[0][..mid[0].len - 5] // tear the FIRST record instead
	os.write_file(mp, mid.join('\n') + '\n') or { panic('write mid-torn') }
	mut ms3 := cc_new(root)
	if _ := store_cxpack_load(mut ms3) {
		assert false, 'a torn NON-final record must be a hard integrity error'
	} else {
		assert ms3.doc_order.len == 0, 'refused load must leave no partial state'
	}
	_ = h2
}

// A kill mid-segment-write must never expose a torn pack at a segment's final
// name: the writer goes through a temp sibling + atomic rename, discovery
// ignores the .tmp, and the store reopens whole without the in-flight flush.
fn test_stray_segment_tmp_is_ignored() {
	root := cc_root('tmpseg')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	mut ms := cc_new(root)
	h1 := cc_put(mut ms, '[a [x 1]]')
	// what a kill mid-flush_segment leaves: a partial pack at the temp name
	next_seg := os.join_path(root, cxpack_seg_name(ms.obj_pack.segment_count()))
	os.write_file(next_seg + '.tmp', 'PARTIAL-GARBAGE-NOT-A-PACK') or { panic('write tmp') }

	mut ms2 := cc_new(root)
	store_cxpack_load(mut ms2) or { panic('a stray segment .tmp must be invisible: ${err.msg()}') }
	assert store_doc_present(ms2, h1)
	// and a TRUNCATED pack at a FINAL segment name (pre-#624 direct writes
	// could leave one) refuses with a typed error — never a crash.
	seg0 := os.join_path(root, cxpack_seg_name(0))
	whole := os.read_bytes(seg0) or { panic('read seg0') }
	os.write_file_array(seg0, whole[..whole.len / 2]) or { panic('truncate seg0') }
	mut ms3 := cc_new(root)
	if _ := store_cxpack_load(mut ms3) {
		assert false, 'a truncated pack at a final segment name must refuse loudly'
	}
}

// Corrupt pack internals (a lying index count / garbage entry offsets) yield
// typed refusals from the reader — pinned at the cxstore layer so the mmap
// path can never walk out of bounds (#624's SIGBUS leg).
fn test_pack_reader_bounds_are_checked() {
	root := cc_root('bounds')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	os.mkdir_all(root) or { panic(err) }
	p := os.join_path(root, 'p.cxpack')
	cxstore.write_pack(p, ['payload-one'.bytes(), 'payload-two'.bytes()]) or { panic(err.msg()) }
	mut data := os.read_bytes(p) or { panic('read pack') }
	// footer layout: …[index_count u32][records]…[footer_crc32][flen u64].
	// Overwrite index_count with a huge value AND refresh the footer crc so
	// the count check (not the crc) is what refuses.
	flen := int(u64(data[data.len - 8]) | (u64(data[data.len - 7]) << 8) | (u64(data[data.len - 6]) << 16) | (u64(data[data.len - 5]) << 24))
	fstart := data.len - 8 - flen
	data[fstart] = 0xff
	data[fstart + 1] = 0xff
	data[fstart + 2] = 0xff
	data[fstart + 3] = 0x7f
	refreshed := crc32.sum(data[fstart..data.len - 12])
	data[data.len - 12] = u8(refreshed & 0xff)
	data[data.len - 11] = u8((refreshed >> 8) & 0xff)
	data[data.len - 10] = u8((refreshed >> 16) & 0xff)
	data[data.len - 9] = u8((refreshed >> 24) & 0xff)
	os.write_file_array(p, data) or { panic('rewrite') }
	if _ := cxstore.open_pack(p) {
		assert false, 'a pack whose index count exceeds its footer must refuse'
	}
}

// ── source: vcx/platform/store_document_model_test.v ──
// §6 + §4.6 for the DEGENERATE document model (#129 B2): `model=document` stores each
// doc as ONE object ("don't decompose") on any object-graph substrate, reusing the
// same seam + store_graph refs/replay. The model is INVISIBLE to the Layer-1 API:
// the same doc has the same store-key and the same byte-identical round-trip under
// both models; the only observable difference is object count (document = 1/doc,
// subtree = many) — i.e. document trades dedup for simplicity.

fn dm_canon_hash(text string) (string, string) {
	c := render_canonical(cx.parse(text) or { panic('parse: ${err.msg()}') }.elements[0])
	h := cx.cx_text_hash(c) or { panic('hash: ${err.msg()}') }
	return c, h
}

fn test_document_model_mem_api_invisibility() {
	text := '[order [id 1] [customer [name "Acme"] [addr [city "NYC"] [zip "10001"]]]]'
	c, h := dm_canon_hash(text)

	// document model (mem)
	mut doc_ms := &MemStore{
		backend: 'mem'
		is_open: true
		model:   'document'
	}
	assert store_objgraph_active(doc_ms)
	store_put_canonical(mut doc_ms, h, c) or { panic('doc put: ${err.msg()}') }
	got_doc := store_doc_text(doc_ms, h) or { panic('doc get: ${err.msg()}') }
	doc_objs := doc_ms.obj_sink.objects.len

	// subtree model (mem, default)
	mut sub_ms := &MemStore{
		backend: 'mem'
		is_open: true
	}
	store_put_canonical(mut sub_ms, h, c) or { panic('sub put: ${err.msg()}') }
	got_sub := store_doc_text(sub_ms, h) or { panic('sub get: ${err.msg()}') }
	sub_objs := sub_ms.obj_sink.objects.len

	// API-invisible: identical store-key (same h used) + identical round-trip text.
	assert got_doc == c, 'document round-trip not byte-identical'
	assert got_sub == c, 'subtree round-trip not byte-identical'
	assert got_doc == got_sub, 'document and subtree must return identical text for the same doc'
	// The model shows ONLY in object count: document = exactly 1 object, subtree = many.
	assert doc_objs == 1, 'document model must store exactly one object per doc, got ${doc_objs}'
	assert sub_objs > 1, 'subtree model must decompose into multiple objects, got ${sub_objs}'
}

fn test_document_model_cxobj_reopen() {
	root := os.join_path(os.temp_dir(), 'cxobj_docmodel_${os.getpid()}')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	c, h := dm_canon_hash('[note [meta [author "ep"]] [body "hello document model"]]')

	mut ms := &MemStore{
		backend: 'cxobj'
		root:    root
		is_open: true
		model:   'document'
	}
	store_cxobj_backend(mut ms) or { panic('attach: ${err.msg()}') }
	store_put_canonical(mut ms, h, c) or { panic('put: ${err.msg()}') }
	store_cxobj_flush(mut ms) or { panic('flush: ${err.msg()}') }

	// reopen with model=document → replay restores the raw object (no decompose),
	// round-trip byte-identical.
	mut ms2 := &MemStore{
		backend: 'cxobj'
		root:    root
		is_open: true
		model:   'document'
	}
	store_cxobj_load(mut ms2) or { panic('reopen: ${err.msg()}') }
	assert store_doc_present(ms2, h), 'doc must survive a document-mode reopen'
	got := store_doc_text(ms2, h) or { panic('get: ${err.msg()}') }
	assert got == c, 'document reopen round-trip not byte-identical'
}

// #129 PR-H: the canonical `document+` URI prefix selects the document model on
// the mem / sqlite / s3 substrates (consistent with file://), and a bare substrate
// URI is subtree by default — both via the live open dispatcher (not just opts).
fn test_document_prefix_open_dispatch() {
	// document+mem:// → document model (hermetic; mem is capability-free).
	h := store_open_impl('document+mem://', '', '', false, true, map[string]string{})
	id := store_handle_of(h) or { panic('document+mem:// did not return a handle: ${h}') }
	ms := store_lookup(id) or { panic('no store for document+mem://') }
	assert ms.backend == 'mem', 'document+mem:// substrate should be mem, got ${ms.backend}'
	assert ms.model == 'document', 'document+mem:// must select the document model'

	// bare mem:// → subtree default.
	h2 := store_open_impl('mem://', '', '', false, true, map[string]string{})
	ms2 := store_lookup(store_handle_of(h2) or { panic('no handle for mem://') }) or {
		panic('no store for mem://')
	}
	assert ms2.model == '', 'bare mem:// must be the subtree default, got model=${ms2.model}'

	// the legacy [opts model=document] surface still selects document (back-compat).
	h3 := store_open_impl('mem://', '', '', false, true, {
		'model': 'document'
	})
	ms3 := store_lookup(store_handle_of(h3) or { panic('no handle for opts mem://') }) or {
		panic('no store for opts mem://')
	}
	assert ms3.model == 'document', '[opts model=document] must still select document'
}

// ── source: vcx/platform/store_flat_file_test.v ──
// store_flat_file_test.v — flat file:// document-model parity + hygiene
// (#290 / #291 / #292). The flat model is the LEGACY on-disk form (new file://
// stores land on the cxpack object graph), but pre-existing stores replay
// through it forever, so it keeps the same contracts:
//
//   #290 gc/prune succeed per the store.md §15 capability table (flat
//        semantics: every present doc is its own object AND a root, mirroring
//        pc_reclaim's obj_roots semantics — reclaimed=0, objects=len(docs);
//        gc additionally compacts the append log to a snapshot).
//   #291 delete-doc appends a T (tombstone) record — the O(1) append path —
//        instead of rewriting the whole snapshot; store_read_index replays it;
//        the compaction heuristic folds tombstones away; an OLD index (no
//        tombstones) replays identically; a re-put after a tombstone comes back.
//   #292 open sweeps stale sibling `.cxstore-index.tmp.<pid>` files whose pid
//        is no longer a live process (crash between temp write and rename).
//   #298 delete-alias appends an X (alias tombstone) record — the #291
//        contract on the alias plane (durability, re-add ordering, compaction).

fn ff_root(tag string) string {
	root := os.join_path(os.temp_dir(), 'cxflat_${tag}_${os.getpid()}')
	os.rmdir_all(root) or {}
	return root
}

// ff_open opens (or reopens) a flat document-model store at root via the
// PUBLIC open path (self-describing reopen included), with all caps granted.
fn ff_open(url string, read_only bool) cx.Node {
	caps_set_all()
	h := store_open_impl(url, '', '', read_only, true, map[string]string{})
	store_handle_of(h) or { panic('flat open ${url} did not return a handle: ${h}') }
	return h
}

fn ff_ms(h cx.Node) &MemStore {
	id := store_handle_of(h) or { panic('no handle: ${h}') }
	return store_lookup(id) or { panic('no store for handle ${id}') }
}

fn ff_put(h cx.Node, text string) string {
	r := store_stdlib_builtin_inner('store-put-doc-text', [h, store_str(text)]) or {
		panic('put: ${err.msg()}')
	}
	assert !is_err_value(r), 'put must succeed: ${r}'
	return sw_scalar(r)
}

fn ff_get(h cx.Node, hash string) cx.Node {
	return store_stdlib_builtin_inner('store-get-doc-text', [h, store_str(hash)]) or {
		panic('get: ${err.msg()}')
	}
}

fn ff_delete(h cx.Node, hash string) cx.Node {
	return store_stdlib_builtin_inner('store-delete-doc', [h, store_str(hash)]) or {
		panic('delete: ${err.msg()}')
	}
}

fn ff_err_code(n cx.Node) string {
	if !is_err_value(n) {
		return ''
	}
	if n is cx.Element {
		return sw_attr(n, 'code')
	}
	return ''
}

fn ff_attr_int(n cx.Node, name string) int {
	if n is cx.Element {
		return sw_attr(n, name).int()
	}
	return -999
}

fn ff_index_path(root string) string {
	return os.join_path(root, store_index_name)
}

// ff_canon_hash produces the STRICT canonical text + its genuine store key —
// the same canonical.md §1.2 identity put-doc-text computes (needed when
// fabricating an index by hand and when asserting round-trip bytes).
fn ff_canon_hash(text string) (string, string) {
	c := cx.cx_text_canonical(text) or { panic('canonical: ${err.msg()}') }
	h := cx.cx_text_hash(c) or { panic('hash: ${err.msg()}') }
	return c, h
}

// ── #290: gc / prune succeed on the flat model ────────────────────────────────

fn test_flat_prune_succeeds_with_flat_semantics() {
	root := ff_root('prune')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	ff_put(h, '[doc [item "x"]]')
	ka := ff_put(h, '[doc [item "y"]]')
	d := ff_delete(h, ka)
	assert !is_err_value(d), 'delete must succeed: ${d}'
	r := store_stdlib_builtin_inner('store-prune', [h]) or { panic('prune: ${err.msg()}') }
	assert !is_err_value(r), 'prune on flat file:// must succeed per §15, got ${r}'
	assert r is cx.Element && (r as cx.Element).name == 'prune-result', 'prune result shape: ${r}'
	// flat semantics: every present doc is its own object and a root — nothing
	// sub-doc to reclaim, honest zero.
	assert ff_attr_int(r, 'reclaimed') == 0, 'flat prune reclaims nothing: ${r}'
	assert ff_attr_int(r, 'objects') == 1, 'flat prune reports live docs as objects: ${r}'
}

fn test_flat_prune_empty_store() {
	root := ff_root('prune_empty')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	r := store_stdlib_builtin_inner('store-prune', [h]) or { panic('prune: ${err.msg()}') }
	assert !is_err_value(r), 'prune on an empty flat store must succeed: ${r}'
	assert ff_attr_int(r, 'reclaimed') == 0 && ff_attr_int(r, 'objects') == 0, 'empty flat prune: ${r}'
}

fn test_flat_gc_succeeds_and_compacts_log() {
	root := ff_root('gc')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	keep := ff_put(h, '[doc [item "keep"]]')
	gone := ff_put(h, '[doc [item "gone"]]')
	ff_delete(h, gone)
	r := store_stdlib_builtin_inner('store-gc', [h]) or { panic('gc: ${err.msg()}') }
	assert !is_err_value(r), 'gc on flat file:// must succeed per §15, got ${r}'
	assert r is cx.Element && (r as cx.Element).name == 'gc-result', 'gc result shape: ${r}'
	assert ff_attr_int(r, 'reclaimed') == 0, 'flat gc reclaims nothing sub-doc: ${r}'
	assert ff_attr_int(r, 'objects') == 1, 'flat gc reports live docs as objects: ${r}'
	// gc = prune + compaction: the on-disk index is now a snapshot of live state
	// (one D record for the kept doc, no tombstones, no stale records).
	mut ms := ff_ms(h)
	raw := os.read_file(ff_index_path(root)) or { panic('read index: ${err.msg()}') }
	assert raw.contains('D\t${keep}\t'), 'compacted snapshot keeps the live doc'
	assert !raw.contains('D\t${gone}\t'), 'compacted snapshot drops the deleted doc record'
	assert !raw.contains('T\t'), 'compacted snapshot carries no tombstones'
	assert ms.log_records == ms.doc_order.len + ms.alias_order.len, 'gc resets the log to live size, got ${ms.log_records}'
	// live state intact + durable
	h2 := ff_open('file://${root}', false)
	keep_c, _ := ff_canon_hash('[doc [item "keep"]]')
	assert sw_scalar(ff_get(h2, keep)) == keep_c, 'kept doc round-trips after gc'
}

fn test_flat_gc_prune_read_only_still_denied() {
	root := ff_root('gc_ro')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	ff_put(h, '[doc [item "x"]]')
	ro := ff_open('file://${root}', true)
	g := store_stdlib_builtin_inner('store-gc', [ro]) or { panic('gc: ${err.msg()}') }
	assert ff_err_code(g) == 'cx-err:CXER1110', 'gc on a read-only flat store stays denied: ${g}'
	p := store_stdlib_builtin_inner('store-prune', [ro]) or { panic('prune: ${err.msg()}') }
	assert ff_err_code(p) == 'cx-err:CXER1110', 'prune on a read-only flat store stays denied: ${p}'
}

// ── #291: delete-doc appends a tombstone, replayed on open ───────────────────

fn test_flat_delete_appends_tombstone_not_snapshot() {
	root := ff_root('tomb')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	ka := ff_put(h, '[doc [item "a"]]')
	kb := ff_put(h, '[doc [item "b"]]')
	d := ff_delete(h, ka)
	assert d is cx.ScalarNode && sw_scalar(d) == 'true', 'delete of a present doc returns true: ${d}'
	raw := os.read_file(ff_index_path(root)) or { panic('read index: ${err.msg()}') }
	// O(1) append path: the log carries the ORIGINAL D record AND the T record —
	// no whole-snapshot rewrite happened.
	assert raw.contains('T\t${ka}\t'), 'delete must append a tombstone record, index:\n${raw}'
	assert raw.contains('D\t${ka}\t'), 'the original D record stays in the log (append, not rewrite)'
	assert raw.contains('D\t${kb}\t'), 'unrelated doc record intact'
	// tombstone replays on reopen: deleted doc absent, sibling present.
	h2 := ff_open('file://${root}', false)
	ms2 := ff_ms(h2)
	assert ka !in ms2.docs, 'tombstoned doc must not replay'
	b_c, _ := ff_canon_hash('[doc [item "b"]]')
	assert sw_scalar(ff_get(h2, kb)) == b_c, 'sibling doc replays intact'
	// deleting an absent doc is a clean false, and appends nothing new.
	before := os.file_size(ff_index_path(root))
	d2 := ff_delete(h2, ka)
	assert d2 is cx.ScalarNode && sw_scalar(d2) == 'false', 'delete of an absent doc returns false'
	assert os.file_size(ff_index_path(root)) == before, 'a no-op delete appends no record'
}

fn test_flat_old_index_without_tombstones_replays_identically() {
	root := ff_root('oldidx')
	defer {
		os.rmdir_all(root) or {}
	}
	// Fabricate a pre-tombstone index EXACTLY as the old writer laid it out:
	// header + D records + A record. This is the #291 back-compat contract.
	c1, h1 := ff_canon_hash('[user name=al]')
	c2, h2 := ff_canon_hash('[user name=bo]')
	os.mkdir_all(root) or { panic('mkdir: ${err.msg()}') }
	mut content := 'CXSTORE\tv1\n'
	content += store_doc_record(h1, c1)
	content += store_doc_record(h2, c2)
	content += store_alias_record('current', h1)
	os.write_file(ff_index_path(root), content) or { panic('write: ${err.msg()}') }
	// bare file:// reopen (self-describing detection picks the flat model).
	h := ff_open('file://${root}', false)
	ms := ff_ms(h)
	assert ms.model == 'document', 'legacy index reopens as the flat document model'
	assert ms.doc_order == [h1, h2], 'doc order preserved from the old index'
	assert sw_scalar(ff_get(h, h1)) == c1, 'old doc 1 replays byte-identically'
	assert sw_scalar(ff_get(h, h2)) == c2, 'old doc 2 replays byte-identically'
	assert ms.aliases['current'] == h1, 'old alias replays'
	assert ms.log_records == 3, 'replay seeds the log count from the inherited records'
}

fn test_flat_tombstoned_doc_reput_comes_back() {
	root := ff_root('reput')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	k := ff_put(h, '[doc [item "phoenix"]]')
	ff_delete(h, k)
	k2 := ff_put(h, '[doc [item "phoenix"]]')
	assert k2 == k, 'same content re-puts under the same hash'
	// replay order semantics: D, T, D → the doc is PRESENT after reopen.
	ha := ff_open('file://${root}', false)
	phoenix_c, _ := ff_canon_hash('[doc [item "phoenix"]]')
	assert sw_scalar(ff_get(ha, k)) == phoenix_c, 're-put after tombstone must come back on replay'
	// and a trailing tombstone wins again: D, T, D, T → absent.
	ff_delete(ha, k)
	hb := ff_open('file://${root}', false)
	msb := ff_ms(hb)
	assert k !in msb.docs, 'trailing tombstone must win on replay'
}

fn test_flat_delete_heavy_log_compacts() {
	root := ff_root('compact')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	keep := ff_put(h, '[doc [item "base"]]')
	// 45 put+delete cycles = 90 log records against live=1 — well past the
	// store_append redundancy threshold (2*live + 64). Tombstones MUST count
	// toward redundancy so a delete-heavy log folds to a snapshot.
	for i in 0 .. 45 {
		k := ff_put(h, '[doc [item "churn-${i}"]]')
		ff_delete(h, k)
	}
	ms := ff_ms(h)
	live := ms.doc_order.len + ms.alias_order.len
	assert live == 1, 'only the base doc stays live'
	// 91 records were appended against live=1; tombstones count toward the
	// redundancy measure, so compaction MUST have fired and the log stays
	// bounded by the store_append threshold (a tail of post-compaction appends
	// may legitimately remain, tombstones included).
	assert ms.log_records <= 2 * live + 64, 'delete-heavy log must have compacted, log_records=${ms.log_records}'
	raw := os.read_file(ff_index_path(root)) or { panic('read index: ${err.msg()}') }
	d_count := raw.count('D\t')
	t_count := raw.count('T\t')
	assert d_count + t_count == ms.log_records, 'on-disk records (${d_count}D + ${t_count}T) must match the log bookkeeping (${ms.log_records})'
	assert t_count < 45, 'compaction folds tombstoned records away, ${t_count} T records remain'
	// durability: the survivor replays.
	h2 := ff_open('file://${root}', false)
	base_c, _ := ff_canon_hash('[doc [item "base"]]')
	assert sw_scalar(ff_get(h2, keep)) == base_c, 'base doc survives compaction'
}

// ── #298: delete-alias appends an X tombstone, replayed on open ──────────────

fn ff_set_alias(h cx.Node, alias string, hash string) {
	r := store_stdlib_builtin_inner('store-set-alias', [h, store_str(alias), store_str(hash)]) or {
		panic('set-alias: ${err.msg()}')
	}
	assert !is_err_value(r), 'set-alias must succeed: ${r}'
}

fn ff_delete_alias(h cx.Node, alias string) cx.Node {
	return store_stdlib_builtin_inner('store-delete-alias', [h, store_str(alias)]) or {
		panic('delete-alias: ${err.msg()}')
	}
}

fn test_flat_delete_alias_appends_tombstone_not_snapshot() {
	root := ff_root('atomb')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	k := ff_put(h, '[doc [item "target"]]')
	ff_set_alias(h, 'cur', k)
	ff_set_alias(h, 'other', k)
	d := ff_delete_alias(h, 'cur')
	assert d is cx.ScalarNode && sw_scalar(d) == 'true', 'delete-alias of a present alias returns true: ${d}'
	raw := os.read_file(ff_index_path(root)) or { panic('read index: ${err.msg()}') }
	// O(1) append path: the log carries the ORIGINAL A record AND the X record —
	// no whole-snapshot rewrite happened. X mirrors A's length-prefixed payload
	// shape (alias names may contain any bytes).
	assert raw.contains('X\t${'cur'.len}\t0\ncur\n'), 'delete-alias must append an X tombstone, index:\n${raw}'
	assert raw.contains('A\t${'cur'.len}\t${k}\ncur\n'), 'the original A record stays in the log (append, not rewrite)'
	// tombstone replays on reopen: deleted alias absent, sibling present.
	h2 := ff_open('file://${root}', false)
	ms2 := ff_ms(h2)
	assert 'cur' !in ms2.aliases, 'tombstoned alias must not replay'
	assert 'cur' !in ms2.alias_order, 'tombstoned alias must leave alias_order'
	assert ms2.aliases['other'] == k, 'sibling alias replays intact'
	// deleting an absent alias is a clean false, and appends nothing new.
	before := os.file_size(ff_index_path(root))
	d2 := ff_delete_alias(h2, 'cur')
	assert d2 is cx.ScalarNode && sw_scalar(d2) == 'false', 'delete-alias of an absent alias returns false'
	assert os.file_size(ff_index_path(root)) == before, 'a no-op delete-alias appends no record'
}

fn test_flat_alias_tombstone_reset_comes_back() {
	root := ff_root('areset')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	k1 := ff_put(h, '[doc [item "v1"]]')
	k2 := ff_put(h, '[doc [item "v2"]]')
	ff_set_alias(h, 'ptr', k1)
	ff_delete_alias(h, 'ptr')
	ff_set_alias(h, 'ptr', k2)
	// replay order semantics: A, X, A → the alias is PRESENT at its LAST target.
	ha := ff_open('file://${root}', false)
	msa := ff_ms(ha)
	assert msa.aliases['ptr'] == k2, 're-set alias after tombstone must come back at the new target'
	assert msa.alias_order.filter(it == 'ptr').len == 1, 'alias_order holds the re-set alias exactly once'
	// and a trailing tombstone wins again: A, X, A, X → absent.
	ff_delete_alias(ha, 'ptr')
	hb := ff_open('file://${root}', false)
	msb := ff_ms(hb)
	assert 'ptr' !in msb.aliases, 'trailing alias tombstone must win on replay'
}

fn test_flat_delete_alias_heavy_log_compacts() {
	root := ff_root('acompact')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	k := ff_put(h, '[doc [item "abase"]]')
	ff_set_alias(h, 'keep', k)
	// 45 set+delete cycles = 90 log records against live=2 (1 doc + 1 alias) —
	// past the store_append threshold (2*live + 64). Alias tombstones MUST count
	// toward redundancy so a delete-alias-heavy log folds to a snapshot.
	for i in 0 .. 45 {
		ff_set_alias(h, 'churn-${i}', k)
		ff_delete_alias(h, 'churn-${i}')
	}
	ms := ff_ms(h)
	live := ms.doc_order.len + ms.alias_order.len
	assert live == 2, 'only the base doc + kept alias stay live'
	assert ms.log_records <= 2 * live + 64, 'delete-alias-heavy log must have compacted, log_records=${ms.log_records}'
	raw := os.read_file(ff_index_path(root)) or { panic('read index: ${err.msg()}') }
	recs := raw.count('D\t') + raw.count('A\t') + raw.count('T\t') + raw.count('X\t')
	assert recs == ms.log_records, 'on-disk records (${recs}) must match the log bookkeeping (${ms.log_records})'
	assert raw.count('X\t') < 45, 'compaction folds alias-tombstoned records away, ${raw.count('X\t')} X records remain'
	// durability: the survivors replay.
	h2 := ff_open('file://${root}', false)
	ms2 := ff_ms(h2)
	assert ms2.aliases['keep'] == k, 'kept alias survives compaction'
}

// ── #292: open sweeps stale .cxstore-index.tmp.<pid> orphans ─────────────────

// ff_dead_pid returns a pid that is guaranteed not to be a live process: it
// spawns /usr/bin/true and waits for it to exit.
fn ff_dead_pid() int {
	mut p := os.new_process('/usr/bin/true')
	p.run()
	p.wait()
	assert p.pid > 0, 'spawn for dead-pid fixture failed'
	return p.pid
}

fn test_open_sweeps_stale_tmp_files() {
	root := ff_root('sweep')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	k := ff_put(h, '[doc [item "survivor"]]')
	idx := ff_index_path(root)
	dead := ff_dead_pid()
	stale := '${idx}.tmp.${dead}'
	live_tmp := '${idx}.tmp.${os.getpid()}' // our own pid = a live writer's in-flight persist
	weird := '${idx}.tmp.not-a-pid' // unknown shape — never touched
	os.write_file(stale, '') or { panic('stale fixture: ${err.msg()}') }
	os.write_file(live_tmp, 'in-flight') or { panic('live fixture: ${err.msg()}') }
	os.write_file(weird, 'unknown') or { panic('weird fixture: ${err.msg()}') }
	// reopen → the dead writer's orphan is swept; everything else untouched.
	h2 := ff_open('file://${root}', false)
	assert !os.exists(stale), 'stale tmp from a dead pid must be swept at open'
	assert os.exists(live_tmp), 'a live pid tmp (in-flight persist) is never touched'
	assert os.exists(weird), 'non-pid-suffixed files are never touched'
	assert os.exists(idx), 'the live index is never touched'
	survivor_c, _ := ff_canon_hash('[doc [item "survivor"]]')
	assert sw_scalar(ff_get(h2, k)) == survivor_c, 'store content intact after sweep'
	os.rm(live_tmp) or {}
	os.rm(weird) or {}
}

fn test_read_only_open_does_not_sweep() {
	root := ff_root('sweep_ro')
	defer {
		os.rmdir_all(root) or {}
	}
	h := ff_open('document+file://${root}', false)
	ff_put(h, '[doc [item "x"]]')
	idx := ff_index_path(root)
	dead := ff_dead_pid()
	stale := '${idx}.tmp.${dead}'
	os.write_file(stale, '') or { panic('stale fixture: ${err.msg()}') }
	// a read-only open holds only the read grant — it must not delete files.
	ff_open('file://${root}', true)
	assert os.exists(stale), 'read-only open must not sweep (no write grant)'
	os.rm(stale) or {}
}

// ── source: vcx/platform/store_ft_test.v ──

fn test_store_ft_search_and_stemming() {
	dir := os.join_path(os.temp_dir(), 'cxstore_ft_rt')
	os.rmdir_all(dir) or {}
	mut repo := cxstore.open_repo(dir) or {
		assert false, 'open: ${err}'
		return
	}
	ka := repo.put_text('[doc [title "the quick brown fox"] [body "it jumps over"]]') or {
		assert false, 'putA: ${err}'
		return
	}
	kb := repo.put_text('[doc [title "a lazy sleeping dog"]]') or {
		assert false, 'putB: ${err}'
		return
	}

	ix := build_store_ft(repo)

	// term hits the right doc
	assert ix.search('quick') == [ka]
	assert ix.search('dog') == [kb]
	// Porter2 stemming: query 'jumping' stems to 'jump', matches 'jumps'
	assert ix.search('jumping') == [ka]
	// stopword-only query yields nothing
	assert ix.search('the') == []
	// absent term
	assert ix.search('zebra') == []
	// AND semantics: both terms in the same doc
	assert ix.search('quick fox') == [ka]
	assert ix.search('quick dog') == [] // not in the same doc

	os.rmdir_all(dir) or {}
}

fn test_store_ft_multi_doc_and_sidecar() {
	dir := os.join_path(os.temp_dir(), 'cxstore_ft_multi')
	os.rmdir_all(dir) or {}
	mut repo := cxstore.open_repo(dir) or {
		assert false, 'open: ${err}'
		return
	}
	k1 := repo.put_text('[log [entry "database error occurred"]]') or {
		assert false, 'put1: ${err}'
		return
	}
	k2 := repo.put_text('[log [entry "database connection restored"]]') or {
		assert false, 'put2: ${err}'
		return
	}
	ix := build_store_ft(repo)
	dbhits := ix.search('database')
	assert dbhits.len == 2
	assert k1 in dbhits && k2 in dbhits
	assert ix.search('error') == [k1]

	// sidecar round-trips
	sc := os.join_path(dir, 'ft.tsv')
	ix.save(sc) or {
		assert false, 'save: ${err}'
		return
	}
	ix2 := load_store_ft(sc) or {
		assert false, 'load: ${err}'
		return
	}
	assert ix2.search('database').len == 2
	assert ix2.search('error') == [k1]

	os.rmdir_all(dir) or {}
}

// ── source: vcx/platform/store_introspection_test.v ──
// store_introspection_test.v — #129-D: object-graph introspection (object_count
// + dedup ratio) surfaces through StoreStats / store_mount_stats and the
// /metrics exposition, ONLY for the content-addressed backend (no fabricated
// zeros for the flat backends), with the dedup walk cached against a mutation
// fingerprint.

fn ti_canon_hash(text string) (string, string) {
	doc := cx.parse(text) or { return text, '' }
	c := render_canonical(doc.elements[0])
	h := cx.cx_text_hash(c) or { return c, '' }
	return c, h
}

fn ti_put(mut ms MemStore, text string) {
	c, h := ti_canon_hash(text)
	store_put_canonical(mut ms, h, c) or { panic('put: ' + err.msg()) }
}

// a cxpack store reports object_count and a >1 dedup ratio once docs share
// subtrees; the engine-level stat walk distinguishes logical vs distinct.
fn test_objgraph_stats_object_count_and_dedup() {
	mut ms := &MemStore{
		backend: 'cxpack'
		root:    ''
		is_open: true
	}
	big := '[customer [name "Acme"] [addr [street "1 Main"] [city "NYC"] [zip "10001"]] [tags [t "a"] [t "b"] [t "c"]]]'
	ti_put(mut ms, '[order [id 1] ${big}]')
	ti_put(mut ms, '[order [id 2] ${big}]') // shares the whole `big` subtree

	stats := store_objgraph_stats(mut ms, ms.doc_order.len)
	assert stats.has_object_graph
	assert stats.object_count == ms.obj_sink.objects.len
	// two docs share a big subtree → logical (no-sharing) count strictly exceeds
	// the distinct objects actually stored → dedup ratio > 1.
	assert stats.logical_objects > i64(stats.distinct_objects), 'expected sharing: logical ${stats.logical_objects} vs distinct ${stats.distinct_objects}'
	assert stats.distinct_objects > 0
}

// the dedup walk is cached: a second stats call with no mutation in between does
// not change the cached fingerprint (and a mutation invalidates it).
fn test_objgraph_stats_cache_fingerprint() {
	mut ms := &MemStore{
		backend: 'cxpack'
		is_open: true
	}
	ti_put(mut ms, '[a [x 1]]')
	_ := store_objgraph_stats(mut ms, ms.doc_order.len)
	g_docs := ms.graph_stats_docs
	g_objs := ms.graph_stats_objects
	assert g_docs == 1
	// re-read with no mutation → fingerprint unchanged (cache hit).
	_ = store_objgraph_stats(mut ms, ms.doc_order.len)
	assert ms.graph_stats_docs == g_docs && ms.graph_stats_objects == g_objs

	// a mutation moves the fingerprint → next read recomputes.
	ti_put(mut ms, '[b [y 2]]')
	s2 := store_objgraph_stats(mut ms, ms.doc_order.len)
	assert ms.graph_stats_docs == 2
	assert s2.object_count > g_objs
}

// engine-level: object_graph_stats counts logical (with multiplicity) vs distinct.
fn test_object_graph_stats_engine() {
	mut sink := cxstore.ObjectSink{}
	doc := cx.parse('[order [id 1] [a [k "v"]] [a [k "v"]]]') or { panic('parse') }
	root := cxstore.store_document(mut sink, doc, cxstore.default_fanout)
	getter := fn [sink] (h []u8) ?[]u8 {
		return sink.get(h)
	}
	logical, distinct := cxstore.object_graph_stats(getter, [root])
	// the two identical `[a [k "v"]]` children collapse to one object set →
	// logical (counts both) strictly exceeds distinct (stores them once).
	assert logical > i64(distinct), 'logical ${logical} should exceed distinct ${distinct} given repeated subtree'
	assert distinct > 0
}

// /metrics: cxpack emits cxstore_store_objects + cxstore_store_dedup_ratio; the
// flat mem backend emits ONLY docs — no object-graph series (no fabricated zeros).
fn test_metrics_objgraph_series_gated_by_backend() {
	// cxpack mount registered directly (bypasses cap_guard, like the other
	// engine-level cxpack tests).
	mut cp := &MemStore{
		backend: 'cxpack'
		is_open: true
	}
	ti_put(mut cp, '[doc [x 1] [y 2]]')
	cp_id := store_register(cp)
	cp_handle := store_handle_element(cp_id, cp)

	// a flat (document-model) mount — file:// keeps the flat index, so it must emit
	// the docs gauge but NO object-graph series (mem is now the subtree model, so
	// file:// is the genuine flat example here).
	mut flat := &MemStore{
		backend: 'file'
		is_open: true
	}
	flat.docs['h1'] = '[a 1]'
	flat.doc_order << 'h1'
	flat_id := store_register(flat)
	flat_handle := store_handle_element(flat_id, flat)

	out := svc_store_internal_metrics({
		'graph': cp_handle
		'flat':  flat_handle
	})
	// docs gauge for both
	assert out.contains('cxstore_store_docs{store="graph",backend="cxpack"}'), out
	assert out.contains('cxstore_store_docs{store="flat",backend="file"}'), out
	// object-graph series ONLY for the cxpack mount
	assert out.contains('cxstore_store_objects{store="graph",backend="cxpack"}'), out
	assert out.contains('cxstore_store_dedup_ratio{store="graph",backend="cxpack"}'), out
	assert !out.contains('store="flat"') || !out.contains('cxstore_store_objects{store="flat"'), 'flat backend must not emit object-graph series (no fabricated zeros): ${out}'
	assert !out.contains('cxstore_store_objects{store="flat"'), out
	assert !out.contains('cxstore_store_dedup_ratio{store="flat"'), out
}

// ── source: vcx/platform/store_legacy_code_refusal_test.v ──
// A3 (RULED 2026-08-08): a legacy computation-identity-keyed code record —
// the retired `code:` key prefix / `C` record kind, whose key was never the
// hash of the stored bytes — is REFUSED LOUDLY at load on every substrate.
// No silent skip, no read-tolerance window. These tests craft the legacy
// records on disk exactly as the retired writer emitted them and pin the
// refusal on both persisted formats (flat index + pack manifest).

fn lcr_root(tag string) string {
	return os.join_path(os.temp_dir(), 'cx-legacy-code-${os.getpid()}-${tag}')
}

fn lcr_open(url string) cx.Node {
	caps_set_all()
	return store_open_impl(url, '', '', false, true, map[string]string{})
}

fn lcr_close(h cx.Node) {
	store_stdlib_builtin_inner('store-close', [h]) or {}
}

// flat index: a legacy `D`-record with a code:-prefixed key (the retired
// flat persistence form) refuses at open with the integrity class.
fn test_flat_index_refuses_legacy_code_record() {
	root := lcr_root('flat')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	h := lcr_open('document+file://${root}')
	assert !is_err_value(h), 'setup open failed: ${render_canonical(h)}'
	store_stdlib_builtin_inner('store-put-doc-text', [h, store_str('[order id=1]')]) or {
		panic('setup put: ${err}')
	}
	lcr_close(h)

	// append the legacy record exactly as the retired writer framed it
	src := '[?def f (\$x) \$x]'
	legacy := 'D\tcode:sha2-256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\t${src.len}\n${src}\n'
	idx := os.join_path(root, store_index_name)
	mut f := os.open_append(idx) or { panic('append: ${err}') }
	f.write_string(legacy) or { panic('write: ${err}') }
	f.close()

	got := lcr_open('document+file://${root}')
	assert is_err_value(got), 'legacy code: record must REFUSE at open, got a live handle'
	rendered := render_canonical(got)
	assert rendered.contains('CXER1120'), 'refusal must be the integrity class: ${rendered}'
	assert rendered.contains('legacy code'), 'refusal must NAME the legacy record: ${rendered}'
}

// pack manifest: a legacy `C` manifest line refuses at open the same way.
fn test_pack_manifest_refuses_legacy_code_record() {
	root := lcr_root('pack')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	h := lcr_open('file://${root}')
	assert !is_err_value(h), 'setup open failed: ${render_canonical(h)}'
	store_stdlib_builtin_inner('store-put-doc-text', [h, store_str('[order id=1]')]) or {
		panic('setup put: ${err}')
	}
	lcr_close(h)

	mp := os.join_path(root, cxpack_manifest)
	mut f := os.open_append(mp) or { panic('append: ${err}') }
	f.write_string('C\tcode:sha2-256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\t${'cc'.repeat(32)}\n') or {
		panic('write: ${err}')
	}
	f.close()

	got := lcr_open('file://${root}')
	assert is_err_value(got), 'legacy C manifest record must REFUSE at open, got a live handle'
	rendered := render_canonical(got)
	assert rendered.contains('legacy code record'), 'refusal must NAME the legacy record: ${rendered}'
}

// ── source: vcx/platform/store_lifecycle_wave3_test.v ──
// store_lifecycle_wave3_test.v — W3 lifecycle fixes (#183 cxobj open, #180/#199
// TLS+env config, #181 watchdog, #186/#211 drain, #187 read-timeout, #219 framing).
// Behavioral: drives store_open_impl / parse_service_config / the drain path.
// ── #183: a FRESH cxobj store opens via the public [$store:open] path ─────────

fn test_cxobj_fresh_open_via_public_path() {
	caps_set_all()
	root := os.join_path(os.temp_dir(), 'w3_cxobj_${os.getpid()}')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	// fresh open — previously tripped the partial-store guard (objects/ dir created
	// by the backend attach before the presence check).
	h := store_open_impl('file://${root}?encoding=object-per-key', '', '', false, true,
		map[string]string{})
	assert w3_err_code(h) == '', 'fresh cxobj open must succeed, got ${w3_err_code(h)}: ${w3_err_msg(h)}'
	// put → get round-trips
	sk := store_stdlib_builtin_inner('store-put-doc-text', [h, store_str('[doc [x 1]]')]) or {
		panic('put: ${err.msg()}')
	}
	sks := cx.scalar_value_str_public((sk as cx.ScalarNode).value)
	got := store_stdlib_builtin_inner('store-get-doc-text', [h, store_str(sks)]) or {
		panic('get: ${err.msg()}')
	}
	assert cx.scalar_value_str_public((got as cx.ScalarNode).value) == '[doc [x 1]]', 'cxobj round-trip'
	// reopen the now-populated store
	h2 := store_open_impl('file://${root}?encoding=object-per-key', '', '', false, true,
		map[string]string{})
	assert w3_err_code(h2) == '', 'cxobj reopen must succeed, got ${w3_err_code(h2)}'
	got2 := store_stdlib_builtin_inner('store-get-doc-text', [h2, store_str(sks)]) or {
		panic('get2: ${err.msg()}')
	}
	assert cx.scalar_value_str_public((got2 as cx.ScalarNode).value) == '[doc [x 1]]', 'cxobj reopen round-trip'
}

fn test_cxobj_encrypted_fresh_open() {
	caps_set_all()
	os.setenv('CX_STORE_KEK_w3k', 'a'.repeat(64), true)
	root := os.join_path(os.temp_dir(), 'w3_cxobj_enc_${os.getpid()}')
	os.rmdir_all(root) or {}
	defer {
		os.rmdir_all(root) or {}
	}
	// #183 + #184: encryption-at-rest is reachable now that cxobj opens.
	h := store_open_impl('file://${root}?encoding=object-per-key', '', '', false, true, {
		'encrypt-key-id': 'w3k'
	})
	assert w3_err_code(h) == '', 'encrypted cxobj open must succeed, got ${w3_err_code(h)}: ${w3_err_msg(h)}'
	sk := store_stdlib_builtin_inner('store-put-doc-text', [h, store_str('[secret [v "PLAINTEXTPROBE"]]')]) or {
		panic('put: ${err.msg()}')
	}
	sks := cx.scalar_value_str_public((sk as cx.ScalarNode).value)
	// the object files on disk must NOT contain the plaintext (sealed at rest).
	mut found_plain := false
	objdir := os.join_path(root, 'objects')
	if os.exists(objdir) {
		for sh in (os.ls(objdir) or { [] }) {
			sub := os.join_path(objdir, sh)
			if !os.is_dir(sub) {
				continue
			}
			for f in (os.ls(sub) or { [] }) {
				blob := os.read_bytes(os.join_path(sub, f)) or { continue }
				if blob.bytestr().contains('PLAINTEXTPROBE') {
					found_plain = true
				}
			}
		}
	}
	assert !found_plain, 'encrypted cxobj must NOT store plaintext on disk'
	// and it round-trips (decrypt)
	got := store_stdlib_builtin_inner('store-get-doc-text', [h, store_str(sks)]) or {
		panic('get: ${err.msg()}')
	}
	assert cx.scalar_value_str_public((got as cx.ScalarNode).value).contains('PLAINTEXTPROBE'), 'encrypted cxobj must decrypt on read'
}

// ── #180 / #199: TLS + env-var config ─────────────────────────────────────────

fn test_config_tls_parses_cert_key_ca() {
	c := parse_service_config('[cxstore-service [bind addr="h:1"] [tls cert="/etc/c.pem" key="/etc/k.pem" ca="/etc/ca.pem"] [stores [store name="s" url="mem://s"]]]') or {
		panic('tls config rejected: ${err}')
	}
	t := c.tls or {
		assert false, 'tls config must be present'
		return
	}
	assert t.cert == '/etc/c.pem'
	assert t.key == '/etc/k.pem'
	assert t.ca == '/etc/ca.pem'
}

fn test_config_env_var_resolution() {
	os.setenv('W3_TLS_KEY_PEM', '-----BEGIN PRIVATE KEY-----\nMII...\n-----END PRIVATE KEY-----', true)
	c := parse_service_config('[cxstore-service [bind addr="h:1"] [tls cert="/etc/c.pem" key="\${env:W3_TLS_KEY_PEM}"] [stores [store name="s" url="mem://s"]]]') or {
		panic('env config rejected: ${err}')
	}
	t := c.tls or {
		assert false, 'tls present'
		return
	}
	assert t.key.contains('BEGIN PRIVATE KEY'), 'env-injected key PEM must resolve'
}

fn test_config_env_var_unset_fails_fast() {
	if _ := parse_service_config('[cxstore-service [bind addr="h:1"] [tls cert="/etc/c.pem" key="\${env:W3_DEFINITELY_UNSET_VAR}"] [stores [store name="s" url="mem://s"]]]') {
		assert false, 'a referenced-but-unset env var must fail config parse'
	}
}

fn test_svc_load_pem_content_vs_path() {
	// PEM content passes through verbatim
	pem := '-----BEGIN CERTIFICATE-----\nabc\n-----END CERTIFICATE-----'
	got := svc_load_pem(pem) or {
		assert false, 'PEM content must load: ${err.msg()}'
		return
	}
	assert got == pem
	// a missing path fails fast
	if _ := svc_load_pem('/nonexistent/path/${os.getpid()}.pem') {
		assert false, 'a missing PEM file path must fail'
	}
}

// ── #187 / #219: read-timeout config + framing ────────────────────────────────

fn test_config_read_timeout() {
	c := parse_service_config('[cxstore-service [bind addr="h:1"] [timeouts read-ms=5000] [stores [store name="s" url="mem://s"]]]') or {
		panic('timeouts config rejected: ${err}')
	}
	assert c.read_timeout_ms == 5000
	// default when omitted
	c2 := parse_service_config('[cxstore-service [bind addr="h:1"] [stores [store name="s" url="mem://s"]]]') or {
		panic('config rejected: ${err}')
	}
	assert c2.read_timeout_ms == 30000, 'default read timeout is 30s'
}

// ── #186 drain_complete is the live in-flight probe ───────────────────────────

fn test_drain_complete_bounded_semantics() {
	mut s := new_service_state()
	s.mark_ready()
	// not draining → drain_complete false
	assert !s.drain_complete(false)
	s.begin_drain()
	// draining, no in-flight → complete
	assert s.drain_complete(false)
	// draining, deadline reached → complete regardless
	assert s.drain_complete(true)
}

fn w3_err_code(n cx.Node) string {
	if n is cx.Element && n.name == 'err' {
		for a in n.attrs {
			if a.name == 'code' {
				return cx.scalar_value_str_public(a.value)
			}
		}
	}
	return ''
}

fn w3_err_msg(n cx.Node) string {
	if n is cx.Element && n.name == 'err' {
		for a in n.attrs {
			if a.name == 'message' {
				return cx.scalar_value_str_public(a.value)
			}
		}
	}
	return ''
}

// ── source: vcx/platform/store_modify_select_test.v ──
// store_modify_select_test.v — #134-1 (nested target via select) + #134-2
// (child-remove). Exercises the issue's exact repros against store_modify_apply.

fn parse_el(src string) cx.Element {
	doc := cx.parse(src) or { panic('parse ${src}: ${err}') }
	if doc.elements.len == 0 || doc.elements[0] !is cx.Element {
		panic('not an element: ${src}')
	}
	return doc.elements[0] as cx.Element
}

// #134-1: select="//t" sets the attr on the CHILD, not the root.
fn test_modify_select_targets_nested_child() {
	root := parse_el('[targets [t mmsi="111" sog="0"]]')
	act := parse_el('[set-attr select="//t" name=sog value="9"]')
	out := store_modify_apply(root, '//t', act) or { panic(err.msg()) }
	r := render_canonical(out)
	// the child t now has sog='9'
	assert r.contains("[t mmsi='111' sog='9']"), 'child not updated: ${r}'
	// the root targets did NOT get a stray sog attr
	assert r.starts_with('[targets ['), 'root gained a stray attr: ${r}'
	assert !r.contains("[targets sog="), 'sog leaked onto root: ${r}'
}

// #134-2: [remove select="//t"] deletes the matched child.
fn test_modify_remove_child() {
	root := parse_el('[targets [t mmsi="111"] [t mmsi="222"]]')
	act := parse_el('[remove select="//t"]')
	out := store_modify_apply(root, '//t', act) or { panic(err.msg()) }
	r := render_canonical(out)
	assert r == '[targets]', 'expected all t children removed, got: ${r}'
}

// #134-2: remove a specific keyed child (one of several) — descendant match.
fn test_modify_remove_is_scoped_to_matches() {
	root := parse_el('[doc [keep [v "k"]] [drop [v "d"]] [keep [v "k2"]]]')
	act := parse_el('[remove select="//drop"]')
	out := store_modify_apply(root, '//drop', act) or { panic(err.msg()) }
	r := render_canonical(out)
	assert !r.contains('drop'), 'drop not removed: ${r}'
	assert r.contains("[keep [v 'k']]") && r.contains("[keep [v 'k2']]"), 'keep nodes lost: ${r}'
}

// back-compat: no select edits the root element (the original behavior).
fn test_modify_no_select_edits_root() {
	root := parse_el('[targets [t mmsi="111"]]')
	act := parse_el('[set-attr name=count value="1"]')
	out := store_modify_apply(root, '', act) or { panic(err.msg()) }
	r := render_canonical(out)
	assert r.contains("[targets count='1'"), 'root not edited: ${r}'
}

// remove without a select is an error (can't remove the document root).
fn test_modify_remove_without_select_errors() {
	root := parse_el('[targets [t mmsi="111"]]')
	act := parse_el('[remove]')
	store_modify_apply(root, '', act) or { return } // expected error
	assert false, 'expected an error removing the root with no select'
}

// append into a nested match.
fn test_modify_append_nested() {
	root := parse_el('[doc [list [item "a"]]]')
	act := parse_el('[append select="//list" [item "b"]]')
	out := store_modify_apply(root, '//list', act) or { panic(err.msg()) }
	r := render_canonical(out)
	assert r.contains("[item 'a']") && r.contains("[item 'b']"), 'append into child failed: ${r}'
}

// ── source: vcx/platform/store_open_opts_map_test.v ──
// store_open_opts_map_test.v — #259: `store-open-opts` read opts from
// opts.attrs ONLY, but a CX map literal ({"k": v}) materializes its entries
// as CHILD ELEMENTS of the __cx_map__ envelope — so every opt passed as a CX
// map was silently dropped. For `encrypt-key-id` that meant the store was
// created PLAINTEXT where the caller asked for a sealed one (fail-open,
// violating store.md §9 fail-closed). These tests drive the REAL builtin with
// both entry shapes and assert the secret bytes never rest in the clear.

const oomt_kek = '00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff'

const oomt_secret = 'oomt-plaintext-secret-0123456789abcdef'

fn oomt_dir_has_plaintext(dir string) bool {
	entries := os.ls(dir) or { return false }
	for f in entries {
		p := os.join_path(dir, f)
		if os.is_dir(p) {
			if oomt_dir_has_plaintext(p) {
				return true
			}
			continue
		}
		blob := os.read_bytes(p) or { continue }
		if blob.bytestr().contains(oomt_secret) {
			return true
		}
	}
	return false
}

fn oomt_open(dir string, opts_text string) cx.Node {
	opts := cx.parse(opts_text) or { panic('opts parse: ${err.msg()}') }.elements[0]
	url := cx.Node(cx.ScalarNode{ value: cx.ScalarValue('file://${dir}') })
	r := store_stdlib_builtin('store-open-opts', [url, cx.Node(opts)]) or {
		panic('store-open-opts returned none')
	}
	return r
}

fn oomt_seal_case(t string, opts_text string) {
	caps_set_all()
	dir := os.join_path(os.temp_dir(), 'cx_oomt_${t}_${os.getpid()}')
	os.rmdir_all(dir) or {}
	defer {
		os.rmdir_all(dir) or {}
	}
	os.setenv('CX_STORE_KEK_tenc1', oomt_kek, true)
	defer {
		os.unsetenv('CX_STORE_KEK_tenc1')
	}
	h := oomt_open(dir, opts_text)
	assert !is_err_value(h), 'open failed: ${render_canonical(h)}'
	sec := cx.Node(cx.ScalarNode{ value: cx.ScalarValue(oomt_secret) })
	ph := store_stdlib_builtin('store-put-doc', [h, sec]) or { panic('put none') }
	assert !is_err_value(ph), 'put failed: ${render_canonical(ph)}'
	// round-trip through the same handle
	got := store_stdlib_builtin('store-get-doc', [h, ph]) or { panic('get none') }
	assert render_canonical(got).contains(oomt_secret), 'roundtrip lost the doc'
	// THE point: nothing at rest carries the plaintext
	assert !oomt_dir_has_plaintext(dir), '${t}: PLAINTEXT AT REST — encrypt-key-id was dropped'
}

// the CX map-literal shape: entries are child elements of __cx_map__ (#259
// regression — this shape was silently ignored).
fn test_open_opts_encrypt_key_id_via_map_children_seals() {
	oomt_seal_case('children', '[__cx_map__ [encrypt-key-id tenc1]]')
}

// the attrs shape (pre-existing path) must keep sealing too.
fn test_open_opts_encrypt_key_id_via_attrs_seals() {
	oomt_seal_case('attrs', '[opts encrypt-key-id=tenc1]')
}

// ── source: vcx/platform/store_silent_partial_wave5_test.v ──
// store_silent_partial_wave5_test.v — W5 silent-partial guards (#185/#209 non-
// object-graph porcelain must error not fabricate success; #192 query predicate/
// attribute CXPath must match or fail-closed, never a lying empty result).

fn w5_open(url string) cx.Node {
	return store_open_impl(url, '', '', false, true, map[string]string{})
}

fn w5_err_code(n cx.Node) string {
	if n is cx.Element && n.name == 'err' {
		for a in n.attrs {
			if a.name == 'code' {
				return cx.scalar_value_str_public(a.value)
			}
		}
	}
	return ''
}

// register a synthetic columnar-backed handle (the guard checks ms.backend, no
// Arrow build needed to exercise the porcelain gate).
fn w5_columnar_handle() cx.Node {
	mut ms := &MemStore{
		url:     'document+file:///tmp/w5col?encoding=parquet'
		backend: 'columnar'
		is_open: true
		op_lock: sync_new()
	}
	id := store_register(ms)
	return store_handle_element(id, ms)
}

fn sync_new() &sync.Mutex {
	return sync.new_mutex()
}

// ── #209: columnar clone/push/pull → CXER1709 "use migrate", never objects=0 ──

fn test_columnar_porcelain_errors_not_silent() {
	caps_set_all()
	col := w5_columnar_handle()
	mem := w5_open('mem://w5-col-dst')
	// clone FROM columnar → hard error (source has no object identity).
	r_clone := store_stdlib_builtin('store-clone', [col, mem]) or {
		cx.Node(cx.ScalarNode{})
	}
	assert w5_err_code(r_clone) == 'cx-err:CXER1709', 'clone from columnar must be CXER1709 (§4 use migrate), got ${w5_err_code(r_clone)}'
	// push TO columnar → hard error (dest has no object identity).
	r_push := store_stdlib_builtin('store-push', [mem, col]) or { cx.Node(cx.ScalarNode{}) }
	assert w5_err_code(r_push) == 'cx-err:CXER1709', 'push to columnar must be CXER1709, got ${w5_err_code(r_push)}'
	// crucially: NOT a fabricated objects=0 success.
	assert w5_err_code(r_clone) != '', 'columnar clone must NOT return a *-result success'
}

// ── #185: remote byte-source porcelain → CXER1709, never phantom success ──────

fn test_remote_porcelain_errors_not_phantom() {
	caps_set_all()
	// a remote byte-source handle (ftp) has no object wire → porcelain must error.
	remote := w5_open('ftp://ftp.example.invalid/store/')
	if w5_err_code(remote) != '' {
		// open itself may defer connection; if it errored, skip (can't test the guard)
		return
	}
	mem := w5_open('mem://w5-remote-src')
	r := store_stdlib_builtin('store-push', [mem, remote]) or { cx.Node(cx.ScalarNode{}) }
	assert w5_err_code(r) == 'cx-err:CXER1709', 'push to a remote byte-source must be CXER1709 (#185 no phantom success), got ${w5_err_code(r)}'
}

// ── #192: query predicate + attribute CXPath ──────────────────────────────────

fn w5_query(local cx.Node, path string) cx.Node {
	return store_stdlib_builtin('store-query', [local, store_str(path)]) or {
		cx.Node(cx.ScalarNode{})
	}
}

fn w5_result_count(n cx.Node) int {
	mut c := 0
	if n is cx.Element {
		for it in n.items {
			if it is cx.Element && it.name == 'result' {
				c++
			}
		}
	}
	return c
}

fn test_query_predicate_matches() {
	caps_set_all()
	local := w5_open('mem://w5-query')
	store_stdlib_builtin('store-put-doc-text', [local, store_str('[users [user name="al"] [user name="bo"]]')]) or {
		panic('put')
	}
	// L97 flat relation: one [result doc= source= MATCH] tuple per MATCH —
	// the 2 user elements in the one doc are 2 tuples (the former doc-keyed
	// nesting counted 1 result per doc; honestly re-pinned at the cutover).
	names := w5_query(local, '//user')
	assert w5_result_count(names) == 2, '//user must yield one tuple per match (2 users), got ${w5_result_count(names)}'
	// predicate: only user[@name='al'] passes → 1 tuple
	pred := w5_query(local, "//user[= $_@name 'al']")
	assert w5_err_code(pred) == '', 'predicate query must not error: ${w5_err_code(pred)}'
	assert w5_result_count(pred) == 1, "//user[= \$_@name 'al'] must match (was silently ()), got ${w5_result_count(pred)}"
	// a predicate that matches nothing → genuinely 0 results (not an error)
	nomatch := w5_query(local, "//user[= $_@name 'zz']")
	assert w5_err_code(nomatch) == '', 'non-matching predicate is empty, not an error'
	assert w5_result_count(nomatch) == 0, 'non-matching predicate → 0 results'
	// attribute axis: //user/@name → one tuple per attribute value (2 users)
	attr := w5_query(local, '//user/@name')
	assert w5_err_code(attr) == '', 'attribute-axis query must not error'
	assert w5_result_count(attr) == 2, '//user/@name must yield one tuple per match (was silently ()), got ${w5_result_count(attr)}'
	// provenance attributes ride every tuple: doc= (content address) + source=
	// (store-url#cxpath)
	if names is cx.Element {
		first := names.items[0]
		if first is cx.Element {
			mut doc_attr := ''
			mut src_attr := ''
			for a in first.attrs {
				if a.name == 'doc' {
					doc_attr = cx.scalar_value_str_public(a.value)
				}
				if a.name == 'source' {
					src_attr = cx.scalar_value_str_public(a.value)
				}
			}
			assert doc_attr.starts_with('sha2-256:'), 'tuple doc= must carry the tagged content address, got ${doc_attr}'
			assert src_attr == 'mem://w5-query#//user', 'tuple source= must spell store-url#cxpath, got ${src_attr}'
		}
	}
}

// ── source: vcx/platform/store_subtree_objectmodel_test.v ──
// store_subtree_objectmodel_test.v — #129 foundation evidence. Proves the
// vcx/cxstore subtree object-graph engine delivers, at the code-module
// integration boundary (with render_canonical, the store's hash input), the
// three properties the subtree storage model must guarantee:
//
//   (1) canonical-text round-trip — a doc reconstructed from the object graph
//       re-renders to byte-identical canonical text, so the content hash
//       (cx_text_hash(render_canonical(...))) is preserved. This is the
//       "render_canonical <-> emit_node_bin" reconciliation that store_cxpack.v
//       flagged as the blocker; the probe cases show it holds.
//   (2) cross-document subtree dedup — an identical subtree in two unrelated
//       documents shares object(s).
//   (3) modify structural sharing — a one-field change reuses every untouched
//       subtree object; only the path from the change to the root is new.
//
// This validates the engine before the [$store] backend wiring (the next brick).

// obj_keys returns the set of object-hash keys produced by content-addressing a
// document into a fresh sink.
fn obj_keys(src string) map[string]bool {
	mut keys := map[string]bool{}
	doc := cx.parse(src) or { return keys }
	mut sink := cxstore.ObjectSink{}
	cxstore.store_document(mut sink, doc, cxstore.default_fanout)
	for k, _ in sink.objects {
		keys[k] = true
	}
	return keys
}

fn intersect_count(a map[string]bool, b map[string]bool) int {
	mut n := 0
	for k, _ in a {
		if k in b {
			n++
		}
	}
	return n
}

// (1) canonical-text round-trip across varied + adversarial constructs.
fn probe_rc_roundtrip(src string) (string, string) {
	doc := cx.parse(src) or { return 'PARSE_ERR: ${err}', '' }
	if doc.elements.len == 0 {
		return 'NO_ELEMENTS', ''
	}
	c0 := render_canonical(doc.elements[0])
	mut sink := cxstore.ObjectSink{}
	root := cxstore.store_document(mut sink, doc, cxstore.default_fanout)
	getter := fn [sink] (h []u8) ?[]u8 {
		return sink.get(h)
	}
	doc2 := cxstore.load_document_from(getter, root) or { return c0, 'LOAD_ERR: ${err}' }
	if doc2.elements.len == 0 {
		return c0, 'NO_ELEMENTS_AFTER'
	}
	c1 := render_canonical(doc2.elements[0])
	return c0, c1
}

fn test_subtree_canonical_text_roundtrip() {
	cases := [
		'[note id="x" [title "Hello"] [body "first"]]',
		'[db [meta [version 1] [name "store"]] [rec [id 1] [name "alice"] [tags [t "a"] [t "b"]]]]',
		'[m a=1 b="two" c=true [child [leaf 3.14]]]',
		'[x p="a b" q=\'single\' n=42 f=1.5 t=true]',
		'[doc [empty] [nested [deep [deeper "v"]]]]',
		'[el xmlns:b="urn:b" xmlns:a="urn:a" a:x="1" b:y="2"]',
		'[n neg=-5 z=0 f=-3.14 e=1.5e10 big=123456789012345678]',
		'[s a="he said \\"hi\\"" b="line1\\nline2" c="it\'s" d="tab\\there"]',
		'[p "leading text" [b "bold"] "trailing text"]',
		'[u name="café" emoji="🜨" cjk="日本語"]',
		'[doc [; a comment ] [keep "v"]]',
		'[f flag enabled="" zero=0]',
	]
	mut failures := []string{}
	for src in cases {
		c0, c1 := probe_rc_roundtrip(src)
		if c0 != c1 {
			failures << 'MISMATCH\n  src: ${src}\n  c0:  ${c0}\n  c1:  ${c1}'
		}
	}
	if failures.len > 0 {
		assert false, '\n' + failures.join('\n---\n')
	}
}

// (2) cross-document subtree dedup: an identical subtree in two unrelated docs
// shares object(s).
fn test_cross_doc_subtree_dedup() {
	d1 := '[doc1 [unique1 "u1"] [common [k "same"] [k2 "same2"]]]'
	d2 := '[doc2 [unique2 "u2"] [common [k "same"] [k2 "same2"]]]'
	common := intersect_count(obj_keys(d1), obj_keys(d2))
	assert common > 0, 'expected common subtree objects across unrelated docs, got 0'
}

// (3) modify structural sharing: a one-field deep change reuses untouched
// subtree objects — only the changed path is new.
fn test_modify_structural_sharing() {
	// A large untouched subtree (`keep`) + one small mutable field (`mut/v`), so
	// reuse dominates: only the v->root path should be rehashed.
	d := '[doc [keep [a "1"] [b "2"] [c "3"] [d "4"] [e "5"] [f "6"]] [mut [v "ORIGINAL"]]]'
	dp := '[doc [keep [a "1"] [b "2"] [c "3"] [d "4"] [e "5"] [f "6"]] [mut [v "CHANGED"]]]'

	d_alone := obj_keys(d)
	dp_alone := obj_keys(dp)

	// the untouched `keep` subtree contributes common objects to both versions.
	common := intersect_count(d_alone, dp_alone)
	assert common >= 3, 'expected the untouched subtree to share >=3 objects, got ${common}'

	// storing D' on top of D adds only the changed path (b/y + ancestors), far
	// fewer than D' has in total — i.e. untouched subtrees are reused, not rewritten.
	doc_d := cx.parse(d) or {
		assert false, 'parse d'
		return
	}
	doc_dp := cx.parse(dp) or {
		assert false, 'parse dp'
		return
	}
	mut sink := cxstore.ObjectSink{}
	cxstore.store_document(mut sink, doc_d, cxstore.default_fanout)
	before := sink.objects.len
	cxstore.store_document(mut sink, doc_dp, cxstore.default_fanout)
	added := sink.objects.len - before
	assert added < dp_alone.len, 'no reuse: D\' added ${added} objects, has ${dp_alone.len} total'
	// the changed path is small; most of D' was reused.
	assert added < common, 'expected fewer new objects (${added}) than common/reused (${common})'
}

// ── source: vcx/platform/store_verbatim_roundtrip_evidence_test.v ──
// EVIDENCE battery for the F1' letter (evidence-before-ruling, adopted
// 2026-08-08 after the S2 premise failure). This test PINS the current,
// observed round-trip behavior of the store's document path for
// representative document classes — it is documentation-of-fact, green
// against today's tree, cited verbatim by the F1' letter in the stream
// ledger. It asserts what IS, including the gap:
//
//   * structured cx DATA round-trips CANONICALIZED (by design — the
//     content address is the hash of canonical bytes; non-canonical
//     input is normalized);
//   * a def whose surface survives data-canonicalization round-trips;
//   * a def with a STRING-LITERAL body (the shipped dir-sync example's
//     greet def) does NOT round-trip byte-exact — data canonicalization
//     rewrites code's concrete syntax (params absorbed into a quoted
//     scalar), and the result no longer parses as the same program;
//   * the LOSSLESS formatter (cx_text_fmt) also does not preserve such
//     a def byte-exact (evidence against a fmt-based alternative).
//
// Consequence carried by the letter: code is an OPAQUE document (identity
// = raw bytes) and the store needs a general verbatim surface; the retired
// put-def was that path in disguise, mis-keyed by computation identity.
// When the verbatim surface lands, its own fixtures supersede the gap
// pins here (the data-canonicalization pins remain correct forever).

const ev_greet_def = "[?def greet (\$name) [str-format 'hello, {}' \$name]]"

const ev_simple_def = '[?def f (\$x) \$x]'

fn ev_store() cx.Node {
	return store_open_impl('mem://verbatim-evidence', '', '', false, true, map[string]string{})
}

fn ev_roundtrip(text string) string {
	h := ev_store()
	put := store_stdlib_builtin_inner('store-put-doc-text', [h, store_str(text)]) or {
		panic('put: ${err}')
	}
	hash := cx.scalar_value_str_public((put as cx.ScalarNode).value)
	got := store_stdlib_builtin_inner('store-get-doc-text', [h, store_str(hash)]) or {
		panic('get: ${err}')
	}
	if got is cx.ScalarNode {
		return cx.scalar_value_str_public(got.value)
	}
	if got is cx.TextNode {
		return got.value
	}
	panic('unexpected get-doc-text shape')
}

// Structured DATA: canonicalized round-trip is the CONTRACT (identity =
// canonical bytes). Non-canonical spacing normalizes; canonical input is
// byte-stable.
fn test_evidence_structured_data_round_trips_canonicalized() {
	assert ev_roundtrip('[order   id=1    total=99.5]') == '[order id=1 total=99.5]'
	canonical := '[order id=1 total=99.5]'
	assert ev_roundtrip(canonical) == canonical
}

// A def SIMPLE enough to survive data-canonicalization round-trips — this
// is the exact unrepresentative case the reverted S2 premise was declared
// on. Pinned to show WHY the premise looked true.
fn test_evidence_simple_def_survives() {
	got := ev_roundtrip(ev_simple_def)
	assert got == ev_simple_def, 'simple def: ${got}'
	// and its computation identity is preserved
	h1 := code.cx_code_tier2_hash(ev_simple_def) or { panic(err) }
	h2 := code.cx_code_tier2_hash(got) or { panic(err) }
	assert h1 == h2
}

// THE GAP: a def with a string-literal body — the shipped dir-sync
// example's greet def — is REWRITTEN by data canonicalization: the param
// list is absorbed into a quoted scalar and the result no longer parses
// as a def at all. Code's concrete syntax is NOT structured cx data.
fn test_evidence_string_literal_def_mangles_through_doc_path() {
	got := ev_roundtrip(ev_greet_def)
	assert got != ev_greet_def, 'expected the documented mangling, got byte-exact — if this now round-trips, the F1-prime evidence base changed: re-derive'
	// the mangled form is no longer the same program (parse_def refuses)
	if _ := cx.parse_def(got) {
		// If it still parses as a def, it must at least keep computation
		// identity to count as preserved — pin that it does NOT.
		h1 := code.cx_code_tier2_hash(ev_greet_def) or { panic(err) }
		h2 := code.cx_code_tier2_hash(got) or {
			return
		}
		assert h1 != h2, 'mangled def unexpectedly kept computation identity'
	}
}

// The LOSSLESS formatter is not a verbatim substitute either: cx_text_fmt
// of the greet def does not reproduce the source byte-exact (evidence
// against solving the gap with a fmt-canonical storage form).
fn test_evidence_lossless_fmt_is_not_verbatim_for_code() {
	fmtd := cx.cx_text_fmt(ev_greet_def) or { panic('fmt: ${err}') }
	assert fmtd.trim_space() != ev_greet_def, 'cx_text_fmt now reproduces the def byte-exact — re-examine the F1-prime evidence base'
}
